liferay/clay

- tasks/release.js
Comments in released scss files are a version behind.
> Misc: Comments in released files should contain the correct version

- src/scss/lexicon-base/_1bs3-components-compat.scss
- src/scss/lexicon-base/compat/_toggle-card.scss
This commit ensures the Toggle-card correct functionality in Liferay-portal while Toggle-card component is deleted from Clay and new pattern be implemented in liferay-portal
> Toggle-card dropped in clay to compact layer

- packages/clay-card/src/__tests__/__snapshots__/ClayFileCard.js.snap
- packages/clay-card/src/__tests__/__snapshots__/ClayHorizontalCard.js.snap
- packages/clay-card/src/__tests__/__snapshots__/ClayImageCard.js.snap
- packages/clay-card/src/__tests__/__snapshots__/ClayUserCard.js.snap
- packages/clay-checkbox/src/ClayCheckbox.soy
- packages/clay-checkbox/src/__tests__/__snapshots__/ClayCheckbox.js.snap
- packages/clay-dataset-display/src/__tests__/__snapshots__/ClayDatasetDisplay.js.snap
In use cases like ClayCard when it is not necessary to pass `$label` it is rendered unnecessarily. Only by placing inside the `{if}` conditional so that they are not rendered in these use cases. What do you think?
```soy
{let $spanLabelClasses kind="text"}
custom-control-label-text
{if $hideLabel}
{sp}sr-only
{/if}
{/let}
<span class="{$spanLabelClasses}">{$label}</span>
```
> Fix render unnecessary custom-control-label-text on other components in ClayCheckbox

- packages/clay/src/scss/atlas/variables/_tables.scss
- packages/clay/src/scss/mixins/_navbar.scss
- packages/clay/src/scss/variables/_application-bar.scss
- packages/clay/src/scss/variables/_management-bar.scss
- packages/clay/src/scss/variables/_tables.scss
Update: Table title should use `$font-size-base`
Update: Table Action Link should inherit dropdown action styles
New: Added option to configure `btn-monospaced-font-size` and `btn-monospaced-font-size-mobile` to `clay-navbar-size` mixin
Update: Atlas Application Bar and Management Bar icons should be 1rem
> Update: (Fixes #490) Tweak font-sizes to match Lexicon V2

- packages/clay-progress-bar/demos/a11y.html
- packages/clay-progress-bar/demos/index.html
- packages/clay-progress-bar/src/__tests__/ClayProgressBar.js
In the API, it no longer uses `minValue` and `maxValue`.
> Remove unnecessary use of minValue and maxValue in the ProgressBar

- package.json
- packages/clay-card-grid/src/ClayCardGrid.js
- packages/clay-dropdown/src/ClayDropdownBase.js
- packages/clay-pagination/src/__tests__/ClayPagination.js
- yarn.lock
hey @jbalsas this update updates `prettier-eslint` to 8.2.2 that takes the Rob changes, which we had discussed at https://github.com/metal/metal-clay-components/pull/146.
> Update prettier-eslint-cli to 4.7.0

- packages/clay/src/content/sheet.html
- packages/clay/src/scss/components/_sheets.scss
- packages/clay/src/scss/components/_tbar.scss
- packages/clay/src/scss/components/_utilities.scss
- packages/clay/src/scss/variables/_sheets.scss
- packages/clay/src/scss/variables/_utilities.scss
The updated markup is `span` heavy, but I think it provides a lot of flexibility for adding buttons to headings or any text component. This pattern should be useful for creating stuff in the Sites section of Lexicon.
> (#547) sheet-subtitle can contain an "add button" right aligned

- packages/clay-button/src/ClayButton.soy
- packages/clay-button/src/__tests__/__snapshots__/ClayButton.js.snap
- packages/clay-management-toolbar/src/__tests__/__snapshots__/ClayManagementToolbar.js.snap
This can fix issue #522, forcing the attribute to be rendered separate from others. We still have to investigate why this happens only in TagLibs.
> Adds disabled="true" to force your render separate from other attributes | Fixes #522

- packages/clay-charts/src/ChartBase.js
> #610 Check for Number instead of Boolean on axisY.tick.count prop

- packages/clay-alert/src/ClayAlertBase.js
hey @carloslancha, the messages from **warn** happened when the dispose was made on the components that used `ClayAlertBase`, the dispose happened from top to bottom and when it arrived in `ClayAlertBase` in some cases it had no more reference of `_visible`... The way to omit this is to check when it has already been disposed.
> Check if the dispose has already been done and does nothing | Fixes #582

- packages/clayui.com/electric.config.js
- packages/clayui.com/utils/icons.js
> Add generate icon data | Fixes #696

- packages/clay/src/content/form_elements_input_groups.html
- packages/clay/src/scss/_components.scss
- packages/clay/src/scss/_mixins.scss
- packages/clay/src/scss/_variables.scss
- packages/clay/src/scss/atlas/_variables.scss
- packages/clay/src/scss/atlas/variables/_forms.scss
- packages/clay/src/scss/components/_forms.scss
- packages/clay/src/scss/components/_input-groups.scss
- packages/clay/src/scss/components/_labels.scss
- packages/clay/src/scss/mixins/_input-groups.scss
- packages/clay/src/scss/mixins/_labels.scss
- packages/clay/src/scss/variables/_bs4-variable-overwrites.scss
- packages/clay/src/scss/variables/_forms.scss
Breaking: Changed the order of imports for labels and stickers. When we release next, the imports in Portal need to be updated.
/cc @jbalsas
> #690 Markup for Lexicon Input Labels Field

- packages/clay-charts/src/ChartBase.js
When generating the API Docs, the methods of the ChartBase class are rendered out of context. I'm adding some JSDOC tags to try to adjust this.
> Adds new JSDOC tags to ChartBase

- packages/clayui.com/src/pages/index.soy
@jbalsas<br><br>These two commits fix two homepage links currently 404-ing due to pointing to the wrong location and removes redundant css classes<br><br>Let me know if you have any questions. Thanks! :rocket:<br><br>@alexandervalencia
> Removes redundant text-center classes

- packages/clayui.com/src/pages/docs/components/badges.md
- packages/clayui.com/src/pages/docs/components/cards.md
- packages/clayui.com/src/pages/docs/components/forms/form_elements_input_groups.md
- packages/clayui.com/src/pages/docs/components/info_panel.md
- packages/clayui.com/src/pages/docs/components/labels.md
- packages/clayui.com/src/pages/docs/components/list.md
- packages/clayui.com/src/pages/docs/components/modals.md
- packages/clayui.com/src/pages/docs/components/stickers.md
- packages/clayui.com/src/pages/docs/layout/grid.md
(#886) Clay UI Docs update Sticker with icons to use `.inline-item`
> (#777) Clay UI Docs update Label and Badge markup to new pattern

- packages/clay-dropdown/src/ClayDropdownBase.js
I've been working on looking at the best approach to close the dropdown when it has a click on the iframe.
We could listen to the click events of some iframe element on the screen, but we would have problems with some use cases:
* We do not know when there will be an iframe on screen (Modal case)
* The click event will only work if the iframe domain is the same as the navigation
We could go with the simpler approach of closing the dropdown when clicking on some dropdown item but we can not due to interactions in the dropdown.
We can listen to the `blur` event in `window` and check the `activeElement` if it is an iframe so we can close the dropdown.
I'm following with the 3 approach to cover use cases.
> NOTE: I ended up changing the way we are attaching the events, instead of adding them …
> Add events to ClayDropdown to close on mobile and when the esq is pressed and when the iframe is clicked

- clayui.com/content/docs/components/loading-indicator.md
- packages/clay-isomorphic/fixtures/expected/ClayLoadingIndicator.render
- packages/clay-isomorphic/fixtures/input/ClayLoadingIndicator.render
- packages/clay-loading-indicator/LICENSE.md
- packages/clay-loading-indicator/README.md
- packages/clay-loading-indicator/demos/a11y.html
- packages/clay-loading-indicator/demos/index.html
- packages/clay-loading-indicator/package.json
- packages/clay-loading-indicator/src/ClayLoadingIndicator.js
- packages/clay-loading-indicator/src/ClayLoadingIndicator.soy
- packages/clay-loading-indicator/src/__tests__/ClayLoadingIndicator.js
- packages/clay-loading-indicator/src/__tests__/__snapshots__/ClayLoadingIndicator.js.snap
- packages/clay-loading-indicator/webpack.config.js
https://github.com/liferay/clay/issues/1171
> Fixes #1171 - Implementation of loading indicator

- packages/clay-alert/src/ClayStripe.js
- packages/clay-alert/src/ClayToast.js
hey @jbalsas was this what you wanted to put? does it make sense to also add in the class `ClayAlert`?
> Fixes #969 - Adds the close method to ClayStripe and ClayToast

- README.md
The Clay README instructs people to install and use Yarn, and we ship with a yarn.lock, but we don't consistently use `yarn` in the commands that we show in the README; this commit fixes that for consistency.
Tested the commands manually to make sure they all run as intended.
Related: https://issues.liferay.com/browse/IFI-421
> Fixes #1457 - Refer to Yarn consistently in Clay README

- packages/generator-metal-clay/__tests__/test-app.js
These were disabled in 2017 in commit 844f56f35006377911427bd8ae325df3c without explanation. I want to propose a change to the generator, so I've made the tweaks necessary here to get these tests running and passing again.
Tested with `yarn test`.
Related: https://issues.liferay.com/browse/IFI-420
> Fixes #1458 - Re-enable and update generator-metal-clay tests

- packages/generator-metal-clay/app/templates/src/_Boilerplate.js
I asked about the convention of doing a double export:
```javascript
export Thing;
export default Thing;
```
here:
https://github.com/liferay/clay/pull/1440#discussion_r248758900
I just wanted to throw up this PR to have something concrete to use as a basis for discussion about potentially moving away from this pattern. I think it would be desirable in the interests of being "conventional" (down with innovation! viva la convention!).
We'd need to do 2 or potential 3 steps to make this happen:
1. (This PR) Make the generator produce only the default export.
2. In the existing packages, consider emitting a deprecation warning if people use the non-default export.
3. In a future major semver release, remove the non-default exports.
Step 2 there is optional, but would consist of some …
> [IFI-419] Remove redundant export from generator-metal-clay template

- packages/clay-css/src/scss/_mixins.scss
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/atlas/variables/_labels.scss
- packages/clay-css/src/scss/components/_labels.scss
- packages/clay-css/src/scss/mixins/_close.scss
- packages/clay-css/src/scss/mixins/_labels.scss
Also prepped the `.close` component so we can upgrade to Bootstrap 4.1.2+ in the near future.
> Fixes #1522 - ClayCSS Label Dismissible Lg `.close` should be smaller

- packages/clay-css/src/content/badges_and_labels.html
- packages/clay-css/src/content/cards.html
- packages/clay-css/src/content/images_aspect_ratio.html
- packages/clay-css/src/content/test_table_valign.html
- packages/clay-css/src/content/test_table_view_template.html
- packages/clay-css/src/content/test_table_view_template_info_panel.html
- packages/clay-css/src/content/timelines.html
- packages/clay-css/src/content/utilities.html
- packages/clay-css/src/scss/atlas/variables/_stickers.scss
- packages/clay-css/src/scss/components/_stickers.scss
- packages/clay-css/src/scss/mixins/_stickers.scss
- packages/clay-css/src/scss/variables/_stickers.scss
ClayCSS Mixins added `clay-sticker-variant` for creating other sticker types
ClayCSS Stickers added new variant `.sticker-user-icon` and Sass map `$sticker-user-icon` which uses `clay-sticker-variant` mixin
@matuzalemsteles for `ClayUserCard` sticker we need to add `sticker-user-icon` to `elementClasses`
or
`ClaySticker` we will need to add a shape `user-icon` and change the shape in `ClayUserCard` to `user-icon`.
> Fixes #1510 - ClayCSS 2.x Atlas Stickers invert background-color with color (Breaking)

- packages/clay-css/src/content/badges_and_labels.html
- packages/clay-css/src/content/cards.html
- packages/clay-css/src/content/images_aspect_ratio.html
- packages/clay-css/src/content/test_table_valign.html
- packages/clay-css/src/content/test_table_view_template.html
- packages/clay-css/src/content/test_table_view_template_info_panel.html
- packages/clay-css/src/content/timelines.html
- packages/clay-css/src/content/utilities.html
- packages/clay-css/src/scss/atlas/variables/_stickers.scss
- packages/clay-css/src/scss/components/_stickers.scss
- packages/clay-css/src/scss/mixins/_stickers.scss
- packages/clay-css/src/scss/variables/_stickers.scss
ClayCSS Mixins added `clay-sticker-variant` for creating other sticker types
ClayCSS Stickers added new variant `.sticker-user-icon` and Sass map `$sticker-user-icon` which uses `clay-sticker-variant` mixin
> Fixes #1510 - ClayCSS Atlas Stickers invert background-color with color (Breaking)

- packages/clay-navigation-bar/src/ClayNavigationBar.js
This is an assumption I can not debug to see if this happens, when you add `_setCollapseHeight` in the click and then remove it in `sync_isTransitioning` if they happen in a short period so that it does not cause an animation and breaks the menu.
> Fixes #1592 - Adds collapse height when closing to ensure animation happens

- packages/clay-css/src/scss/atlas/variables/_panels.scss
- packages/clay-css/src/scss/atlas/variables/_sheets.scss
- packages/clay-css/src/scss/components/_sheets.scss
- packages/clay-css/src/scss/variables/_sheets.scss
Fixes #1629 ClayCSS Sheet added option to configure `$sheet-subtitle-collapse-icon-font-size`
Fixes #1629 ClayCSS Atlas Sheet `$sheet-subtitle-collapse-icon-font-size` should be 12px
> Fixes #1629 ClayCSS 2.x Atlas Accordion collapse icon should be 12px

- packages/clay-css/src/scss/atlas/variables/_panels.scss
- packages/clay-css/src/scss/atlas/variables/_sheets.scss
- packages/clay-css/src/scss/components/_sheets.scss
- packages/clay-css/src/scss/variables/_sheets.scss
Fixes #1629 ClayCSS Sheet added option to configure `$sheet-subtitle-collapse-icon-font-size`
Fixes #1629 ClayCSS Atlas Sheet `$sheet-subtitle-collapse-icon-font-size` should be 12px
> Fixes #1629 ClayCSS Atlas Accordion collapse icon should be 12px

- packages/clay-css/src/content/test_toggle_switch_old.html
- packages/clay-css/src/content/toggle_switch.html
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_toggle-switch.scss
- packages/clay-css/src/scss/variables/_toggle-switch.scss
This adds support for using `<label for=""></label>` markup pattern in `toggle-switch`. I had to wrap `<input class="toggle-switch-check" id="" type="checkbox">` and `<span aria-hidden="true" class="toggle-switch-bar"></span>` in `<span class="toggle-switch-check-bar"></span>` and change the placement of the checkbox.
This is **potentially a breaking change** if you want #1618 to apply to all the Toggle Switches shown on the test site. #1618 will still apply to all the designs defined by Lexicon using the old markup pattern.
New markup:
```
<span class="simple-toggle-switch toggle-switch">
<span class="toggle-switch-check-bar">
<input class="toggle-switch-check" id="theToggleSwitchCheckId" type="checkbox">
<span aria-hidden="true" class="toggle-switch-bar">
<span …
```
> Fixes #1689 ClayCSS Toggle Switch add option to use label for="id" markup

- migrate-the-clay-components-from-v2-to-v3.md
- packages/clay-icon/src/ClayIcon.tsx
- packages/clay-icon/src/__tests__/__snapshots__/ClayIcon.tsx.snap
- packages/clay-label/README.md
- packages/clay-label/demo/App.tsx
- packages/clay-label/demo/index.html
- packages/clay-label/package.json
- packages/clay-label/src/ClayLabel.tsx
- packages/clay-label/src/__tests__/ClayLabel.tsx
- packages/clay-label/src/__tests__/__snapshots__/ClayLabel.tsx.snap
- packages/clay-label/tsconfig.declarations.json
- packages/clay-label/tsconfig.json
- packages/clay-label/webpack.config.js
Once https://github.com/liferay/clay/pull/1738/commits/64058ec39c06dee1c7dbde8dfb194c902fe4714c is merged, I will go through and add additional docs for this component for v2-v3 migration
> Fixes #1757 - Create @clay/label

- clayui.com/README.md
- clayui.com/package.json
- clayui.com/static/wedeploy.json
I'm just updating the new way of deploying clayui.com, we will keep the version of 2.x on gh-pages and the new site will go to Netlify to get into our workflow process.
> Fixes #1834 - Update deployment clayui.com

- packages/clay-css/src/scss/atlas/variables/_breadcrumbs.scss
- packages/clay-css/src/scss/components/_breadcrumbs.scss
- packages/clay-css/src/scss/variables/_breadcrumbs.scss
Fixes #1913 ClayCSS Breadcrumb use `clay-link` mixin for `.breadcrumb-link` and add Sass map `$breadcrumb-link`
> Fixes #1913 ClayCSS Atlas Breadcrumb focus styles should match Lexicon

- packages/clay-css/src/scss/atlas/variables/_breadcrumbs.scss
- packages/clay-css/src/scss/components/_breadcrumbs.scss
- packages/clay-css/src/scss/variables/_breadcrumbs.scss
Fixes #1913 ClayCSS Breadcrumb use `clay-link` mixin for `.breadcrumb-link` and add Sass map `$breadcrumb-link`
> Fixes #1913 ClayCSS 2.x Atlas Breadcrumb focus styles should match Lexicon

- clayui.com/src/html.js
- clayui.com/src/styles/main.scss
hey @pat270 I'm reversing the use of Atlas direct from css, it was breaking the site's css in production. We can analyze this better in 3.x.
> Revert the use of the atlas by link

- package.json
Needed as a peer dependency of `@storybook/react` otherwise we get issues running storybook. Not sure why the yarn.lock didn't update after adding this...
> Add babel-loader peer dependency

- packages/clay-css/src/scss/atlas/variables/_alerts.scss
- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/atlas/variables/_labels.scss
- packages/clay-css/src/scss/atlas/variables/_pagination.scss
- packages/clay-css/src/scss/variables/_alerts.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/src/scss/variables/_pagination.scss
ClayCSS Globals use sassdoc syntax to document deprecated variables
ClayCSS Pagination use sassdoc syntax to document deprecated variables
ClayCSS Atlas Custom Forms use sassdoc syntax to document deprecated variables
ClayCSS Atlas Labels use sassdoc syntax to document deprecated variables
> ClayCSS use sassdoc syntax to document deprecated variables

- next.clayui.com/content/docs/migration/migrate-the-clay-components-from-v2-to-v3.md
- package.json
- packages/clay-autocomplete/README.md
- packages/clay-autocomplete/package.json
- packages/clay-autocomplete/src/Context.ts
- packages/clay-autocomplete/src/DropDown.tsx
- packages/clay-autocomplete/src/Input.tsx
- packages/clay-autocomplete/src/Item.tsx
- packages/clay-autocomplete/src/LoadingIndicator.tsx
- packages/clay-autocomplete/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-autocomplete/src/__tests__/index.tsx
- packages/clay-autocomplete/src/index.tsx
- packages/clay-autocomplete/stories/index.tsx
- packages/clay-autocomplete/tsconfig.declarations.json
- packages/clay-autocomplete/tsconfig.json
- packages/clay-data-provider/src/index.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-form/README.md
- packages/clay-form/package.json
- packages/clay-form/src/Input.tsx
- packages/clay-form/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-form/src/__tests__/index.tsx
- packages/clay-form/src/index.tsx
- packages/clay-form/stories/index.tsx
- packages/clay-form/tsconfig.declarations.json
- packages/clay-form/tsconfig.json
- packages/clay-shared/src/useDebounce.ts
- yarn.lock
I ended up creating the `ClayForm` component to handle `Input`, but I'm still not sure if it would be necessary, what do you think?
I also did some fixes on `useResource` hook that I ended up having to deal with. I still have to add tests, as soon as we're okay with it, I'll work on it.
> feat(Autocomplete): Create ClayAutocomplete component

- packages/clay-css/src/content/management-bar.html
- packages/clay-css/src/scss/components/_management-bar.scss
https://issues.liferay.com/browse/LEXI-477
We need to add the class `nav-item-shrink` to the `navbar-text` container to make long text with no white space break to new line.
> ClayCSS Management Bar navbar-text should break to new line

- packages/clay-date-picker/src/InputDate.tsx
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/src/index.tsx
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/__tests__/index.tsx
- packages/generator-clay-component/app/index.js
Got annoyed with the red errors in our tests so I went through and tried to fix some. I also cleaned up the clay-modal tests to avoid async stuff with react-testing-library. anytime we use setTimeout, I think we should try to use jest's built in fakeTimer API. makes it a bit cleaner IMO.
> fix(generator-clay-components): add check for skipInstall

- packages/clay-data-provider/package.json
- packages/clay-data-provider/src/useResource.ts
- yarn.lock
Since we have a [polyfill for searchParams](https://github.com/liferay/liferay-portal/blob/b628b3a178accd00caa4908222c1a122f8b539df/modules/apps/frontend-compatibility/frontend-compatibility-ie/build.gradle#L293-L307) in portal, can we can just use URL instead?
cc: @jbalsas
> fix(clay-data-provider): remove metal-uri dependency in favor of URL

- packages/clay-charts/src/BillboardWrapper.tsx
Fixes https://github.com/liferay/clay/issues/2120
> fix(clay-charts): asyncronously call 'onafterinit' prop in order to have access to ref

- package.json
- packages/clay-button/package.json
- packages/clay-button/src/Button.tsx
- packages/clay-button/src/ButtonWithIcon.tsx
- packages/clay-button/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-button/src/__tests__/index.tsx
- packages/clay-button/src/index.tsx
- packages/clay-button/stories/index.tsx
note: I also added a static port for storybook. I got tired of builds failing and not know what url to hit after it was successful.
> feat(clay-button): create ClayButtonWithIcon component

- packages/clay-autocomplete/src/Item.tsx
- packages/clay-autocomplete/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-autocomplete/stories/index.tsx
- packages/clay-drop-down/src/Item.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/index.tsx
- packages/clay-shared/src/Portal.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useDebounce.ts
- packages/clay-shared/src/useKeyHandlerForList.ts
- packages/clay-shared/src/useTransitionHeight.ts
The aim of these hooks is to address https://github.com/liferay/clay/issues/2107. To see how they work, checkout the autocomplete stories. 
My initial thought is to get these reviewed and approved and if they look good, add them to the multiselect high-level component for an initial testing ground.
> add useArrowKeysForList and useEnterKey hooks

- packages/clay-modal/src/Hook.ts
Fixes #2165
~~This was a solution that I found most appropriate at the moment, since the "document" becomes the `modal-backdrop` for the case of the modal I think it is safe to check if the click was in it so we could close the modal. But leave your thoughts.~~
> fix(@clayui/modal): stop closing the modal when the element is removed from the modal content

- packages/clay-autocomplete/src/Item.tsx
- packages/clay-autocomplete/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-autocomplete/stories/index.tsx
- packages/clay-button/src/Button.tsx
- packages/clay-drop-down/src/DropDownWithBasicItems.tsx
- packages/clay-drop-down/src/Item.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useFocusManagement.ts
Fixes #1987
This is a draft from a focus manager, possibly a substitute for `useKeyHandlerForList`, which may cover more cases in Modal, DropDown and perhaps DatePicker. I have taken as a basis the initial and experimental implementation of the FocusManager API (https://github.com/facebook/react/pull/15849) that may be acceptable.
In terms of design the use of `createScope` becomes more feasible to dribble element problems in React Portal, I tried to do the same as FocusManager API in having a `FocusScope` but here I only have access to DOM elements and not the fibers that would become easier but I want to hear other ideas.
> feat(@clayui/shared): add experimental useFocusManagement hook

- packages/clay-card/package.json
- packages/clay-card/src/CardWithFile.tsx
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/Description.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/src/index.tsx
- packages/clay-card/stories/index.tsx
- packages/clay-drop-down/src/DropDownWithBasicItems.tsx
Fixes https://github.com/liferay/clay/issues/2195
Fixes https://github.com/liferay/clay/issues/2196 
Fixes https://github.com/liferay/clay/issues/2197
> feat(card): create CardWithFile high-level component

- packages/clay-drop-down/src/DropDownWithBasicItems.tsx
- packages/clay-drop-down/src/Item.tsx
- packages/clay-pagination/src/PaginationWithBar.tsx
- packages/clay-pagination/src/__tests__/index.tsx
- packages/clay-pagination/stories/index.tsx
This will probably conflict with #2223, but do not need to enter to `milestone.2` now. We have to always try to use `ClayDropDownWithBasicItems` and when we can't have to add `useFocusManagement` hook we should do the same for the other components that are using DropDown.
> refactor(@clayui/pagination): remove low-level components from DropDown and use ClayDropDownWithBasicItems

- packages/clay-card/src/Description.tsx
As described [here](https://github.com/liferay/clay/pull/2208#discussion_r310028803), we can use `as const` to prevent TypeScript from widening the type from the desired `'span' | 'div' | 'h3'` to `string`.
> refactor: remove an unnecessary cast

- packages/clay-drop-down/src/DropDown.tsx
Noticed this while looking at: https://github.com/liferay/clay/pull/2223
This is perhaps a better fix than casting to `any`, which can hide legitimate errors.
> refactor: remove another cast

- packages/clay-drop-down/src/DropDownWithBasicItems.tsx
- packages/clay-form/src/InputWithAutocomplete.tsx
- packages/clay-form/src/MultiSelect.tsx
- packages/clay-form/src/__tests__/InputWithAutocomplete.tsx
- packages/clay-form/src/__tests__/__snapshots__/MultiSelect.tsx.snap
- packages/clay-multi-step-nav/src/Indicator.tsx
- packages/clay-multi-step-nav/src/MultiStepNavWithBasicItems.tsx
- packages/clay-multi-step-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation/src/BreadcrumbEllipsis.tsx
- packages/clay-pagination/src/PaginationEllipsis.tsx
- packages/clay-pagination/src/__tests__/index.tsx
- packages/clay-shared/src/FocusScope.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useFocusManagement.ts
Fixes #2227
I ended up creating the `FocusScope` component that deals only with the logic of controlling focus with tab and arrow keys to minimize the logic we may have repeated between some components.
I also made some important improvements to `useFocusManagement` to cover cases that I just caught with our components (I added some comments to the code.).
I tried to force the use of the `ClayDropDownWithBasicItems` component in some cases which I found that it was not necessary to add a low-level component. Maybe we can force more elsewhere.
These changes are also in conjunction with #2224.
> refactor: add useFocusManagement to components and create FocusScope

- .travis.yml
It is no longer necessary to use java since we no longer have Java dependencies as in v2.
> chore(travis.yml): remove java usage in favor of nodejs

- tsconfig.json
Fixes #2235
I just changed the `@clayui/*` package path so that typescript looks inside `node_modules`, so it does not consider that it should generate types at build time but will still look at them to make sure everything is fine.
> fix(tsconfig.json): consume clay packages from `node_modules` to correctly generate of the types

- packages/clay-modal/src/index.tsx
- packages/clay-shared/src/Portal.tsx
- packages/clay-shared/src/__tests__/Portal.tsx
Added two new APIs to our portals. One is a target for nested portals, and the other is to render the portal to a specific element. By default portals now nest in one another as well.
this fixes https://github.com/liferay/clay/issues/2246
> fix(portal): automatically nest portals if they are inside one another

- packages/clay-navigation/package.json
- packages/clay-navigation/src/Breadcrumb.tsx
- packages/clay-navigation/src/Nav.tsx
- packages/clay-navigation/src/NavItem.tsx
- packages/clay-navigation/src/NavLink.tsx
- packages/clay-navigation/src/Vertical.tsx
- packages/clay-navigation/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation/src/__tests__/index.tsx
- packages/clay-navigation/src/index.tsx
- packages/clay-navigation/stories/index.tsx
Wanted to send this to get external opinions. As of now, I sort of see `Vertical` as a high-level component. I also created low-level nav components but I wasn't totally sure how we want to expose those within the navigation package.
Let me know your thoughts.
TODO:
> feat(navigation): add Navigation.Vertical component

- packages/clay-pagination/src/PaginationWithBar.tsx
> fix(@clayui/pagination): imports ClayPagination from its origin component and avoids circular dependency

- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_time.scss
@matuzalemsteles the class to add is `focus`
> feat(clay-css): Clay Time add focus styles for hours, minutes, seconds, etc

- packages/clay-autocomplete/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
Fix #2288
- This prevents DropDown from closing when it has a portal nested to it, for example DatePicker.
- The same is done for Modal, it was closing when it has some action on these portals nested to it, the strategy was to wrap them all in a `fade modal` child element and simulate the element as if it were `modal-dialog` without an overflow for example to keep the modal closed when clicking outside the modal.
- There have been many updated snapshot tests due to the wraps on top of these components that affect many others.
Let me know if you think this is weird or have another strategy.
> fix: stop closing DropDown or Modal when clicking inside element on a nested sub portal

- packages/clay-modal/package.json
- packages/clay-modal/src/Modal.tsx
Just adding a warning to help developers correctly use `ClayModal`.
> chore(@clayui/modal): adds a warning when observer is not passed to ClayModal

- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-pagination/src/PaginationWithBar.tsx
- packages/clay-pagination/src/__tests__/index.tsx
- packages/clay-pagination/stories/index.tsx
Two issues here:
1) `<ClayPaginationWithBar />` was an uncontrolled component. We should default our components to be controlled(both a value and onChange). This gives users a flexibility provide a specific value in reaction to some other change.
2) `<ClayDropDownWithItems />` isn't currently closing the dropdown after clicking an item. I added a context here so that it will automatically close when item is clicked.
Both of these issues arose from chatting with @thektan and @oliv-yu as they tried to use `<ClayPaginationWithBar />`
> fix(drop-down): automatically close dropdown when clicking on item

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
> fix(@clayui/modal): change the default size of the `modal-dialog` wrapping div

- packages/clay-css/src/content/form_elements_input_groups.html
- packages/clay-css/src/content/form_elements_multiselect.html
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-form/src/InputWithMultiSelect.tsx
- packages/clay-form/src/__tests__/InputWithMultiSelect.tsx
- packages/clay-form/src/__tests__/__snapshots__/InputWithMultiSelect.tsx.snap
- packages/clay-form/stories/index.tsx
- packages/clay-label/src/index.tsx
Fixes #2335
This follows the [new specifications in the document for MultiSelect](https://docs.google.com/document/d/1LJ8yiO8V5mSEGOjaYzHd5Nex_De_8fMRQAEKQoHMiiM/edit).
It still remains to cover the tab order that looks different here, I will have to make some changes in `useFocusManagement` to respect the `tabindex`, I will work on that in another PR.
> feat(@clayui/form): adds the Clear All specification in multi-select

- packages/clay-table/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-table/src/__tests__/index.tsx
- packages/clay-table/src/index.tsx
- packages/clay-table/stories/index.tsx
> feat(@clayui/table)!: `bordered` property was renamed to `borderedColumns` due consistency and `borderless` property was added (#2387)

- packages/clay-panel/stories/index.tsx
- packages/clay-shared/src/useTransitionHeight.ts
this is a necessary fix for panel, we will have to make sure to release a new version of shared before as well.
> fix(panel): collapsing doesn't work well when there is more than one child element

- packages/clay-navigation/src/BreadcrumbEllipsis.tsx
- packages/clay-navigation/src/BreadcrumbItem.tsx
This is just a subtle improvement, since we allow `otherProps` in this component we must say what other props can be passed to it.
> chore(@clayui/navigation): improve types

- packages/clay-shared/src/useTransitionHeight.ts
In different builds, the spread is transformed differently, causing errors on the next.clayui.com site but it worked fine on the Storybook. Converting to something "older" to make sure transpilations don't cause consistency.
This affects `ClayPanel` but there is no need for a patch release, we can hold back a bit and release later.
> fix(@clayui/shared): use another method to create a new array from an HTMLCollection

- next.clayui.com/content/docs/foundations/composing.md
- next.clayui.com/content/docs/foundations/index.md
- next.clayui.com/content/docs/get-started/how-to-use-clay.md
- next.clayui.com/content/docs/get-started/what-is-clay.md
- next.clayui.com/src/styles/_guide.scss
- next.clayui.com/src/templates/docs.js
This will most likely fix issues #2474, #2209, and #2478
I have added leaner documentation to the "How to use clay" document, if we need more information we can add it elsewhere.
I just added the document I'll work on tomorrow for "Composing" to explain how composing works for Clay components and low-level and high-level philosophy.
> chore(next.clayui.com): add guide to install components and quick start

- next.clayui.com/gatsby/createPages.js
- next.clayui.com/src/components/LayoutNav/LayoutNav.js
- next.clayui.com/src/pages/index.js
- next.clayui.com/src/templates/blog.js
This is a start to preparing the site launch by removing the redirect from the landing page and adding the blog to the menu.
I'm working on submitting the introduction content and components documentation.
> chore(next.clayui.com): remove redirect from landing page and show blog menu

- next.clayui.com/package.json
- next.clayui.com/src/components/clay/DataProvider.js
- next.clayui.com/src/components/clay/Editor.js
In regards to https://github.com/liferay/clay/issues/2554
This was the quickest way to keep formatting consistent in the docs. I think we can later iterate on this, but I think this provides a quick and helpful formatting for our examples that utilize react-live
> docs: add prettier for react-live editor

- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-drop-down/src/Menu.tsx
Fixes #2579
This causes the alignment to be done before the browser can paint.
> fix(@clayui/drop-down): fixes DropDown.Menu component error blinks when aligning

- packages/clay-navigation/package.json
- packages/clay-navigation/src/NavLink.tsx
- packages/clay-navigation/src/__tests__/__snapshots__/index.tsx.snap
Fixes #2456
Once this is merged I think we can release Navigation to a stable release, let me know if you see anything that might prevent it from being released.
Importantly we also make a patch release of `@clayui/css` which contains the changes to this #2597, we will also need to make a patch release for 2.x, because the portal is still using 2.x css.
> fix(@clayui/navigation): fixes focus problem on elements with DropDown

- packages/clay-modal/src/Hook.ts
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
Fixes #2165
This adds the ability for the person to control Modal closing when clicking outside Modal occurs. Since it is a generic click event within `document`, it may happen that other Portal methods can prevent this, so it is a bit dangerous, adding that we will be assuming that people will control. This also enables Portal to implement the option to open more than one modal on the screen.
cc @julien
> feat(@clayui/modal): does not close Modal when document click event is prevented

- packages/clay-autocomplete/src/index.tsx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-shared/src/FocusScope.tsx
Fixes: https://github.com/liferay/clay/issues/2592
So it turned out we were running into issues with callback refs for dropdown. It wasn't properly aligning due to the ref being null. See reacts doc for info on callback refs, https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs
> fix: ref callbacks are first calling with null. https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs

- packages/clay-icon/src/index.tsx
Fixes #2642
As suggested by @jbalsas, it was the same solution in Metal. Forces to change the `key` of the element so that React does not reuse the node, so `svg4everybody` will re-capture the node to make its changes.
I am adding this straight to `ClayIcon` because it is common for someone to do this and so we can support it directly, I don't see a real problem with that so please let me know if you see anything.
Once we get on with this, we will need to release some fix patches for the components that use the ClayIcon. I'm eyeing ColorPicker that symbol change...
> fix(@clayui/icon): forces React not to reuse node when symbol changes

- packages/clay-card/src/Description.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
Fixes #2607
I'm leaving the `p` tag pattern to follow the same pattern we did in 2.x. #1733
> fix(@clayui/card): add prop `tag` to make Description configurable

- packages/clay-color-picker/src/Hue.tsx
Fixes #2649
Updating Hue in most cases was causing blocking since we are always updating the `left` of the range pointer.
> fix(@clayui/color-picker): update Hue before the browser can paint

- CONTRIBUTING.md
- lerna.json
- packages/demos/package.json
Spent some time investigating a release process that would allow us to do regular releases for all packages without having to manually do it like we did for 3.0.0. I updated our lerna config and added steps for publishing. Let me know if you think I missed anything or if anyone has any other ideas.
implements https://github.com/liferay/clay/issues/2610
> docs(contributing): add release process steps

- .eslintignore
- .prettierignore
- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/Sidebar/Sidebar.js
- clayui.com/src/components/TrackingIssues/Tracking.js
- clayui.com/src/components/clay/Editor.js
- clayui.com/src/components/clay/PaginationBar.js
- clayui.com/src/pages/index.js
- clayui.com/src/templates/blog.js
- clayui.com/src/templates/docs.js
I added an alert to the homepage to point to v2. I think this will help anyone who might be confused at the design change and who didn't scroll to see the deprecation warning. This helps keep the alert above the scroll line and will help inform users of knowing where v2 docs are at, as well as knowing this is a v3 site.
We can eventually remove it, but I think itd be good to keep around for a bit.
> docs: add warning to point to 2.x on homepage

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
Fixes #2674
@bryceosterhaus I ended up choosing `menuElementAttrs` instead of `menuProps`, since we already have `DropDown.Menu` specific props in DropDown root.
> feat(@clayui/drop-down): add new prop to pass element attributes to DropDown.Menu

- packages/clay-form/src/Form.tsx
> feat(@clayui/form): add `forwardRef` support for `<ClayForm />`

- packages/clay-data-provider/src/useResource.ts
- packages/clay-data-provider/stories/index.tsx
Fixes #2679
Replace the use of `setInterval` to `setTimeout` is safer for now, because we may have cases when `pollInterval` is set to 1000ms and the request may take longer than this time and we may have more than one request being made. and that number can accumulate. So we will always wait for the request to succeed in scheduling the next one.
Such a change means that `pollInterval` is not always executed every 1000ms for example, it also contains the time of the previous request. In a way, we already had this when we were using `setInterval`... but we are preventing more than one request from being made at the same time and possibly creating some kind of server overload.
A change to `pollInterval` also to enable you to make a mechanism to enable and disable `poll` by setting to some …
> fix(@clayui/data-provider): replace setInterval in favor of setTimeout and polling engine improvements

- clayui.com/content/docs/components/forms/form.mdx
- clayui.com/plugins/gatsby-remark-api-table/index.js
- packages/clay-form/src/Form.tsx
Fixes https://github.com/liferay/clay/issues/2716
Note, we specify the component by using its name via `some/file.tsx#FooBar`
Also, `react-docgen` doesn't seem to accurately pick up displayName of some components. This may be because of using arrow functions, but im not quite sure. This is why I explicitly added displayName to the form components
> chore: scrape API table for a specific specific named component

- packages/clay-css/src/content/form_validation.html
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/components/_form-validation.scss
- packages/clay-css/src/scss/variables/_forms.scss
> feat(clay-css): Form Validation add Sass maps `$input-danger-readonly`, `$input-success-readonly`, and `$input-warning-readonly`

- packages/clay-css/src/content/form_validation.html
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/components/_form-validation.scss
- packages/clay-css/src/scss/variables/_forms.scss
> feat(clay-css): 2.x Form Validation add Sass maps `$input-danger-readonly`, `$input-success-readonly`, and `$input-warning-readonly`

- clayui.com/content/docs/components/icon.mdx
Reading through documentation when I came across a broken link. Haven't kept up with the developments around this project, but I'm guessing the location for this svg was correct during the v2 versions and `next` was v3 before release.
Please let me know if you have any questions. Thanks!
Fixes #2771
> docs(icon): Remove next subdomain from clayui.com icon download link

- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/stories/index.tsx
After looking at https://github.com/liferay/clay/pull/2668, I think it's a bit more clear to use fragments instead of empty arguments. This should at least help readability.
> chore: use fragments instead of empty args

- packages/clay-css/src/content/form_elements.html
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
> feat(clay-css): Forms support `label` element without `for` attribute

- packages/clay-css/src/content/form_elements.html
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
> feat(clay-css): 2.x Forms support `label` element without `for` attribute

- packages/clay-popover/package.json
- packages/clay-popover/src/index.tsx
- packages/clay-popover/stories/index.tsx
- yarn.lock
> feat(popover): add align functionality

- packages/clay-dropdown/demos/index.html
- packages/clay-dropdown/src/ClayDropdownItem.js
- packages/clay-dropdown/src/ClayDropdownItem.soy
- packages/clay-dropdown/src/ClayDropdownLabel.soy
- packages/clay-isomorphic/fixtures/expected/ClayDropdownLabel.render
- packages/clay-isomorphic/fixtures/input/ClayDropdownLabel.render
Fixes #2856
Just a hack to force the label to be treated as HTML so it can escape special characters.
> fix(clay-dropdown): escape special characters in label

- packages/clay-css/src/scss/components/_tooltip.scss
- packages/clay-tooltip/stories/index.tsx
> fix(css): allow newline characters to display properly for tooltips

- packages/clay-css/src/content/dropdowns.html
- packages/clay-css/src/content/form_custom.html
- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
- packages/clay-css/src/scss/components/_dropdowns.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
The only thing that needs to happen in Clay Dropdown is changing `dropdown-item` to `dropdown-section` for any `custom-control` components.
> feat(clay-css): Dropdown Section add specific styles for nested `custom-control`s

- packages/demos/package.json
- packages/demos/src/recharts/Tooltip.tsx
- packages/demos/src/recharts/config.ts
- packages/demos/src/recharts/index.tsx
- packages/demos/stories/Recharts.tsx
- packages/demos/stories/index.tsx
- yarn.lock
I spent some time re-creating our existing charts using `recharts` and overall the experience was really nice. Recharts was super easy to use and highly configurable. I haven't approached the predictive or geomap charts yet, I am going to look into those now.
One question I have for people, is how would you expect us to offer the "clay" portion of charts? Is exporting colors and potentially custom components such as tooltips, legends, and axis enough? Or do you expect something else? I am hesitant to wrap rechart components and export them with our own default config. Check out the storybook for clay-recharts(name subject to change) and let me know what you all think.
> chore(demos): add recharts examples to storybook

- packages/clay-css/src/content/modals.html
- packages/clay-css/src/content/test_upload_documents.html
- packages/clay-css/src/scss/components/_modals.scss
- packages/clay-css/src/scss/variables/_modals.scss
fixes #2844 
The autofit pattern was the most robust when it came to tossing in additional components into the header. I piggy backed off the `modal-item` class. The markup for additional items is below:
```
<div class="modal-header">
<div class="modal-item-group">
<div class="modal-item">
<div class="modal-title-section">
<div class="modal-title" id="modalLabel">
Modal Title
</div>
</div>
</div>
<div class="modal-item modal-item-shrink">
<div class="modal-subtitle-section">
<div class="text-truncate-inline">
<div class="text-truncate">
<div class="modal-subtitle">Step 1 of 2</div>
<div class="modal-subtitle-divider">/</div>
<strong>Details</strong>
</div>
</div>
</div>
</div>
</div>
<button aria-label="Close" class="close" data-dismiss="modal" type="button">
x
</button>
</div>
```
The …
> feat(clay-css): Modal additional components in Modal Header

- packages/clay-card/src/Card.tsx
Not sure if this is a React bug or we were just doing it wrong, but using [the `<Content>` component inside the `ClayCard` implementation](https://github.com/liferay/clay/blob/1fbdfa21e64e623f9470fa50e5d242c0743a0809/packages/clay-card/src/Card.tsx#L56-L60) was causing React to remove one of the descendent elements from the DOM and re-insert it, even though there was no actual diff. When the descendent element is an `<img>`, this is bad and can cause a visual flicker (maybe something we haven't noticed before because we tend not to re-render cards much; but @boton noticed it now because he is rendering a progress bar inside the card that updates frequently).
To see this in action, see this demo:
https://codesandbox.io/s/blissful-shaw-xrekn
There is a fork of `ClayCard` in there called …
> fix(card): prevent unwanted DOM thrash in ClayCard (#2916)

- packages/clay-popover/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-popover/src/__tests__/index.tsx
- packages/clay-popover/src/index.tsx
- packages/clay-popover/stories/index.tsx
fixes #2738
This fix may look a little odd, and here is my line of thinking...
1. We initially released and documented a `show` prop on the components interface.
2. However, we don't use it for anything and handle all show/hide internally.
3. Since we initially released it on the interface and because we typically release "controlled" components, we should provide a full controllable API.
4. In order to keep current functionality and not break the internal show/hide, make it so we can do both.
5. Conclusion: make it usable via both controlled and uncontrolled.
Any concerns with this?
The other option would be to just remove it from the interface since it doesnt actually do anything and act like nothing happened
> fix(@clayui/popover): make 'show' prop actually usable

- clayui.com/content/docs/components/css-icons.mdx
- clayui.com/content/docs/components/icon.mdx
- clayui.com/src/components/IconSearch/index.js
- clayui.com/src/templates/docs.js
- clayui.com/static/js/flags.json
- clayui.com/static/js/icons.json
Hey @bryceosterhaus here's my draft of the Icon Filtering feature we talked about in [the issue](https://github.com/liferay/clay/issues/2029).
A couple notes:
- The filtering via the search input and the icon rendering is in the React component
- I couldn't figure out how to import that React component in the `css-icons.md` file, I did convert it into an `mdx` file but then it wasn't considered a sibling of `icon.mdx` as defined in [icon.mdx:5](https://github.com/liferay/clay/blob/master/clayui.com/content/docs/components/icon.mdx#L5)
- Gonna have to do a cleanup of the `icons.json` file because there are some icons that don't have a file associated with them
I doubt that putting the `<IconSearch />` in the `icon.mdx` is the best place to do it because it duplicates the icon list found in …
> feat(@clayui.com): Icon Filtering

- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
Looks like e393c07f3f9b21bb7f146037d7372e1b updated some but not all of the snapshots.
> chore: update stale snapshots

- packages/clay-css/src/scss/components/_tables.scss
fix(clay-css): Table removes table-responsive hack related to border-collapse
https://issues.liferay.com/browse/LPS-95346
> fix(clay-css): 2.x Add border-spacing, border-collapse not working in IE

- clayui.com/src/styles/_prismjs.scss
> fix(clayui.com): White text in gatsyby-highlight html

- packages/clay-css/src/content/form_elements.html
- packages/clay-css/src/content/form_elements_clay_reorder.html
- packages/clay-css/src/content/form_elements_dual_listbox.html
- packages/clay-css/src/content/form_validation.html
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/atlas/_variables.scss
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/atlas/variables/_reorder.scss
- packages/clay-css/src/scss/components/_dual-listbox.scss
- packages/clay-css/src/scss/components/_form-validation.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_reorder.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_dual-listbox.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-css/src/scss/variables/_reorder.scss
There are some issues with `select[size]` and `select[multiple]` in Firefox and Safari. They render the scrollbar track even if there is no overflowing content. I couldn't work around this with native inputs in those browsers so there is a potential "bug" that could pop up. On the other hand they look nice on Chrome, IE11, and Edge.
@kresimir-coko you can find the markup for the component on my test site under Form Elements (Dual Listbox). @jonmak08 mentioned he put in a lot of work with keyboard shortcuts in the old Input Move Boxes component. ~I tried look for the ticket, but can't find it.~ Here it is https://issues.liferay.com/browse/LPS-77051. We should find out what shortcuts we need.
> feat(clay-css): Adds Dual Listbox component (input move box replacement)

- .github/workflows/main.yml
We are getting an error in our curl call stating "Resource not accessible by integration", so I am adding this flag to help debug the action since this worked fine on my local fork.
> chore: add verbose flag to debug github action

- .github/workflows/main.yml
Long story short, this action works only if the PR is from the same repo. If its fork, the token doesnt have access for writing comments.
See https://github.com/actions/labeler/issues/12#issuecomment-525762657 for more indepth discussion
> chore: disable action due to it not working properly when PR is from a fork

- CHANGELOG.md
"dissapear" is a misspelling of "disappear".
> fix(CHANGELOG.md): fix a typo

- packages/clay-tooltip/src/TooltipProvider.tsx
fixes #2998
This approach seemed the most straight forward. I had looked into via MDN and stackoverflow and this was the primary way recommended.
If you have any concerns, let me know!
> fix(@clayui/tooltip): add polyfill for element.matches

- .github/workflows/main.yml
Gh errors with `you may only define one of branches and branches-ignore for a single event`. Removing branches for now
> chore: fix gh action error

- packages/clay-css/package.json
- packages/clay-css/src/scss/mixins/_globals.scss
fixes #2990
This shaves ~1.2 seconds off the `compile:css` task.  I'm going to be updating other mixins to use the `clay-css` mixin so the actual number might be closer to ~.5 seconds in the end. It's still better than what it is now and will have more properties that are configurable. If anyone sees a way to speed it up more let me know.
> fix(@clayui/css): Mixins `clay-css` only loop through properties that are passed via Sass map instead of listing everything

- clayui.com/content/docs/css/content/c-kbd.md
- clayui.com/content/docs/css/utilities/c-focus-inset.md
- clayui.com/content/docs/css/utilities/c-inner.md
- packages/clay-css/src/scss/components/_dropdowns.scss
Fixes #2971
So it turns out this issue was because `left: 0;` on `.dropdown-menu` was getting flipped to `right: 0;` when using rtl in portal. This is an issue because dom-align is setting the `left` property and that is ignored if the `right` property exists.
rlt specification says
> If direction of the containing block is rtl, right wins and left is ignored.
It also looks like we encountered this in portal before and we added this file, https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_dropdown.scss#L5. However that style was specifically scoped within `#clay_dropdown_portal` which is no longer used.
So ultimately the question here is, should we add this to `@clayui/css`(like ive done here), or …
> fix(@clayui/css): override specific styles for rtl support

- packages/clay-time-picker/src/index.tsx
> fix(@clayui/time-picker): prevent scroll when using arrow keys to cycle numbers

- clayui.com/content/docs/get-started/how-to-read-this-documentation.md
- clayui.com/content/docs/get-started/how-to-use-clay.md
- clayui.com/content/docs/migration/migrate-the-clay-components-from-v2-to-v3.md
- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/Sidebar/Navigation.js
- clayui.com/src/components/Sidebar/Sidebar.js
- clayui.com/src/styles/_code.scss
- clayui.com/src/styles/_guide.scss
- clayui.com/src/styles/_navbar.scss
- clayui.com/src/styles/site/_sidebar-site.scss
- clayui.com/src/templates/docs.js
Renamed all docs with `nav-toc` from `.md` to `.mdx`. The code changes to doc files are from running `yarn  format:all`.
fixes #3042
going to revisit `nav-toc` later, just used browser default focus styles for now.
> docs(clayui.com): Use c-inner for better focus experience

- yarn.lock
Not sure when this became out of date, but the updates to it seem fine
> chore: update stale yarn.lock

- clayui.com/content/docs/components/label.mdx
- packages/clay-label/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-label/src/__tests__/index.tsx
- packages/clay-label/src/index.tsx
- packages/clay-label/stories/index.tsx
continued conversation from https://github.com/liferay/clay/pull/3066
> feat(@clayui/label): use a hybrid API appraoch to expose low-level components

- packages/clay-localized-input/.yarnrc
- packages/clay-localized-input/README.md
- packages/clay-localized-input/package.json
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/__tests__/index.tsx
- packages/clay-localized-input/src/index.tsx
- packages/clay-localized-input/stories/index.tsx
- packages/clay-localized-input/tsconfig.declarations.json
- packages/clay-localized-input/tsconfig.json
Hey @kresimir-coko, I made some changes on top of your PR which was mostly just refactoring and chaniging the API a bit. This way we provide a very controlled interface for users but also give flexibility if they need to do anything custom. 
Could you go through and review this and then could you additionally add some unit tests to verify our functionality
Let me know if you have any questions!
> chore(@clayui/form): refactor LocalizedInput

- packages/clay-css/src/scss/mixins/_grid.scss
> feat(@clayui/css): Mixins `clay-container` and `clay-row` should use `clay-css` mixin

- packages/clay-css/src/scss/atlas/variables/_forms.scss
> fix(clay-css): 2.x Forms small form elements should have 4px border-radius

- packages/clay-localized-input/stories/index.tsx
Fixes [3115](https://github.com/liferay/clay/issues/3115)
> fix(@clayui/localized-input): Add missing spritemap value for Localized Input story

- clayui.com/content/docs/components/text-input-localizable.mdx
- clayui.com/src/components/clay/LocalizableInput.js
- packages/clay-localized-input/src/index.tsx
Fixes #3104 .
@bryceosterhaus things to note:
- Naming inconsistencies, `Localized` and `Localization` keeps getting mixed around so I didn't make a decision there
- The `textarea` prop isn't consumed anywhere in the implementation
> feat(clayui.com): Add Localized Input Documentation

- packages/demos/stories/TableColumnsDragDrop.tsx
- packages/demos/stories/TableRowsDragDrop.tsx
- packages/demos/stories/index.tsx
Hey @bryceosterhaus I've drafted a PR with 2 commits:
- Demos Commit is the one that I've tackled first thinking that's the requirement of the task, but then I figured out that your sentence "Feel free to get creative with it and make a "real" table that has drag and drop." might mean to give users of ClayTable an option to support DnD via a `draggable` prop. So in demos is an example of having a DnD Table but, at least IMO that doesn't really help our users as much as it could, it just gives them an example of how to use it.
- The @clayui/table commit is my proposition of how the API could look without investing too much time into making a working example as I'm unsure what're the exact requirements of the task.
Let me know which of the commits to pursue and polish. In case you wanna …
> feat(@clayui/demos): Drag and drop demo for table columns and rows

- clayui.com/content/docs/components/css-tables.md
Fixes #2201 
I believe this is what the requirements of the issue are, just removing all of the non-necessary titles from various table cells, like `title` which should never need it, but leaving titles for long values like `Wings eu, pumpkin spice robusta, kopi-luwak mocha caffeine froth grounds`. If I've misunderstood the issue feel free to clarify.
> chore(clayui.com): Remove titles from Table CSS/Markup examples from various elements

- clayui.com/content/docs/components/Panel.mdx
- clayui.com/content/docs/components/css-panel.md
Fixes #3122 
Hey @bryceosterhaus I've added the Markup docs for the Panel here. I couldn't figure out how to give panels the ability to collapse and show. I tried looking into other examples to find traces of javascript being hooked to it, but I couldn't find anything relevant. So yea, this is missing the actual ability to collapse the panels.
> feat(clayui.com): Add CSS/Markup docs for Clay Panel

- packages/clay-modal/src/Body.tsx
- packages/clay-modal/stories/index.tsx
Hey @bryceosterhaus & @matuzalemsteles is this what we want from the [issue](https://github.com/liferay/clay/issues/3111)? I included a usage example to showcase how I think it will get used. I picked up the pattern from other places that we have on Clay, like ClayTabs etc.
> feat(@clayui/modal): Add iFrameProps to ModalBody

- packages/clay-card/stories/index.tsx
PR for #3142 
LMK if anything can be improved. There are some parts where I had to use a lot of HTML instead of Clay components, not sure if we can fix that somehow, maybe by adding more small, highly reusable components. For example this excerpt, specifically the `c-mb-3` container, the `card-subtitle`, and some others used in the demo:
```jsx
<div className="c-mb-3">
<div className="card-subtitle" title="AR385672">
<span className="text-truncate-inline">
<span className="text-truncate">{'AR385672'}</span>
</span>
</div>
...
</div>
```
> feat(@clayui/card): Add Product Card story to ClayCard

- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
fix(@clayui/css): Mixins `clay-dropdown-item-variant` and `clay-dropdown-menu-variant` deprecated keys should win to preserve backward compatibility
feat(@clayui/css): Mixin `clay-dropdown-menu-variant` adds `enabled` to prevent styles from being output for a specific close variant. This is set to `true` by default.
issue #3075
> feat(@clayui/css): Mixin `clay-dropdown-menu-variant` and `clay-dropdown-item-variant` use `clay-css` mixin to generate properties

- packages/clay-css/src/scss/mixins/_close.scss
- packages/clay-css/src/scss/mixins/_modals.scss
feat(@clayui/css): Mixin `clay-close` should match `clay-link` to preserve compatibility.
feat(@clayui/css): Mixin `clay-modal-variant` should use `clay-close` to generate `.close` properties
feat(@clayui/css): Mixin `clay-modal-variant` add option to passin base selector styles
feat(@clayui/css): Mixin `clay-modal-variant` adds `enabled` to prevent styles from being output for a specific close variant. This is set to `true` by default.
fix(@clayui/css): Mixin `clay-modal-variant` deprecated keys should win to preserve backward compatibility
issue #3075
> feat(@clayui/css): Mixin `clay-modal-variant` should use `clay-css` mixin to generate properties

- packages/clay-css/src/scss/mixins/_panels.scss
feat(@clayui/css): Mixin `clay-panel-variant` adds options `header`, `header-collapsed`, `header-c-inner`, `title`, `collapse-icon`, `body`, `footer`
feat(@clayui/css): Mixin `clay-panel-variant` adds `enabled` to prevent styles from being output for a specific close variant. This is set to `true` by default.
fix(@clayui/css): Mixin `clay-panel-variant` deprecated keys should win to preserve backward compatibility
issue #3075
> feat(@clayui/css): Mixin `clay-panel-variant` should use `clay-css` mixin to generate properties

- packages/clay-css/src/scss/mixins/_tbar.scss
feat(@clayui/css): Mixin `clay-tbar-variant` adds options `btn-c-inner`, `btn-monospaced-c-inner`, `link-c-inner`, `link-monospaced-c-inner`
fix(@clayui/css): Mixin `clay-tbar-variant` deprecated keys should win to preserve backward compatibility
issue #3075
> chore(@clayui/css): Mixin `clay-tbar-variant` follow `map-merge` pattern in other mixins

- packages/clay-css/src/scss/mixins/_utilities.scss
fix(@clayui/css): Mixin `clay-autofit-row` deprecated keys should win to preserve backward compatibility
fixes #3075
> feat(@clayui/css): Mixin `clay-autofit-row` should use `clay-css` mixin to generate properties

- packages/clay-css/src/scss/mixins/_stickers.scss
feat(@clayui/css): Mixin `clay-sticker-variant` adds option `sticker-overlay` to generate properties for `.sticker-overlay`
feat(@clayui/css): Mixin `clay-sticker-variant` adds option `sticker-outside`, `sticker-outside-bottom-left`, `sticker-outside-bottom-right`, `sticker-outside-top-right`
feat(@clayui/css): Mixin `clay-sticker-variant` adds `enabled` to prevent styles from being output for a specific close variant. This is set to `true` by default.
fix(@clayui/css): Mixin `clay-sticker-variant` deprecated keys should win to preserve backward compatibility
issue #3075
> feat(@clayui/css): Mixin `clay-sticker-variant` should use `clay-css` mixin to generate properties

- clayui.com/src/pages/404.js
- clayui.com/src/styles/_404-page.scss
- clayui.com/src/styles/main.scss
This is my proposal for an initial implementation of a custom 404 page for clayui.com.
It's pretty basic but I think it gets the job done. I wasn't sure if using a different font is something we are "allowed" to use, and also I wasn't sure where to get some illustrations, so that's why it looks barebones.
@pat270 can you check the layout and the styles I used, and point out any mistakes in that regard?
@esanzp do you know who we could ask for some illustrations (some pre-existing ones) to maybe spice up this page?
> feat(clayui.com): Add a custom 404 page

- .github/workflows/stats.yml
- package.json
I realized that there was no need to add a bundle step since size-limit can already test that with a vanilla webpack bundle. I think using size-limit alone will give a more realistic idea of sizes.
I also realized you can run `yarn sizeLimit --why` to see a graph of all our dependencies.
> chore: lower size limit boundary and remove bundle step

- packages/clay-data-provider/stories/index.tsx
- packages/clay-form/INPUT.mdx
- packages/clay-form/README.mdx
- packages/clay-form/src/Form.tsx
- packages/clay-form/src/Input.tsx
- packages/clay-link/README.mdx
- packages/clay-link/src/index.tsx
- packages/clay-upper-toolbar/README.mdx
- packages/clay-upper-toolbar/src/index.tsx
Issue #3209 
In this PR I've improved/fixed API tables for the components that need it:
- Form
- Input
- Link
Took me a while to figure out that `componentName.displayName = 'newName'` is a thing that makes these things work.
> feat(clayui.com): Improve API docs of Form, Input & Link components

- clayui.com/src/templates/docs.js
Hey @bryceosterhaus this brings back the Icon's missing page, as noted in #3215.
I've manually checked some pages to see if this doesn't break anything, and I haven't noticed any problems. The problem was in the `tab && tab.html` check not returning true in the case of Icon because it's the only page that has an `.mdx` file for the Markup/CSS page because it needs to have a search functionality.
> fix(clayui.com): Fix missing Icon Markup/CSS page

- packages/clay-layout/.yarnrc
- packages/clay-layout/README.md
- packages/clay-layout/package.json
- packages/clay-layout/src/Col.tsx
- packages/clay-layout/src/Container.tsx
- packages/clay-layout/src/ContainerFluid.tsx
- packages/clay-layout/src/Content.tsx
- packages/clay-layout/src/Row.tsx
- packages/clay-layout/src/Sheet.tsx
- packages/clay-layout/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-layout/src/__tests__/index.tsx
- packages/clay-layout/src/index.tsx
- packages/clay-layout/stories/index.tsx
- packages/clay-layout/tsconfig.declarations.json
- packages/clay-layout/tsconfig.json
Here is my initial idea for the low-level components of row, col, and container.
cc @pat270 can you checkout the demos on storybook and verify these make sense?
> feat(@clayui/layout): create low-level layout utilities

- clayui.com/src/templates/docs.js
- packages/clay-badge/README.mdx
- packages/clay-breadcrumb/README.mdx
- packages/clay-breadcrumb/docs/index.js
- packages/clay-form/DUAL_LIST_BOX.mdx
- packages/clay-loading-indicator/README.mdx
- packages/clay-localized-input/README.mdx
- packages/clay-multi-step-nav/README.mdx
Addresses some components listed in #3210 
@bryceosterhaus I decided to send this halfway through to make it easier to review and iterate over. I'll be working on the other half of the components listed in the issue next.
- Add content where it was missing
- Rename `badges` to `badge`
- Rename `text-input-localizable` to `localized-input`
- Update headings to start at h1 (amount of `#` in Markdown)
- Update some navigations where it was needed
- Badges
- Breadcrumbs
- Dual List Box
- Loading Indicator
- Localized Input
- Multi Step Nav
Localized Input is missing prop to render textarea, this example was included in the Markup/CSS page but we had no support for that. So I removed the example with the idea of eventually adding it back when we add a prop to the component.
> feat(clayui.com): Update content of some components

- packages/clay-date-picker/README.mdx
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/index.tsx
> feat(@clayui/date-picker): add props to control expand functionality

- packages/clay-tabs/README.mdx
- packages/clay-tabs/src/index.tsx
> feat(@clayui/tabs): add TabPanel as an alias for TabPane

- packages/clay-alert/src/index.tsx
As per @wincent's report: #3281 I'm making the default `autoClose` interval 10 seconds instead of 8. Pretty self-explanatory, I've checked the docs, stories and tests for mention of the interval but found nothing, so this should all be self-contained within this one file.
> fix(@clayui/alert): Make the default autoClose interval 10 seconds instead of 8

- clayui.com/content/docs/examples.mdx
- clayui.com/content/docs/storybook.md
- clayui.com/src/pages/index.js
Hey @matuzalemsteles @jbalsas here's a draft for the Examples page.
- I included a couple screenshots I took manually, and the rest are placeholder images.
- I added some copy that we can expand on/alter or whatever, describing Storybook and how we use it
- The examples I added are just the Demos we have, not all components, as I don't think we want all components as that would duplicate all the examples we have in component-specific docs
- We might need some illustrations instead of screenshots to showcase the examples, as they are visually quite complex for the low resolution, at least the ones I decided to showcase
- If we do want to have a component frontpage like in [Carbon Design](https://www.carbondesignsystem.com/components/overview/) we can utilize the Component homepage for that …
> feat(clayui.com): Add documentation for examples in form of list of links to their stories

- clayui.com/plugins/gatsby-remark-api-table/index.js
- packages/clay-button/README.mdx
- packages/clay-date-picker/README.mdx
Fixes #3228 
Hey @bryceosterhaus can you please review this.
I've done the following as part of this PR:
- Add `id="api-${key}"` to the `tr` that's being constructed by the `gatsby-remark-api-table` plugin
- Add all the DatePicker subcomponents to the APITable of DatePicker because some of them were being referenced so I assumed that was the right course
- Note: most of these are missing descriptions/JSDoc
- Reword a couple sentences in Button and Date Picker to match these, now fixed, links to API props
> fix(clayui.com): Fix links that pointed to APITable but didn't work

- packages/clay-list/README.mdx
- packages/clay-list/package.json
- packages/clay-list/src/Header.tsx
- packages/clay-list/src/Item.tsx
- packages/clay-list/src/List.tsx
fixes #3295
I wasn't able to find a great way to force child elements to render an `li` element. I read a handful of places that people recommended setting the type to ReactElement with specific props, and then I also added a warning for if the child is not a Item or Header.
I'm open to other ideas here as well.
> fix(@clayui/list): add dev warning to ensure child elements

- clayui.com/content/docs/get-started/using-clay-in-jsps.md
Hey @bryceosterhaus this PR addresses #3286, and it aims to fill some initial documentation requirements for our users that want to use Clay in JSPs.
-  I took inspiration from [Liferay Help Center](https://help.liferay.com/hc/en-us/articles/360017888252-Using-the-Clay-Taglib-in-Your-portlets) when it comes to text
-  I referenced [liferay-clay.tld](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/liferay-clay.tld) to get the list of components that exist as tags
-  Badge, Icon, Label & Sticker are for some reason marked as deprecated, making me think that Clay doesn't support them 😕 
-  Stripe & Sheet are mentioned but we don't have them on clayui.com 🤷
> feat(clayui.com): Document using Clay in JSPs

- packages/clay-date-picker/README.mdx
- packages/clay-date-picker/docs/index.js
- packages/clay-date-picker/package.json
- packages/clay-date-picker/src/DateNavigation.tsx
- packages/clay-date-picker/src/DayNumber.tsx
- packages/clay-date-picker/src/Helpers.ts
- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/InputDate.tsx
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/index.tsx
- packages/demos/stories/Recharts.tsx
- yarn.lock
I went with a POC in removing moment by replacing it with ~luxon~ date-fns. We still have a dependency, but its about 50kb smaller than when we used moment.
One caveat is that the "format" strings are different, so that would be a breaking change, although we could create some sort of map.
Additionally, I want to see if it'd be possible to just use native APIs, so I will continue on that and see what it requires.
Curious to hear any thoughts on this
~**1st commit is using luxon**~
~**2nd commit is using date-fns**~
> fix(@clayui/date-picker): remove moment.js

- packages/clay-link/src/index.tsx
- packages/clay-link/stories/index.tsx
- tsconfig.json
fixes #3301
Here is a POC of adding ClayLink to Button so that we can render both links as buttons and buttons as links.
Any concerns with this?
> feat(@clayui/link): add ability to style link like a button

- packages/clay-shared/src/FocusScope.tsx
fixes #3332
I ran this through a handful of manual tests and seems to fix the problem while also maintaining previous functionality.
@matuzalemsteles, can you think of any edge cases this would break?
> fix(@clayui/shared): only preventDefault if next/previous node exists in the focusManager

- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-upper-toolbar/src/__tests__/__snapshots__/index.tsx.snap
Hey @bryceosterhaus, I took this trying to identify some performance problems that were making the Forms editing very slow in App Builder, I think this is not the root cause but I realized that it was eating 20ms in every rendering that happened. I added this fix on my local machine to test it, inside the Portal to see how it would flow, apparently saving 20ms each rendering helped a lot to take away the impression of slowness when trying to edit a Text in App Builder as a result in Forms too. This is in the migration I'm doing to React.
Some images, this is before this fix: You can see that there are many long tasks, all of which are based on a React keypress event, in the end, there are 20ms of domAlign.
Another image after this fix: You can see that the duration of tasks is shorter and …
> fix(@clayui/drop-down): fixes the side effect of recalculating domAlign with each rendering

- packages/clay-css/src/content/test_reboot.html
- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/atlas-variables.scss
- packages/clay-css/src/scss/atlas.scss
- packages/clay-css/src/scss/base-variables.scss
- packages/clay-css/src/scss/base.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/components/_type.scss
issue #3149
List of changes to Bootstrap's Reboot:
- We don't need to set `font-family`, `line-height` on the `html` element already set on `body`
- Don't set `text-align: left` on `body` due to RTL issues. See #1743
- Remove `:focus-visible` future-proof rule (very experimental https://caniuse.com/#search=focus-visible)
- Remove uses of Bootstrap's `font-size` and `hover` mixin, we don't support it in Clay CSS
- Remove Bootstrap's `text-align` reset on `th`. See #2219
- Remove Bootstrap's "hand" cursor to non-disabled button elements. We don't support `$enable-pointer-cursor-for-buttons`. We can change the cursor to whatever we want in Clay CSS.
- Use selector `[href]` for styling anchor links instead of `a` so we don't need to overwrite placeholder anchor styles with `a:not([href])`. …
> feat(@clayui/css): Absorb Bootstrap 4 _reboot.scss

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_grid.scss
feat(@clayui/css): Grid use placeholder `%container-fluid` and extend that instead of `.container-fluid` so unused selectors and CSS aren't output
feat(@clayui/css): Grid don't use Bootstrap's grid mixins to output styles for `.row`, `.col-*-*`, `.container` because they are called only once
feat(@clayui/css): Grid use `!optional` flag for all `@extend` directives so it doesn't error if placeholder doesn't exist
issue #3149
> feat(@clayui/css): Absorb Bootstrap 4 _grid.scss into Clay CSS

- clayui.com/content/docs/get-started/using-clay-in-jsps.md
Fixes #3400 
Pretty basic, we left the `draft` status on this page to `true` in it's early stages and forgot to remove it once the page was ready.
> fix(clayui.com): Make Using Clay in JSPs page not draft so it shows up in the navigation

- packages/clay-card/package.json
- packages/clay-card/src/CardWithNavigation.tsx
> Open Storybook on CardWithNavigation story: https://storybook.clayui.com/?path=/story/components-claycard--cardwithnavigation, try to focus the onClick card and then press SPACE or ENTER key.
The original behaviour is when a button is focused, this element be triggered by SPACE or a ENTER key but when using a div with a role="button" this isn't possible.
I needed to hack the onKeyDown event for detecting a SPACE or ENTER keydown event passing the event of keydown for these keys to onClick callback.
Is there a way for avoiding using a div with a role="button" attribute? /cc @pat270
See https://twitter.com/scottohara/status/1183020913509502978
Closes #3365
> fix(@clayui/card): When pressing `enter` or `space`, triggers a click event on CardWithNavigation

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/Provider.tsx
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/__tests__/index.tsx
- packages/clay-modal/stories/index.tsx
Fixes #3414
We apparently missed this use case when we were building this component or it was a recent change to Lexicon. 🤷‍♂️
> feat(@clayui/modal): Adds a new `center` API to vertically center the modal

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_jumbotron.scss
> feat(@clayui/css): Absorb Bootstrap's _jumbotron.scss into Clay CSS

- packages/clay-button/docs/index.js
Addendum to #3444 
Initial implementation had a couple small issues that I caught when adding the Icon JSP code example, this fixes them:
- The JSP example textarea had to be disabled
- React imports weren't being showed because the Editor API expects the imports to be defined inside the code object
- Excess empty lines that were at the end of code strings
> fix(clayui.com): Fix Button JSP code example

- packages/clay-date-picker/src/DayNumber.tsx
1. Open our Date Picker component on storybook: https://storybook.clayui.com/?path=/story/components-claydatepicker--default
2. Navigate thru days using tabs and select a day using SPACE key
3. Navigate faster thru days and try to select multiple days using SPACE key
4. You will able to select multiple days when using SPACE key
----
For solving this problem, the keyDown event when the space key is pressed was prevented and when keyUp, the click callback was called.
- chore(@clayui/date-picker): Prefer destructuring
- fix(@clayui/date-picker): When selecting a date using space key, removes properly the `:active` state of the element. This issue can't be reproduced on IE/FF but it can be reproduced on Chrome/Safari. Apparently this is a WebKit issue
Closes #3374
> fix(@clayui/date-picker): When selecting a date using space key, removes properly the `:active` state of the element

- packages/clay-alert/docs/index.js
Fixes #3425 
I used simple values within the JSP code example instead of `Liferay.Language.get(...)`.
I also added `clay:stripe` in here, and made the JSP code example match the 2 alerts in the React example.
> feat(clayui.com): Add JSP code example to Alert

- packages/clay-icon/docs/index.js
Fixes #3447.
Apart from the title, I removed an empty line from React code import because it was creating a double empty line, making the spacing between imports and code bigger than it's supposed to be.
> feat(clayui.com): Add JSP code example to Icon

- packages/clay-date-picker/package.json
- packages/clay-date-picker/src/index.tsx
- packages/demos/stories/FormPage.tsx
> Add a ClayDatePicker to the Storybook Form Page Demo
Note that when opening the Date Picker calendar using SPACE, we were unable to focus any elements within the DatePicker using TABS.
---
To solve this problem, I used FocusScope and fixed the Focus problem when opening the Date Picker Calendar.
When going through the entire focus, the Focus scope does not close the component and focuses on the next component in the DOM tree (which is still right 🤔)
When closing the Date Picker Calendar by pressing the ESC key, the next element to focus according to the focus scope is the closest element to the document.body (where the ClayDropDown.Menu element portal was opened) making the focus stay on the submit.
- docs(@clayui/date-picker): Adds a DatePicker on FormPage story
- …
> fix(@clayui/date-picker): Adds FocusScope for an appropriated tab navigation on DatePicker's calendar

- packages/clay-css/gulpfile.js
- packages/clay-css/src/scss/_license-text.scss
- packages/clay-css/src/scss/components/_print.scss
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
fix(@clayui/css): `gulp version` use the s flag to make `.` match everything including newlines instead of `[\s\S]`, remove excess escaping of double quote, and use more robust `+` instead of `*`
issue #3437 
@wincent
> fix(@clayui/css): Adds leading whitespace for License texts

- packages/clay-data-provider/BREAKING.md
- packages/clay-data-provider/README.mdx
- packages/clay-data-provider/src/__tests__/index.tsx
- packages/clay-data-provider/src/types.ts
- packages/clay-data-provider/src/useResource.ts
- packages/clay-data-provider/stories/index.tsx
This PR introduces two changes and at the same time improvements for cache validation for custom fetch cases, this is explained better in the documentation.
- Deprecates the behavior of the `link` API to accept an async function (Throws a warning if used)
- Adds the new API `fetcher`
The `fetcher` API facilitates the custom fetch use cases and improves the cache validation when used, mainly for the Portal use cases that we need to use the `fetch` from ` frontend-js-web`.
```javascript
import {fetch} from 'frontend-js-web';
useResource({
fetcher: fetch,
link: 'https://clay.data/',
}); 
```
> feat(@clayui/data-provider): Adds the new fetcher API and deprecated the link behavior in accepting async function

- packages/clay-modal/src/Hook.ts
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
Fixes #3107
This removes the extra container that we were adding before. I did some tests with a DropDown being rendered and other bugs that we got related to that and it works well. The strange thing is that I have the feeling that I’ve done this before and I don't remember the reason why I didn't do it 🤷‍♂️.
Thanks @pat270 for helping me with this!
> fix(@clayui/modal): simplifies subportal grouping implementation and removes the extra container

- packages/clay-css/src/scss/components/_reboot.scss
> fix(@clayui/css): Reboot makes `use[href]` inherit parent styles

- packages/clay-css/.gitignore
- packages/clay-css/gulpfile.js
- packages/clay-css/package.json
issue #3282 
Hey @bryceosterhaus, I ended up adding a gulp task (`gulp copy:licenses`) that runs when `gulp compile` is run. It copies the licenses used by Clay CSS into `clay-css/LICENSES`. We should include this directory when we publish. I can add a commit to do that, I just don't know where.
I had a hard time trying to figure out `ncp dir1 dir2 --filter=""`.  My conclusion is that it's bugged.
> chore(@clayui/css): Copy Licenses from root to clay-css/LICENSES

- clayui.com/content/docs/components/css-color-picker.md
- packages/clay-css/src/scss/components/_clay-color.scss
- packages/clay-css/src/scss/components/_form-validation.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/variables/_clay-color.scss
docs(clayui.com): css-color-picker adds examples of color-picker with `.form-group-sm` and `.input-group-sm`
fixes #3514
> feat(@clayui/css): Clay Color should support `.input-group-sm` and `.form-group-sm`.

- packages/clay-color-picker/README.mdx
- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/index.tsx
- packages/clay-css/src/scss/variables/_clay-color.scss
fix(@clayui/color-picker): Removes fixed sizes for Splotch
fixes #3514
Not related to this issue, but I was wondering why we use a hidden input to store the color value when we already have an input in the `input-group`? Can't we just use that one?
> fix(@clayui/color-picker): Add option to make Color Picker small

- packages/clay-card/package.json
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-date-picker/src/DayNumber.tsx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/hooks.ts
- packages/clay-form/package.json
- packages/clay-form/src/SelectBox.tsx
- packages/clay-modal/src/Hook.ts
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-shared/src/FocusScope.tsx
- packages/clay-shared/src/Keys.ts
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useFocusManagement.ts
- packages/clay-time-picker/src/__tests__/index.tsx
- packages/clay-time-picker/src/index.tsx
Some keys can be different depending the browser which is being running the application but React normalize it when creating the synthetic event on: https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/events/getEventKey.js#L12-L29
Regarding
> but React normalize it when creating the synthetic event
From https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values: 
>[1] Older browsers may return "Spacebar" instead of " " for the Space Bar key. Firefox did so until version 37, as did Internet Explorer 9, 10, and 11.
Spacebar: 
https://github.com/liferay/clay/pull/3513/files#diff-18ecf9fd4dc1fbbb2a2bff5e734cc990L52
1. Open our Storybook on IE11
2. Open ClayCardWithNavigation story
3. Try navigating via tabs and select the …
> chore: Replace `keyCode` usages with `key` for KeyboardEvents

- packages/clay-breadcrumb/package.json
- packages/clay-card/package.json
- packages/clay-color-picker/package.json
- packages/clay-data-provider/package.json
- packages/clay-date-picker/package.json
- packages/clay-drop-down/package.json
- packages/clay-form/package.json
- packages/clay-multi-select/package.json
- packages/clay-nav/package.json
- packages/clay-navigation-bar/package.json
- packages/clay-pagination-bar/package.json
- packages/clay-pagination/package.json
- packages/clay-panel/package.json
- packages/clay-popover/package.json
- packages/clay-tabs/package.json
- packages/clay-time-picker/package.json
- packages/clay-tooltip/package.json
Current upstream is failing "Verify Dependencies" since we updated and publish shared and modal independently without updating packages that were dependent on them
> fix: update packages to appropriate dependencies

- packages/clay-css/src/images/icons/closed-book.svg
- packages/clay-css/src/scss/functions/_global-functions.scss
Due to [LEXI-962](https://issues.liferay.com/browse/LEXI-962) we've decided to add a new icon to represent a Collection in DXP. 
This is a complex concept because 1 or more collections can be part of an asset library. Thus we have decided to design the icon thinking the relationship with the asset library icon (_books_). In addition, we also added a little bookmark in anticipation of the icon for adding/saving elements to a Collection. 
@pat270 I named it _closed-book_ what do you think? I would have liked to name it book-closed but checking the other book icon (_info-book_) it's wiser to follow that naming order, isn't?
> feat: Icon for Collections in DXP

- packages/clay-css/src/scss/atlas/variables/_alerts.scss
fixes #3557 
@drakonux We decided to change the `font-size` in Clay CSS because we would have to change the icon name in too many places.
> fix(@clayui/css): Atlas Alerts change `.alert .close` font-size to 12px

- CONTRIBUTING.md
fixes #3544
This is just a general idea for now. I think ideally we could find a more automated process for releasing one-off packages.
> docs: update release process for one-off packages

- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/stories/index.tsx
- packages/clay-list/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-sticker/docs/index.js
- packages/clay-sticker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-sticker/src/__tests__/index.tsx
- packages/clay-sticker/src/index.tsx
- packages/clay-sticker/stories/index.tsx
fixes #3541
I also added a new API to allow for imgs directly instead of custom classes and child elements.
> docs(@clayui/sticker): fix bad example

- packages/clay-css/src/scss/atlas/variables/_alerts.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/variables/_alerts.scss
feat(@clayui/css): Alerts adds Sass maps `$alert-btn-group`, `$alert-fluid`, `$alert-fluid-container`, `$alert-fluid-dismissible-container`, `$alert-notification`, `$alert-notification-sm-down`
feat(@clayui/css): Alerts use `clay-css` mixin to output styles
fixes #3558
@drakonux regarding
> there is a good reason to have distances not multiple of 8px (maybe the Lexicon team did a visual change agreed with you or similar)
Distances multiples of (4px or 8px) along with sizes multiple of (4px or 8px) doesn't always work out because CSS Box Model is margin + border + padding + content. Regular one line alerts (56px height in Lexicon) with border 1px, padding 16px, and content 21px is 55px (1px + 1px + 16px + 16px + 21px). We can hack around the Box Model by using `box-shadow` to make borders …
> fix(@clayui/css): Atlas Alerts adjust spacing to match Lexicon specs

- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
Fix for https://issues.liferay.com/browse/LPS-118116
> fix(@clayui/multi-select): key should be ',' instead of 'Comma'

- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/index.tsx
Hey @victorg1991, is this what you would expect for https://github.com/liferay/clay/issues/3527? Check out the storybook demo https://5f2322ebba586a00071c8a01--next-storybook-clayui.netlify.app/?path=/story/components-claycolorpicker--custom-w-o-palette
> feat(@clayui/color-picker): add prop for disabling palette for custom colors

- packages/clay-css/src/scss/atlas/variables/_drilldown.scss
fix(@clayui/css): Atlas Drilldown variables removes unused `$drilldown-item-header`
fixes #3576
> fix(@clayui/css): Atlas Drilldown header button is off by 1px

- packages/clay-css/src/content/test_reboot.html
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/components/_type.scss
Placeholders are styled the same as links now which makes it easier to use markup like `<a class="btn btn-primary" role="button" tabindex="0">` without having to add styles.
`hr` was not showing a horizontal line due to sorting properties by alphabetical order
fixes #3568 and https://issues.liferay.com/browse/LPS-118088
> fix(@clayui/css): Reboot go back to Bootstrap 4's styling `a` tag directly but omit styling placeholder anchors

- clayui.com/content/docs/components/css-dropdown.md
- clayui.com/content/docs/css/content/c-kbd.md
- packages/clay-css/src/content/dropdowns.html
- packages/clay-css/src/content/typography_kbd.html
- packages/clay-css/src/scss/components/_type.scss
- packages/clay-css/src/scss/variables/_type.scss
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd#Representing_keystrokes_within_an_input is the reason for this update.
fixes #3283
> fix(@clayui/css): C Kbd each key in a keyboard shortcut should be wrapped in its own `kbd` element

- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-modal/src/Body.tsx
- packages/clay-popover/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-popover/src/index.tsx
Fixes #3581 
I took a different approach to Modal and maybe we can replicate for Popover, unfortunately, I still need `tabIndex` and I'm also using `c-inner` to remove the outline, as suggested by @pat270.
The case of Modal is that its content is not controllable, so there may be focusable elements or not, so it is still necessary to support that the container scroll is done via keyboard using Up/Down, so I using the strategy of when the keyboard of Up/Down is pressed to change the focus to the body, so it will be possible to scroll and remove it from the focus order and we have a behavior similar to the page scroll.
For Modal's case, this makes sense since when Modal is open it removes the scroll from the page but for Popover's case, we still need to deal with it better.
> fix(@clayui/modal): Changes the body's tabIndex with scroll and focuses on the element only when pressing the Up/Down keyboard

- packages/clay-css/src/scss/components/_tables.scss
> fix(clay-css): 2.x Table `.table` should have 1px borders

- packages/clay-css/src/scss/atlas/variables/_tables.scss
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/src/scss/variables/_tables.scss
fix(@clayui/css): Table `.table` should have 1px borders
feat(@clayui/css): Table adds Sass maps `$c-table-base` and `$c-th-base` for styling base `table` and `th` elements
fix(@clayui/css): `variables/_globals.scss` and `components/_reboot.scss` rename `$c-button` Sass map, added in #3575, to `$c-button-base`. This namespace references a base element, in this case, `<button>`. This is to free up the variable namespace `$c-button` to refer to `.button` if we ever need it in the future.
fix(@clayui/css): Table use function `clay-enable-rounded` to support `$enable-rounded` variable instead of Bootstraps `border-radius` mixin / inlining `if` check
chore(@clayui/css): Table reorganize `$table-list-*` variables so properties for `.table-list` are grouped together
fixes #3592
> fix(@clayui/css): Table `.table` should have 1px borders

- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
fixes #3524
This addresses several issues with native mode
1. Native shoudl now work across browsers
3. If browser is IE11, we use don't use type="color" since it is not supported
One change was for type="color", we were using hex values without the hash, however this wrong since the html specification says the value must include a hash.
> fix(@clayui/color-picker): fix native usage across browsers

- packages/clay-color-picker/src/index.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/hooks.ts
fixes #3539
> We should normalize where the focus is placed when closing a color picker menu via keyboard. I think it should always return to the dropdown toggle splotch when the menu closes with esc or enter.
> fix(@clayui/color-picker): splotch should get focus if menu is closed via 'esc'

- packages/clay-localized-input/package.json
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/index.tsx
fix(@clayui/localized-input): Language Dropdown Toggle should display selected locale text and use `btn-secondary`
fix(@clayui/localized-input): `input-group-prepend` adjacent sibling should have `input-group-append`
fix(@clayui/localized-input): ClayInput should have attribute `type="text"` because devs sometimes use the CSS selector `input[type="text"]` to style all text inputs
fixes #3591
> fix(@clayui/localized-input): Dropdown Item should use autofit pattern to position labels

- clayui.com/plugins/gatsby-remark-use-clipboard/index.js
- clayui.com/src/components/CodeToggle/index.js
- clayui.com/src/styles/_code.scss
Fixes #3610 
Single commit in this PR touches on 3 files:
- `gatsby-remark-use-clipboard/index.js`: I've added the HTML to display the text
- `CodeToggle/index.js`: rename `isCodeCollapse` to `isCodeCollapseBtn` as it confused me for some time, to explicitly say it means that it references the button, not a state
- `styles/_code.scss`: Styles for this `span`, initially I went with the classic Bootstrap classes, but I needed to add `z-index` which I didn't find covered by a class in the docs, so I moved it all into CSS
> feat(clayui.com): Add Code Sample Info to HTML/CSS collapsed code samples

- clayui.com/content/docs/components/css-forms-hierarchy.md
- clayui.com/content/docs/css/content/index.md
- clayui.com/content/docs/css/utilities/index.md
- clayui.com/content/docs/examples.mdx
- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/templates/blog.js
- clayui.com/src/templates/docs.js
- chore(clayui.com): Supress console warning `A page wasn't found for index.html`
- fix(clayui.com): `/docs/examples.html` links are prefixed with `https://clayui.com/`
- fix(clayui.com): A page wasn't found for "/docs" message in browser console (hover over Docs on top nav)
- fix(clayui.com): Blogs `Warning: ClayIcon requires a `spritemap` via prop or ClayIconSpriteContext` in console (`yarn develop`)
- fix(clayui.com): Removes `13:7  warning  'spritemap' is assigned a value but never used  no-unused-vars` from blog.js (`yarn develop`)
> fix(clayui.com): Random fixes

- packages/clay-localized-input/stories/index.tsx
Fixes #3605 
Pretty simple fix, for the sake of simplicity when I made the story initially, I had two inputs share the same state as not to clutter the code. Now I added a set of states for the 2nd input as well, and also removed the old notice header.
> fix(@clayui/localized-input): Add separate state for the URL example and SF

- packages/clay-css/src/content/tables.html
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
`table-list` should now work for IE11, Chrome, Safari 11+, and FF.  
fixes #3624
@matuzalemsteles @jbalsas @brunobasto
> fix(@clayui/css): Table List use `border-collapse` and `border-width` instead of `box-shadow` hack for rounded corners

- clayui.com/gatsby-browser.js
- clayui.com/src/components/Hooks/useStateWithLocalStorage.js
- clayui.com/src/utils/localStorage.tsx
Fixes #3611 
The goal of this factory function is to standardize the way we use `localStorage`, and even `sessionStorage` in a safe and consistent way.
1. I've thoroughly read and investigated the factory function from this [article](https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/) that @wincent linked in Slack a few days ago. I figured why reinvent the wheel and ported the function into our codebase.
2. I've adapted some small things to our ESLint rules but outside of that the code is the same. I'm unsure how we feel about "stealing" code from articles like this.
3. I tested this in-depth, making sure the site works on master and on my custom branch to make sure it works as intended considering I haven't written the implementation myself.
- `localStorage` is used …
> feat(clayui.com): Add a utility function for Local Storage

- packages/clay-nav/BREAKING.md
- packages/clay-nav/README.mdx
- packages/clay-nav/docs/index.js
- packages/clay-nav/package.json
- packages/clay-nav/src/Trigger.tsx
- packages/clay-nav/src/Vertical.tsx
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-nav/src/__tests__/index.tsx
- packages/clay-nav/stories/index.tsx
- packages/demos/stories/FormPage.tsx
Fixes #2821
@kresimir-coko I went ahead and made some changes, I simplified the `ClayVerticalNav.Trigger` a little so it can be reused for other cases and removes the existing conditionals a little while still maintaining all the use cases. I also added some cases in the documentation and add the warning.
> fix(@clayui/nav): Fix the button that shows the vertical navigation when on mobile

- packages/clay-modal/src/Modal.tsx
Fixes #3643 
Modal window's zIndex is set to the value provided by the user, and the backdrop value is decreased by 10 to maintain the connection between the 2 elements. I've tested this in storybook to make sure both styles are applying properly and overriding the default ones.
> feat(@clayui/modal): Add zIndex prop 

- clayui.com/gatsby/onCreateNode.js
- packages/clay-css/src/scss/variables/_tbar.scss
- packages/clay-toolbar/README.mdx
- packages/clay-toolbar/package.json
- packages/clay-toolbar/src/Input.tsx
- packages/clay-toolbar/src/Label.tsx
- packages/clay-toolbar/src/index.tsx
- packages/clay-toolbar/stories/index.tsx
- packages/clay-upper-toolbar/README.mdx
- packages/clay-upper-toolbar/stories/index.tsx
From #3528
@kresimir-coko I just added a warning to the ClayUpperToolbar document. I realized that the ticket for this is closed, we must create another issue or reopen, I'm not sure if it was closed by mistake.
> feat(@clayui/toolbar): Deprecated ClayUpperToolbar and adds examples with ClayToolbar

- packages/clay-form/docs/radiogroup.js
Fixes #3647 
Simple PR, I made the examples not match the React ones 1:1, but instead opted for more 3 different Radios showcasing all of the available props
> feat(@clayui/form): Add Radio JSP code example

- packages/clay-shared/src/useFocusManagement.ts
Fixes #3656
This is a very specific case that can happen in IE 11 when there are svg elements. We will probably have to make a release and send about the ticket https://issues.liferay.com/browse/LPS-119771.
> fix(@clayui/shared): fixes side effect of focusing on the first element when the active element does not exist in the scope

- packages/clay-color-picker/src/index.tsx
Fixes #3651
This fixes an issue in issue #3651 but we still need to understand the other problem that I cannot reproduce. Marking this as a draft initially to correct the other problems, still ignoring the case of the ColorPicker accepting `transparent`, `red`, `black`... as colors.
> fix(@clayui/color-picker): maintains the value entered by the user when the color is not valid

- packages/clay-drop-down/README.mdx
- packages/clay-drop-down/docs/index.js
Fixes #3649 
So this one is first of it's kind, as it has 2 JSP tags for one component, each represeting a variant.
The `<clay:dropdown-menu />` is the regular dropdown, whereas the `<clay:dropdown-action />` is a dropdown with an `ellipsis-v` icon as the trigger ([source](https://liferay.slack.com/archives/G3JBR21HA/p1598349490107100)).
This is why I added a section in the documentation describing this, while keeping the example simple to reflect the React example.
> feat(@clayui/drop-down): Add JSP code example

- packages/clay-shared/src/useFocusManagement.ts
Fixes #3660
Elements within the scope with `tabindex="-1"` are no longer controlled by the focus manager, previously these elements received focus when tabbing occurred.
> fix(@clayui/shared): ignores elements within the scope with tabindex="-1" from the focus manager

- clayui.com/content/docs/contributing.md
Hey, so this one is pretty simple but that might be not a good thing in this case (I might have made it too simple by not making it generic enough).
I wanted to make it generic so that the check isn't testing against this specific file (`contributing.html`), but I couldn't figure it out within the confines of the `writeRedirectsFile` function.
I attempted changing the `FILE_PATH` conditionally but I couldn't get to a simpler solution than what I ended up with in this PR.
> fix(clayui.com): Fix Contributing page not properly redirecting

- packages/clay-form/src/SelectBox.tsx
- packages/clay-form/src/__tests__/__snapshots__/DualListBox.tsx.snap
- packages/clay-form/src/__tests__/__snapshots__/SelectBox.tsx.snap
- packages/clay-form/stories/index.tsx
Fixes #3682 
I believe I've handled all cases of buttons being disabled except for one, and that is something has been transferred between select boxes but nothing is visually selected. After investigating, I noticed that the transferred item (or items if more have been selected), is kept in the `leftSelected` variable (in the case when transfering from left to right). I couldn't figure out a clean way of resetting the `leftSelected` value back to an empty array.
> feat(@clayui/dual-list-box): Make reorder & transfer button state more consistent

- packages/clay-tooltip/src/TooltipProvider.tsx
This is just an initial implementation of #3696, the problem with this is you can still close DropDown when it is open and there is a Tooltip, so I thought about adding the event in the capture phase so we could get the event first before others but it also depends when the event was added, the order influences, in this implementation here I always add the event when I open the tooltip and then remove it to avoid problems. I think we managed to get around some behaviors within Clay but not something in a DXP world where people can add events and we have no control. Suggestions?
I added the Tooltip to the Button inside the Modal with an Autocomplete in the ClayModal story for testing.
> chore(@clayui/tooltip): close the tooltip when pressing Esc

- packages/clay-nav/src/Vertical.tsx
- packages/clay-navigation-bar/src/__tests__/index.tsx
- packages/clay-navigation-bar/src/index.tsx
- packages/clay-panel/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/src/__tests__/index.tsx
- packages/clay-panel/src/index.tsx
- packages/clay-shared/src/useTransitionHeight.ts
Fixes #3637, From #3677
I made some changes on top of @pat270's PR, instead of implementing a fallback in support of the `transitionEnd` event, I decided to remove it and rewrite the implementation on top of `setTimeout`.
> fix(@clayui/shared): useTransitionHeight should still expand and collapse if transitions aren't supported

- packages/clay-charts/README.mdx
- packages/clay-charts/docs/api-chart.mdx
- packages/clay-charts/src/BillboardWrapper.tsx
- packages/clay-charts/src/GeoMap.tsx
- packages/clay-charts/src/Predictive.tsx
Fixes #3714 
I went ahead and made this super simple in the end after pondering on the offered advice. Only meaningful thing I added is the notice that we're switching to Recharts, which from what I understand we will make a wrapper around, similar to how we did with Billboard?
Other than that, @matuzalemsteles :
> maybe write a documentation explaining better the examples we have in the Storybook and how you can reach the Lexicon specification with recharts.
Not a 100% sure what you meant with this, I do understand the idea behind it, but not sure how to explain the examples as they're pretty basic Rechart charts. As for reaching Lexicon specs, shouldn't Lexicon be enough for that?
> feat(@clayui/charts): Split API into it's file, add notice we're switching to Recharts, and cast props to IProps

- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/index.tsx
fixes #3681
Are there any edge cases I missed here? You should now be able to used named colors and hex values
> feat(@clayui/color-picker): add ability to use named colors

- clayui.com/gatsby/createPages.js
- clayui.com/gatsby/onCreateNode.js
- clayui.com/src/templates/docs.js
- clayui.com/src/utils/getSection.js
- packages/clay-form/CHECKBOX.mdx
- packages/clay-form/DUAL_LIST_BOX.mdx
- packages/clay-form/INPUT.mdx
- packages/clay-form/RADIO_GROUP.mdx
- packages/clay-form/README.mdx
- packages/clay-form/SELECT.mdx
- packages/clay-form/SELECT_BOX.mdx
- packages/clay-form/TOGGLE_SWITCH.mdx
Fixes #3736 
I'm pretty happy with this result, and I learned how the navigation get's prepared and filled up.
It's pretty simple, even though i took me a couple days to get here, but I did the following:
- added a `formPackageMember` to the frontmatter of components that belong to the `@clayui/form` package
- made Form a folder by assigning it in `getSection`, not sure if we can add that too to its frontmatter
- made the Form always open by adding `alwaysActive` to its frontmatter
- move components that belong to `@clayui/form` to that folder and remove them from the regular nav
> feat(clayui.com): Put form components under Form folder in the navigation

- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
In the [ticket LPS-121351](https://issues.liferay.com/browse/LPS-121351), we had a minor visual bug in Windows OS due to the [Bootstrap background image](https://getbootstrap.com/docs/4.5/components/forms/#radios) we were using for the custom radio button and the size of our radio button defined by lexicon. I've updated the image and the size following the [Lexicon specification for radio buttons](https://www.figma.com/file/A7ZNuyNHxj7kzJ6SYwQbQ3/Component-Library-Template-(Intra-Test)?node-id=1096%3A11397) and the [Clay pattern for the custom checkbox](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/atlas/variables/_custom-forms.scss#L105)
__Before:__
__After:__
> fix(@clayui/form): Fix custom radio button image

- clayui.com/package.json
- clayui.com/src/templates/docs.js
- yarn.lock
Fixes #3744 
Let me know if this is a suboptimal location to invoke `svg4everybody`, I tried it in `IconSearch` as that's the component that gets called but there it didn't do anything.
The red flag to me is the need for updating that many snapshots, but it might be okay.
> fix(@clayui/icon): Add svg4everybody to fix long loading of Icons page

- packages/clay-css/src/content/dropdowns_drill_down.html
- packages/clay-css/src/scss/components/_drilldown.scss
- packages/clay-css/src/scss/variables/_drilldown.scss
Alrighty, it took me a bit of digging through my notes to find that in order to see this example I need to fire up a gulp server inside clay-css. We should definitely add that into the GitHub readme thingy.
Once I did get it fired up I realized the main culprit, `dropdown-item` is always the parent of the item, and always has the same `padding`, which makes sense. What doesn't make sense is that it's child in case of simple text, like `Folder` in the above example doesn't have an HTML element wrapped around it, so it's just `<div class="dropdown-item">Folder</div>`.
My proposal is to add another layer of HTML, like a `span` to that `Folder` text, so that we can target `dropdown-item` with CSS and remove the `padding` from it. 
I sent a WIP example of the styles just to get feedback from …
> fix(@clayui/drop-down): Increase clickable area of text and icon

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
Fixes #3752
I have the feeling that we should be avoiding props that serve to pass props to sub-components nested within the high-level... I don't have a strong opinion on that yet but I think we should put it in mind.
> feat(@clayui/card): add API to pass props to the checkbox

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-card/src/CardWithUser.tsx
Fixes #3757
I ended up causing the components to extend the base HTML interfaces to extend the number of props that can be passed to the component so we don't have to add it in the future since `<ClayCard />` already does the same.
> feat(@clayui/card): add support for base HTMLDivElement and HTMLAnchorElement props in high-level components

- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
Fixes #3765 and Fixes #3764
I removed the use of `aspect-ratio-item-fluid` that was being added because it ends up doing the same as `sticker-img`.
> chore(@clayui/card): uses the ClaySticker.Image component internally

- packages/clay-card/BREAKING.md
Stems from discussion at https://github.com/liferay/clay/issues/3773
This gives us a way to remember requests like these when we decide to break at 4.x
> chore: add breaking change note for 4.x

- packages/clay-card/src/Description.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
If the card is disabled, a `span` element will be rendered and no
`href` attribute is required
Fixes #3779
> fix(@clayui/card): Avoid setting `href` on `span` element

- packages/clay-card/package.json
- packages/clay-card/src/CardWithHorizontal.tsx
See the bug description in https://github.com/liferay/clay/issues/3781
In this PR we are replacing vanilla `<button>` with `ClayButtonWithIcon`. It adds `type='button'` by default, preventing form submission.
> fix(@clayui/card): Use ClayButtonWithIcon instead of vanilla button in CardWithHorizontal 

- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
This is a followup on https://github.com/liferay/clay/pull/3794, applying the same change to `ClayCardWithInfo` and `ClayCardWithUser`.
> fix(@clayui/card): Use ClayButtonWithIcon instead of vanilla button in clay-card

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
This PR fixes the bug in https://github.com/liferay/clay/issues/3807
There is no need to update tags on the portal side, we are [already setting](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/DropdownActionsTag.java#L31) the `unstlyed` display style in server-side rendering.
This issue was unnoticed because button styles were overriden by `.component-action` styles, that is why trigger looks correct in the storybook. But, in recent portal changes, higher priority was given to `btn-primary` class, that exposed the issue.
To test without portal, just on storybook:
1. Remove `color` and `background-color` from `.component-action`
2. Compare before and after PR
@julien …
> fix(@clayui/card): Set display type of dropdown triggers to `unstyled`

- packages/clay-time-picker/src/__tests__/index.tsx
- packages/clay-time-picker/src/index.tsx
fixes #3784
fixes #3782
The interactions should now be more consistent with the html native time picker
> fix(@clayui/time-picker): make sure input always has a leading 0 for single digits

- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
Fixes https://github.com/liferay/clay/issues/3816
With this pr we're adding support to pass `stickerProps={null}`, which will cause that the sticker will not be rendered.
In DXP we'll need to add a `showSticker` attribute to `vertical-card`, `file-card` and `image-card` tags, defaults to `true` and in `VerticalCard.js` pass `stickerProps={null}` if `showSticker` is `false`.
We'll need to add `isSticker` method to `VerticalCard.java` model, defaults to `true`.
> fix: Make stickerProps nullable and minor refactor

- packages/clay-css/src/content/tables.html
- packages/clay-css/src/scss/components/_tables.scss
Hey @eduardoallegrini,
There are some gotchas with using these utilities outside of `.table-autofit`. Every table cell needs a class on it (`table-cell-contract`, `table-cell-expand`, `table-cell-expand-small`, `table-cell-expand-smaller`, or `table-cell-expand-smallest`). There were some inconsistencies with table utility naming. I added aliases to make them more consistent.
For portal, we need to replace `table-cell-field` => `table-cell-contract`. The class `table-cell-content` => `table-cell-expand`.
@carloslancha I'll merge this once everything passes.
fixes #3818
> fix(@clayui/css): Tables don't require the class `table-autofit` for column utilities

- packages/clay-card/src/Card.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
Fixes: https://github.com/liferay/clay/issues/3789
In this PR we are removing the case of double `card` class:
- Outer class is [added](https://github.com/liferay/clay/blob/master/packages/clay-card/src/Card.tsx#L71) when `!selectable`
- Inner class is [added](https://github.com/liferay/clay/blob/master/packages/clay-card/src/Body.tsx#L24-L26) when the card is `horizontal` and `!interactive`. 
In analysis I found that removing inner card would we problematic, but removing outer would be doable after we remove the only case that relies on outer CSS class: horizontal interactive card. We achieved this with navigation card, so we're good to go.
As this is released, we need to update server side rendering in horizontal tag to match markup, specifically we need to delete [these three …
> fix(@clayui/card): prevent double 'card' class on ClayCardWithHorizontal

- packages/clay-shared/src/Portal.tsx
For reasons that we haven't fully determined but which are [explained here](https://github.com/liferay-frontend/liferay-portal/pull/565#issuecomment-736854056) we see that unmounting portals sometimes fails because they get mounted on `document.body`, but by the time the portal gets mounted, they have somehow been "re-parented".
The simple-but-untested mitigation applied here is to use `remove()` which will remove the DOM node irrespective of parenthood. Note that [`remove()` isn't supported on IE11](https://caniuse.com/childnode-remove) so we include a `typeof` check to fall back to the old behavior which will at least work most of the time (and in DXP, we probably have this covered by our polyfill anyway on 7.3.x and older branches). As such, we expect this to be "backport-safe".
Test …
> fix(shared): avoid race condition with Senna.js

- packages/clay-card/src/Body.tsx
- packages/clay-card/src/Card.tsx
- packages/clay-card/src/CardHorizontal.tsx
- packages/clay-card/src/CardNavigation.tsx
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/stories/index.tsx
Fixes #3789
This is an initial implementation to start simplifying the low-level component of ClayCard, it is currently very complex and was in [our sights for improvements and revision for v4](https://paper.dropbox.com/doc/Clay-4.x-API-review-and-improvements--BAejQ~GmATHhMLeDKFcBBZqqAQ-uUNnd4tTNFTU7lNP6yQfP). The changes here do not break the API, consequently, it corrects #3789 and there were many changes in the snapshot due to the fact that we removed the double declaration from `card` to horizontal and changes in class ordering.
The idea here was to break the ClayCard component into two more new components `<ClayCardHorizontal />` and `<ClayCardNavigation />`. These two new components are being used only internally but are not yet being public, we will work on that in the next …
> refactor(@clayui/card): Simplifies the use of the ClayCard component and separates it into components by responsibilities

- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
From https://github.com/liferay/clay/pull/3819#discussion_r534104466
We already had this behavior being done where setting `null` to `stickerProps` he did not render the Sticker in CardWithInfo and passing the `undefined` he would render the default Sticker. I just did correct the test, as we have a default value for `stickerProps`, when the value of `stickerProps` is `undefined` it starts with its default value so rendering the default Sticker ie just `null` will not render the sticker.
> chore(@clayui/card): fixes the test of not rendering a sticker on CardWithInfo and improves type

- packages/clay-css/src/scss/mixins/_navbar.scss
- packages/clay-css/src/scss/variables/_management-bar.scss
fixes #3855
This sets a `min-height` on `management-bar` so swapping out contents via js doesn't resize the bar.
> fix(@clayui/css): Management Bar set min-height for desktop / mobile views

- packages/clay-css/src/content/navigation-bar.html
- packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
fixes #3862
This adds 1px gray bottom border to `navigation-bar-light` and minor spacing adjustments to align active highlight.
> fix(@clayui/css): Navigation Bar Light should have 1px gray bottom border

- packages/clay-form/src/Toggle.tsx
> fix(@clayui/form): ClayToggle shouldn't overwrite props

- clayui.com/content/docs/components/markup-forms-hierarchy.md
- clayui.com/content/docs/css/utilities/autofit.md
- packages/clay-css/src/content/sheet.html
- packages/clay-css/src/content/test_sheet_commerce.html
- packages/clay-css/src/content/test_sheet_dataset.html
- packages/clay-css/src/content/utilities.html
- packages/clay-css/src/scss/components/_sheets.scss
- packages/clay-css/src/scss/components/_utilities.scss
- packages/clay-css/src/scss/variables/_sheets.scss
- packages/clay-css/src/scss/variables/_utilities.scss
We should be able to use `sheet` for these components:
https://liferay.design/lexicon/core-components/forms/forms-sheet/#multiple-form
https://liferay.design/lexicon/core-components/forms/forms-sheet/#dataset-content
fixes #3762
> fix(@clayui/css): Adapt Sheet to fit Commerce patterns

- packages/clay-css/src/content/badges_and_labels.html
- packages/clay-css/src/content/form_elements_input_groups.html
- packages/clay-css/src/content/form_elements_multiselect.html
- packages/clay-css/src/content/tbar.html
- packages/clay-css/src/content/test_labels.html
- packages/clay-css/src/content/test_subnav_tbar.html
- packages/clay-css/src/content/utilities_c_inner.html
- packages/clay-css/src/scss/atlas/variables/_labels.scss
- packages/clay-css/src/scss/variables/_labels.scss
- packages/clay-label/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-label/src/index.tsx
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
Part of the fix for https://github.com/liferay/clay/issues/3879
@pat270 I wasn't totally sure what css changes to make for this, but I updated the components so that Label now uses times-small. Let me know what changes need to be made to address this issue in full.
> fix(@clayui/label): close icon should be times-small

- packages/clay-css/src/scss/atlas/variables/_breadcrumbs.scss
- packages/clay-css/src/scss/components/_breadcrumbs.scss
Removes margin-bottom, reduce top and bottom padding, active font-weight semi-bold
fixes #3874
> fix(@clayui/css): Breadcrumbs match sizes to Lexicon specs

- packages/clay-layout/src/Content.tsx
Adds new css utils from https://github.com/liferay/clay/pull/3883 to components
> fix(@clayui/layout): add autofit-padded-no-gutters-sm and autofit-col-shrink utils

- packages/clay-drop-down/README.mdx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/stories/index.tsx
fixes #3790
This adds the css utils to the react components.
@pat270, would you mind just verifying this is how its supposed to work? You can check out the storybook preview here and then toggle the "knobs" to see the different widths.
> feat(@clayui/drop-down): add props for making menu different widths

- packages/clay-css/src/scss/atlas/variables/_toggle-switch.scss
- packages/clay-form/docs/markup-toggle-switch.md
fix(@clayui/css): Atlas Toggle Switch change checked state button icon color to primary
docs(clayui.com): Toggle Switch update markup examples to 3.x. Wraps toggle-switch-check and toggle-switch-bar in toggle-switch-check-bar
fixes #3835, fixes #3872, fixes #3845
> feat(@clayui/css): Atlas Toggle Switch make it 40px by 24px in desktop views

- .eslintrc.js
- CHANGELOG.md
- package.json
- scripts/generate-global-changelog.js
Since we are planning on releasing tomorrow I thought I could throw together a super crude idea of auto-generating the global changelog with each release. Let me know what you think
> chore(docs): add script for generating global changelog for each release

- .github/workflows/dxp-release-labeler.yml
fixes #3898
This action works as follows
Event: Whenever we close a milestone
- Gets every closed issue in a milestone
- Grabs the Jira issue from the milestone title
- Comments on each issue and adds the link to track the LPS
> chore: add gh action for commenting DXP release on closed issues in a milestone

- .github/workflows/dxp-release-labeler.yml
Accidentally had `https://https://...`
> chore: fix jira link in github action

- packages/clay-color-picker/src/Basic.tsx
- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
I accidentally merged a new API in this PR https://github.com/liferay/clay/pull/3916. I initially needed the API for adding the class name for last row, however that was removed in a later commit and I didn't remember to remove the API and markup from the component.
> fix(@clayui/color-picker): remove last-row classes and API that was added on accident

- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-drop-down/src/observeRect.ts
- packages/clay-drop-down/stories/index.tsx
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-upper-toolbar/src/__tests__/__snapshots__/index.tsx.snap
fixes #3804
I added our own observer util with inspiration from observe-rect and seems to work as intended.
There is still an issue with the z-index of the drop-down, and I'm not quite sure what we want to do about that. Perhaps the best option is to check if the dropdown is still in the view(modal or document) and if it is not, we close the drop-down. Although I am fearful that might lead to poor UX.
> feat(@clayui/drop-down): add util for aligning dropdown on scroll

- packages/clay-drop-down/src/Menu.tsx
fixes #3951
Bug was reproducible by going to storybook and quickly clicking into different DropDown stories
> fix(@clayui/drop-down): make sure element exists before passing to domAlign

- packages/clay-color-picker/src/Custom.tsx
Fixes https://github.com/liferay/clay/issues/3949
> fix(@clayui/color-picker): RGB inputs should only accept numeric values from 0 to 255

- README.md
- gulpfile.js
- tasks/release.js
- Remove message `and push to gh-pages` from release task we removed it a while ago (this is being done manually at the moment)
- Release task is based only on 1.x now
- ~Release task should push changes to 1.x-stable instead of 1.x-develop, also changed this a while ago~
> chore(lexicon-ux): Update release tasks

- clayui.com/content/docs/css/content/menubar.md
- packages/clay-css/src/content/menu-bar-vertical-decorated.html
- packages/clay-css/src/content/menu_bar_vertical.html
- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/variables/_menubar.scss
Updates Menubar active state to be more visible. Still waiting on confirmation for menubar decorated.
fixes #3785
> fix(@clayui/css): Atlas Menubar (Vertical Navigation) link active state should be more visible

- packages/clay-button/docs/index.js
> docs(clayui.com): ClayButton adds example of Base Button

- packages/clay-date-picker/src/DateNavigation.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
This adds clay css classes but also leaves `btn-monospaced` and `btn-sm` just incase.
fixes #3992
>  fix(@clayui/date-picker): Date Navigation Controls are wrong color

- packages/clay-date-picker/src/index.tsx
Fixes #3981
We are disabling focus control using the arrow keys because it causes inappropriate behavior in the Date Picker, when there is input instead of going through the strings it will jump to the next element. We have no way of identifying whether the user skips to the next element or continues to go through the input string.
The best case for this would be to deal with a better focus control only within the Date Picker, disregarding the input.
This change still allows focus control but only using `tab` and `shift + tab`.
> fix(@clayui/date-picker): disable focus control using the arrow keys

- README.md
- clayui.com/src/styles/site/_content-site.scss
- packages/clay-css/src/content/form_elements_date_picker.html
- packages/clay-css/src/scss/atlas/variables/_date-picker.scss
- packages/clay-css/src/scss/components/_date-picker.scss
- packages/clay-css/src/scss/variables/_date-picker.scss
- packages/clay-date-picker/docs/markup-date-and-time-pickers.md
- packages/clay-date-picker/src/DayNumber.tsx
- packages/clay-date-picker/src/Weekday.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
TODO: Still need to write documentation for this.
Had to wrap days and dates in `<div class="date-picker-col">` to achieve Lexicon's Date Range pattern. I tried to keep the markup as is, but it was too messy. Good news is the old markup will still work, just no styles for Date Range. We still need to implement the JS for this.
fixes #3986
> feat(@clayui/css): Date Picker adds Date Range styles

- packages/clay-date-picker/README.mdx
- packages/clay-date-picker/docs/index.js
- packages/clay-date-picker/src/DayNumber.tsx
- packages/clay-date-picker/src/Helpers.ts
- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/InputDate.tsx
- packages/clay-date-picker/src/__tests__/BasicRendering.tsx
- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/__tests__/Internationalization.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/src/types.ts
- packages/clay-date-picker/stories/index.tsx
I'm just adding a few more commits to correct some things, for context see the original PR: #4012
We still have some problems that we need to fix:
- We have a CSS bug where the `active` state of the date is disabled it does not appear, maybe we should just show color of the `active` with less opacity instead of removing it? cc @pat270 @drakonux 
- ~~The experience for changing the start range when an end date is already selected seems a little confusing https://github.com/liferay/clay/pull/4012#issuecomment-822558650~~
Despite having some small details to fix I think that both do not prevent this PR from entering the master.
> feat(@clayui/date-picker): Adds ClayDatePicker Range variation

- packages/clay-management-toolbar/docs/index.js
- packages/clay-management-toolbar/docs/markup-management-toolbar.md
- packages/clay-management-toolbar/stories/index.tsx
- packages/demos/stories/ListPage.tsx
Fixes #4023
This just updates our examples to use the new icons in Storybook and clayui.com. @pat270 since we have new icons to represent the asc or desc sort, I got rid of `order-arrow-down-active` in the examples, let me know if it still becomes necessary.
> docs(clayui.com): updates the `order by` icons in the Management Toolbar documentation

- packages/clay-shared/src/useFocusManagement.ts
Seeing as The Liferay Way™ is to sort sortable things, I'm sorting the expressions in these statements. Sometimes there are logical reasons for not sorting in order (eg. wanting to short-circuit) or performance reasons (eg. putting the cheapest checks first), but in this case, the comparisons all just string equality checks which can be considered to have essentially zero cost.
Noticed while reading [#3942](https://github.com/liferay/clay/pull/3942).
There is one other sortable thing in that PR that I didn't touch, and that is `FOCUSABLE_ELEMENTS`, because there is just a tiny little chance that it might have some subtle performance ramification depending on how the browser matches the selector, so I'd rather not risk changing it.
> refactor(@clayui/shared): sort expressions

- packages/clay-shared/src/useFocusManagement.ts
Not sure whether this would actually cause a bug, so labeling this as a refactor commit.
`contentEditable` can be a string (eg. `'true'`)or a bool (or `undefined`), so we probably shouldn't coerce it (eg. `!!'false'` is `true`). Instead, explicitly check against `true` and `'true'`.
Originally started looking at this because the `!!` in [this PR](https://github.com/liferay/clay/pull/3942) looked a bit off.
> refactor(@clayui/shared): don't coerce `contentEditable`

- packages/clay-drop-down/src/Menu.tsx
- packages/clay-popover/src/index.tsx
- packages/clay-popover/stories/index.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/observeRect.ts
Fixes #4035
Nothing much different from what was done for `DropDown.Menu`, we just call the alignment method with each change in the `trigger`. The change is that I moved the `observeRect` utility to `shared` to allow reuse in DropDown and Popover.
> feat(@clayui/popover): add observeRect to align the popover on the scroll

- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/variables/_menubar.scss
- Adds keys `mobile`, `collapse`, `collapse-mobile`, `nav-nested`, `nav-nested-mobile`, `nav-nested-margins`, `nav-nested-margins-mobile`, `toggler-mobile`
- Deprecated keys `border-color-mobile`, `border-style-mobile`, `border-width-mobile`, `margin-bottom-mobile`, `margin-left-mobile`, `margin-right-mobil`, `margin-top-mobile`, `max-width-mobile`, `min-height-mobil`, `padding-x-mobile`, `padding-y-mobile`,
- Deprecated `collapse-border-color-mobile`, `collapse-border-style-mobile`, `collapse-border-width-mobile`, `collapse-margin-top-mobile`, `collapse-max-width-mobile`, `collapse-left-mobile`, `collapse-right-mobile`, `collapse-z-index-mobile`
- Deprecated `collapse-border-color-mobile`, `collapse-border-style-mobile`, `collapse-border-width-mobile`, `collapse-inner-spacer-y-mobile`, …
> feat(@clayui/css): Update `clay-menubar-vertical-expand` to use the `clay-css` pattern

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-css/src/scss/variables/_time.scss
This updates the way we merge Sass map keys in `clay-form-control-variant` so deprecated keys will win over the new ones. This is for backward compatibility with older versions of Clay CSS.
issue #3987
> fix(@clayui/css): Mixins `clay-form-control-variant` old keys should win over new keys

- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/variables/_menubar.scss
- Mixins `clay-menubar-vertical-variant` moves default styles to variables. The mixin should only output styles if values are given.
- Setting `enable: false` should prevent styles from being output
- Deprecate old keys in favor of simpler pattern: `bg`, `bg-mobile`, `border-color-mobile`, `border-style-mobile`, `collapse-bg-mobile`, `collapse-border-color-mobile`, `collapse-border-radius-mobile`, `collapse-border-style-mobile`, `collapse-box-shadow-mobile`
- Menubar convert old Sass map keys to key names so older keys used by previous versions will win
- Removes dependency on other component variables such as `$btn`, `$dropdown`, and `$navbar` so it's more portable (e.g., removing navbar import won't cause menubar to fail)
issue #3987
> fix(@clayui/css): Update `clay-menubar-vertical-variant` to use the `clay-css` pattern 

- packages/clay-panel/src/Group.tsx
- packages/clay-panel/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/src/__tests__/index.tsx
- packages/clay-panel/stories/index.tsx
Fixes #4025
Just by adding the new `small` API to` <ClayPanel.Group />` which renders small panels within the group, I also removed the use of `react-test-renderer` in favor of using only `testing-library`, I went through a few tests and we still use it a lot, I will create another issue later to track it and remove the use of `react-test-renderer` from our test suite.
> feat(@clayui/panel): adds the small API to Panel.Group

- packages/clay-css/src/content/management-bar.html
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-management-toolbar/docs/markup-management-toolbar.md
fix(@clayui/css): Input Groups add `btn-monospaced` support for buttons inside `input-group-inset-item`
fix(@clayui/css): Input Group adds Sass maps `$input-group-inset-item-btn-monospaced`, `$input-group-lg-inset-item-btn-monospaced`, `$input-group-sm-inset-item-btn-monospaced`
fixes #4049
> fix(@clayui/css): Management Bar Search Bar button should be 32px x 32px and icon size 16px

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/modal.tsx.snap
- packages/clay-modal/src/__tests__/modal.tsx
Fixes #4044 Extended ClayModal API to support custom opener window
Added a new prop called `opener` to `ClayModal` that would allow to render it in a different element than the default `document.body`.
> feat(@clayui/modal): support custom opener for the modals

- packages/clay-shared/src/delegate.ts
- packages/clay-shared/src/index.tsx
- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/stories/index.tsx
back at it with more tooltip adventures.... [Previous convo on DXP changes here](https://github.com/liferay-frontend/liferay-portal/pull/1016)
Okay, so I went with a solution that allowed our provider to be used as a singleton plus the ability to scope it within a specific set of selectors. By making these changes here we could re-write our tooltip-support-web file to be really simple...
```js
import {ClayTooltipProvider} from '@clayui/tooltip';
import {render} from '@liferay/frontend-js-react-web';
const SELECTOR_TRIGGER = `
.lfr-portal-tooltip,
.manage-collaborators-dialog .lexicon-icon[data-title]:not(.lfr-portal-tooltip),
.manage-collaborators-dialog .lexicon-icon[title]:not(.lfr-portal-tooltip),
.manage-collaborators-dialog [data-restore-title],
.management-bar …
```
> feat(@clayui/tooltip): update logic to handle scoping and a global listener

- packages/clay-color-picker/src/index.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-shared/src/Portal.tsx
- packages/clay-shared/src/index.tsx
Fixes #4028
Adding new APIs to add properties to get to `<ClayPortal />`, ideally, we wanted to get rid of having APIs with `*Props` as this may mean that we can go in mismatch the composition or our own foundations but this has become very common in our components.
I'm following the pattern here to maintain consistency but I have some ideas about this to avoid adding more APIs with `*Props` and creating a consistent pattern for all components without having to hurt our foundations. I will try to create a proposal for us to discuss.
> feat(@clayui/color-picker): Add the new DropDownContainerProps API

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-modal/src/Modal.tsx
- packages/clay-popover/src/index.tsx
- packages/clay-tooltip/src/TooltipProvider.tsx
Fixes #4083
It just does the same thing that was done for ClayColorPicker, we are adding for all components that depend on `<ClayPortal />`.
> feat: Add the new ContainerProps API to Popover, TooltipProvider, Modal and DropDown

- packages/clay-table/src/Cell.tsx
- packages/clay-table/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-table/src/__tests__/index.tsx
- packages/clay-table/stories/index.tsx
Passing the `noWrap` (boolean) props to `<ClayTable.Cell />` will make
it use the `table-cell-ws-nowrap` CSS class, which keep table cells on
one line.
Fixes #4058
> feat(@clayui/table): Adds the `noWrap` prop to ClayTable.Cell

- packages/clay-drop-down/README.mdx
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/src/__tests__/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/drilldown/Menu.tsx
- packages/clay-drop-down/stories/index.tsx
In this change, we're adding the possibility to render dividers
in the `ClayDropDownWithDrilldown` component. The change is rather
straightforward: if a menu item with the `type: 'divider'` is passed
in the `menus` prop, it will be rendered as a `<Divider />`.
Fixes #4089
> feat(@clayui/drop-down): Make it possible to render dividers

- packages/clay-drop-down/README.mdx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/stories/index.tsx
- packages/clay-shared/src/MouseSafeArea.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useMousePosition.ts
Fixes #4097 
Well add this just as a draft just missing to understand how the visibility of the cascading menu will work, it is still not very clear if when hovering the mouse outside the cascading menu it should disappear, looking at the Figma prototype it looks like this but I'm not sure about that.
- [Spec](https://docs.google.com/document/d/1gnFu8Fwb_JEl1Lat_THfzXN9vkCJ7Q4f6zM82ioj1Wo/edit?usp=sharing)
I thought that just adding a level would be easier but in fact, our API allows you to add another level, so implementing it in a recursive way is more natural for our implementation. this is because we only want one level. To create a cascading menu is the same as creating a `group` but just change the type to `contextual` (I'm not sure about that name yet, suggestion is welcome), this …
> feat(@clayui/drop-down): add the new contextual type to create a cascading menu

- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/stories/index.tsx
Two new props have been added to `ClayDropDownWithDrillDown`:
`active` and `onActiveChange`. Setting `active` to `true` will make the
menu initially `active` (open), and `onActiveChange` will allow the menu
to be toggled.
Fixes #4103
>  feat(@clayui/drop-down): Allow the menu to be toggled

- docs/0000-proposal-template.md
- docs/README.md
- docs/proposals/0001-component-offerings.md
Well initially we've already made an attempt to document our decisions with the [ADR](https://github.com/joelparkerhenderson/architecture-decision-record) model (#2017) and then moved to the Wiki (#2818) because we don't use it as much or because we don't see more value, but this has changed as Clay has evolved and more and more we need to make more decisions from Clay's future, API decisions... which are reflected in developers, a lot of these decisions are focused on specific issues of a component or a PR that adds a new API that we can ignore in certain moments the impact this has on the experience of using the components and harm consistency, over time this is very easy to be distorted even if someone is from the beginning.
The RFC idea may be similar to the idea of …
> docs: Adds RFC process and documentation template

- packages/clay-layout/src/Content.tsx
Found this while using the Layout components, I think this should be `autofit-col-end` instead of `autofit-col-float-end`
> fix(@clayui/layout): ContentCol should use autofit-col-end instead of autofit-col-float-end

- packages/clay-css/src/scss/atlas/variables/_links.scss
- packages/clay-css/src/scss/cadmin/variables/_links.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/variables/_links.scss
> fix(@clayui/css): Links convert variables to use nested Sass map pattern

- packages/clay-list/src/Header.tsx
- packages/clay-list/src/ItemText.tsx
- packages/clay-list/src/ItemTitle.tsx
- packages/clay-list/src/QuickActionMenu.tsx
- packages/clay-list/src/QuickActionMenuItem.tsx
Fixes #4149
Well, I went ahead and also added `forwardRef` to the other ClayList components, we only had a few, so it might be good practice to add to the others.
@bryceosterhaus I added it to the `ClayList.ItemTitle` component but I'm not sure if that solves your problem, from what I understand from the `next/link` it will pass the `href` to the `children`, in this case we have a `div` that wraps `children` of `ClayList.ItemTitle` or if it is a Link.
> feat(@clayui/list): Add `forwardRef` to ClayList components

- packages/clay-list/src/QuickActionMenuItem.tsx
When building types, this error appears: "Default export of the module has or is using private name 'IItemProps'." Probably a regression of #4157 or because we are exporting the types in another way with `forwardRef`, strange thing is that CI didn't catch that, I'll check later if we're checking the types.
> fix(@clayui/list): fix error when building types

- packages/clay-list/docs/api-list.mdx
Fixes #4163
Well, we removed this component in favor of using `ClayLayout.ContentCol` directly because it had the same markup and `ItemField` was built well before ClayLayout, so the file was removed and so it doesn't generate the table, I point to the `ContentCol` component because we still keep the `ItemField` for compatibility.
> docs(@clayui/list): Fixes error when generating `List.ItemField` API table

- packages/clay-css/src/scss/atlas/variables/_loaders.scss
- packages/clay-css/src/scss/cadmin/variables/_loaders.scss
- packages/clay-css/src/scss/cadmin/variables/_sheets.scss
- packages/clay-css/src/scss/mixins/_loaders.scss
- packages/clay-css/src/scss/mixins/_sheet.scss
- packages/clay-css/src/scss/variables/_loaders.scss
- packages/clay-css/src/scss/variables/_sheets.scss
fixes #3987
I'm going to move the last task `clay-range-input-variant` to its own issue so we can close it out.
> fix(@clayui/css): Mixins update `sheet-footer-btn-block` and `clay-loading-animation-variant` to use `clay-css` pattern

- packages/clay-css/src/content/form_group.html
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/components/_forms.scss
> fix(@clayui/css): Forms `form-group-sm div.form-control` should be 32px tall and grow to fix content inside, similar to a textarea element

- clayui.com/content/docs/components/markup-treeview.md
- clayui.com/plugins/gatsby-plugin-clay-css-tasks/gatsby-node.js
- clayui.com/src/html.js
- packages/clay-css/src/content/cadmin_treeview.html
- packages/clay-css/src/scss/cadmin.scss
- packages/clay-css/src/scss/cadmin/_variables.scss
- packages/clay-css/src/scss/cadmin/components/_links.scss
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_links.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
I'm not 100% happy with this implementation. The markup is huge since I'm trying to cover all use cases. I tried to pare it down, but couldn't find a good solution for icon placement and working with all the different combinations of html elements (`a`, `button`). If the markup causes laggy rendering issues in the React component, I was thinking about adding a version with lighter markup for specific cases. 🤷 
Also we need the Cadmin pr to get merged in Portal before we can use this component. I can focus on getting that merged next. We can break things now.
fixes #4111
> feat(@clayui/css): Adds Cadmin Treeview

- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/index.tsx
- packages/clay-shared/src/useFocusManagement.ts
Fixes #4173
Hey @pat270 I realized that we can't add a `type=hidden` because we use this `input` as support for the native state, we need it for when I click on `Splotch` to open the native input, so I had to go with the first solution of adding the `position: absolute;`. This is related to this PR #3596
This PR also fixes an error on `FocusScope`, when you press `Tab + Shift` you get stuck on `input` which is not visible, so I added the behavior to ignore focus when `tabIndex` of `input` is smaller than the minimum and if not, keep the default behavior of ignoring only with type hidden and file.
> fix(@clayui/color-picker): fix error of "hidden" input add extra margin

- packages/clay-tooltip/src/TooltipProvider.tsx
Fixes: https://github.com/liferay/clay/issues/4187
The root cause of the issue is that none of the existing hide events trigger when node is being dragged. Funnily enough, this includes `mouseout`; it makes sense as the node is all the time below the mouse. Once the drop happens, node is removed from DOM, leaving a dangling tooltip in portal.
To fix this, in this PR we are adding `dragstart` to list of events that trigger tooltip hide.
Before PR:
After PR:
> fix(@clayui/tooltip): Hide tooltip on `dragstart`

- packages/clay-autocomplete/src/Item.tsx
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
Fixes #4169
Well to avoid XSS issues in Autocomplete because values can come from user input, I'm removing the use of `dangerouslySetInnerHTML` and "parsing" it to better handle the fuzzy output.
> fix(@clayui/autocomplete): fixes a potential XSS vulnerability in autocomplete by removing the use of `dangerouslySetInnerHTML`

- packages/clay-core/package.json
- packages/clay-provider/package.json
- yarn.lock
These two packages were created well before and entered after the update in PR #4186, just updating to keep consistent and avoid CI failed.
> chore: updates peer dependency of React in `core` and `provider` packages

- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/variables/_globals.scss
> feat(@clayui/css): Reboot `body` element should use clay-css mixin for generating properties

- packages/clay-css/src/scss/components/_list-group.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/functions/_type-conversion-functions.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/src/scss/variables/_list-group.scss
- packages/clay-css/src/scss/variables/_tables.scss
fixes #4180
I couldn't get the `$theme-colors` map to play nicely with CSS variables, ended up creating separate maps for each utility that depends on it. This is much better since it allows better customization of colors and support for CSS variables.
```
$bg-theme-colors
$bg-gradient-theme-colors
$border-theme-colors
$text-theme-colors
$list-group-item-theme-colors
$table-row-theme-colors
```
This pr also adds some nice functions for converting a color string to type color from https://github.com/KittyGiraudel/SassyJSON/tree/master/stylesheets/decode. This will allow fallback values from CSS variables to work with Sass color functions if needed.
> fix(@clayui/css): Removes the use of `$theme-colors` Sass map to generate utility properties and replaces with new maps

- packages/clay-css/src/scss/cadmin/components/_modals.scss
fix(@clayui/css): Cadmin Modal .modal-full-screen, .modal-full-screen-sm-down, .modal-height-*, and .modal-{color} variants should work if the cadmin is class is applied on the same element
fixes #4203
> fix(@clayui/css): Cadmin Modal .modal.show should have display: block

- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination/src/Ellipsis.tsx
- packages/clay-pagination/src/PaginationWithBasicItems.tsx
- packages/clay-pagination/stories/index.tsx
Fixes #4165
Well, this adds the API to control the position of DropDown within a Pagination component, essentially we should investigate the case of https://codesandbox.io/s/eloquent-darkness-g8lms where the `dom-align` might be getting lost but adding this API makes sense and unlocks this.
> feat: Add the `alignmentPosition` API to PaginationWithBasicItems and PaginationBarWithBasicItems component

- custom-types/dom-align/index.d.ts
- packages/clay-drop-down/package.json
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-popover/package.json
- packages/clay-popover/src/index.tsx
- packages/clay-shared/package.json
- packages/clay-shared/src/doAlign.ts
- packages/clay-shared/src/index.tsx
- packages/clay-tooltip/package.json
- packages/clay-tooltip/src/TooltipProvider.tsx
Fixes #4238
From #4239, I added some changes to this PR of the @carloslancha, moved the method to our `@clayui/shared` package to be able to use it in other components that also use `dom-align`, I also went with @jbalsas' advice to get the element direction, since there may be the use case that we have different directions on the same page in some scenarios, seems safer than checking the document.
> feat: Adds RTL OOTB support to methods using dom-align

- packages/clay-shared/src/doAlign.ts
Well, the types for `dom-align` are defined inside Clay but we don't export them because they are `declare module` in our types root, it wouldn't make much sense either, in this case, I'm just adding the types that are needed as part of the `shared` package to allow error-free distribution.
> fix(@clayui/shared): fixes error when importing the type that is not available in the module

- packages/clay-shared/src/doAlign.ts
Well, again one more error that passed silently 😭 (I'll have to cut one more release patch), this time I did more tests and checked the generated types to make sure it aren't exporting private types.
As we have the explicit return from the `domAlign` method it will also return `IConfig` which is a private type in the package dos types generation. We need to find a way to test this to avoid problems in the future.
> fix(@clayui/shared): fix error export type from root in package distribution

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
> feat(@clayui/css): Forms convert label and .form-control to use clay-css mixin

- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_globals.scss
fixes #4252
This allows passing CSS Custom Properties to any Sass map that uses the `clay-css` mixin.
```
$btn-primary: (
--btn-primary-background-color: blue,
);
.btn-primary {
@include clay-css($btn-primary);
}
```
should output:
```
.btn-primary {
--btn-primary-background-color: blue;
}
```
>  feat(@clayui/css): Mixins `clay-css` should output any CSS Custom Properties passed into it

- packages/clay-core/package.json
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/index.ts
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-provider/src/Provider.tsx
Fixes #4117
Well, this is an initial draft for implementation of components for TreeView, the idea is that it looks like a low-level and high-level component, the idea of TreeView is that it is very flexible to build other components like Vertical Navigation or just customize the Node to behave in different variations. An important part of this design is that the TreeView is data agnostic and allows to build a static or dynamic TreeView, we still don't have all the resources because we will be building with other issues.
This component is already being built in `@clayui/core` but it is not being exposed so we are not officially releasing it even if a new version is cut.
You can see the stories that have been added with some basic examples.
This component follows some different behaviors …
> feat(@clayui/core): Add initial sketch of components to TreeView

- packages/clay-core/package.json
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
Fixes #4210
This functionality is written under PR #4218. Still putting it as a draft because it's not done, I still need to tweak the code and clean up some parts.
As I mentioned in PR, it is possible to make expandable without necessarily having to render props, but that would need a restricted API, as we commonly use in high-level.
Why not use `maps` actually people can use them if they want, but the component won't have visibility of items that are rendered just from the markup but we can't do much without the control we can have with render props, neither would we be able to do nested rendering automatically or apply virtualization strategies, perhaps even a scroll-based "load more", commonly known as an infinite scroll.
```jsx
<TreeView>
{ITEMS.map(item, () => (
<TreeView.Item> …
```
> feat(@clayui/core): adds functionality for expandable nodes and nested nodes

- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/demos/stories/ListPage.tsx
Fixes #4249
The idea here is to force `align` to recalculate the Tooltip position in a position contrary to the center alignment which can happen the x-axis is modified because the Tooltip is on a smaller screen, this avoids having the x-axis modified by choosing the best position.
This fixes when you are in the top or bottom position. See the List Page demo example and play around with increasing and decreasing the Storybook Sidebar to decrease content and reproduce reported use cases, Tooltip has been added at both ends of the Management Toolbar, in Checkbox and in the Add button.
> fix(@clayui/tooltip): forces tooltip to be repositioned when the x-axis is modified

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/cadmin/components/_buttons.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_buttons.scss
feat(@clayui/css): Clay CSS and Cadmin Buttons convert `.btn`, `.btn-lg`, `.btn-sm`, `.btn-monospaced`, `.btn-monospaced-lg`, `.btn-monospaced-sm`, `.btn-unstyled`, and `.btn-outline-borderless` to use `clay-button-variant` mixin
feat(@clayui/css): Buttons adds `$btn`, `$btn-lg`, `$btn-sm`, `$btn-monospaced`, `$btn-monospaced-lg`, `$btn-monospaced-sm`, `$btn-unstyled`, and `$btn-outline-borderless` Sass maps
fixes #4269
> feat(@clayui/css): Buttons convert components to use `clay-button-variant` mixin for more customizing options

- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
In the attempt of reduce the CSS footprint in Liferay Portal, we are moving CSS classes where they make more sense.
https://issues.liferay.com/browse/LPS-134071
---
In this case, we are moving the class `.hide`, an alias of `.d-none`.
https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/base/_util.scss#L1-L3
> feat(@clayui/css): Move .hide from liferay-portal to clay-css

- packages/clay-tooltip/src/TooltipProvider.tsx
Fixes #4289
I think I ended up commenting with `adjustX` to false doing tests 🤦‍♂️ and I also didn't notice that in the Storybook of the PR build it wasn't working. I tested it on DXP and it works fine too.
> fix(@clyaui/tooltip): fixes error when not forcing Tooltip repositioning when X axis is modified

- packages/clay-drop-down/src/Menu.tsx
Fixes #4288
Adds a more detailed description about the API and removes the `auto` value that doesn't exist for `width` and adds the `full` that was missing.
> fix(@clayui/drop-down): fixes the values of the `width` property of the Menu

- packages/clay-autocomplete/src/DropDown.tsx
> feat(@clayui/autocomplete): adds `closeOnClickOutside` API support to DropDown

- packages/clay-css/src/scss/atlas/variables/_alerts.scss
- packages/clay-css/src/scss/cadmin/components/_alerts.scss
- packages/clay-css/src/scss/cadmin/variables/_alerts.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/mixins/_alerts.scss
- packages/clay-css/src/scss/variables/_alerts.scss
fixes #4304
- Make same changes to Cadmin
- Adds Sass maps `$alert-primary`, `$alert-secondary`, `$alert-info`, `$alert-warning`, `$alert-danger`, `$alert-light`, `$alert-dark`
- Use `clay-alert-variant` mixin to generate alert variant styles
- Mixins Alerts adds `clay-alert-variant` mixin and deprecate Bootstrap's `alert-variant` mixin
> fix(@clayui/css): Alerts allow better customization of alert variant components

- packages/clay-form/src/DualListBox.tsx
- packages/clay-form/src/__tests__/__snapshots__/DualListBox.tsx.snap
- packages/clay-form/stories/index.tsx
Fixes #4312
See issue https://github.com/liferay/clay/issues/4312 to understand the context of the change and why we are following this as a fix rather than not changing this default behavior now.
> fix(@clayui/form): change the Dual List Box ordering side following the right side as the default behavior

- packages/clay-css/src/content/badges_and_labels.html
- packages/clay-css/src/scss/atlas/variables/_stickers.scss
- packages/clay-css/src/scss/cadmin/variables/_stickers.scss
fixes #4310
BREAKING CHANGE: `sticker-light` now has a light font color and `sticker-dark` has a dark font color. All instances of `sticker-light` should be updated to use `sticker-dark` and all instances of `sticker-dark` should be updated to use `sticker-light`. If you do not want to make this change in your markup, you can revert back to the original styles with:
```
$sticker-light-bg: $dark !default;
$sticker-light-color: $white !default;
$sticker-dark-bg: $dark !default;
$sticker-dark-color: $white !default;
```
> fix(@clayui/css): Atlas and Cadmin Stickers swap background and foreground colors for `sticker-light` and `sticker-dark`

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/useTree.ts
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
Well, this is a very early draft for implementing "load more" or allowing the TreeView to load a large amount of data and still work fine without causing any slowdowns or crashes, yet this component doesn't implement any improvement related to loading a render a big payload.
One of the first attempts here is to allow you to load parts of the structure asynchronously, the final implementation is not yet ready to deal with this, there are some tradeoffs we will have to deal with and we can also try different strategies on how to approach this:
- The TreeView shouldn't handle the responsibility of loading asynchronous data or handling it, it's data agnostic. This is responsible for the `useResource` hook which will load the data with the possibility of aggregating the data and fetching using …
> feat(@clayui/core): adds `onLoadMore` API to TreeView

- packages/clay-provider/docs/provider.mdx
- packages/clay-provider/package.json
- packages/clay-provider/src/Provider.tsx
- packages/clay-shared/package.json
Fixes #4399
Unfortunately, this is the only option we have for not using `peerDependencies`. We can for now remove the ClayModalProvider from the ClayProvider and when we can stabilize the package dependencies on `@clayui/core` we can add that support again, it's safe to remove the ClayProvider because it's not used yet.
> fix(@clayui/provider): removes dependency from ClayModal to avoid circular dependency issues

- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/src/index.tsx
Fixes #4408
For the text alignment to work well I also needed to change the markup to the feedback variant which requires the Indicator not to be separated from the text due to the CSS implementation.
> chore(@clayui/alert): adds the indicator and changes the markup for text alignment in the feedback variant

- packages/clay-core/src/tree-view/TreeViewItem.tsx
See #4389
When a Node is asynchronous, we must handle the request's error, in this case, we only suppress the error but don't show anything to the user, this can be up to whoever is implementing the method, returning an empty value also means that the Node it is not asynchronous or should do nothing.
> chore(@clayui/core): suppresses the error from the `onLoadMore` request and returns void does nothing

- .eslintignore
- .prettierignore
- docs/treeview_performance.md
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
- tsconfig.json
Fixes #4115
This PR only makes a few small changes to stabilize reference to methods that are available through the context but nothing more related to performance improvement, the purpose of this PR is also to bring a TreeView load test analysis and the limitations that exist in which scenarios.
All tests were done using the `performance` example in the Storybook which loads the same XXL data as the Tango team test. I'm just considering the bigger data which is the ultimate goal here.
> chore(@clayui/core): add a new performance test example using a very large data

- packages/clay-css/src/scss/cadmin/components/_input-groups.scss
- packages/clay-css/src/scss/components/_input-groups.scss
fixes #4423
Input Groups input disappears when focused inside a modal with iframe.
> fix(@clayui/css): Cadmin and Clay Input Group move `.btn` and `.form-control` z-index styles to `input-group-prepend` and `input-group-append`

- packages/clay-drop-down/src/Search.tsx
- packages/clay-drop-down/stories/index.tsx
Fixes: https://github.com/liferay/clay/issues/4434
In this PR, a default function is provided for the onSubmit handler in the ClayDropDown.Search component. This prevents de form submission when pressing enter and the input is focused.
This can also be done from the outside passing a custom onSubmit function, but I believe that it is better to control this from the inside since the behaviour is a bit weird.
Let me know what do you think  :)
> fix(@clayui/drop-down): Provide a default on submit function to avoid form navigation

- docs/README.md
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
See #4389
Added a new API to `TreeView.Item` so that the developer still has the freedom to add the actions using composition, there's not a very clear way to do this on `children` because `children` is used to building the Node and groups and do this using `children` in a simple way without generating new complexities.
There are some markup issues here though, see example in Storybook of `Actions`, this will work fine with `Button` and `Icon` compositing, but it won't work well using directly eg `DropDown`, because it has a wrapper on the trigger and we need to add the `component-action` to the `Button`. @pat270 is there any way we can get this to work with DropDown's markup, without necessarily being a `Button`?
We also have a limitation for the case of DropDown as an action, the …
> chore(@clayui/core): add the feature to add actions to the item in TreeView

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/mixins/_forms.scss
fixes #4430
The checked unfocused styles have background `#e7e7ed`. Still have to confirm styles for Microsoft Edge browsers.
Chrome (Mac) 96.0.4664.55
Firefox (Mac) 94.0.1
Safari (Mac) 14.1.2
>  fix(@clayui/css): Atlas `select.form-control` size and multiple styles should match Lexicon

- packages/clay-css/src/scss/cadmin/components/_toggle-switch.scss
- packages/clay-css/src/scss/cadmin/variables/_toggle-switch.scss
- packages/clay-css/src/scss/components/_toggle-switch.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_toggle-switch.scss
- packages/clay-css/src/scss/variables/_toggle-switch.scss
This adds mixins `clay-toggle-switch-bar-variant`, `toggle-switch-check-variant`, and `toggle-switch-variant`. The styles haven't changed, but the option to change them is available.
fixes #4375
> feat(@clayui/css): Toggle Switch adds option to customize hover, focus, disabled, checked, indeterminate styles

- package.json
Recently we were seeing the Storybook build failing on Netlify due to lack of memory, I was thinking that the container's memory but doesn't make sense because it looks like the container can use up to 32GB of memory 🙂.
I'm increasing the memory capacity of Node.js to 4 GB, this seems enough because before it was bursting at 2 GB and in some moments finishing the build.
> chore: increase Node.js memory usage in Storybook build

- packages/clay-card/docs/index.js
Looks like this was missed at some point.
> fix(clayui.com): Incorrect import for ClayCardWithNavigation

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/components/_reboot.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/variables/_globals.scss
> feat(@clayui/css): _reboot convert `a` tag to use `clay-link` mixin

- packages/clay-color-picker/src/index.tsx
Fixes: https://github.com/liferay/clay/issues/4479
In this PR, `active` and `onActiveChange` props are added to control the ClayDropDown.Menu from outside.
Let me know what do you think :)
> fix(@clayui/color-picker): Add active and onActiveChange props

- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/mixins/_close.scss
- packages/clay-css/src/scss/mixins/_links.scss
- Mixins `clay-link` and `clay-close` Removes the `.show > &` selector
- Mixins `clay-button-variant` adds option to style `::before` and `::after`
- Update `clay-button-variant` documentation
fixes #4475
> fix(@clayui/css): Mixin `clay-button-variant` unbundles `.show` from `.active`

- packages/clay-link/demos/index.html
- packages/clay-link/src/ClayLink.js
Calling the `preventDefault` method every time on Click will change the behavior for all components and we don't want that because we will be breaking all existing behaviors.
I'm also changing the demo to listen for the `handleClick` event, it is called internally due to the explicit listener added in the component but its name is changed due to the ClayComponent implementation.
> fix(clay-link): listens for the `handleClick` event and removes the preventDefault call by default

- packages/clay-css/src/scss/atlas/variables/_application-bar.scss
- packages/clay-css/src/scss/atlas/variables/_management-bar.scss
- packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
- packages/clay-css/src/scss/atlas/variables/_sidebar.scss
- packages/clay-css/src/scss/cadmin/variables/_management-bar.scss
- packages/clay-css/src/scss/cadmin/variables/_navigation-bar.scss
- packages/clay-css/src/scss/cadmin/variables/_sidebar.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/mixins/_custom-forms.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/mixins/_navbar.scss
- packages/clay-css/src/scss/variables/_application-bar.scss
- packages/clay-css/src/scss/variables/_management-bar.scss
- packages/clay-css/src/scss/variables/_navigation-bar.scss
- packages/clay-css/src/scss/variables/_sidebar.scss
This provides complete customization of all the Navbar spin off components. There are some breaking changes in this pr.
- The mixin `clay-navbar-variant` output `border-color: transparent` and `border-style: solid` by default. This has been removed to reduce unnecessary CSS. You will need to declare them in your Sass map if you relied upon it.
- We previously output `navbar-expand-{sm|md|lg|xl}` for the variants of Application Bar, Management Bar, Navigation Bar, Sidebar Navigation Bar. We only output those that are needed namely, `navbar-expand-md`. If you relied upon other breakpoints you will need to declare them in the respective Sass map.
These changes reduced ~17kb from Atlas. For the future I'd like to move away from using `clay-navbar-size` since it outputs a lot of unused styles. …
> fix(@clayui/css): Mixins `clay-navbar-variant` should be able to output selectors that `clay-navbar-size` can

- packages/clay-card/src/AspectRatio.tsx
Fixes #4510
Using this API will have no effect because it must be used in an `img` tag and to support this in the component it's necessary to add a new API to define an img for example.
Rather than adding a new API to this component, it semantically makes more sense for us to create a new component that deals directly with the `img` tag, we will consider creating this component shortly.
> fix(@clayui/card): remove unnecessary `backgroundImageAspectRatio` property

- packages/clay-multi-step-nav/README.mdx
- packages/clay-multi-step-nav/src/MultiStepNav.tsx
- packages/clay-multi-step-nav/src/__tests__/__snapshots__/index.tsx.snap
Fixes #4507
Well, that PR just add a new API but does not improve the API to improve the DX, since you need to make `subTitle` the title, for example, is quite counterintuitive but we can not change the API now to do this, but maybe we can add a new API to change the names and remove the idea Subtitle for something like label for example and depreciate the subtitle of `<ClayMultiStepNav.Indicator />` and `<ClayMultiStepNavWithBasicItems />`.
> feat(@clayui/multi-step-nav): add the new indicatorLabel API to indicate the position of the indicator label

- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/TimePicker.tsx
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/index.tsx
Fixes #4505
Even though TimePicker already supports 12-hour time we need to add more rules for formatting and interpreting the syntax in DatePicker so that everything works fine.
> feat(@clayui/date-picker): adds 12-hour time support

- clayui.com/plugins/gatsby-plugin-clay-css-tasks/gatsby-node.js
- clayui.com/src/styles/colors-base.scss
- clayui.com/src/styles/colors.scss
- clayui.com/src/styles/dart-sass-atlas.scss
- clayui.com/src/styles/dart-sass-base.scss
- clayui.com/src/styles/dart-sass-cadmin.scss
- clayui.com/src/styles/main.scss
- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/cadmin/variables/_alerts.scss
fixes #4493 
This uses `calc()` to fix the deprecation warnings for using / as division in Cadmin. This also updates clayui.com to `@use 'sass:math' as *;`. The deprecation warnings shouldn't show when running clayui.com.
> fix(@clayui/css): Cadmin convert a few places where we are still using slash as division

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/stories/TreeView.stories.tsx
This will only happen when the expandOnCheck prop is passed to
TreeView
Fixes #4523
> feat(@clayui/core): expand child nodes when parent is checked

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/variables/_buttons.scss
fixes #4521 
This creates the Sass maps `$btn-sizes` and `$btn-monospaced-sizes` and loops through it outputting Sass placeholders and styles. It allows devs to modify or create their own button sizes.
```scss
$btn-sizes: (
btn-sm: (
padding-bottom: 2px,
padding-left: 4px,
padding-right: 4px,
padding-left: 2px,
),
'.extra-small-button': (
padding: 0,
),
);
```
Outputs:
```scss
%clay-btn-sm {
padding-bottom: 2px;
padding-left: 4px;
padding-right: 4px;
padding-left: 2px;
}
.btn-sm {
@extend %clay-btn-sm !optional;
}
%extra-small-button {
padding: 0;
}
.extra-small-button {
@extend %extra-small-button !optional;
}
```
Other fixes:
- Atlas Buttons some disabled button-outline variants have white text on hover
> feat(@clayui/css): Buttons allow setting a variety of button sizes via `$btn-sizes` and `$btn-monospaced-sizes`

- packages/clay-css/src/scss/cadmin/components/_input-groups.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_input-groups.scss
- packages/clay-css/src/scss/mixins/_labels.scss
- packages/clay-css/src/scss/variables/_forms.scss
fixes #4514 
This converts most `input-group` to the Clay mixin pattern.
> feat(@clayui/css): Input Group convert to Clay mixin pattern

- packages/clay-core/package.json
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/demos/package.json
- packages/demos/stories/index.tsx
- yarn.lock
These dependencies need to be in sync with the ones used in DXP.
Additionally, HTML5Backend is now a named export (previously was a
default export).
Another reason to move Clay into DXP
Fixes #4530
> chore(@clayui/core): update react-dnd and react-dnd-html5-backend

- packages/clay-core/docs/treeview.js
- packages/clay-core/src/index.ts
In [3939f07](https://github.com/liferay/clay/commit/3939f07b9df6ba39116ec1291a30caf2b0ea514b), we decided
to export the TreeView component as UNSAFE_TreeView. This doesn't have
any benefit since the component is still exported (and thus can be
imported), it just makes it look a bit "strange" when importing the
component, and there's nothing "unsafe" about this component.
Fixes #4528
Depends on #4531 #4532
> fix(@clayui/core): don't export TreeView as UNSAFE_TreeView

- packages/clay-css/src/scss/mixins/_cards.scss
- packages/clay-css/src/scss/variables/_cards.scss
> feat(@clayui/css): Mixin `clay-card-variant` make `form-check-card` and `form-check-input` customizable

- packages/clay-css/src/scss/cadmin/variables/_navs.scss
Prevents theme nav-underline active highlight from bleeding into cadmin components fixes #4562
> fix(@clayui/css): Cadmin Nav adds `background-color` to `.active` pseudo element

- CONTRIBUTING.md
Not everyone likes installing packages globally, so here we're just adding an alternative.
> chore: add additional information about npm-check-updates

- packages/clay-css/src/scss/cadmin/components/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_custom-forms.scss
- Set `z-index` on `custom-control` psuedo elements and `position` on the `label` element to prevent customizations on custom-control from impacting Cadmin custom controls
fixes #4570
> fix(@clayui/css): Cadmin reset Custom Checkbox and Radio pseudo elements

- packages/clay-css/src/scss/cadmin/components/_navs.scss
> fix(@clayui/css): Cadmin reset `nav-link` pseudo elements

- clayui.com/content/docs/components/markup-treeview.md
- packages/clay-core/docs/treeview.js
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/cadmin/components/_links.scss
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_links.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_links.scss
- packages/clay-css/src/scss/variables/_treeview.scss
fixes #4588
- removed unnecessary `setter()`'s from code
- added docs for `.treeview-item.disabled`, `.treeview-dropping`, `.treeview-dragging-*`
- removed cadmin from examples in the docs
> feat(@clayui/css): Ports over Treeview to Clay from Cadmin

- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
fix(@clayui/css): Treeview use `box-shadow` instead of border to indicate drop zone
fix(@clayui/css): Treeview use `clay-link` mixin for `treeview-dropping-*` it gives more styling options like hover, focus, active, disabled and pseudo elements
fixes #4592
> fix(@clayui/css): Treeview dropping an item above or below causes items to shift

- .storybook/main.js
- package.json
This is just a test PR, apparently, Storybook is consuming too much memory and maxing out, not sure if it's related to the Node.js limit set before 4GB now to 8GB because the process is being killed with `exit code 137`, so it is more related to the operating system in this case Linux, maybe the container in our plan has a limit of 4GB or less, I will look more at the documentations.
> chore: increases storybook memory usage and split files more into chunks

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
- Removes dropping styles and style `treeview-link` directly
@matuzalemsteles I wasn't able to make the disable links when dragging happen since it requires pointer events on the item being dragged. This just frees up the `disabled` class for future use. I think it will come in handy.
fixes #4593
> fix(@clayui/css): Rename `.treeview-item.disabled` to `treeview-item-dragging`

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
>  fix(@clayui/css): Forms `label` inside `form-control` should use `min-height`

- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/TimePicker.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-date-picker/src/index.tsx
Fixes #4608
Just small fixes related to Date Picker with Time Picker. Some changes are more related to the Time Picker default value which was always starting with the value.
> fix(@clayui/date-picker): fix time picker default value and error when not formatting time in 12hours when passing to time picker

- packages/clay-css/README.md
chore(@clayui/css): Removes old build instructions from README. We no longer use gulp here.
fixes #4598
> chore(@clayui/css): Update README with how to add SVG icon

- packages/clay-core/docs/treeview.js
- packages/clay-core/docs/treeview.mdx
This PR is just a follow-up to #4603. Added information about selection types and manual selection, let me know if I missed something.
> docs(@clayui/core): adds documentation of selection types and "manual" selection

- packages/clay-pagination/src/Ellipsis.tsx
- packages/clay-pagination/src/PaginationWithBasicItems.tsx
- packages/clay-pagination/src/__tests__/index.tsx
This is potential quick fix for https://github.com/liferay/clay/issues/4605 until lexicon revise this pattern
Here we simply allow disabling the ellipsis button to avoid having a dropdown with a huge number of items (for bigger pagination)
Let me know what do you think :)
> feat: Allow disabling ellipsis button in pagination

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/stories/TreeView.stories.tsx
Fixes #4623
I'm just removing the option to select parent nodes when the `selectionMode` is multiple only, in the code I'm just separating and repeating a bit to avoid the multiple conditions if the `selectionMode` is `multiple-recursive`.
> fix(@clayui/core): TreeView: fix error when selecting parent nodes and controlling intermediate state in multiple selection

- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/index.tsx
Fixes #4580
When there are no custom colors but the editor is enabled it was not synchronizing what the user was typing in the Field with the editor just the inverse path, this commit corrects this behavior for this scenario.
> fix(@clayui/color-picker): fixes error when not syncing the field state with the editor when there are no palettes

- packages/clay-core/src/tree-view/TreeViewItem.tsx
Fixes #4652
This PR is adding the possibility to call the `onChange` method if it is declared in the `Checkbox`, ideally, the TreeView abstracts the need to control the Checkbox but some need to listen for the `onChange` event to do other operations.
I'm also adding the same behavior as in `onClick` to be able to prevent the default behavior.
> chore(@clayui/core): call `onChange` if declared in Checkbox

- clayui.com/content/docs/css/utilities/markup-text.md
- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/variables/_utilities.scss
Quoting Emiliano (can't find gh user name):
> I just want to add that even if programmatically it would make sense to add more steps from both sizes, from the design point of view I wouldn’t recommend going under 10px in any case. Thus, there shouldn’t be a way to scale it downwards, at least from our side.
> I also think a common scenario for this would be a request to extend between steps (like adding one number between XL and XXL) and that’s difficult to provide, but not impossible.
> I think T-Shirt sizes are a good idea if we adapt it for the web, and for this I would recommend aligning the text sizes with the measures the same way we did with colors and is by adding steps, here’s my idea:
> 16px is the base so it should be an unique Medium size (fs-M).
then we can decrease size: …
> feat(@clayui/css): Utilities adds `font-size` utilities `fs-*`

- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/index.tsx
Fixes #4645
I noticed that we are directly using `NEW_DATE` instead of `initialMonth` (I was probably the one who did it 😄), I changed it because this can generate some conflicts if the property is set.
You can test by checking the example in Storybook using the time example with the date picker. This PR fixes for when the time is 12 hours as well. This PR is related to #4647 which fixes the formatting to 12 hours.
> fix(@clayui/date-picker): fix bug when not changing time to current time when clicking on dot button

- packages/clay-date-picker/src/index.tsx
**@clayui/date-picker:** Reset to actual date when input of the date picker is empty
Fixes #4470
> fix(@clayui/date-picker): Reset actual date when input string is empty

- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/TimePicker.tsx
- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/index.tsx
Fixes #4638
The time formatting was only being done when it was passed to the TimePicker component but not being formatted correctly when it is saved in the internal state, this caused other actions to change the value to the wrong time when changing the date for example.
The second case was always saving the ampm in the time state, just checking that `use12Hours` is enabled before saving.
> fix(@clayui/date-picker): fix error when formatting time using 12 hours

- docs/README.md
- docs/netlify_deploy.md
Fixes #4583
I'm adding the doc to describe a little more about the Netlify deployment flow and how this process works, let me know if this will help or if I'm missing something.
> docs: add Netlify deploy process doc

- packages/clay-core/docs/treeview.mdx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-shared/src/useInternalState.ts
Fixes #4660 #4661
This PR fixes the error that when starting the rendering of the TreeView with selected items, it was not keeping the state of intermediate, that's because this data is not saved in the backend and just for visual effect, so we need to check which items should have the state of intermediate.
Also with items selected in depth were not visible, we need to expand their parent items to make them visible.
Correcting this implied having to traverse the items tree to know which items should be expanded, we have some conditions that can optimize this so that it does not traverse the entire tree, first, we traverse the tree in search of the selected items and stop traversing until we find all the items, depending on the data and where the selected items are, this can be very fast …
> fix(@clayui/core): fixes the error of not revalidating the intermediate state of the selected item's parents in the first render and expands the items

- packages/clay-localized-input/src/index.tsx
Fix a small typo on the label `UNTRANSLATED`
> fix(@clayui/localized-input): fix typo

- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/index.tsx
Fixes #4624
This API simplifies the use case of issue #4624, but I added it in the API description to only disable it when the year range is dynamic, otherwise, there will be a visual bug in the year selector.
> feat(@clayui/date-picker): adds a new `yearsCheck` prop to be able to disable the check if the year is within the years range

- README.md
**What's new?**
Update README.md structure including:
- **Table of Contents**.
- **New Cover**.
- **Better explanation in Setup content**
- **Better organisation**
**FIXES**
#4671
> docs(README): Update README structure

- clayui.com/content/docs/components/markup-treeview.md
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
issue #4676 
@matuzalemsteles This should cover the disabled styles. We need to disable each clickable element inside a disabled link unfortunately. This mostly applies to a checkbox if it's present. The hover controls won't be shown if disabled.
> fix(@clayui/css): Treeview adds disabled styles to `treeview-link`

- package.json
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/Item.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/index.tsx
This issue is linked to https://github.com/liferay-frontend/liferay-portal/pull/1950 and https://issues.liferay.com/browse/LPS-148048
_This issue has been reported by a blind association that is a Liferay customer, for more information see: https://issues.liferay.com/browse/LPS-148048?focusedCommentId=2626115&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2626115_
The pagination button to the current page should be disabled to avoid screen readers read it, as this is confusing for the final users.
After a quick research with several search engines:
- Google: https://www.google.com/search?q=search
- Bing: https://www.bing.com/search?q=search
- Yahoo: https://search.yahoo.com/search?p=search
- Amazon: https://www.amazon.com/s?k=search
All of them are not …
> fix(@clayui/pagination): The current page button must be disabled to avoid screen readers to read it as this is confusing for the final user

- docs/README.md
- docs/tests.md
Well, this document describes most of the recommendations that @john-co reported in his review and recommendations on covering unit tests with organic limits. I've also added the test building approach to the suites that we're already using on most of the more complex components.
Leave your opinion and suggestions on how we can better handle the tests.
> docs: adds Tests coverage document with testing recommendations and strategies

- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/BasicRendering.tsx
- packages/clay-core/src/tree-view/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/tree-view/useTree.ts
Fixes #4658
This PR is just a draft, but it already includes the `BasicRendering` suite for the TreeView component, I'm still working on the incremental interactions suite, it has good coverage of the TreeView cases, I should probably finish it tomorrow.
It also includes a fix for when the content is static setting the key it was getting lost because it was using the [`React.Children.toArray`](https://reactjs.org/docs/react-api.html#reactchildrentoarray) API which does this intentionally 🤦‍♂️.
Any suggestion is welcome!
> chore(@clayui/core): adds TreeView tests

- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-core/docs/treeview.js
- packages/clay-core/docs/treeview.mdx
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/__tests__/BasicRendering.tsx
- packages/clay-core/src/tree-view/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-date-picker/src/index.tsx
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-panel/src/index.tsx
- packages/clay-shared/package.json
- packages/clay-shared/src/useInternalState.ts
Fixes #4662
Well, following with the feedbacks, we are adding properties in the TreeView that define the initial value of controlled props, also adding the warning message when the properties are used incorrectly, the warning message is practically the same as what React.js throws when doing this in the input elements.
This change removes the behavior of `items`, `expandedKeys` and `selectedKeys` from also having the initial state behavior when they are only defined without the handler properties, in the next release we will have to update the use cases in DXP.
> feat(@clayui/core): adds new properties to set the initial value of properties that can be controlled

- .github/workflows/main.yml
- .github/workflows/release.yml
Related #3683
I spent a little bit of the day today trying to bring our manual Clay releases workflow into an automated workflow with Github Actions.
This implementation has some implications that not being able to reproduce the `git push $REMOTE master:stable` step was failing in the CI, I think if I do more tests I can get it working too.
Some considerations, this workflow is [triggered manually via the Github CLI or via the UI in the Actions tab](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow), so whenever we need to cut a new release we just run the workflow manually and it will take care of everything, run tests, cut package versions using semantic version, add the changelog and publish to NPM.
> Apparently, we don't have access to configure …
> chore: adds workflow to generate automated release

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-shared/package.json
- packages/clay-shared/src/doAlign.ts
- yarn.lock
Fixes #4720
This PR adds a new `alignmentByViewport` prop which is passed to `dom-align` to align the element considering the viewport.
I didn't set it as the default because in most scenarios it doesn't make sense because the user can scroll to view the DropDown content and if considering the viewport it can cause strange behavior and not very smooth alignment, in the case of the issue it does feeling because it is inside another container with scroll and fixed on the screen.
> feat(@clayui/drop-down): add new prop to align Menu in viewport

- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/__tests__/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/DropDownWithItems.tsx
- packages/clay-drop-down/src/__tests__/index.tsx
- packages/clay-drop-down/stories/index.tsx
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-upper-toolbar/src/__tests__/__snapshots__/index.tsx.snap
This is an improvement on top of [1d90d45].(https://github.com/liferay/clay/commit/1d90d454d9b2d242dd2d491e4525e815553e9fa3)
By default the behaviour of the component is unchanged, but by passing
the `renderMenuOnClick` prop, the menu will be rendered only when
the trigger is clicked.
> feat(@clayui/drop-down): make it possible to render the menu lazily

- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/hooks.ts
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/index.tsx
**What is new?**
There are some changes:
-  It saves the current colour in the **Custom Colour Palette**. 
- **Hue** synchronization with the current color and the rest of components.
- **Input** elements in upper case.
https://user-images.githubusercontent.com/44723449/155372894-1d37400b-86ed-440e-bcf5-bd3a0a3fbfc0.mov
https://user-images.githubusercontent.com/44723449/155372964-3ad1e707-b7c5-429e-8696-24bc3dfa8abd.mov
**FIXES**
#4580
> fix(@clayui/color-picker): Current colour persist and Hue component synchronization

- packages/clay-modal/src/Context.ts
- packages/clay-modal/src/Header.tsx
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/modal.tsx.snap
- packages/clay-modal/stories/index.tsx
Fixes #4736
It basically adds attributes that we haven't added for accessibility like `role="dialog"` and others.
We are also moving the focus to the `role="dialog"` which has `aria-labelledby` which can help the screen reader read the dialog title, this avoids escaping the Modal focus control along with `aria- hidden="true"`, this implementation does not break `autoFocus` if used.
If you want to test these scenarios, use a screen reader and see the Modal examples in the Storybook. [Remember that the link is generated in the CI checks](https://github.com/liferay/clay/blob/master/docs/netlify_deploy.md#deploy-previews).
> feat(@clayui/modal): improves ClayModal component accessibility

- packages/clay-core/src/tree-view/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
Fixes #4742
Basically, this PR fixes an edge case that was not being considered, considering that in a recursive flow to add or remove the item from the `intermediate` state it was just checking if the children of the parent were selected would decide but exist a case of a tree in-depth than any of the parent's children can have other children and is set to `intermediate`, in which case the recursive multiple selection must preserve the `intermediate` state of the parent if there is any child selected or `intermediate`.
This ASCII represents an illustration of a tree with this edge case:
```
Root (Intermediate)
├─ Item 0 (Checked) <- Click to uncheck
├─ Item 1 (Intermediate)
│  ├─ Item 2 (Checked)
│  ├─ Item 3
```
I'm also adding a test for this selection edge case.
> fix(@clayui/core): fixes error when removing parent's intermediate state when item's sibling is intermediate

- packages/clay-color-picker/src/index.tsx
Fixes #4694
This validation does not prevent how much the user is typing at the moment, only after the user leaves the input the validation is done, either by converting the hex, if the color is not valid it is set to an empty value, this allows people to type different types of colors besides hexadecimal.
For example set the color using CSS Variable, color name, hsl, hsv, rgb. I think the Lexicon document is not covering these cases that came more from the stylebook, so some rules that exist in the specification are very related to the use of hexadecimal but in this case, we can't imply some rules or for example, define the maximum size of the input length instead we leave it free and update the input in `onBlur` that has a better DX to cover all these cases.
> feat(@clayui/color-picker): add color validation in input

- packages/clay-color-picker/src/__tests__/index.tsx
After we added coverage threshold to tests #4739, CI failed after PR #4738 entered master, it hadn't failed PR because it didn't have those coverage limits before this.
This PR adds input validation test cases for the different scenarios covered in PR #4738.
> chore(@clayui/color-picker): add test cases for input validation

- .github/workflows/release.yml
I did a test using the automated release workflow but the version being cut is a patch version, because `actions/checkout@v2` is only fetching the first commit instead of fetching all commits for the conventional commit to working well.
Also, the publishing part of the packages doesn't seem to work for some reason, I think because we are using `lerna publish from-package` instead of `lerna publish from-git` to test this.
> chore: fixes error when not getting git history to cut a new version in workflow

- .github/workflows/release.yml
[I managed to make the release using the automated workflow](https://github.com/liferay/clay/actions/runs/2018503223) but without the publish step, apparently when running the publish step in NPM I was not having visibility of the commit made in the previous step that cuts the new version, so the command says it has none version to be published.
```
Run lerna publish from-git --yes
info cli using local version of lerna
lerna notice cli v4.0.0
lerna info ci enabled
lerna notice from-git No tagged release found
lerna success No changed packages to publish 
```
I made the change to get the Git SHA reference from the version step and use it in the publish step at checkout, now the job can have visibility of recent changes.
> chore: add the version step sha reference in the publish step of the release workflow

- packages/clay-css/src/scss/atlas/variables/_utilities.scss
- packages/clay-css/src/scss/variables/_utilities.scss
- Change `hover-*`, `focus-*`, `disabled-*` to `hover: (property: value,)`, `focus: (property: value,)`, and `disabled: (property: value)`, etc
- Removes the use of `$btn-*` variables, to make the Utilities variable file more modular
- Make focus style consistent for `a` or `button`, we have the `c-inner` pattern for removing focus on click
fixes #4734
> fix(@clayui/css): Utilities Close use newer keys in Sass map

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/mixins/_navbar.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/src/scss/variables/_navbar.scss
- packages/clay-css/src/scss/variables/_navs.scss
- packages/clay-css/src/scss/variables/_progress-bars.scss
- packages/clay-css/src/scss/variables/_utilities.scss
This creates a `$font-scale` map where we can store a Design System's progression of font sizes for reuse. You can reuse them with `map-get($font-scale, #)`. I was hoping to replace `$font-size-base`, `$font-size-sm`, `$font-size-lg`, etc with the font scale, but it would break font sizes for someone who relied on the scaling of Bootstrap's `$font-size-base`.
I ended up fixing #4393 in this pr as well. The font size variables supports CSS Custom Properties now.
/cc @ethib137 
fixes #4718 
fixes #4393
> feat(@clayui/css): Adds $font-scale map for storing a Design System's font sizes

- .github/workflows/release.yml
In PR #4749 I added some workflow changes to use newer SHA so it can be used in the next publish job so that lerna has visibility of the created commit that updates the package versions and can publish correctly but I didn't configure it correctly because the `new_sha` variable was not being exposed so that the `publish` job could have ref visibility.
> chore: add the outputs variable in the release workflow to be exposed in the job

- packages/clay-modal/src/Provider.tsx
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/stories/index.tsx
When not providing footer and header properties on ModalProvider's dispatch, it will not render footer and header sections.
0. Fetch my changes
1. Run `yarn storybook`
2. Go to Clay Modal > w/ Provider
3. Click on Button with the following title: "Open modal without Footer and Header"
4. To close the modal, hit ESC or click outside the modal
Fixes #4778
> feat(@clayui/modal): When using ClayModalProvider, `footer`,`header` properties now are optional

- packages/clay-empty-state/src/__tests__/index.tsx
- packages/clay-empty-state/src/index.tsx
- packages/clay-empty-state/stories/index.tsx
When passing `title={null}` it will not render title related markup.
Ideally we should:
1. Stop naming props as native DOM attrs 
2. Don't provide default values, turning `title` and `description` properties mandatory and not optional anymore, since they should be i18n with `Liferay.Language.get`.
Can I create tickets for it? Maybe to be updated on v4? /cc @matuzalemsteles @bryceosterhaus 
1. Fetch my changes
2. Run `yarn storybook` on Clay repo
3. Go to ClayEmptyState > no title on Storybook :)
Fixes #4776
> feat(@clay/empty-state): Enable users to not render title related markup on empty-state

- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/stories/index.tsx
Fixes #4775
The contextual menu is rendered in a submenu next to the current menu, so the properties of `hasRightSymbols` and `hasLeftSymbols` were not defined, in this case, I am checking if within the items of the current contextual menu there is any icon, the search for this property on `findNested` ignores continuing fetching if there is a sub-menu because it should be fetching only when the element is rendered and with the data of the current contextual menu being rendered, this avoids the case, for example, exists icons in the sub-menu and not in the current menu, this would render extra whitespace unnecessarily.
> fix(@clayui/drop-down): fix contextual menu error not rendering icons without spaces

- jest.config.js
We recently added new behaviors to ColorPicker, #4691 and #4738, and new tests were created to cover these new scenarios in #4746 and #4781. This increases our current coverage and to continue with our strategy of organic growth and safe testing, we raised the threshold closer to the current one to prevent us from losing coverage or failing to test the new behaviors.
> chore: updates test threshold for ColorPicker

- packages/clay-css/src/scss/cadmin/components/_navbar.scss
- packages/clay-css/src/scss/components/_navbar.scss
- packages/clay-navigation-bar/docs/index.js
- packages/clay-navigation-bar/docs/navigation-bar.mdx
- packages/clay-navigation-bar/src/Item.tsx
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/__tests__/index.tsx
- packages/clay-navigation-bar/src/index.tsx
- packages/clay-navigation-bar/stories/index.tsx
**What is new?**
- Adding `text-truncate` in `ClayNavigationBar`.
- Updates snapshots for test cases.
**Before changes:**
https://user-images.githubusercontent.com/44723449/160881502-82ea1313-08b4-467f-b7ad-88e946ab37ef.mov
**After changes:**
**Reproduce in portal:**
Using the Dev tools and applying `text-truncate` in the component, the result is:
https://user-images.githubusercontent.com/44723449/160883404-39f39f3f-b0a5-43e9-8904-2afd793407f0.mov
**Issues:**
#4773
> fix(@clayui/navigator-bar): Long text in Item is truncated

- packages/clay-shared/src/useFocusManagement.ts
Fixes #4787
React 17.x had no internal changes to the Fiber API so the implementation is safe here but only changed the API name for fiber access, previously `__reactInternalInstance` and now in 17.x `__reactFiber`.
> fix(@clayui/shared): fix error when controlling focus in React 17.x

- .github/workflows/release.yml
The release process of cutting the version generates a new commit that we need to send to the master, this happens in the `version` step, and in the `publish` step we get the SHA so that we can work on top of the last change.
The problem with this is that even though we run `git push origin master` it doesn't immediately sync with the upstream, it's probably done after the job finishes.
In the `publish` step we are trying to sync `master:stable` but it is [causing an error](https://github.com/liferay/clay/runs/5819769892?check_suite_focus=true):
```
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/liferay/clay'
Error: Process completed with exit code 1.
```
That's because there seems to be a difference in refs between the master in clay …
> chore: changes the way to sync the master branch with stable in the release flow

- jest.config.js
- packages/clay-core/docs/api-overlay-mask.mdx
- packages/clay-core/docs/overlay-mask.js
- packages/clay-core/docs/overlay-mask.mdx
- packages/clay-core/src/index.ts
- packages/clay-core/src/overlay-mask/OverlayMask.tsx
- packages/clay-core/src/overlay-mask/__tests__/BasicRendering.tsx
- packages/clay-core/src/overlay-mask/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/overlay-mask/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/overlay-mask/index.ts
- packages/clay-core/stories/OverlayMask.stories.tsx
- packages/clay-popover/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-popover/src/__tests__/index.tsx
- packages/clay-popover/src/index.tsx
Fixes #4791
Well, this is a new component to handle element highlighting and overlay, I wanted to try using it in Modal but it's a bit overkill for Modal. Also still not sure about that name, I thought `<HighlightOverlay />` seems like a good option.
This component allows [controlling and uncontrolled](https://github.com/liferay/clay/blob/0ac74bb7b16322be916a0dbcc74646c810037aef/docs/proposals/0002-controlled-and-uncontrolled.md) the `bounds` state that defines the highlight aria, otherwise, it will be automatically detected if `children` is defined.
```jsx
// Create the highlight for the Button component
<OverlayMask visible>
<ClayButton>Button</ClayButton>
</OverlayMask>
```
Another option is to define the children as a function and the `ref` is passed via render props to allow you to …
> feat(@clayui/core): adds the new OverlayMask component

- packages/clay-shared/src/__tests__/FocusScope.tsx
**What is new?**
Adding more test cases to FocusScope:
1. Some interactions using `tab + shift`.
2. Some interactions using `Arrow Up` and `Arrow Down`
3. Some interactions using `ClayPortal` to move the focus outside the React Tree
**Issues:**
#4621
> feat(@clayui/clay-shared): Add more test cases to FocusScope

- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_grid.scss
- packages/clay-css/src/scss/variables/_forms.scss
fixes #4711
This converts `form-control` sizes to use the Clay Mixin pattern.
textarea, textarea.form-control-lg, textarea.form-control-sm, .form-control-lg, .form-control-sm, .form-control-select.form-control-sm
>  fix(@clayui/css): Forms input sizes should be generated using the Clay Mixin pattern

- packages/clay-core/stories/OverlayMask.stories.tsx
After PR #4801 entered the master new properties were added to the popover which are used in compositing with the OverlayMask, this PR just updates the example in the storybook to use the new properties.
> chore(@clayui/core): updates the OverlayMask example with popover to use the new properties

- clayui.com/static/images/icons/icons.svg
- clayui.com/static/js/icons-autogenerated.json
We recently added new icons but they were not updated in the documentation, I just added the generated files here. Maybe one way to avoid generating these files every time and being tracked by git is bypassing git and letting it run at build time, probably build time for production is already done and we don't update in git.
> chore(clayui.com): add the new icons in the documentation

- .github/workflows/release.yml
For some reason, it is not possible to sync with master with stable by Github Action, for now, I will do it manually and send another PR to test another option. Submitting this so we can see if we can automate the end-to-end release today.
> chore(release): remove the step of sync master with stable

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/atlas/variables/_navs.scss
- packages/clay-css/src/scss/atlas/variables/_sheets.scss
- packages/clay-css/src/scss/atlas/variables/_sidebar.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_panels.scss
- packages/clay-css/src/scss/variables/_tbar.scss
- interpolate multiple box-shadows and transitions
- use the global $component-focus-box-shadow where applicable
- Mixins clay-button-variant should be able to style .active:focus
fixes #4804
> fix(@clayui/css): Atlas .btn.active:focus should have outline

- clayui.com/content/docs/examples.mdx
- clayui.com/gatsby/onCreateNode.js
- clayui.com/src/templates/docs.js
- packages/clay-alert/docs/alert.mdx
- packages/clay-badge/docs/badge.mdx
- packages/clay-charts/docs/charts.mdx
- packages/clay-color-picker/docs/color-picker.mdx
- packages/clay-core/docs/overlay-mask.mdx
- packages/clay-core/docs/treeview.mdx
- packages/clay-form/docs/checkbox.mdx
- packages/clay-form/docs/dual-list-box.mdx
- packages/clay-form/docs/form.mdx
- packages/clay-form/docs/input.mdx
- packages/clay-form/docs/radio-group.mdx
- packages/clay-form/docs/select-box.mdx
- packages/clay-form/docs/select.mdx
- packages/clay-form/docs/toggle-switch.mdx
- packages/clay-label/docs/label.mdx
- packages/clay-management-toolbar/docs/management-toolbar.mdx
- packages/clay-multi-step-nav/docs/multi-step-nav.mdx
- packages/clay-panel/docs/panel.mdx
- packages/clay-provider/docs/provider.mdx
- packages/clay-sticker/docs/sticker.mdx
- packages/clay-table/docs/table.mdx
- packages/clay-upper-toolbar/README.md
- packages/clay-upper-toolbar/docs/upper-toolbar.mdx
Fixes #4821
This PR just updates the examples links to Storybook, after we updated the Storybook version we rearranged the content to be clearer and that changed the paths so we are updating here.
> chore: updates broken links to examples in storybook

- packages/clay-core/src/typography/Heading.tsx
- packages/clay-core/src/typography/__tests__/__snapshots__/index.tsx.snap
Following up #4659
I ended up not noticing in the implementation's PR that we weren't updating the tag according to the `level` definition, in this case, we need to make the tag follow the definition to keep the markup semantics adequate for each level. Maybe it got confused when I explained that the sizes must follow the mapping of the classes.
> fix(@clayui/core): the Heading tag follows the level definition

- .github/workflows/release.yml
This is an attempt to correct #4822.
This is a solution so that Lerna can publish the packages through CI using NPM tokens, unfortunately, lerna has no other option to get the token via env.
> chore: add npm token via CI

- tsconfig.declarations.json
Fixes #4836
I'm setting the `removeComments` property to `false` because this TypeScript config is an extension of the build config that omits comments in the output.
> chore: add comments to types outputs

- clayui.com/plugins/gatsby-remark-api-table/index.js
Fixes #4835
I'm adding a deprecated badge along with the property name in the API table in the documentation. This is a step so that people can see that some properties have been deprecated, I think that in the improvements later in the documentation and in the more adjusted visual, we will put a better interaction like showing the information of which alternative to the property if exist (this information is currently in the description).
> feat(clayui.com): add deprecated prop badge to doc

- packages/clay-css/src/scss/variables/_alerts.scss
- packages/clay-css/src/scss/variables/_tables.scss
I wanted to remove all uses of Bootstrap's `theme-color-level` function, but might be too breaking.
fixes #4281
> fix(@clayui/css): Alerts/Table deprecate `$alert-*-level` and `$table-*-level` variables

- jest.config.js
- packages/clay-core/src/overlay-mask/OverlayMask.tsx
Fixes #4851
This is an improvement to the `<OverlayMask />` component that tracks the position of the container when the window is scrolled or resized. I tried to make it not need the `observeRect` but it's not working very well when I use the window resize listener I also wanted to do it via CSS it didn't work very well either. I need to set the value to the element size. Maybe I'm missing something here, any suggestions are welcome.
> chore(@clayui/core): track svg container position in OverlayMask

- packages/clay-tooltip/src/TooltipProvider.tsx
- [LPS-149687](https://issues.liferay.com/browse/LPS-149687)
* Fix tooltip misalignment when hovering and clicking on trigger
Tooltip shows but isn't in the right position
https://user-images.githubusercontent.com/6642927/167459355-814f0d5f-2348-442a-8113-e288adf6a196.mov
Tooltip doesn't show until you after you hover over the trigger again
https://user-images.githubusercontent.com/6642927/167459404-1b44b27c-4824-46eb-bcac-e7e19b33ecbc.mov
* Go to DXP Forms
* Add a new form
* Add any field
* Hover over the field, hover over the actions button, quickly click on it
* See that a tooltip appears on the bottom left of the screen
The cause of this is that in scoped mode, we are subscribing to [all these events](https://github.com/liferay/clay/blob/master/packages/clay-tooltip/src/TooltipProvider …
> fix(@clayui/tooltip): cancel scheduled tooltip before scheduling new one

- jest.config.js
- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/__tests__/BasicRendering.tsx
- packages/clay-date-picker/src/index.tsx
Fixes #4856
Well, this is not a specific bug of the implementation of controlled or uncontrolled, actually, we were not covering this use case, we just consider the value of the `initialMonth` property instead of considering the value of `value` or `defaultValue`.
Considering that this is a behavior that was from the beginning of the component construction, probably people always used the `initialMonth` to start the default value, maybe this was misinterpreted the use of this property that ended up covering a wrong behavior of the component, with the introduction of more solid controlled and uncontrolled components got more clearer for developers.
> fix(@clayui/date-picker): fix date picker error not starting with default values using controlled or uncontrolled

- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
- component-expander should be smaller 10px
- component-icon and component-action should be larger 16px
fixes #4862
> fix(@clayui/css): Treeview and Cadmin Treeview update font size of icons

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
Closes #4863
There is another way to provide this like we do for selection but I think the expander is not needed now, we can see if there are use cases in the future and we can think about adding that possibility.
I'm adding the `expandDoubleClick` API that expanding by clicking on the node will only be done by double-click on the node, it is also possible to avoid this behavior but I think it is something that may not even make sense to be added because to have this behavior is enabled via props but I'm adding to keep the same behavior we have for `onClick`.
> feat(@clayui/core): adds new API to expand node via double click in TreeView

- .github/workflows/release.yml
- package.json
- packages/clay-charts/stories/Chart.stories.tsx
- packages/clay-data-provider/stories/DataProvider.stories.tsx
- packages/clay-empty-state/stories/EmptyState.stories.tsx
- packages/clay-shared/stories/FocusScope.stories.tsx
- packages/demos/stories/Recharts.stories.tsx
- yarn.lock
Closes #4802
Well I did some exploring with [Chromatic](https://www.chromatic.com/) and we don't really need to do any configuration, this is [very simple and OOTB with storybook](https://storybook.js.org/docs/react/writing-tests/visual-testing) is pretty cool.
The problem is that you need a Cloud service from [Chromatic](https://www.chromatic.com/) itself, you can't run something locally as far as I know but there is a [free plan that offers 5,000 snapshots per month](https://www.chromatic.com/pricing), this is good because so far we have 192 snapshots.
One way to not hit this limit is to run this UI test only on every workflow release instead of running it on every pull request.
I already made an account and it syncs the `liferay/clay` collaborators in …
> feat: add chromatic for visual testing

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
Fixes #4871
This PR I'm adding two new features to the TreeView, one is that it allows to use of the `onKeyDown` callback in the Item and ItemStack components and it is also possible to ignore the default behavior of the component, The second one is adding a new `onSelect` API in the TreeView which is similar to `onSelectionChange` will always be called when there is a selection of an item but passing as a parameter the properties of the item being selected.
It seems to be a default behavior that happens a lot in DXP because cases need item properties to save, this I think could be changed, it's an overload of information being sent between methods unnecessarily as well as being sent to the backend in some At times, the ideal would be to better control the information states and work only …
> feat(@clayui/core): calls onKeyDown on Item and ItemStack if defined

- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-shared/src/useInternalState.ts
Fixes #4874
The intermediate state is something internal only and we only add the node to this state when it interacts with public APIs like `selection.toggle` in render props or when the user interacts with the checkbox but we don't cover the case when the developer updates the `selectedKeys ` when being controlled, in this scenario we need to revalidate the intermediate states.
The solution I added was to always revalidate when `selectedKeys` is updated only on recursive multiple selection, a plus point about this is that updating refs doesn't cause a re-render but we need to update at render time so I used `useMemo` instead of `useEffect` here.
> fix(@clayui/core): revalidate the state of intermediate for recursive multiple selection when the state is controlled

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/BasicRendering.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
Related to the conversation in PR #4883
Allows you to add a Text component to an item in the TreeView to truncate or compose with any other property.
```jsx
<TreeView>
<TreeView.Item>
<TreeView.ItemStack>
<Icon symbol="folder" />
<Text size={3} truncate>Root</Text>
</TreeView.ItemStack>
<TreeView.Group>
<TreeView.Item>Item</TreeView.Item>
</TreeView.Group>
</TreeView.Item>
</TreeView>
```
> feat(@clayui/core): adds OOTB support for Text component in TreeView.Item/ItemStack

- clayui.com/content/docs/components/markup-treeview.md
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
fixes #4861
@matuzalemsteles I kept going back and forth on how to display these buttons.
We need to add `show-quick-actions-on-hover` to `treeview` and `quick-action-item` to the buttons/links we want to hide. The markup is below:
The first image:
```
<div class="treeview-link" role="treeitem" tabindex="-1">
<div class="c-inner" tabindex="-2">
<div class="autofit-row">
<div class="autofit-col autofit-col-expand">
<span class="component-text">
<span class="text-truncate-inline">
<span class="text-truncate">Categorization</span>
</span>
</span>
</div>
<div class="autofit-col">
<button class="btn btn-monospaced component-action quick-action-item" tabindex="-1" type="button">
<span class="c-inner" tabindex="-2">
<svg>...</svg>
</span>
</button>
</div>
</div>
</div>
</div>
```
The second …
> fix(@clayui/css): Treeview `btn` should be 24px tall and adds show-quick-actions-on-hover

- packages/clay-core/stories/TreeView.stories.tsx
Closes #4869
I'm adding some examples of using the TreeView [following the recommendations of the document](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/1970078399/LEXI-1257+Clarify+behavior+for+DXP+Trees), there are still some details of the button that will be made by issue #4861 and some behavior details like pressing enter on the focused node should select the children if exists a toggle button.
I'm leaving this as a draft to wait for the adaptations of the button to the TreeView.
> chore(@clayui/core): Add usage examples with TreeView

- .github/workflows/release.yml
I'm adding a separate step for the UI test with Chromatic because it needs all the history of commits to know the baseline and which one to compare, also creating a separate step to run the tests in parallel with the unit test, it's not necessary to wait all unit tests run and other checks in that case.
> chore: add separate step for ui test

- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
This may be enough to disable Elipses for @clayui/pagination-bar
https://github.com/liferay/clay/issues/4886
> feat(@clayui/pagination-bar): Add flag disableEllipsis to PaginationBarWithBasicItems

- packages/clay-date-picker/src/__tests__/BasicRendering.tsx
- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/index.tsx
Fixes #4888
This PR updates the Date Picker state when the component is controlled if the state is updated by an action other than the Date Picker.
> fix(@clayui/date-picker): updates Date Picker state when component is controlled

- packages/clay-css/src/scss/mixins/_slideout.scss
- packages/clay-css/src/scss/variables/_slideout.scss
fixes #4896
@matuzalemsteles `tbar-item-expand` should work now for the Vertical Navigation.
> fix(@clayui/css): c-slideout should use display: flex on tbar-stacked for show/transition

- packages/clay-core/src/tree-view/useMultipleSelection.tsx
Closes #4897
We are changing the behavior in favor of maintaining consistency and improving the UX of selecting a node with an intermediate state. To understand more about the reasons for this change see issue #4897.
The new rule here is that "select" a node that is in the intermediate state must go into the unchecked state as well as its children if it is in recursive multiple selection mode. This works not only when clicking the checkbox but also when using the `selection.toggle` API which is available via render props.
> chore(@clayui/core): clicking on a node intermediate should uncheck the node and its children

- .github/workflows/release.yml
I'm adding the possibility that we can set the release version hardcoded instead of following the conventional commit, we have the case that we want some breaking changes for example to update the visual of the loading indicator without increasing the major version.
> chore(release): Adds input to define specific release version

- packages/clay-css/src/scss/cadmin/variables/_loaders.scss
- packages/clay-css/src/scss/variables/_loaders.scss
- The rotating animation on `.loading-animation` caused elements with overflow: auto to show scrollbars
@matuzalemsteles this should fix the issues in https://github.com/liferay-frontend/liferay-portal/pull/2315. I moved the animation to the pseudo elements.
> fix(@clayui/css): Loading Animation move animation to pseudo elements

- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
Fixes #4912
I added a test case as well to cover this use case, as this component is not a conventional input but tries to mimic one with selected labels, we need to ignore the placeholder when labels exist.
> fix(@clayui/multi-select): fix error when showing placeholder when it has items

- packages/clay-multi-select/src/index.tsx
Closes #4915
It is safe to make this change, no component in DXP is using `ref` to get something from the container. It makes more sense for `ref` to go to input so you can control focus or get other information, this will be used more.
> chore(@clayui/multi-select): move ref to input

- jest.config.js
- packages/clay-color-picker/src/index.tsx
Fixes #4920
This is a small fix, which calls the `onBlur` method when it is declared in the component by the developer but I am also adding the possibility to ignore the default behavior of the component when using the `event.preventDefault()` of the `onBlur` method, this is similar to the pattern we use in TreeView, this allows better flexibility to extend behaviors or change when necessary, I believe it is not used much but it helps to create extra input validation mechanism for example that is not covered in some cases of Lexicon.
> fix(@clayui/color-picker): fix error when `onBlur` method is declared but not called

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/variables/_globals.scss
fixes #4922
- throws warning if type is not number, string, and parameter value is equal to null
> fix(@clayui/css): Global Variables remove math function parenthesis from $spacers

- packages/clay-autocomplete/src/DropDown.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-date-picker/src/index.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/stories/DropDown.stories.tsx
Fixes #4928
This fixes the bug of calling the `setActive` method even when the Menu is invisible. Add in the condition checking the status of `active`.
> fix(@clayui/drop-down): fix bug of calling `setActive` method when the menu is invisible

- packages/clay-multi-select/src/index.tsx
Fixes #4934
This was a regression from #4918, I didn't change it everywhere to use `inputElementRef` instead of `inputRef`, this is to toggle when the `ref` is declared use it instead, otherwise, we will use a ref internally.
> fix(@clayui/multi-select): fix error when you have a ref declared it is not possible to delete the label by pressing backspace

- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_input-groups.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_input-groups.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-multi-select/docs/index.js
- packages/clay-multi-select/docs/markup-text-input-multi-select.md
- packages/clay-multi-select/docs/multi-select.mdx
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/MultiSelect.stories.tsx
fixes #4911
This provides 3 ways to make Multi Select small. `.form-group-sm` works on all Multi Select. `.input-group-sm` should be used on the first `.input-group` in this [example](https://clayui.com/docs/components/multi-select.html#select-button). `.form-control-tag-group-sm` should go on `.form-control` in this [example](https://clayui.com/docs/components/multi-select.html#autocomplete).
~I still need to update cadmin and I'll update the Multi Select component too.~
> fix(@clayui/css): Clay Multi Select should have small size

- packages/clay-css/src/scss/mixins/_badges.scss
- packages/clay-css/src/scss/mixins/_border-radius.scss
- packages/clay-css/src/scss/mixins/_box-shadow.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/mixins/_cards.scss
- packages/clay-css/src/scss/mixins/_close.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_gradients.scss
- packages/clay-css/src/scss/mixins/_grid.scss
- packages/clay-css/src/scss/mixins/_labels.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/mixins/_list-group.scss
- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/mixins/_tbar.scss
Hey @pat270 I'm submitting because this was causing the build to fail in Clay's DXP release, I believe that the way in which the conditional syntax was declared in Sass is causing it to break, which is strange because if I'm not mistaken we use sass build to compile.
For more information https://github.com/liferay-frontend/liferay-portal/pull/2394#issuecomment-1161006017
> fix(@clayui/css): fix syntax error in conditional declaration

- packages/clay-css/src/scss/bootstrap/_grid.scss
`$container-max-widths` are verified to be in ascending order we can use the positions instead of values
Percent values should now work. Use to test:
```scss
$container-max-widths:(
xs: 90%,
sm: 90%,
md: 95%,
lg: 95%,
xl: 1200px
);
```
>  fix(clay-css): Grid compare the breakpoint positions instead of the `$container-max-widths` values

- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/Editor.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/src/util.ts
Closes #4733
I'm refactoring the implementation of the built-in Custom component and the way it handles state, this was creating a lot of complexity to deal with updating states and having to come up with different ways to update states. This PR creates a new component to separate the Editor from the Custom component because only the editor can be used without the custom and we are also moving the editor state to the root component so it is easier to manipulate the state when the user is still is editing in input for example.
> refactor(@clayui/color-picker): refactors the component state implementation of Custom and create the component editor

- packages/clay-drop-down/src/DropDownWithItems.tsx
This pr uses the value inside item to set a default value for the radio group in DropDownWithItems
> feat(@clayui/drop-down): Allow setting a default selected value for the radiogroup

- packages/clay-core/docs/api-treeview.mdx
- packages/clay-core/docs/treeview.mdx
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/BasicRendering.tsx
- packages/clay-core/src/tree-view/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/stories/TreeView.stories.tsx
This PR exposes new APIs to allow controlling the TreeView's internal states so that the developer can cover more use cases than the default behavior, read the issue with proposal #4949 to understand the use cases. This PR doesn't have demos to demonstrate how to get to this use case but I'll be adding more in this PR.
Controlling a node's expansion state is similar to controlling a node's selection, APIs are exposed via render props as a low-level API.
```jsx
<TreeView>
{(item, selection, expand) => (
<TreeView.Item
onClick={(event) => {
clearTimeout(clickTimerRef.current);
event.preventDefault();
switch (event.detail) {
case 1:
clickTimerRef.current = setTimeout(() => {
if (!selection.has(item.id)) {
selection.toggle(item.id);
}
}, 200);
break;
case 2:
if (!selection.has(item.id)) { …
```
> feat(@clayui/core): adds new APIs to TreeView to control node active state and expand

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
This is a complement to #4949, just adding in a separate PR because I'm not sure if we should go this way, I'm just adding the support class to the atlas but not adding it to `cadmin` yet, I'll add it later if we agree that this is the best solution.
@pat270 let me know what you think, the intention of this PR is to add a class that allows you to disable hover on a specific node.
> feat(@clayui/css): add support class to remove hover from treeview link

- packages/clay-alert/src/index.tsx
- packages/clay-css/src/scss/_license-text.scss
- packages/clay-css/src/scss/cadmin/components/_alerts.scss
- packages/clay-css/src/scss/cadmin/variables/_alerts.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/variables/_alerts.scss
Applies the same explanation we did for this PR
https://github.com/liferay-frontend/liferay-portal/pull/2478
=====
[Jira issue](https://issues.liferay.com/browse/LPS-157502)
[Lexicon](https://liferay.design/lexicon/core-components/alerts)
The icon in the alert tag component seems misaligned with the text
Use the baseline alignment for the flex children
In any use case of the tag, check the icon + text alignment.
> fix(@clayui/css): Alert Indicator inside alert-autofit-row aren't vertically aligned with text

- clayui.com/content/docs/components/markup-aspect-ratio.md
- clayui.com/content/docs/css/utilities/markup-borders.md
- clayui.com/content/docs/css/utilities/markup-color-utilities.md
- clayui.com/content/docs/css/utilities/markup-text.md
- packages/clay-alert/docs/markup-alert.md
- packages/clay-badge/docs/markup-badge.md
- packages/clay-button/docs/markup-button.md
- packages/clay-css/src/scss/cadmin/components/_alerts.scss
- packages/clay-css/src/scss/cadmin/components/_aspect-ratio.scss
- packages/clay-css/src/scss/cadmin/components/_badges.scss
- packages/clay-css/src/scss/cadmin/components/_buttons.scss
- packages/clay-css/src/scss/cadmin/components/_labels.scss
- packages/clay-css/src/scss/cadmin/components/_popovers.scss
- packages/clay-css/src/scss/cadmin/components/_stickers.scss
- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/components/_aspect-ratio.scss
- packages/clay-css/src/scss/components/_badges.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_labels.scss
- packages/clay-css/src/scss/components/_popovers.scss
- packages/clay-css/src/scss/components/_sidebar.scss
- packages/clay-css/src/scss/components/_stickers.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-label/docs/markup-label.md
- packages/clay-popover/docs/markup-popover.md
- packages/clay-sticker/docs/markup-sticker.md
fixes #4970
Bootstrap generated variants with theme color keys like `primary`, `secondary`, `success`. We are taking it deeper by allowing custom classes, id's and Sass placeholder.
The old style keys `primary`, `secondary`, `custom-color` will still generate a Sass placeholder and selector with the component prefix (e.g., `%btn-custom-color` and `.btn-custom-color { @extend %btn-custom-color !optional; }`).
The new style keys should be a class, id, or Sass placeholder wrapped in single quotes (e.g., `'.btn-xxl': ( font-size: 100px, )`).
```
$btn-sizes: (
'%btn-xxl': (
font-size: 100px,
),
'.btn-xxl': (
extend: '%btn-xxl',
),
);
```
~Still need to update the docs~
> fix(@clayui/css): Add option to generate placeholders separately in component variant maps

- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
Closes #4984
This PR is adding a new `onItemMove` API to the TreeView. Two main things here are that the two parameters correspond to the item being moved and the `parentItem` is the new location of the item, the TreeView also matters of position within the array, this API does not provide this information but if it is something that some devs need we can provide but for that first iteration this is fine.
I had some thoughts that this API could also be an option for the developer to create rules like validating whether moving the item to another place is valid, so we could use the boolean return to ignore the move or move on. I'm not sure if there are use cases for this but we can use this API for that purpose in the next iterations as well.
> feat(@clayui/core): adds new `onItemMove` API

- docs/proposals/0004-collection-components.md
This is just a follow-up PR from #4840 to update the RFC number and add the link to the RFC PR in the proposal document.
> docs(RFC): update RFC number and PR number

- packages/clay-autocomplete/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-drop-down/src/Caption.tsx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Item.tsx
- packages/clay-drop-down/src/ItemList.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/Section.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-drop-down/stories/DropDown.stories.tsx
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-upper-toolbar/src/__tests__/__snapshots__/index.tsx.snap
Fixes #4994
I'm adding some properties to make DropDown more accessible in addition to adding the `aria-expanded` property. I'm marking this PR still as a draft because it looks like pressing enter and the down arrow key is not moving focus to Menu using JAWS screen reader and NVDA on Windows, I'll try to test this to see if this behavior persists because I can't play in Mac voice over.
> fix(@clayui/drop-down): improves DropDown accessibility

- jest.config.js
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/drilldown/Menu.tsx
- packages/clay-drop-down/src/drilldown/index.tsx
Fixes #4996
I had to do a little history logic to be able to navigate between the menus and go back to the element with the previous focus, so we get more accessible navigation using the arrow keys, also the focus is only activated when the keyboard is used for navigation.
> fix(@clayui/drop-down): fixes error when losing focus using arrow keys in Drilldown and improves accessibility

- packages/clay-navigation-bar/src/Item.tsx
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
Hi!
This is a fix for the accessibility issue mentioned here: https://github.com/liferay/clay/issues/5002
It's meant to address the client reported issue seen on [LPP-45909](https://issues.liferay.com/browse/LPP-45909) as HRG-06 where screen readers are not informed of what the 'current page' on a navigation bar, even when highlighting it.
I've attempted to format the commits correctly, but please let me know if anything needs adjusting. Thanks!
> Navigation bar does not inform screen readers of "current page".

- packages/clay-tooltip/docs/tooltip.mdx
Closes #4992
Adds a recommendation to use the tooltip on disabled elements with title, an idea to try to mitigate this is to make Clay components like `Button` do this by default if the `title` property is set, we would also have to avoid call the component event callbacks to maintain the same behavior as `disabled`, but this can cause other side effects as the events bubbling and in case some applications in DXP have added events that expect elements with the disabled state do not emit events.
I think we can recommend developers to do this first because we would only be able to mitigate this for components in React.js and it could also cause unknown side effects.
> docs(@clayui/tooltip): adds usage recommendation with disabled elements with title

- custom-types/dom-align/index.d.ts
- packages/clay-shared/src/useMousePosition.ts
- packages/clay-tooltip/docs/tooltip.mdx
- packages/clay-tooltip/package.json
- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/stories/Tooltip.stories.tsx
Closes #4991
This feature is only available with the `<TooltipProvider />`, as we are already using it in DXP the developers just need to add the `data-tooltip-floating="true"` property to the element with the `title` for the tooltip to be floating according to the mouse position on the element. See the [example in the storybook](https://deploy-preview-5007--next-storybook-clayui.netlify.app/?path=/story/design-system-components-tooltip--floating).
> feat(@clayui/tooltip): adds new properties to configure the tooltip to be floating

- LICENSES/Apache-2.0.txt
- packages/clay-css/src/scss/mixins/_utilities.scss
Noticed a wrong use of Apache-2.0 SPDX License ID, so I fixed it and included the appropriate license text in the right folder too.
Nothing in the code should be affected by this, as it is only touching tags in comments.
> chore(@clayui/css): Fix Apache-2.0 SPDX ID

- jest.config.js
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownContext.ts
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Item.tsx
Fixes #5022
This PR fixes the focus loss when clicking on an item in DropDown, the issue is that this was not the main problem in the documentation example, because something was breaking and resetting the component because clicking on the item and closing the dropdown was not supported in low-level component but now I've added this new functionality by enabling the `closeOnClick` property on `<ClayDropDown />`.
> feat(@clayui/drop-down): Focus improvements in DropDown and new `closeOnClick` API

- jest.config.js
- packages/clay-tooltip/src/TooltipProvider.tsx
https://github.com/liferay/clay/pull/5007#issuecomment-1201277452
Hey @carolrodmar I believe this should be the closest behavior, let me know if something more subtle would be needed. You can test this change in the storybook as soon as the [preview deploy generated by Netlify](https://github.com/liferay/clay/blob/master/docs/netlify_deploy.md#deploy-previews) once the build finishes.
> fix(@clayui/tooltip): remove the behavior of moving the tooltip when the mouse moves

- jest.config.js
- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/stories/Tooltip.stories.tsx
Closes #5029
More context https://github.com/liferay/clay/pull/5023#issuecomment-1209778896, I'm reversing the change I made in the PR that was merged to fix #5029, this behavior is no longer needed because the behavior that was wanted before may be able to arrive by correctly setting the properties.
This is probably the definitive behavior for the floating mode of the tooltip so as not to generate too much confusion I updated the demo in the Storybook to have a more real case of the behavior that originated its creation so as not to create any confusion.
Basically floating it can be used for other use cases as well if it exists, not necessarily in a text as in the demo but also in an item drop zone for example.
> docs(@clayui/tooltip): updates the floating tooltip demo

- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
> fix(@clayui/css): Cadmin Buttons btn-monospaced icons should be centered

- .github/workflows/main.yml
- package.json
- tsconfig.global.json
In PR #5050 I added the possibility to check TypeScript types in CI because we only did that when a new release was made but this directly called `buildTypes` which generates only the types but this is extremely slow it increased the CI time for almost 8m in this step alone, I'm adding a lighter approach that runs the TypeScript CLI globally and just checks the types without generating this is much faster and only takes a few seconds.
> chore: add global script to just check TypeScript types

- packages/clay-provider/src/Provider.tsx
Closes #5054
If a new rendering happens in the component, the DataClient would be reinitialized, which causes the cached data and requests in progress to be lost, now we only create an instance when the component is mounted or when the property is updated.
> fix(@clayui/provider): stabilizes the DataClient reference

- packages/clay-shared/src/useFocusManagement.ts
This is a very specific behavior for some scenarios, for example in DropDown when a trigger is defined with a Button and Icon and the icon symbol changes according to the active state of the menu, this causes a change of state and icon rendering when the menu is opened if at the same time a focus change by the focus manager happens it would break because the icon fiber is in React's WorkInProgress queue and properties like `memoizedProps` are not available for access at this time. We need this information to know if the element is focusable, both `memoizedProps` and `stateNode` come null if the element is not ready yet.
We just have to ignore that element and jump to the next one.
> fix(@clayui/shared): fix error when checking a fiber element in progress in focus management

- clayui.com/src/components/LayoutNav/Search.js
- clayui.com/src/styles/_autocomplete.scss
- clayui.com/src/styles/site/_site.scss
- clayui.com/src/templates/docs.js
https://github.com/liferay/clay/issues/5073
---
I've added a second commit with accesskey K to go to the searchbar
> feat(clayui.com): Add Accessibility bar

- jest.config.js
- packages/clay-drop-down/src/DropDown.tsx
Fixes #5053
This is a bit of a hacky approach to solving this problem. To better understand what is happening here is that the focus manager relies on the DOM reference that React provides to move the focus, since the dropdown menu is not rendered on the first iteration only when the user interacts with it.
Trying to use focus manager to move focus in this scenario doesn't work, for some reason when using `useLayoutEffect` or `useEffect` we don't have visibility of elements rendered in DropDown visible in DOM to move focus manually, so I made a fallback if the focusManager is unable to move the focus on the first iteration.
This behavior of not being able to have visibility of the element in the DOM is very strange, testing a super simple implementation with just React this approach …
> fix(@clayui/drop-down): fixes error when not moving focus to element in menu when renderMenuOnClick property is set

- clayui.com/src/components/LayoutNav/Search.js
- clayui.com/src/styles/_autocomplete.scss
Native combination keys should be known by user but a good practice is print the all combination so:
- In mac is "control + option + K"
- In linux is "alt + K"
- In windows is "control + K"
So I've added the combinations:
Linux:
Mac:
Windows:
It is a good exercise if we consider to add native shortcuts without conflicting to screen readers and exposing the key by "aria-keyshortcuts".
If we would use this example in general, probably we could move the `@at-root` clases to a general new `.c-kbd-platform-frefix` class or something similar so then you add the class and the key is preceded by the platform native combination.
Of course, key combinations can be changed in SO configuration but those cases cannot be covered even by native aria, so I think is not a stopper.
In small devices we hide …
> feat(clayui.com): Add key shortcut keys by platform type and hiding it in mobile

- packages/clay-data-provider/src/__tests__/index.tsx
- packages/clay-data-provider/src/useResource.tsx
Fixes #5066
I've added a few more test scenarios that cover the scenarios we discovered when we updated the package in DXP, this brings more coverage to the DataProvider tests, I'm still writing tests when it's integrated with Suspense but I'm having some issues with jest. Also I fix a bug that even with `suspense` enabled it wasn't working.
> fix(@clayui/data-provider): add more test scenarios for multiple `useResource` instances and fix error

- packages/clay-drop-down/src/DropDown.tsx
Fixes #5090
As we were using `focusManager` to move the focus it worked but only for the scenario where `renderMenuOnClick` was disabled, when `renderMenuOnClick` is enabled the `focusManager` looks for the next element out of scope as it does not find the Menu rendered yet so fallback was not used.
I went ahead and just used fallback as the first option only and removed the use of `focusManager` for that purpose, I think we could still use `focusManager` as it is a better option and configure it to do nothing when not find a focusable element within the scope by providing some property in the call to `focusManager.focusNext()`, but for now I'll just go with the fallback solution to avoid possible regressions with focusManager to support this use case.
> fix(@clayui/drop-down): fix error when not focusing on first item of DropDown

- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_custom-forms.scss
- packages/clay-css/src/scss/mixins/_custom-forms.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
- packages/clay-form/docs/markup-checkbox-radio.md
- packages/clay-form/src/Checkbox.tsx
- packages/clay-form/src/__tests__/Checkbox.tsx
- packages/clay-form/src/__tests__/__snapshots__/Checkbox.tsx.snap
fixes #5085
Nothing needs to be done for the React component, it uses the same markup.
> feat(@clayui/css): Custom Checkbox adds readonly styles

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/IncrementalInteractions.tsx
Fixes #5086
I made a fix for the TreeView with actions when it has a DropDown and clicking on it and clicking away kept the actions still open, there were also other ways to reproduce this easily like moving the focus to an element with actions and clicking outside kept the action still visible .
This fixes these scenarios with a simple strategy to detect if the focus and click are inside the item and keep the action still visible, moving the focus or clicking outside the item makes the actions not visible. I also added some tests for these scenarios. I also added some tests for these scenarios.
> fix(@clayui/core): fix error of TreeView actions not disappearing

- packages/clay-css/src/scss/cadmin/components/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
fixes #4876
This fixes table row modifiers that don't work. I removed them in Cadmin since we don't use them in our admin interface.
> fix(@clayui/css): Tables table row variants should style the background

- jest.config.js
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/index.ts
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/vertical-bar/Bar.tsx
- packages/clay-core/src/vertical-bar/Content.tsx
Closes #5098, From #5045
In PR #5045 the idea is to create a Collection virtualization with support for the Tree data structure, the first thing that needed to be done is to make the TreeView component use the base component of Collection. This PR brings the commits of the other PR that adds new functionality to the Collection component to support the TreeView use cases, a gain of this is that we can have the Collection centralized now and we leave #5045 with low priority for now and on hold, see the comments in PR.
I'm submitting this in a new PR to keep progress history of the virtualization implementation for Tree.
> feat(@clayui/core): uses the Collection component for the TreeView

- jest.config.js
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/index.ts
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/vertical-bar/Bar.tsx
- packages/clay-core/src/vertical-bar/Content.tsx
Closes #5030
This PR is a WIP of the Collection Tree implementation, as mentioned in the issue the hardest part here is getting the nested virtualization to have accessibility, I'm still working on it but I'm submitting a piece of work that adds some more features to the Collection implementation that are needed to use in TreeView.
- Support to create unique key in tree
- Add an API to configure a component to wrap the item
- Adds an API to pass properties to the children function when it's a dynamic collection
- Adds a property to configure a list of properties that should be omitted when passing item data to children function
These are necessary resources to use in the TreeView component, see the commit d4f84198576bee69e66e5de1939099f4086f4f5c that shows how it is being used.
As …
> feat(@clayui/core): Add Collection Tree implementation

- packages/clay-autocomplete/package.json
- packages/clay-autocomplete/src/DropDown.tsx
- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
We probably forgot to apply [RFC 0002 Controlled and uncontrolled components](https://github.com/liferay/clay/blob/master/docs/proposals/0002-controlled-and-uncontrolled.md) to this component. I just creating an API to follow the standard and maintaining compatibility.
> feat(@clayui/autocomplete): deprecated the `onSetActive` API and replaced it with `onActiveChange`

- packages/clay-core/docs/treeview.mdx
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
- packages/clay-core/src/tree-view/useLayout.ts
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/src/tree-view/useTree.ts
- packages/clay-core/stories/TreeView.stories.tsx
Closes #5096
To support paginated data in TreeView, I had to expose a new API to render props to allow it to be called in composition, this is a bit similar to how it works in `useResource`, the return of `loadMore` tells how it will behave, this works like a contract to allow having the behavior of loading the item's children when expanding a node or loading a node's paginated data. It is also possible to say that you do not want to load the data of a specific item, for example in the stories that are in the Storybook.
```jsx
<TreeView
onLoadMore={async (item) => {
// Fetch data
return {
cursor: result.next,
items: result.data.list,
};
}}
>
{(item, selection, expand, loadMore) => (
<TreeView.Item>
...
{expand.has(item.id) && (
<Button
borderless
displayType="secondary"
onClick={() => …
```
> feat(@clayui/core): add paginated data support to TreeView

- packages/clay-core/stories/TreeView.stories.tsx
It just fixes the error of a TreeView example that was failing, this ends up not being caught by CI because the Storybook loaded the examples on demand and not at compile time.
> chore(@clayui/core): fix error in TreeView example in Storybook

- packages/clay-core/src/tree-view/TreeViewItem.tsx
We added this recently which allows rendering other elements when it has declared as sibling of `TreeView.ItemStack` and `TreeView.Group` this allows rendering other child elements, but when there is the composition of `TreeView.Item` having only node elements, the elements were rendered twice.
This bug was caught by running the visual test with Chromatic https://www.chromatic.com/test?appId=627ec7506f193c004ac64938&id=6334b9128e3868d044515a22.
> fix(@clayui/core): fixes error of duplicating element rendering in TreeView

- packages/clay-autocomplete/src/index.tsx
- packages/clay-shared/src/FocusScope.tsx
These turned out to be bugs introduced by PR #5108.
Add `otherProps` to the Autocomplete container when using the old behavior and for the new one it doesn't add it goes to the new component which is the Input.
The other bug is that `FocusScope` when the child has declared a function in the `ref` of the container, it doesn't call the function so that the forwardRef happens correctly. There was an Autocomplete bug in the old behavior of not aligning the menu with the input.
> fix(@clayui/autocomplete): fix of switching the owner of otherProps on Autocomplete

- packages/clay-autocomplete/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-autocomplete/src/index.tsx
In DXP there are quite complicated compositions and full of wrappers on top of the components, this makes it difficult to identify if the old behavior is being used, so it is easier to identify if the new behavior is used.
> fix(@clayui/autocomplete): changes the way to identify the new behavior

- packages/clay-css/src/scss/functions/_global-functions.scss
- removes converting null and list to empty map to prevent running map-get on non existing maps
- removes error message and just returns null
Couldn't get it faster with a for loop and chaining `map-get`'s due to needing to use the `nth` function. This came out 500ms faster for 100,000 iterations of `map-deep-get` over the old one.
> fix(@clayui/css): Global Functions speed up `map-deep-get`

- packages/clay-core/src/tree-view/DragLayer.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/useTree.ts
This fixes https://github.com/liferay/clay/issues/5125 and also adds the possibility to specify a different key for item's name from outside. I've also added a check in the drag preview to prevent it to be shown in other drag and drop context, as discussed with @matuzalemsteles in Slack 🙂
> feat(@clayui/core): add possibility to specify item name key

- packages/clay-core/docs/treeview.mdx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
Closes #5011
This PR adds two options to bypass item drag and drop. This provides better options for teams to customize based on their data.
- Disable drag and drop of a specific item using the `draggable` property for `<TreeView.Item />` or `<TreeView.ItemStack />`
- Disable dropping an item on another item by returning `false` in the `onItemMove` function
I also added documentation on these two possibilities.
> feat(@clayui/core): adds support for `onItemMove` to decide if item should be droppable

- packages/clay-css/src/scss/atlas/variables/_links.scss
- packages/clay-css/src/scss/cadmin/variables/_links.scss
- packages/clay-css/src/scss/variables/_links.scss
> fix(@clayui/css): Links `.component-action` and `.link-outline` should have focus shadow

- packages/clay-css/src/scss/cadmin/variables/_management-bar.scss
- packages/clay-css/src/scss/cadmin/variables/_navigation-bar.scss
- packages/clay-css/src/scss/mixins/_navbar.scss
fixes #3236
I was hoping to completely remove the dependency to the mixin `clay-navbar-size`, but it's too breaking. I moved as much as I could to use `clay-navbar-variant`. This reduces the size of Clay CSS and Cadmin by 42kb  and 29kb respectively.
> fix(@clayui/css): Removes unused sm, lg, xl breakpoint styles from Navigation, Management and Application Bars

- packages/clay-shared/src/useFocusManagement.ts
Fixes #5148
Using `window.getComputedStyle` is a bit slow but unfortunately we don't have any other strategy to identify if the element is visible when `visibility` is used on a parent element or a very distant container. I added it just to check as a last resource when the element is marked as focusable, this ensures that we don't need to call `window.getComputedStyle` on every element that exists in the DOM every time.
I only added when getting elements in the document instead of the React tree, I believe that this scenario should not easily exist when the page or there are more elements in the tree in React since FocusScope controls a small part, so this will be more common when the element with FocusScope is rendered alone in the React tree on a page.
> fix(@clayui/shared): fixes error when identifying non-visible element as focusable

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-shared/src/FocusScope.tsx
- packages/clay-shared/src/useFocusManagement.ts
Fixes #5147, fixes #5140
This PR fixes the two issues related to focus control accessibility losing which the next and previous element should be focused on the Menu, it also fixes the esc is opening the menu when the focus is on the trigger, and when the menu closes the focus is lost.
> fix(@clayui/drop-down): fix focus control error losing order and wrong behavior of Esc

- jest.config.js
- packages/clay-tabs/docs/index.js
- packages/clay-tabs/src/Item.tsx
- packages/clay-tabs/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-tabs/src/__tests__/index.tsx
- packages/clay-tabs/src/index.tsx
- packages/clay-tabs/stories/Tabs.stories.tsx
Fixes #5151
In order to be able to control the automatic activation state of the tab when navigating, we have to have control of the active state, in the current implementation, the developer controls the state. In this PR I am applying the pattern from [RFC 0002 Controlled and uncontrolled components](https://github.com/liferay/clay/blob/master/docs/proposals/0002-controlled-and-uncontrolled.md) to allow the component to have state visibility, this makes it possible during tab navigation when selecting a tab changes the current tab.
```jsx
const [active, setActive] = useState(0);
<>
<ClayTabs
active={active}
onActiveChange={setActive}
>
<ClayTabs.Item
innerProps={{
'aria-controls': 'tabpanel1',
}}
>
Tab 1
</ClayTabs.Item>
<ClayTabs.Item
innerProps={{
'aria-controls': 'tabpanel2',
}}
> …
```
> feat(@clayui/tabs): add new API to configure browsing behavior between tabs

- jest.config.js
- packages/clay-shared/src/delegate.ts
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useInteractionFocus.ts
- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/src/__tests__/index.tsx
- packages/clay-tooltip/src/useAlign.ts
- packages/clay-tooltip/src/useClosestTitle.ts
- packages/clay-tooltip/src/useTooltipState.ts
Fixes #5153
I had to make a lot of changes to be able to detect when the user is interacting with the elements using only the keyboard, mouse or screen reader, this helps us to identify to show the tooltip only when the user focuses on the element using the keyboard or screen reader, we have to differentiate this because for example clicking on the element also triggers a focus event. I implemented a hook in shared that helps us to identify which type of interaction, this will help us in other components and it works like a singleton because it needs to add several listeners on the page.
I also did a refactoring of the code to try to simplify the implementation to be able to identify when it is hovering or focusing on the element that has a title, that's because when it has focus it …
> refactor(@clayui/tooltip): simplifies singleton implementation to add support for showing tooltip in focus using keyboard

- packages/clay-shared/src/FocusScope.tsx
- packages/clay-shared/src/useFocusManagement.ts
Related #5158
The previous PR wasn't fixing the root issue, for some reason this is only reproducible in some scenarios in DXP but doesn't fail in our tests.
The scope reference was being set to `null`, this is the default behavior of React when rendering the first time and then updating the reference. We had previously done so not to update the reference with the value `null` during the FocusScope lifecycle.
> fix(@clayui/shared): fix error when moving focus when reference is null

- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/src/useAlign.ts
Fixes #5159
When focusing on elements in sequence that have the tooltip, the alignment wasn't being recalculated because the open state sometimes didn't change from false to true and onwards as long as it has blur and focus is called correctly.
This is because when you have the same state update in sequence, React interrupts the previous update for the latest one... I'm using the tooltip title to trigger the alignment.
> fix(@clayui/tooltip): fixes error when not aligning the tooltip with focus in sequence of elements

- packages/clay-autocomplete/package.json
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-autocomplete/src/DropDown.tsx
- packages/clay-autocomplete/src/Item.tsx
- packages/clay-core/package.json
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/index.ts
- packages/clay-drop-down/docs/drop-down.mdx
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/package.json
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownContext.ts
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Group.tsx
- packages/clay-drop-down/src/ItemList.tsx
- packages/clay-drop-down/src/Search.tsx
- packages/clay-drop-down/src/__tests__/index.tsx
- packages/clay-drop-down/stories/DropDown.stories.tsx
Closes #5101
In order to use the internal component of Collection in DropDown, I had to deal with the circular dependency problem, for that I had to remove the DropDown re-export in the `@clayui/core` package. I believe that no one is still using DropDown through the core, if so I'll update in DXP.
The Collection pattern is now available in the DropDown component, providing features such as static and dynamic content. This lets you simplify some simpler cases, for example how to just render a simple list of options.
```jsx
<DropDown
items={['one', 'two', 'three', 'four']}
trigger={<Button>Click Me</Button>}
>
{(item) => <DropDown.Item key={item}>{item}</DropDown.Item>}
</DropDown>
```
When the component renders for example an input to filter the list, it now works in an OOTB way without …
> feat(@clayui/drop-down): add collection pattern

- jest.config.js
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-shared/src/useFocusManagement.ts
Well this PR fixes two types of behavior, one when the Menu has no focusable element the focus manager moved the focus out of scope, now we have an option that we can tell the focus manager to move the focus only to some element within the scope.
Another behavior is that `fiber.alternate` sometimes has the old reference of the element and may not find the focusable elements of the menu, as a second attempt when it doesn't find these elements, we try to navigate through `fiber.child` in search of focusable elements.
> fix(@clayui/shared): add prop to move focus only if in scope

- packages/clay-tabs/src/Content.tsx
- packages/clay-tabs/src/__tests__/index.tsx
- packages/clay-tabs/src/index.tsx
Fixes #5169
This prevents the child from being cloned when it is not a valid React element. Adding conditionals in the content rendering breaks the control via index, this is not recommended. It is intentional that this happens here because we could do a filter before doing the clone but that would be a quadratic iteration that I want to avoid and we will support activating tabs in other ways with the help of the collection pattern #5172.
> fix(@clayui/tabs): fix error when trying to clone an invalid element

- packages/clay-tabs/src/TabPane.tsx
Fixes #5163
This allows you to configure the Panel `tabIndex` when you don't want the Panel to receive the focus but the first focusable item.
> fix(@clayui/tabs): add configurable tabIndex property to TabPane component

- packages/clay-drop-down/src/DropDown.tsx
Fixes #5182
This PR just fixes the simplified collection case for DropDown #5182 where the markup wasn't rendering correctly because it doesn't render the `ItemList`, I'm not using it here because it would be a nested Collection rendering which might have problems, as this is a case very simple it is better to just add the markup instead of the component and allow to change the `role`.
> fix(@clayui/drop-down): fix error when not properly rendering markup for simplified collection

- packages/clay-tabs/src/Content.tsx
- packages/clay-tabs/src/List.tsx
- packages/clay-tabs/src/__tests__/index.tsx
- packages/clay-tabs/src/index.tsx
- packages/clay-tabs/stories/Tabs.stories.tsx
Closes #5171
This PR implements a more simplified composition and better DX than before, which makes it easier to control internal states and improve the flow of data through components. It will also be possible to more easily implement the Collection pattern and other features such as responsive tabs.
```jsx
<Tabs>
<Tabs.List>
<Tabs.Item>Tab 1</Tabs.Item>
<Tabs.Item>Tab 2</Tabs.Item>
<Tabs.Item>Tab 3</Tabs.Item>
</Tabs.List>
<Tabs.Panels>
<Tabs.TabPanel>Tab Content 1</Tabs.TabPanel>
<Tabs.TabPanel>Tab Content 2</Tabs.TabPanel>
<Tabs.TabPanel>Tab Content 3</Tabs.TabPanel>
</Tabs.Panels>
</Tabs>
```
The component still maintains backward compatibility which should stop supporting the next major version. Also now the automatic activation mode works with the component in uncontrolled mode. …
> feat(@clayui/tabs): adds new compositing pattern

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
Closes #5141
This is a draft PR, I should add another `onItemHover` API tomorrow and add some usage examples. There is one consideration is that `onItemHover` probably doesn't block any or disable the item from being droppable, so you will have to have the support of a state outside the TreeView to do the conditional using the `draggable` API on the Item. I will study if we can do something internally to improve the DX of use.
> feat(@clayui/core): add index data when moving item in TreeView

- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
fixes #5155 
This adds the `#` symbol to hex values in the title. It also adds `splotchProps` so we can pass attributes to the Input Group splotch. This would allow passing custom titles to the Input Group Splotch.
```
<ClayColorPicker
splotchProps={{
title: `Background Color: #${color}`,
}}
value={color}
/>
```
> feat(@clayui/color-picker): Adds splotchProps to pass custom attributes to the input group splotch

- clayui.com/content/docs/components/markup-menubar.md
- jest.config.js
- packages/clay-nav/docs/api-nav.mdx
- packages/clay-nav/docs/api-vertical-nav.mdx
- packages/clay-nav/docs/index.js
- packages/clay-nav/docs/nav.mdx
- packages/clay-nav/docs/vertical-nav.mdx
- packages/clay-nav/src/NavLink.tsx
- packages/clay-nav/src/Vertical.tsx
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-nav/src/__tests__/index.tsx
- packages/clay-nav/stories/Nav.stories.tsx
- packages/clay-shared/src/useNavigation.tsx
Fixes #5170
This PR is a draft to add accessibility to the VerticalNav component, still needs to make adjustments to the interaction with the keyboard is working more or less but I still need to improve the navigation flow of the arrows from top to bottom that is not discarding elements not visible on the screen.
There are also some other interactions using the keyboard, for example for menu with submenus, maybe we can use the same strategy as we do in TreeView:
- pressing the right arrow key on an element with submenu and it has focus, expands the submenu, if pressed again move focus to the first child element
- press the left arrow key on an element with submenu and it has focus, close the menu
- press left arrow key on first submenu item move focus to element parent
> feat(@clayui/nav): add accessibility to the Vertical Nav component

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
Fixes #5186
For some reason we added this intentionally but I don't remember, but it seems wrong and also the documentation says it should be keyboard navigable, so removing the `tabIndex` to make the action items navigable.
> fix(@clayui/core): fixes error of actions not being navigable via keyboard in TreeView

- packages/clay-modal/package.json
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
Fixes #5184
Using the same strategy that was used for Autocomplete and Dropdown with menus in the body, using the `aria-hidden` package to add the attribute on all elements of the document with `aria-hidden="true"` minus the content, this prevents elements outside the menu or modal from being navigable when using a screen reader.
> fix(@clay/modal): fix error of content outside the modal is still navigable with JAWS

- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/src/useClosestTitle.ts
Fixes #5189
This PR follows the approach of persisting the title attribute when browsing via keyboard, since the browser does not show the title in the focus.
> fix(@clayui/tooltip): persist the title attribute when navigate via keyboard

- packages/clay-date-picker/package.json
- packages/clay-date-picker/src/DayNumber.tsx
- packages/clay-date-picker/src/DaysTable.tsx
- packages/clay-date-picker/src/WeekdayHeader.tsx
- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/src/types.ts
- packages/clay-date-picker/stories/DatePicker.stories.tsx
- packages/clay-drop-down/src/Menu.tsx
Fixes #5201
This PR improves DatePicker's semantic accessibility but doesn't add the keyboard navigation recommendations yet, I'll add this in another PR once we have a clearer picture of what it should look like.
This PR adds semantic accessibility for the date grid and `aria-hidden` for elements that should not be assertive by SR when the menu is open, the same as we do for the other menus.
> feat(@clayui/date-picker): improves semantic accessibility for the component

- jest.config.js
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-shared/src/useNavigation.tsx
Related https://github.com/liferay-frontend/liferay-portal/pull/2877#issuecomment-1324097316
DropDown has the `typeahead` functionality enabled that when typing it moves the focus to the first corresponding item within the Menu, DropDown also has the possibility of the Search component, in this case this PR avoids the `typeahead` when the focus it's in the input.
> fix(@clayui/shared): fixes error when stop typing in DropDown Search

- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/drilldown/Menu.tsx
- packages/clay-drop-down/src/drilldown/index.tsx
- packages/clay-drop-down/stories/DropDown.stories.tsx
Related #5041
This PR fixes some accessibility issues that exist in Drilldown, some like `aria-hidden="true"` for the active menu and not exposing an API to add aria-label to buttons with unlabeled actions for example.
I also noticed that there are some cases that this component is not covering according to the documentation https://docs.google.com/document/d/1PVQwknqVIOQhf2JL0kEv0k6WHOExKOskiX-CxxWYRqs/edit#, so maybe a review is needed on this component, I should create a separate issue to deal with it.
> fix(@clayui/drop-down): fixes Drilldown accessibility issues

- packages/clay-core/src/tree-view/__tests__/useTree.ts
- packages/clay-core/src/tree-view/useItem.tsx
- packages/clay-core/src/tree-view/useLayout.ts
- packages/clay-core/src/tree-view/useTree.ts
Fixes #5213
I ended up discovering more problems with the mechanism of moving items inside the TreeView behaving wrongly and moving to wrong positions, so I fixed that as well. I also improved the part of expanding the item when the drag hovers over the item, it was always expanded regardless of whether the user's intention was to move above or below the item, I added it only to expand when the intention to move is inside the item, this greatly improves the user experience.
> fix(@clayui/core): improves interactions of moving item in TreeView

- jest.config.js
- packages/clay-autocomplete/package.json
- packages/clay-date-picker/package.json
- packages/clay-drop-down/package.json
- packages/clay-modal/package.json
- packages/clay-shared/package.json
- packages/clay-shared/src/Overlay.tsx
- packages/clay-shared/src/Portal.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useFocusManagement.ts
- packages/clay-shared/src/useInteractOutside.tsx
- packages/clay-shared/src/useOverlayPositon.ts
- yarn.lock
This PR is a fork of #5208 where it was originally implemented, I'm sending it separately from this PR so we can have this merged into the master and we can work on other issues that depend on it as well while the PR is under review.
In summary, this PR is implementing a new foundation component to handle accessibility and keyboard focus and navigation interactions for components that need Overlay, for example: DatePicker, DropDown, Autocomplete, Modal, ColorPicker and other components.
Currently we have a duplication of implementation spread across these components, for example Modal has its own focus trap system, click outside the modal and suppression of elements outside the modal, this is implemented in other places too, which increases the duplication and possible inconsistent …
> feat(@clayui/shared): add component to handle Overlay for Clay components

- packages/clay-css/src/scss/atlas/variables/_clay-color.scss
- packages/clay-css/src/scss/atlas/variables/_date-picker.scss
- packages/clay-css/src/scss/atlas/variables/_modals.scss
- packages/clay-css/src/scss/atlas/variables/_panels.scss
- packages/clay-css/src/scss/atlas/variables/_tbar.scss
- packages/clay-css/src/scss/atlas/variables/_time.scss
- packages/clay-css/src/scss/cadmin/variables/_cards.scss
- packages/clay-css/src/scss/cadmin/variables/_clay-color.scss
- packages/clay-css/src/scss/cadmin/variables/_date-picker.scss
- packages/clay-css/src/scss/cadmin/variables/_modals.scss
- packages/clay-css/src/scss/cadmin/variables/_sheets.scss
- packages/clay-css/src/scss/cadmin/variables/_tbar.scss
- packages/clay-css/src/scss/cadmin/variables/_time.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/components/_progress-bars.scss
- packages/clay-css/src/scss/mixins/_input-groups.scss
- packages/clay-css/src/scss/mixins/_modals.scss
- packages/clay-css/src/scss/mixins/_panels.scss
- packages/clay-css/src/scss/mixins/_tbar.scss
- packages/clay-css/src/scss/variables/_clay-color.scss
- packages/clay-css/src/scss/variables/_date-picker.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-css/src/scss/variables/_modals.scss
- packages/clay-css/src/scss/variables/_panels.scss
- packages/clay-css/src/scss/variables/_progress-bars.scss
- packages/clay-css/src/scss/variables/_tbar.scss
fixes #5217
Everything should be backward compatible.
> fix(@clayui/css): Normalize Sass map keys to be closer to the selector name

- packages/clay-alert/src/index.tsx
Fixes #5222
I'm not going with a specific API to disable the `role` property, just set the `role` property to `null`, as elsewhere this is a simpler and more consistent pattern.
> feat(@clayui/alert): adds possibility to remove alert attribute

- packages/clay-breadcrumb/docs/index.js
- packages/clay-breadcrumb/docs/markup-breadcrumb.md
- packages/clay-breadcrumb/src/Ellipsis.tsx
- packages/clay-breadcrumb/stories/Breadcrumb.stories.tsx
- packages/clay-button/docs/index.js
- packages/clay-button/docs/markup-button.md
- packages/clay-card/docs/markup-card.md
- packages/clay-drop-down/docs/markup-dropdown.md
- packages/clay-label/docs/index.js
- packages/clay-link/docs/markup-link.md
- packages/clay-list/docs/index.js
- packages/clay-list/docs/markup-list.md
- packages/clay-list/stories/List.stories.tsx
- packages/clay-management-toolbar/docs/index.js
- packages/clay-management-toolbar/docs/markup-management-toolbar.md
- packages/clay-modal/docs/markup-modal.md
- packages/clay-pagination-bar/docs/index.js
- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination-bar/stories/PaginationBar.stories.tsx
- packages/clay-pagination/docs/index.js
- packages/clay-pagination/docs/markup-pagination.md
- packages/clay-pagination/src/Ellipsis.tsx
- packages/clay-pagination/src/PaginationWithBasicItems.tsx
- packages/clay-pagination/stories/Pagination.stories.tsx
- packages/clay-toolbar/docs/index.js
- packages/clay-toolbar/docs/markup-toolbar.md
- packages/clay-toolbar/stories/Toolbar.stories.tsx
Fixes #5237
This PR is further updating all the examples to add `aria-label` and `title` to elements that only have icons. I also ended up adding a new property to the Breadcrumb, Pagination and PaginationBar component to be able to configure `aria-label` and `title` for the ellipsis trigger.
> docs: Adds `aria-label` and `title` to documentation examples

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_dropdowns.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_forms.scss
#5226
@matuzalemsteles I added the variants `form-control-select-secondary` and `dropdown-menu-select`. The custom select element markup looks like:
```html
<div class="form-group">
<label for="formControlSelectSecondary1">A Button Styled Like a Select Element</label>
<button class="form-control form-control-select form-control-select-secondary" id="formControlSelectSecondary1" type="button">Custom Select</button>
</div>
```
For the dropdown menu, we just need to add the class `dropdown-menu-select`. It should work with all the `dropdown-menu` modifier classes. I'm going to mark this as draft since the specs don't seem to be done.
> feat(@clayui/css): Adds variants to be used in Custom Select

- jest.config.js
- packages/clay-core/docs/api-picker.mdx
- packages/clay-core/docs/picker.js
- packages/clay-core/docs/picker.mdx
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/index.ts
- packages/clay-core/src/collection/types.ts
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/collection/utils.ts
- packages/clay-core/src/index.ts
- packages/clay-core/src/picker/Option.tsx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/__tests__/BasicRendering.tsx
- packages/clay-core/src/picker/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/picker/context.ts
- packages/clay-core/src/picker/index.ts
- packages/clay-core/src/vertical-bar/Bar.tsx
- packages/clay-core/stories/Picker.stories.tsx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-nav/src/Vertical.tsx
- packages/clay-shared/src/Overlay.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useHover.ts
- packages/clay-shared/src/useIsMobileDevice.ts
- packages/clay-shared/src/useNavigation.tsx
- packages/clay-tabs/src/List.tsx
Closes #5226
I'm submitting it as a separate PR from #5246, so I can add more info on the component's implementation in React.js and also to better separate the discussions. There are some CSS issues that still need to be fixed, I added some comments about that in PR #5246.
Firstly I went ahead with the `<Picker />` name here for combobox-only selection, I can't find another alternative here, names with Custom Select synthetically are bad to read and sound like customization/alternative, in which case I I think we don't want to just leave this as an alternative but be the main component to replace the native Select component.
Well, this component is following the w3c recommendations https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html. It also implements Clay …
> feat(@clayui/core): Adds new Picker/Custom Select component

- jest.config.js
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/Ellipsis.tsx
- packages/clay-pagination/src/Item.tsx
- packages/clay-pagination/src/Pagination.tsx
- packages/clay-pagination/src/PaginationWithBasicItems.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/stories/Pagination.stories.tsx
fixes #5233
- This wraps the pagination in `<nav aria-label="Pagination" role="navigation">`. You can change the nav attributes with `navProps`.
- Adds a default `aria-label` for previous, items, and next buttons
- Adds a default `aria-label` and `title` "Show pages %START% through %END%"
- Only output a `ClayLink` no buttons for items. The ellipsis menu still contains buttons.
I think [Warning about dropdown/level-2](https://github.com/liferay/clay/issues/5233#issue-1475584259) should be done in another pr.
I still need to write documentation on this. I need feedback before I start.
> feat(@clayui/pagination): PaginationWithBasicItems should have aria-labels by default

- packages/clay-core/src/picker/Option.tsx
- packages/clay-core/src/typography/Text.tsx
- packages/clay-core/stories/Picker.stories.tsx
From https://github.com/liferay/clay/pull/5248#issuecomment-1357329149
I'm using `aria-labelledby` instead of `aria-label` I think it's better here to link the elements with the option and also adding `aria-describedby` to link the description and label texts. I've done some tests with VoiceOver and it seems that even then it continues to read the other texts together as if it were a single word, so I added `aria-hidden` to the description and label to make it work properly.
> chore(@clayui/core): improves accessibility of Picker custom options example

- packages/clay-form/docs/markup-text-input.md
- packages/clay-form/stories/Input.stories.tsx
- packages/clay-multi-select/stories/MultiSelect.stories.tsx
Fixes #5247
This PR just updates the documentation and examples, ideally we want to provide this OOTB but we still don't have validation control and we need to work on issue #4741 first to find out the possibilities for handling form related components, for now we will leave the documentation and the examples following accessibility recommendations.
> docs: adds in examples accessibility for error validation

- jest.config.js
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/variables/_utilities.scss
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-multi-select/package.json
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/MultiSelect.stories.tsx
Fixes #5194
This PR is just a draft of the accessibility improvements for the MultiSelect component and I will just add the w3c grid layout recommendations here, the combobox pattern will be done by issue #5203 which depends on the revision in Autocomplete.
There are still some things missing here to be ready, also a discussion is about the input if it should be part of the `grid` of pills, this in the w3c implementation, it is outside the grid but our markup needs it to be inside the grid to not visually breaking maybe i need help from @pat270 here to try to solve this. I'm also not sure if this can work very well together the combobox pattern and pills, in Lexicon the navigation behaviors allow them to be very integrated with each other, for example pressing backspace when it's empty …
> feat(@clayui/multi-select): adds accessibility improvements to MultiSelect

- packages/clay-button/src/Button.tsx
- packages/clay-button/src/ButtonWithIcon.tsx
- packages/clay-button/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-button/src/__tests__/index.tsx
- packages/clay-button/src/index.tsx
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
Fixes #5249
This improves the message for the button accessibility error which only ignored the message when `aria-label` was set but did not consider `aria-labelledby`. The message is that you have to define either one and the `title` attribute is optional.
It also improves the type of the `<ButtonWithIcon />` component that makes the type conditional, that is, if you don't declare any of the two properties the build will fail but if you declare any of the two the error will disappear.
> fix(@clayui/button): improves the error message for button accessibility and the ButtonWithIcon component type

- .storybook/main.js
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/stories/Picker.stories.tsx
- packages/clay-drop-down/src/Group.tsx
- packages/clay-shared/src/useNavigation.tsx
Fixes #5260
Now this works better with nested collection, it assembles nested collections even if the Menu is not rendered, there are still some improvements we can do to optimize, for example cache the nested collection result and reuse when React renders the component, for now this just builds the structure of the layout. I'll work on that later.
Also fix the error of the `key` being defined with numbers, let's find for the item by the global `id`, so the `key` must be unique in the entire document so we also respect the rule for the `id` attribute.
> fix(@clayui/core): computes nested collections to mount the layout

- jest.config.js
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/index.tsx
From https://github.com/liferay/clay/pull/5204#issuecomment-1358397921
I made a different strategy to keep the visual focus on the label and still keep the accessibility focus on the `gridcell`, we are controlling the CSS class of `focus` manually to do that.
@pat270 let me know if the CSS part could cause any problems.
> feat(@clayui/multi-select): moves the visual focus from the `gridcell` to the label

- packages/clay-css/src/scss/variables/_pagination.scss
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/Item.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
fixes #5286
@marcoscv-work I added `tabindex="0"` to links that are active or don't have a `href` attribute. It should receive focus when tabbing now. Disabled links don't receive focus when tabbing. I think this is a better way than making `href` mandatory. We don't need to make up a placeholder url that may or may not make sense.
> fix(@clayui/pagination): Adds tabindex to links with no href

- packages/clay-core/src/picker/Picker.tsx
- packages/clay-shared/src/Overlay.tsx
Closes #5271
Ideally we want to avoid these properties in favor of setting the `theme` via the `<ClayProvider />` but at this point there seems to be some conflicting bundler dependencies on the DXP which is loading different versions of the package in core and in the shared package.
> feat(@clayui/core): add new property to add `className` to Picker menu

- packages/clay-core/src/vertical-bar/Item.tsx
- packages/clay-core/src/vertical-bar/Panel.tsx
- packages/clay-core/src/vertical-bar/VerticalBar.tsx
- packages/clay-core/src/vertical-bar/context.ts
- packages/clay-core/stories/VerticalBar.stories.tsx
- packages/clay-shared/src/useInternalState.ts
Fixes #5292
The issue with the animation not working correctly was that when the component was configured to be controlled, the state changed from controlled to uncontrolled which broke the implementation internally.
This PR fixes this so that this can be `React.Key` or `null` instead of `undefined` which is the type that `useInternalState` uses to determine controlled or uncontrolled behavior.
> fix(@clayui/core): fix Vertical Bar component error change behavior from controlled to uncontrolled

- jest.config.js
- packages/clay-multi-select/src/index.tsx
Fixes #5303
It allows the developer to prevent default behavior of MultiSelect in `onPaste` and `onKeyDown`, the same way we did in newer components like TreeView just calling `event.preventDefault()` will ignore the default behavior.
```jsx
<ClayMultiSelect
onPaste={(event) => event.preventDefault()}
inputName="myInput"
/>
```
> feat(@clayui/multi-select): allows to prevent default behavior of `onPaste` and `onKeyDown`

- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/Item.tsx
- packages/clay-pagination/src/PaginationWithBasicItems.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
Fixes #5297
The case of the issue that `span` has a `tabIndex` could be a DXP specific implementation that is using the low-level APIs instead of the `PaginationWithBasicItems` component, I will check this when I update the Clay dependencies in the DXP .
This PR removes the link of `Prev` and `Next` when they are disabled, I'm also removing the `aria-label` as the element will not have focus and would also generate more confusion and noise.
> fix(@clayui/pagination): remove link from Prev and Next when disabled

- packages/clay-modal/docs/index.js
- packages/clay-modal/src/Header.tsx
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/types.ts
- packages/clay-modal/src/useModal.tsx
- packages/clay-modal/stories/Modal.stories.tsx
Fixes #5295
This PR fixes some Modal accessibility errors, the problem was that the focus happened before the content rendered for some reason that made it not correctly announce the dialog, probably because it didn't find the id of `aria-labelledby`.
Also some small features and fixes:
- Allows you to modify the `role` of the modal
- Restores trigger focus when closing the modal
- Change title tag to h1
> fix(@clayui/modal): fix Modal accessibility bugs

- jest.config.js
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-pagination-bar/package.json
- packages/clay-pagination-bar/src/DropDown.tsx
- packages/clay-pagination-bar/src/PaginationBar.tsx
- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/index.tsx
- packages/clay-pagination-bar/stories/PaginationBar.stories.tsx
Fixes #5287, #5284
API of component `<ClayPaginationBarWithBasicItems />` has not changed, internally we have changed to use Picker instead of DropDown when changing delta, previous API had support for `href` in DropDown but it never seems to be used because it really doesn't make sense to change the delta with link in DropDown.
Also this PR is deprecating the `<ClayPaginationBar.DropDown />` component for those who use the low-level components, it is not possible to do a 1 to 1 compatibility under the hood to switch to Picker, the `ClayDropDownWithItems` API is more opinionated compared to `Picker`.
The package size will increase as we now need to add the `@clayui/core` dependency to use the Picker, we should soon start moving components into the `@clayui/core` package.
> feat(@clayui/pagination-bar): change the DropDown component to the Picker in the high-level component

- packages/clay-css/src/scss/atlas/variables/_links.scss
- packages/clay-css/src/scss/cadmin/components/_links.scss
- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_links.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/components/_links.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/src/scss/variables/_links.scss
- packages/clay-css/src/scss/variables/_utilities.scss
- packages/clay-link/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-link/src/index.tsx
- packages/clay-link/stories/Link.stories.tsx
fixes #5283 
Update: I made most of the changes in this update. I changed `underline` to `decoration` because the underline isn't always set by ClayLink. We can have underlined text coming from CSS and the utility `text-decoration-none` will undo that and vice versa. The attribute `decoration` also has a `null` option to undo the presets in `primary` for example. We can use `decoration={null}` to prevent the primary link from outputting the underline utility.
This one might be a little confusing. I decided to adopt the utility classes since there were so many variants, but didn't want to break the api by changing the `link-primary` and `link-secondary` classes to use text utilities. I also added the base `c-link` class that should be used in every link.
|Regular Links|Classes|
|---|---| …
> feat(@clayui/css): Links adds c-link to be used with utility classes

- jest.config.js
- packages/clay-nav/src/Vertical.tsx
- packages/clay-navigation-bar/src/Item.tsx
- packages/clay-navigation-bar/src/context.ts
- packages/clay-navigation-bar/src/index.tsx
Fixes #5307
This PR adds to the API the possibility of disabling `aria-current` from the `VerticalNav` and `NavigationBar` components when setting `aria-current` to `null`.
```jsx
<ClayNavigationBar>
<ClayNavigationBar.Item active aria-current={null}>
<ClayLink href="#">Item 1</ClayLink>
</ClayNavigationBar.Item>
</ClayNavigationBar>
<ClayVerticalNav
aria-current={null}
/>
```
I'm not sure if this is the behavior we want when disabling `aria-current={null}` we add `aria-selected` instead, but since they are links I'm not sure if this would be the right behavior. @marcoscv-work could you confirm?
> feat: add prop to remove `aria-current` from `VerticalNav` and `NavigationBar` component

- packages/clay-css/src/scss/cadmin/variables/_navigation-bar.scss
- packages/clay-css/src/scss/variables/_navigation-bar.scss
- packages/clay-navigation-bar/src/Item.tsx
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
fixes #5314
@matuzalemsteles I think this should be relatively safe. I checked Portal and seems like the `btn-unstyled` and `link-unstyled` for Navigation Bar aren't used.
> fix(@clayui/navigation-bar): Removes classes btn-unstyled and link-unstyled from nav-link

- packages/clay-multi-select/src/index.tsx
Fixes #5313
This PR adds a new API `allowsCustomLabel` which when set to `false` disables adding custom labels, the labels are only added if they exist in the autocomplete.
This disables creating custom labels when typing `,` and `Enter`, also when pasting text with `,`.
> feat(@clayui/multi-select): Adds new API to disallow adding custom values as label

- packages/clay-css/src/scss/variables/_empty-state.scss
fixes #5328 
This keeps the spacing between the text and image the same even if there is no title.
> fix(@clayui/css): Empty State add bigger margin-bottom on image

- jest.config.js
- packages/clay-core/src/live-announcer/LiveAnnouncer.tsx
- packages/clay-core/src/live-announcer/VisuallyHidden.tsx
- packages/clay-core/src/live-announcer/index.ts
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/platform.ts
- packages/clay-shared/src/useInteractionFocus.ts
Fixes #5281
This PR is a draft, but it already partially fixes the Picker accessibility bug on Apple devices. We use `aria-controls` instead of `aria-owns` on the Apple device to be able to do the manual announcement implemented via JS and also only announce when the menu is opened.
There is still a problem that even when we announce manually VoiceOver will still announce that it is inside the combobox instead of the listbox, I am testing how I can avoid it, maybe I can send a second message that says it is in a listbox. Note that this is only an issue when you open the menu but when navigating through the listbox VoiceOver will announce correctly.
> fix(@clayui/core): fix Picker accessibility error on Apple devices with VoiceOver

- packages/clay-shared/src/index.tsx
It looks like this broke the DXP build, an attempt to avoid DXP bugs.
> chore(@clayui/shared): uses named export instead of `*`

- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
fix(@clayui/css): Atlas Dropdown active state should be font-weight: normal
fixes #5341
> fix(@clayui/css): Atlas Dropdown items should be 32px tall

- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
Closes #5336
We recently added a new API to set the TreeView selection mode when calling the `selection` method in the render props to allow new interaction possibilities and now also providing more options to disable certain selection behaviors.
> feat(@clayui/core): adds new selection API to configure more options

- packages/clay-tabs/src/Item.tsx
- packages/clay-tabs/src/List.tsx
- packages/clay-tabs/src/__tests__/index.tsx
- packages/clay-tabs/src/index.tsx
> feat(@clayui/tabs): adds the pattern of uncontrolled to the `active` property of Tabs.Item in the new composition

- packages/clay-management-toolbar/docs/index.js
- packages/clay-management-toolbar/docs/markup-management-toolbar.md
- packages/clay-management-toolbar/stories/ManagementToolbar.stories.tsx
- packages/demos/stories/ListPage.tsx
Fixes #5330
Updates the documentation examples with the accessibility improvement for the checkbox, this component doesn't handle this because being a low-level component and purely composition, so it doesn't have the visibility to provide this OOTB.
The React.js implementation of this component is also deprecated and moved to the DXP, so we also need to update this in the DXP to be usable, we're just showing you how to use the Management Toolbar and best practices, in this case checkbox accessibility.
> docs(@clayui/management-toolbar): update checkbox accessibility in documentations

- packages/clay-autocomplete/src/Autocomplete.tsx
Fixes #5349
We escape value with special characters from regex when filtering the list of items, we don't remove the input value because it causes a bad user experience when typing.
> fix(@clayui/autocomplete): fix error when filtering autocomplete with regex special character

- jest.config.js
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-shared/src/Overlay.tsx
- packages/clay-shared/src/useInteractOutside.tsx
Fixes #5332
This PR fixes some Overlay things when interacting with the Modal, there is still the problem that having a component that uses the Overlay inside the Modal pressing esc will still close the Modal because the Modal has not been refactored to use the Overlay component yet #5221.
This PR also adds the possibility of having Overlay stacked which allows avoiding for example closing all overlays at once when pressing esc, clicking outside the overlay or moving the focus to another element. For example, DropDown with ColorPicker, Modal with any other component that uses Overlay, DropDown with cascading when using keyboard navigation.
> fix: fixes overlay errors when closing Modal and the page is inaccessible when closed by Overlay with isModal enabled

- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
> fix(@clayui/css): Cadmin text-# utilities should use px values

- packages/clay-css/src/scss/_license-text.scss
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
Follow up #5364
The DXP build with the dialect theme is failing since the `$secondary` variable could be a CSS variable.
> fix(@clayui/css): fix build error when `$secondary` variable is a CSS variable

- packages/clay-core/src/tree-view/context.ts
Fixes #5367
When we implemented asynchronous loading with the cursor it didn't expand the node because we only thought of the case that the node already had items in its first render, now we expand only when node it is not expanded to avoid collapsing the node when loading more data.
> fix(@clayui/core): fix bug that does not expand an asynchronous node with cursor

- packages/clay-link/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-link/src/__tests__/index.tsx
- packages/clay-link/src/index.tsx
Closes #5355
This PR adds an extra label when `target` is set to `_blank`, it also adds a `messages` API which allows changing the text to handle internationalization.
Hey @marcoscv-work I didn't add the visual icon, do you have an example of what this should look like? I think we have to add this via a conditional as well because the link is used in several components and I'm not sure if that would be desired in some occasions.
> feat(@clayui/link): add extra aria-label when target is `_blank`

- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
- packages/clay-core/docs/api-text.mdx
- packages/clay-core/docs/text.js
- packages/clay-core/docs/text.mdx
- packages/clay-core/package.json
- packages/clay-core/src/index.ts
- packages/clay-core/src/typography/TextHighlight.tsx
- packages/clay-core/src/typography/index.ts
- packages/clay-core/stories/Text.stories.tsx
Closes #5351
This PR adds the implementation of the `TextHighlight` component and documentation, I also added an example in the storybook of a custom item in Autocomplete using `TextHighlight`.
> feat(@clayui/core): add TextHighlight component

- jest.config.js
- packages/clay-core/package.json
- packages/clay-core/src/live-announcer/VisuallyHidden.tsx
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/DragAndDrop.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/tree-view/useItem.tsx
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useInteractionFocus.ts
Fixes #5146
This commit still needs some implementation refinements, we need to change the way we handle the element indicator to improve indicator announcer to SRs.
I also still need to move the announcer messages to be configured for internationalization.
> feat(@clayui/core): adds initial implementation of drag and drop via keyboard in treeview

- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/variables/_globals.scss
> fix(@clayui/css): Links change spacing between text and icon back to 8px

- packages/clay-drop-down/src/Search.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
Fixes #5377
Eventually this causes the problem of prop drilling but to avoid this we would have to break the component into small parts for composition for now this is not what we want so it is acceptable to add this API here until we understand better how we want this component.
> feat(@clayui/drop-down): add new prop to pass props to `DropDown.Search` button

- jest.config.js
- packages/clay-nav/src/Vertical.tsx
- packages/clay-navigation-bar/src/index.tsx
> refactor: changes the root component's `aria-current` prop to `itemAriaCurrent`

- jest.config.js
- packages/clay-core/src/aria/index.ts
- packages/clay-core/src/aria/useFocusWithin.tsx
- packages/clay-core/src/live-announcer/VisuallyHidden.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-shared/src/useNavigation.tsx
Fixes #5334
Initial implementation to improve TreeView focus system, we are using `useNavigation` hook instead of FocusScope to handle focus and hotkeys, not covering all shortcut cases yet.
I still need to implement the TreeView focus control to retrieve the focus on the last item of the component, I will probably implement a component that can handle this since we already have 2 existing use cases in Clay that are starting to follow this behavior.
> refactor(@clayui/core): uses `useNavigation` hook for keyboard navigation in TreeView

- packages/clay-empty-state/src/__tests__/index.tsx
- packages/clay-empty-state/src/index.tsx
Fixes #5325
This PR changes the logic to always render the title even when it's not defined or when it's defined as `null` or an empty string, we didn't change the types to avoid breaking the DXP compilation but in the future we will make `title` required and remove the `null`. We don't want to do that right now because it's a breaking change.
> feat(@clayui/empty-state): always render the title

- packages/clay-date-picker/src/Hooks.ts
Fixes #5324
This PR fixes the bug of recovering focus in case of date range when selecting a date in another month.
> fix(@clayui/date-picker): fix focus bug in date picker

- packages/clay-core/src/tree-view/DragAndDrop.tsx
Just a complement and a bug I found while investigating issue #5385 where JAWS was focusing on support text for TreeView DnD indicators.
> chore(@clayui/core): hide Dnd text for SR

- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/cadmin/variables/_menubar.scss
- packages/clay-css/src/scss/mixins/_breakpoints.scss
- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/variables/_menubar.scss
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/index.tsx
fixes #5397
@marcoscv-work There's nothing I can do for [Navigation Bar](https://clayui.com/docs/components/navigation-bar.html). It's already at 100% width. The container it's in is the limitation. We could add some JS that re-calculates the `left` and `right` positions when the  screen size changes, but I'm not sure if we want that.
> fix(@clayui/css): Clay and Cadmin Menubar make collapsed nav 100% wide

- packages/clay-date-picker/src/index.tsx
Fixes: #5404
The root cause of the issue was the memoized updateDate, where I had to include the dateFormat in the dependancy array, as changing this value has an effect on the result.
I also made another commit, where I included every dependancy for the useCallback memoization, I left it in a separate commit in case you don't want to merge that.
Please review my changes.
Thanks
> fix(@clayui/date-picker): updateDate is memoized without dateFormat dependency

- packages/clay-core/src/vertical-bar/Panel.tsx
- packages/clay-core/src/vertical-bar/Resizer.tsx
- packages/clay-core/src/vertical-bar/VerticalBar.tsx
- packages/clay-core/src/vertical-bar/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/vertical-bar/context.ts
- packages/clay-core/stories/VerticalBar.stories.tsx
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/cadmin.scss
- packages/clay-css/src/scss/cadmin/_variables.scss
- packages/clay-css/src/scss/cadmin/components/_resizer.scss
- packages/clay-css/src/scss/cadmin/variables/_resizer.scss
- packages/clay-css/src/scss/cadmin/variables/_slideout.scss
- packages/clay-css/src/scss/components/_resizer.scss
- packages/clay-css/src/scss/mixins/_slideout.scss
- packages/clay-css/src/scss/variables/_resizer.scss
- packages/clay-css/src/scss/variables/_slideout.scss
fixes #5348 
Putting this up for review, I added a Resizer component to VerticalBar. We can enable it with the `resize` attribute on `VerticalBar`. I also added a `panelWidth` prop so we can store the resized width in local storage and set it when rendering the component.
TODO:
- ~keyboard interactions~
- pass in custom function on resize end so we can store the new width in local storage (maybe?)
- aria attributes
- documentation
> feat(@clayui/core): Vertical Bar adds resizing to VerticalBar.Panel

- packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
- packages/clay-css/src/scss/cadmin/variables/_navigation-bar.scss
> fix(@clayui/css): Navigation Bar focus outline should be rounded

- jest.config.js
- packages/clay-core/src/tree-view/TreeViewItem.tsx
Fixes #5430
I'm going in the direction of always showing the drag and drop icon when interacting via mouse or keyboard but clicking the mouse on the drag and drop button won't do anything only when interacting via keyboard. This still maintains the idea that the drag and drop is done via the mouse.
> fix(@clayui/core): always shows the drag and drop icon

- packages/clay-core/src/vertical-bar/Item.tsx
- packages/clay-core/src/vertical-bar/Panel.tsx
- packages/clay-core/src/vertical-bar/VerticalBar.tsx
- packages/clay-core/src/vertical-bar/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/vertical-bar/context.ts
- packages/clay-core/stories/VerticalBar.stories.tsx
> fix(@clayui/core): Vertical Bar open panel shouldn't disappear on resize

- jest.config.js
- packages/clay-core/src/collection/index.ts
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-core/src/tree-view/DragAndDrop.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/useItem.tsx
- packages/clay-css/src/scss/cadmin/components/_treeview.scss
- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/components/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
Fixes #5383
This is a different strategy compared to the implementation in #5428, instead of adding the `useDrop` directly to each indicator it adds to each item and just uses the indicator to display visually.
> refactor(@clayui/core): changes the implementation of the over on the DnD indicators of the TreeView component

- packages/clay-core/src/picker/Picker.tsx
Fixes #5456
This just prevents the implementation from crashing when it doesn't find the item in the collection, the error actually is that the defined key value doesn't exist in the items, so the component tries to find the value that doesn't exist. 
The error of this bug is because the selected value defined in the component does not exist in the `items` options. So this is just a fix to avoid breaking the JS but it also needs to be fixed on the DXP side.
> fix(@clayui/core): prevents JS from breaking component implementation

- packages/clay-core/docs/api-focus-trap.mdx
- packages/clay-core/docs/focus-trap.js
- packages/clay-core/docs/focus-trap.mdx
- packages/clay-core/src/focus-trap/FocusTrap.tsx
- packages/clay-core/src/focus-trap/__tests__/BasicRendering.tsx
- packages/clay-core/src/focus-trap/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/focus-trap/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/focus-trap/index.ts
- packages/clay-core/src/index.ts
- packages/clay-core/stories/FocusTrap.stories.tsx
It fixes: [#5409](https://github.com/liferay/clay/issues/5409)
Hi [@matuzalemsteles](https://github.com/matuzalemsteles)! Here is the draft for the new FocusTrap component. I have proposed the following: the component has an active props, which is in charge of activating the focus trap. In this way, it's the responsibility of the user to activate the focus trap. It could be always activated or, for example, activate it with the click of a button.
I have also added stories for Storybook to verify its behavior (video attached). What do you think?
https://user-images.githubusercontent.com/9701095/225911367-b8e9843c-96b6-4a31-b706-e170c076330c.mov
---
**TO DO:**
- tests
- doc
> feat(@clayui/focus-trap): Add FocusTrap component

- packages/clay-css/src/scss/atlas/variables/_popovers.scss
> fix(@clayui/css): Popover arrow has 1px gap in Safari

- packages/clay-badge/docs/badge.mdx
- packages/clay-badge/docs/index.js
- packages/clay-badge/src/index.tsx
- packages/clay-button/docs/button.mdx
- packages/clay-button/docs/index.js
- packages/clay-button/src/Button.tsx
- packages/clay-css/src/scss/cadmin/components/_badges.scss
- packages/clay-css/src/scss/cadmin/variables/_badges.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/components/_badges.scss
- packages/clay-css/src/scss/variables/_badges.scss
- packages/clay-css/src/scss/variables/_buttons.scss
fixes #5446
One thing I forgot to ask is whether `btn-beta` and `btn-badge` will be used in admin only components. Should we remove this from Clay used on sites?
Also @matuzalemsteles you think it's a good idea to add these to the ClayButton and ClayBadge apis?
/cc @ethib137 @marcoscv-work @drakonux
> feat(@clayui/css): Cadmin and Clay adds btn-beta and badge-beta variants

- clayui.com/src/styles/_guide.scss
- clayui.com/src/templates/docs.js
Fixes #5464
This PR changes the use of the component from ClayTabs to ClayNavigationBar, I also made some changes in the header to adjust the look to improve the weight of the fonts and spacing to visually improve the reading.
| Before | After |
|--------|--------|
| ![Screenshot 2023-04-11 at 16 15 48](https://user-images.githubusercontent.com/13750819/231289998-62bf6fd1-9ea7-4c5b-b608-a4c7e85fc839.png) | ![Screenshot 2023-04-11 at 16 15 15](https://user-images.githubusercontent.com/13750819/231289899-2fbd5d3e-547a-41df-871e-962b71b2a9e9.png) |
> fix(clayui.com): Change tab navigation to navigation bar

- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/components/_aspect-ratio.scss
- packages/clay-css/src/scss/components/_badges.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_dropdowns.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_labels.scss
- packages/clay-css/src/scss/components/_list-group.scss
- packages/clay-css/src/scss/components/_loaders.scss
- packages/clay-css/src/scss/components/_modals.scss
- packages/clay-css/src/scss/components/_navs.scss
- packages/clay-css/src/scss/components/_popovers.scss
- packages/clay-css/src/scss/components/_progress-bars.scss
- packages/clay-css/src/scss/components/_sidebar.scss
- packages/clay-css/src/scss/components/_stickers.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_alerts.scss
- packages/clay-css/src/scss/mixins/_links.scss
fixes #5471
We can prevent variant styles from being output with this pattern:
```scss
$alert-palette: (
primary: c-unset,
);
$btn-sizes: (
btn-xs: c-unset,
);
$btn-monospaced-sizes: (
btn-xs: c-unset,
);
```
previously it would throw an error.
> fix(@clayui/css): Exclude variant styles from being output when using c-unset

- packages/clay-core/docs/focus-trap.mdx
- packages/clay-core/src/focus-trap/FocusTrap.tsx
- packages/clay-core/src/focus-trap/__tests__/__snapshots__/BasicRendering.tsx.snap
Fixes https://github.com/liferay/clay/issues/5480
Hi @matuzalemsteles, as we discussed yesterday, I added the `display: contents` style to the `div`, this makes the children of this element appear as if they were direct children of the element's parent, ignoring the element itself.
I have also added several changes:
- Take into account when the `focusableElements` array is empty
- A more understandable description of the component
> fix(@clayui/focus-trap): Add display contents to ignore the element itself

- packages/clay-css/src/scss/cadmin/components/_drilldown.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_input-groups.scss
- packages/clay-css/src/scss/cadmin/components/_multi-step-nav.scss
- packages/clay-css/src/scss/cadmin/components/_side-navigation.scss
- packages/clay-css/src/scss/components/_drilldown.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/components/_multi-step-nav.scss
- packages/clay-css/src/scss/components/_progress-bars.scss
- packages/clay-css/src/scss/components/_side-navigation.scss
- packages/clay-css/src/scss/components/_spinners.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/mixins/_transition.scss
fixes #5476
This should remove all the transitions and animations I missed from the last update when using `c-prefers-reduced-motion`.  I also had to update the selectors for Cadmin, it was outputting something inconsistent.
> fix(@clayui/css): c-prefers-reduced-motion should completely remove transitions and animations

- jest.config.js
- packages/clay-autocomplete/package.json
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-autocomplete/src/Context.ts
- packages/clay-autocomplete/src/DropDown.tsx
- packages/clay-autocomplete/src/Input.tsx
- packages/clay-autocomplete/src/Item.tsx
- packages/clay-autocomplete/src/LoadingIndicator.tsx
- packages/clay-autocomplete/src/__tests__/IncrementalInteractions.tsx
- packages/clay-autocomplete/src/__tests__/index.tsx
- packages/clay-autocomplete/src/index.tsx
- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
- packages/clay-core/package.json
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/index.ts
- packages/clay-core/src/collection/types.ts
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/collection/useVirtual.ts
- packages/clay-core/src/picker/Option.tsx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/context.ts
- packages/clay-drop-down/src/Item.tsx
- packages/clay-shared/src/useNavigation.tsx
- yarn.lock
Closes #5203
This PR is still a draft of the Autocomplete refactoring, there is a lot of work here to make the accessibility improvements because we need to make changes in the navigation and collection mechanisms, firstly because the navigation in Autocomplete is done with the virtual focus and not with the focus of the browser and second that Autocomplete has virtualization and infinite scroll capabilities this combination means that we need to rebuild the collection virtualization system and the navigation system so that both can work together.
I made some changes to the collection implementation but still incomplete, the first work I did was to finally move the virtualization implementation to the `useCollection` hook and create the `useVirtual` hook that handles the virtualization …
> feat(@clayui/autocomplete): refactors autocomplete implementation with accessibility improvements

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/modal.tsx.snap
Fixes #5493
We are moving ARIA attributes to `modal-content` to avoid Modal visual focus error.
> fix(@clayui/modal): fix focus visual error in Modal

- packages/clay-shared/src/useOverlayPositon.ts
Fixes #5475
The implementation of the `useOverlayPosition` hook was checking the menu instead of the target to see if it changed its positioning, this only worked when the scroll was with the viewport instead of the parent element that has a scroll the right thing is to check the target that is in relation to the scroll of the parent element.
> fix(@clayui/shared): fix error when not recalculating positioning for elements with parent with scroll

- packages/clay-css/src/scss/cadmin/components/_modals.scss
- packages/clay-css/src/scss/cadmin/variables/_modals.scss
- packages/clay-css/src/scss/components/_modals.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/mixins/_modals.scss
- packages/clay-css/src/scss/variables/_modals.scss
fixes #5488
fix(@clayui/css): Mixins clay-modal-variant should use clay-map-to-css where applicable
fix(@clayui/css): Mixins clay-map-to-css should accept parent selector &
This is the first mixin to use `clay-map-to-css`. It gives us more flexibility when customizing variants. We no longer need to declare all the subcomponents in the mixin. It will output classes based on the Sass map.
```scss
$modal-info: (
modal-footer: (
modal-item-last: (
margin: 0,
),
),
);
```
will output:
```css
.modal-info .modal-footer .modal-item-last {
margin: 0;
}
```
> fix(@clayui/css): Modals converts some components to clay Sass map pattern

- packages/clay-core/src/tree-view/DragAndDrop.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
Fixes #5520
If DnD is disabled for a specific item the icon is not rendered for moving the item and also fixes the bug of moving the item to another item that has `draggable` disabled.
> fix(@clayui/core): fix error when not disabling item drag and drop via keyboard

- packages/clay-css/src/scss/components/_navs.scss
- packages/clay-css/src/scss/mixins/_nav-nested.scss
- packages/clay-css/src/scss/variables/_navs.scss
> fix(@clayui/css): Mixins clay-nav-nested should apply to .btn as well

- packages/clay-css/src/scss/cadmin/components/_alerts.scss
- packages/clay-css/src/scss/cadmin/components/_aspect-ratio.scss
- packages/clay-css/src/scss/cadmin/components/_badges.scss
- packages/clay-css/src/scss/cadmin/components/_buttons.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_labels.scss
- packages/clay-css/src/scss/cadmin/components/_list-group.scss
- packages/clay-css/src/scss/cadmin/components/_loaders.scss
- packages/clay-css/src/scss/cadmin/components/_modals.scss
- packages/clay-css/src/scss/cadmin/components/_navs.scss
- packages/clay-css/src/scss/cadmin/components/_popovers.scss
- packages/clay-css/src/scss/cadmin/components/_progress-bars.scss
- packages/clay-css/src/scss/cadmin/components/_sidebar.scss
- packages/clay-css/src/scss/cadmin/components/_stickers.scss
- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/components/_aspect-ratio.scss
- packages/clay-css/src/scss/components/_badges.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_labels.scss
- packages/clay-css/src/scss/components/_modals.scss
- packages/clay-css/src/scss/components/_stickers.scss
fixes #5503
I wrote the issue only for buttons, but there are several places where we do this. This pr will only generate Sass placeholders for certain key names.
```
primary,
secondary,
success,
info,
warning,
danger,
dark,
light
btn-,
label-,
sticker-,
etc
```
Key names such as, `'.btn.btn-dialect'` will only generate the selector and won't encounter the Sass can't extend complex selectors error. There are a couple minor fixes I missed in previous prs.
> fix(@clayui/css): Cadmin only generate Sass placeholders for specific key names

- jest.config.js
- packages/clay-core/src/index.ts
- packages/clay-core/src/nav/Item.tsx
- packages/clay-core/src/nav/Link.tsx
- packages/clay-core/src/nav/Nav.tsx
- packages/clay-core/src/nav/__tests__/BasicRendering.tsx
- packages/clay-core/src/nav/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/nav/index.tsx
- packages/clay-core/src/vertical-nav/Item.tsx
- packages/clay-core/src/vertical-nav/VerticalNav.tsx
- packages/clay-core/src/vertical-nav/__tests__/BasicRendering.tsx
- packages/clay-core/src/vertical-nav/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/vertical-nav/context.ts
- packages/clay-core/src/vertical-nav/index.ts
- packages/clay-core/stories/VerticalNav.stories.tsx
- packages/clay-nav/docs/api-vertical-nav.mdx
- packages/clay-nav/docs/index.js
- packages/clay-nav/docs/vertical-nav.mdx
- packages/clay-nav/package.json
- packages/clay-nav/src/Vertical.tsx
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-nav/src/__tests__/index.tsx
- packages/clay-nav/src/index.tsx
Close #5515
This PR makes a lot of changes, first we are rewriting the `VerticalNav` component to use the Collection API and exposing a new public `<VerticalNav.Item />` component.
We are also adding a new `expandedKeys` API with the pattern of controlled and uncontrolled, this makes it easier to manage this state for items in the tree like implementing expand all or collapse.
We are also moving the implementation of all this to the `@clayui/core` package and the `@clayui/nav` package just keeps backwards compatibility with the old version of the component and possibility to use the new version when declaring the new composition.
With the Collection implementation I needed to rewrite the component and this brings a new composition with the benefits of the Collection pattern.
```jsx …
```
> feat(@clayui/nav): add new composition to Vertical Nav with collection API and adds new `expandedKeys` API

- packages/clay-css/src/scss/_license-text.scss
- packages/clay-css/src/scss/components/_badges.scss
This bug was discovered with build failure when updating Clay in DXP https://github.com/liferay-peds/liferay-portal/pull/53.
It's strange that this is not reproducible in Clay's build, maybe our build is not throwing the console errors or failing the build correctly, we need to investigate if this is an issue in our build or the DXP later.
> fix(@clayui/css): fix syntax error

- packages/clay-shared/src/useOverlayPositon.ts
Fixes #5533
We made a recent change to recalculate the positioning of the Menu based on the `trigger` before it was based on the Menu this ends up breaking the behavior of opening the Menu when the trigger does not change its positioning when it is not related to the scroll of the container or the page but also we need this to recalculate the placement of the trigger compared to the scroll of some parent element so that the menu repositions correctly, so I'm also adding a second "listener" to recalculate the placement of the menu based on the position of the Menu as well.
This happens because the Picker will only render the menu when it is open, different from DropDown which had the behavior of always rendering the menu regardless of whether it is open or not, to calculate the positioning …
> fix(@clayui/shared): fix Picker menu positioning error

- packages/clay-core/src/collection/types.ts
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/vertical-bar/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/vertical-nav/Item.tsx
- packages/clay-core/src/vertical-nav/VerticalNav.tsx
- packages/clay-core/src/vertical-nav/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/vertical-nav/context.ts
- packages/clay-core/stories/VerticalNav.stories.tsx
- packages/clay-nav/docs/index.js
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
Fixes #5516
This PR makes more changes besides fixing the related bug in the issue, as part of being data agnostic I'm deprecating Item's `active` API instead it's just necessary to set the state of `active` in the component root, this makes it simpler than traversing the tree and setting the property to `active` it also lessens the data payload.
I had to make some internal changes to the Collection API because of how Collection nesting works in this component which is different from components like Picker or DropDown. I added comments in the code about some specs.
I still have to do some more backwards compatibility testing and fix the tests.
> fix(@clayui/core): fixes bug with not having a focusable item when there is no active item

- jest.config.js
- packages/clay-drop-down/src/DropDownWithItems.tsx
Fixes #5527
This PR avoids rendering the group if it has no `items` and throws an error in the console for the developer to correct, this improves the fault tolerance of the component and avoids throwing a JS error.
> fix(@clayui/drop-down): fix error when breaking component when group has no items

- jest.config.js
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-card/src/CardWithUser.tsx
Closes #5529
Instead of creating a new API to change the `aria-label` of the title we are using the existing `aria-label` property instead of adding it to the root of the component which will be a div which will have no effect it makes more sense to move this to the titles of the cards.
> feat(@clayui/card): moves root `aria-label` to card titles

- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-multi-select/src/__tests__/IncrementalInteractions.tsx
- packages/clay-multi-select/src/index.tsx
Fixes #5544
This PR fixes two problems, the first one that the OOTB filter was not working, it is disabled when the items come from an asynchronous communication that doesn't need a filter on the client but is done on the server. The second fix is that Autocomplete was rendering two collections instead of one, this caused unnecessary computational cost and also caused some bugs in the component.
I'll merge right away to make a release patch.
> fix(@clayui/multi-select): fix error when not doing OOTB filter

- README.md
I don't think we ever got to update the CI status badge, because it's been a while since we moved our CI to GitHub Actions and it was still showing Travis CI information, strange it was still working but now we are showing the CI status from Github Actions.
> chore: update CI status badge

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/mixins/_input-groups.scss
- packages/clay-css/src/scss/variables/_forms.scss
Solution for https://github.com/liferay/clay/issues/5487
> @clayui/css: More complex input-groups should accommodate inset focus styles

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
I thought I committed the changes in https://github.com/liferay/clay/pull/5510 but I didn't. These are the changes I was supposed to commit.
fixes #5487
> fix(@clayui/css): Transitions should work for .input-group-item.focus

- jest.config.js
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-multi-select/src/index.tsx
Fixes #5565, #5566
The idea is to try to keep the same behavior as before the Menu when the `menuRenderer` property is declared otherwise the new behavior is adopted. I've also added a warning when using the API to encourage teams to move to the new composition-based API that simplifies its use.
As I commented in the issue of this problem, unfortunately we were unable to maintain the same accessibility features for the `menuRenderer` because we were unable to have visibility of the list items through the React implementation and because it allows the developer to render anything in the list, we were unable to infer the which is a item on menu, so we can't do navigation with virtual focus for example or add shortcut keys.
In the DXP cases I'm updating the vast majority that use this API to …
> fix(@clayui/multi-select): maintains backwards compatibility with the `menuRenderer` API but without the new features

- jest.config.js
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/MultiSelect.stories.tsx
Related #5562
Basically this implements some improvements and fixes as I mentioned in issue #5562, adds the behavior of being able to ignore the default behavior of the component when clicking on the `Item` and explicitly adds the types to control the `active` state of the menu.
A small change was to deprecate the `liveRegion` and `hotkeysDescription` APIs to use the `messages` API which has the same goal to add the same API which has the functionality to handle translate. In the future, an idea is to group all this on the `messages` API in all components with the same behavior and we will consume this by ClayProvider so that all components can share and easier to integrate with the DXP internationalization system so that the developers don't have to worry about adding this.
> feat(@clayui/multi-select): adds the possibility to ignore the item's default behavior

- packages/clay-core/src/collection/useCollection.tsx
> fix(@clayui/core): fix the order of importance for using the item id of a collection

- packages/clay-autocomplete/src/Autocomplete.tsx
Fixes #5580
Basically the explanation of this problem is in the issue to understand the context of this correction but here instead of resetting the visual focus only when our component `<Overlay />` notifies that the menu was closed now we use the state of `active` to do this that when its state changes to `false` it is safer because the overlay events can be interrupted due to the ordering of the DOM events.
> fix(@clayui/autocomplete): fixes error when not resetting visual focus when menu is closed by custom logic

- jest.config.js
- packages/clay-autocomplete/src/Autocomplete.tsx
Fixes #5578
Basically, the solution here is to prevent the menu from being kept open after the user selects an option, even if the menu may have other related options.
> fix(@clayui/autocomplete): fix error keeping menu open after selecting option with `menuTrigger="focus"`

- jest.config.js
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-multi-select/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-multi-select/src/index.tsx
Fixes #5562
Well this PR fixes the problem of having to click twice to select an option, in fact what was happening was that when clicking on an option the `onBlur` method of the input was called and internally we listened to this event to update the state of focus of the input to update the focus visual state of the entire container, this causes a rerender in the component that re-renders the menu and with that causes a loss of reference to the nodes of each element in the list, which cancels the `onClick` call because the previous node no longer exists and has been removed from the DOM by a new node. So now we're stabilizing the item's component container references to avoid losing the node reference in the DOM every time a new rerender happens.
Also I fixes some small bugs I found, the …
> fix(@clayui/multi-select): fixes error when having to click twice to select the option

- jest.config.js
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-css/src/scss/cadmin/components/_date-picker.scss
- packages/clay-css/src/scss/components/_date-picker.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-date-picker/package.json
- packages/clay-date-picker/src/DateNavigation.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
Closes #5537
I still need to make some CSS adjustments to better deal with the arrows that should be floating @pat270 maybe you can help me with that here. Still need to understand what happens when clicking on the arrow options there is no description of the behavior of this in the documents cc @emiliano-cicero.
Instead of creating a DatePicker specific component I added an internal property that adds these new behaviors to the Picker component when enabled to avoid duplicating code or creating rules to try and share as resources are minimal, this seems like a better strategy to maintain the code long-term.
> feat(@clayui/date-picker): add Picker component to select year

- packages/clay-multi-select/src/index.tsx
Fixes #5588
If the data is not asynchronous the menu will always appear but the specific case of commerce is that the data is asynchronous so we don't validate again after the `sourceItems` has changed if the menu should only be shown when the `value` changes.
> fix(@clayui/multi-select): fix error of not showing menu if it has suggestions when menuRenderer is used

- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-core/src/index.ts
- packages/clay-multi-select/src/index.tsx
Fixes #5590
This PR implements the announcement to the SR of the amount of options available in an Autocomplete, this reflects to the MultiSelect as well, this only happens when there is no item with focus with the exception of the Voice Over that does not announce. We also announce for any SR when the user is typing and the list changes.
> fix(@clayui/autocomplete): fix bug not announcing available options when autocomplete is open

- packages/clay-form/src/Toggle.tsx
- packages/clay-form/src/__tests__/__snapshots__/Toggle.tsx.snap
> fix(@clayui/form): adds the proper `role` to the switch component

- packages/clay-autocomplete/src/Item.tsx
Fixes #5597
I'm changing the symbol we use to identify in the fuzzy method to avoid suppressing the `+` if it exists as a value.
> fix(@clayui/autocomplete): fixes suppressing the `+` from the value when filtering the list

- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-core/stories/VerticalNav.stories.tsx
- packages/clay-nav/docs/index.js
Fixes #5595
To understand the context see [my comment](https://github.com/liferay/clay/issues/5595#issuecomment-1603341079) in the issue. Basically I'm changing all the examples we have that are related to Collection that has an `id` of type `number` to `string` to avoid problems.
One solution we could try is to internally convert the values of `active` and any property that is related to `key` with type `number` to `string` so that everything internally communicates with type `string` the problem is that if the developer controls the states he can have his state change from type `number` to `string` mainly if he saves some of this information on the server. I believe these cases are more rare normally the `id` are of type `string` instead of `number` when something is related to a list …
> chore: converts all example collections that have id with type `number` to `string`

- jest.config.js
- packages/clay-core/src/tree-view/DragAndDrop.tsx
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
Fixes #5591
We are applying the changes to improve the API of `onItemHover` and `onItemMove` and also maintain feature parity to work when drag and drop interaction is via keyboard.
I'll be adding test cases for these behaviors in another pull request so we can include this in today's release.
> feat(@clayui/core): improves TreeView's `onItemHover` and `onItemMove` API

- package.json
- packages/clay-tooltip/src/useClosestTitle.ts
Fixes #5607
Now even if you have the `title` defined for nested elements the tooltip will be shown for the element that has the focus and also prevents the title of the parent element from being shown by the browser.
> fix(@clayui/tooltip): fix error not showing tooltip on nested elements

- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-autocomplete/src/__tests__/IncrementalInteractions.tsx
- packages/clay-autocomplete/src/index.tsx
- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/MultiSelect.stories.tsx
Fixes #5577
Generic types for the component along with `React.forwardRef` didn't work as expected so I had to do some different strategies to get the types to work correctly so the `<Autocomplete />` wasn't inferring the correct properties of the component that was fixed now. `<MultiSelect />` and `<Autocomplete />` now have type inference for controlled and uncontrolled state APIs just like other components, for example:
```jsx
<MultiSelect
items={items}
onItemsChange={setItems} // <- It works
/>
```
I'm still marking this PR as a draft because it doesn't correct the inference in case the controlled state is an anonymous function, the value is not being inferred, I still don't understand why this is happening, so I'll keep investigating.
```jsx
<MultiSelect
items={items} …
```
> fix(@clayui/autocomplete): fixes type inference for properties and generic type

- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-multi-select/src/index.tsx
> fix(@clayui/autocomplete): makes new `messages` properties optional

- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-multi-select/src/index.tsx
Fixes [LPS-189949](https://liferay.atlassian.net/browse/LPS-189949)
Basically the asynchronous or paged loading was not working correctly in MultiSelect because we forgot to pass the properties back to Autocomplete because we were using it to identify if the component was operating asynchronously or just dynamically.
> fix(@clayui/multi-select): pass async properties to autocomplete

- packages/clay-core/src/aria/useFocusWithin.tsx
Fixes [LPS-190444](https://liferay.atlassian.net/browse/LPS-190444) and [LPS-190440](https://liferay.atlassian.net/browse/LPS-190440)
It happened that we were trying to focus on the first one in the list when none existed, this happens when the component was disassembled but the lifecycle is still happening.
> fix(@clayui/core): fix error when validating focus without any element

- packages/clay-core/stories/Accessibility.stories.tsx
Fixes [LPS-188714](https://liferay.atlassian.net/browse/LPS-188714)
I'm adding examples for the accessibility cases when activated via CSS, unfortunately we have no way to test Reduced Motion with visual regression because visual regression is image comparison, reduced motion is when the user is interacting with the component, it's also difficult to test this via unit test because they would be flaky tests when it involves animation that are simulated and we would not have accurately if an animation really happened or not.
Then adding examples for the options:
- Link Underline
- Letter Spacing 1
- Expanded Text
The tests for `Focus Visible Only` also can't be included yet because it hasn't been added to Clay yet in the works, it would also be hard to test this with visual regression …
> chore: adds examples for visual regression testing for accessibility options

- .github/workflows/close-issues.yml
Adding the workflow to make people aware of using Jira instead of the Github Issue, right now we are only working with Jira to handle metrics and prioritization.
> chore: adds new workflow for migrating issues to Jira

- clayui.com/content/docs/css/utilities/markup-accessibility.md
- clayui.com/static/js/docs-site.js
- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-breadcrumb/src/index.tsx
- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/mixins/_cards.scss
- packages/clay-css/src/scss/mixins/_close.scss
- packages/clay-css/src/scss/mixins/_custom-forms.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/mixins/_modals.scss
- packages/clay-css/src/scss/mixins/_sidebar.scss
- packages/clay-css/src/scss/mixins/_slideout.scss
- packages/clay-css/src/scss/mixins/_toggle-switch.scss
- packages/clay-css/src/scss/variables/_globals.scss
This adds `:focus-visible` support by default. All the browsers that we support have this feature, we can disable it by setting `$enable-focus-visible: false`. Most items should be covered except form `input` and `select`, these always show the focus outline.
This also adds the class `c-prefers-focus` to force focus on click via the accessibility menu. I wanted to include docs today, but couldn't get to it today.
Lastly, I didn't cover the style issues in #5624. I feel like it's too much change for this PR.
#3342 #4972 #5006
@ethib137 @matuzalemsteles @marcoscv-work @veroglez
> feat(@clayui/css): Adds :focus-visible support

- jest.config.js
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useIsFirstRender.ts
Fixes [LPS-191768](https://liferay.atlassian.net/browse/LPS-191768)
This fixes the error when the initial value when rendering the component for the first time the `onChange` is called resetting the value for not being a selected value in the list.
Now this PR fixes this bug by validating the initial value with the list of items and also avoids updating the value on the first render. I also added a new API `allowCustomValue` to avoid this default behavior.
> fix(@clayui/autocomplete): fix error when not validating value with items

- jest.config.js
- packages/clay-empty-state/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-empty-state/src/__tests__/index.tsx
- packages/clay-empty-state/src/index.tsx
- packages/clay-empty-state/stories/EmptyState.stories.tsx
fixes #5638
@matuzalemsteles I didn't update the tests yet. I'm having trouble writing it for:
```
Jest: "./packages/clay-empty-state/src/" coverage threshold for statements (100%) not met: 92.85%
Jest: "./packages/clay-empty-state/src/" coverage threshold for lines (100%) not met: 92.85%
Jest: "./packages/clay-empty-state/src/" coverage threshold for functions (100%) not met: 50%
```
I'm not sure what statements, lines, and functions mean.
> feat(@clayui/empty-state): Output a reduced motion image by default

- jest.config.js
- packages/clay-autocomplete/src/Autocomplete.tsx
Fixes [LPS-192047](https://liferay.atlassian.net/browse/LPS-192047)
This PR improves the behavior of matching the value with the suggestion list when the state is controlled, as most of the mechanism is based on the internal interactions of the component it caused problems when the developer has the state controlled and added new behaviors, for example reset the value.
> fix(@clayui/autocomplete): does not revalidate the value if it is reset by the controlled state

- packages/clay-navigation-bar/src/index.tsx
- packages/clay-navigation-bar/stories/NavigationBar.stories.tsx
https://liferay.atlassian.net/browse/LPS-192418
@matuzalemsteles I added the prop `fluidSize` to ClayNavigationBar. We currently allow `ClayLayout.ContainerFluid` to omit outputting the class `container-fluid-max-{size}` if the `size=false`. Should we add a new `fluidSize`, something like `fluid` or `fluid-layout`, in `ClayLayout.Container` to do that instead?
> feat(@clayui/navigation-bar): Adds fluidSize prop to customize container-fluid width

- package.json
- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/Editor.tsx
- packages/clay-color-picker/src/Hue.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/hooks.ts
- packages/clay-color-picker/src/index.tsx
- packages/clay-drop-down/src/Menu.tsx
Jira ticket: https://liferay.atlassian.net/browse/LPS-190649
> refactor(accessibility): Add accessibility features to Color Picker hue slider

- clayui.com/.env.production
- clayui.com/.gitignore
- clayui.com/gatsby-config.js
- clayui.com/package.json
- clayui.com/src/components/LayoutNav/Search.js
- clayui.com/src/html.js
- clayui.com/src/styles/_docsearch.scss
- yarn.lock
Well, I got an email from the Security team to move this to the env despite being a public key. We are also using a very old version of Algolia and need to migrate soon to using [docsearch](https://docsearch.algolia.com/docs/migrating-from-legacy) which has a new scraper infrastructure.
>  feat(clayui.com): adds Algolia's new docsearch

- packages/clay-breadcrumb/docs/index.js
- packages/clay-breadcrumb/src/Item.tsx
- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-breadcrumb/src/index.tsx
- packages/clay-css/src/scss/cadmin/components/_breadcrumbs.scss
- packages/clay-css/src/scss/cadmin/variables/_breadcrumbs.scss
- packages/clay-css/src/scss/components/_breadcrumbs.scss
- packages/clay-css/src/scss/variables/_breadcrumbs.scss
I'm updating link colors with active state and also updating expand button color. There are other small details, the item with the active state we are setting the `href` to `#` instead of the link to avoid page refresh.
> fix(@clayui/breadcrumb): updates colors to active state with link and expand button

- jest.config.js
- packages/clay-core/package.json
- packages/clay-core/src/drop-down/Item.tsx
- packages/clay-core/src/drop-down/Menu.tsx
- packages/clay-core/src/drop-down/index.ts
- packages/clay-core/src/index.ts
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/package.json
- packages/clay-pagination/src/Ellipsis.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/index.tsx
- packages/clay-pagination/stories/Pagination.stories.tsx
- packages/clay-shared/src/useNavigation.tsx
Fixes #4605 
As part of this PR I'm adding a new experimental component that we're using in Pagination to render a DropDown with a virtualized list that works for nested groups, that part isn't done yet but I'll do it another time.
This allows rendering a large list of items without performance issues this would be the evolution of DropDown in the next major version, a simple API and less configuration with OOTB resources to avoid problems with the current DropDown component and have too much coupling. There are still some tweaks to make currently.
> fix(@clayui/pagination): fix bug rendering large list of items with virtualization

- jest.config.js
- packages/clay-color-picker/src/Editor.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/index.tsx
- packages/clay-css/src/scss/cadmin/components/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_input-groups.scss
- packages/clay-css/src/scss/cadmin/variables/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_input-groups.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-date-picker/src/index.tsx
- packages/clay-drop-down/src/Search.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-management-toolbar/stories/ManagementToolbar.stories.tsx
- packages/clay-time-picker/src/__tests__/index.tsx
- packages/clay-time-picker/src/index.tsx
https://liferay.atlassian.net/browse/LPS-195104
This adds `:focus-within` to our `form-control` elements. This offloads focus interactions to the browser on more complex elements like `input-group`s (e.g., search bar, time picker, rgb inputs in color picker).  We weren't managing the focus class on a lot of input groups and now we no longer need to.
~One thing I don't like is the name of the `form-control-container` class. I was hoping for something better, but can't think of anything. @matuzalemsteles @ethib137 do you think we should add an attribute to the `ClayInput.GroupItem` component to output this? I'm currently adding it via `className="form-control-container"`.~
Edit: Went with `input-group-item-focusable`. Thanks @ethib137 !
> feat(@clayui/css): Adds focus-within

- jest.config.js
- packages/clay-autocomplete/src/Item.tsx
Fixes [LPS-194107](https://liferay.atlassian.net/browse/LPS-194107)
Well, I thought fixing this would be more complex but I ended up using some resources we have to prevent hovering over the item from updating the virtual focus when the scroll moves when navigating via keyboard. The strategy here was simpler than I thought at the beginning, so we just avoided updating the `activeDescendant` on hover over the item when the current interaction is being via keyboard, we got this information with the `isFocusVisible` hook that we have to identify this behavior.
> fix(@clayui/autocomplete): fix error when navigating via keyboard with the mouse over the item

- packages/clay-core/package.json
- packages/clay-core/src/table/Body.tsx
- packages/clay-core/src/table/Column.tsx
- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/Row.tsx
- packages/clay-core/src/table/ScopeContext.ts
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/index.ts
- packages/clay-core/stories/Table.stories.tsx
Closes [LPS-192998](https://liferay.atlassian.net/browse/LPS-192998)
This PR implements new components for Table to make room for new OOTB features for developers, so we can continue improving the UX and making the component more useful and prevent developers from having to implement more features on top of that.
The idea here is to bring a data-oriented composition using the Collection pattern that we already use in other Clay components, this already brings the UX benefits that we have in other components and we can also implement the features such as list virtualization that we need to implement the [treegrid](https://liferay.atlassian.net/browse/LPS-193002) pattern and the [column resizer](https://liferay.atlassian.net/browse/LPS-193001).
Instead of implementing this on top of the …
> feat(@clayui/core): adds the implementation of the new data-oriented composition for Table

- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/stories/DropDown.stories.tsx
https://liferay.atlassian.net/browse/LPS-195376
> fix(@clayui/css): Checkbox and Radio text should be vertically aligned at the start when breaking to new line

- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/table/Column.tsx
- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/context.tsx
- packages/clay-core/src/vertical-nav/Item.tsx
- packages/clay-core/stories/Table.stories.tsx
- packages/clay-data-provider/docs/data-provider.mdx
- packages/clay-data-provider/src/__tests__/index.tsx
- packages/clay-data-provider/src/index.tsx
- packages/clay-data-provider/src/useResource.tsx
Closes [LPS-192999](https://liferay.atlassian.net/browse/LPS-192999) and [LPS-193000](https://liferay.atlassian.net/browse/LPS-193000)
This PR implements column sorting support for an OOTB table with accessibility support, this also adds the controlled and uncontrolled state pattern to the sort API. There are still some details to be done, such as adding sort support to the Data Provider for asynchronous sorting. DX also makes this very simple, see my example of sorting in the storybook.
```jsx
<Table onSortChange={onSortChange} sort={sort}>
<Head>
<Column key="name" sorting>Name</Column>
<Column key="files" sorting>Files</Column>
<Column key="type">Type</Column>
</Head>
<Body items={items}>
{(row) => (
<Row>
<Column>{row.name}</Column>
<Column>{row.files}</Column> …
```
> feat(@clayui/core): adds new API to handle column sorting with accessibility support

- clayui.com/static/js/docs-site.js
- packages/clay-css/src/scss/cadmin/components/_tables.scss
- packages/clay-css/src/scss/cadmin/variables/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/mixins/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
- packages/clay-table/docs/markup-table.md
https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2432237790/Nested+Rows+-+Front-end+DataSet
I'm sending this as draft so we can discuss this implementation. 
I had to use nested tables because we need a container element to animate the collapse if needed. The example in https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/#ex_label is clean and concise, but we can't collapse the rows like we do panels. The code for the nested table looks like:
```html
<tr role="presentation">
<td colspan="6" role="presentation">
<div class="collapse" id="tableCollapse01">
<table role="presentation">
<tbody role="presentation">
<tr aria-level="2" role="row"></tr>
</tbody>
</table>
</div>
</td>
</tr>
```
Voice Over announces this like it's the next table row. The `role="presentation"` …
> feat(@clayui/css): Tables adds table-nested-rows

- clayui.com/content/docs/components/markup-sidebar.md
- packages/clay-css/src/scss/cadmin/components/_panels.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/cadmin/variables/_sidebar.scss
- packages/clay-css/src/scss/components/_panels.scss
- packages/clay-css/src/scss/mixins/_sidebar.scss
- packages/clay-css/src/scss/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_sidebar.scss
https://liferay.atlassian.net/browse/LPS-198267
This adds the `sidebar-sm` modifier class. It's supposed to make everything inside `sidebar` small sized, like inputs, buttons, and margins. We are moving it from DXP to here due to issues with selector specificity. LPS-198267 mostly relates to the `btn-beta` component.
For reference: https://github.com/liferay-peds/liferay-portal/pull/316
> feat(@clayui/css): Sidebar adds sidebar-sm

- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
https://liferay.atlassian.net/browse/LPS-195376
This fixes a regression from https://github.com/liferay/clay/pull/5681 where badge breaks to new line.
> fix(@clayui/css): Checkbox and Radio with badge breaks to new line

- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
- packages/clay-css/src/scss/cadmin/components/_cards.scss
- packages/clay-css/src/scss/cadmin/components/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/components/_dropdowns.scss
- packages/clay-css/src/scss/cadmin/variables/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/components/_dropdowns.scss
- packages/clay-css/src/scss/variables/_cards.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/stories/DropDown.stories.tsx
- packages/clay-form/src/Checkbox.tsx
- packages/clay-form/src/Radio.tsx
- packages/clay-form/src/__tests__/__snapshots__/Checkbox.tsx.snap
- packages/clay-form/src/__tests__/__snapshots__/RadioGroup.tsx.snap
- packages/clay-form/stories/Checkbox.stories.tsx
- packages/clay-form/stories/Radio.stories.tsx
https://liferay.atlassian.net/browse/LPS-195376
@matuzalemsteles I added the modifier class `custom-control-outside`. It's output when there is a `label`. I wish there was a better way to do this globally.
Edit: I'll send a docs update in a separate pr.
> feat(@clayui/form): Checkbox and Radio should use modifier class custom-control-outside if a label is present

- packages/clay-css/src/scss/cadmin/variables/_navs.scss
https://liferay.atlassian.net/browse/LPS-196996
Cadmin Old Nav Tab
Cadmin New Nav Tab
> fix(@clayui/css): Cadmin nav-tabs remove deprecated styles

- babel.config.js
Well, we are deleting `transform-regenerator` so that we can use the [Generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) feature and consequently we can now also use [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) instead of continuing to use `then` for Promise, these are features that have been supported by the browser for a long time and is also included within our compatibility matrix.
- `async/await` - 95.9% https://caniuse.com/async-functions
- `function*` - 96.25% https://caniuse.com/es6-generators
- `yield*` - 95.15% https://caniuse.com/mdn-javascript_operators_yield_star
- `yield` - 95.15% https://caniuse.com/mdn-javascript_operators_yield
> chore: remove the use of regenerator in the build

- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
https://liferay.atlassian.net/browse/LPS-196999
> fix(@clayui/css): Cadmin dropdown-menu-indicator spacing is off by 4px

- packages/clay-core/src/collection/useCollection.tsx
Fixes [LPS-200526](https://liferay.atlassian.net/browse/LPS-200526)
The clean up should only be done in use cases where we have the collection implicitly declared as the VerticalNav component and the list is rendered in render time instead of just once in the root of the component like the Picker component.
> fix(@clayui/core): fixes error when cleaning up the collection for explicitly nested collections

- packages/clay-css/src/scss/atlas/variables/_tables.scss
- packages/clay-css/src/scss/cadmin/components/_tables.scss
- packages/clay-css/src/scss/cadmin/variables/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
This is a follow up for https://liferay.atlassian.net/browse/LPS-197645. We add `.table-focus` to the table row to add a focus outline when needed. I had to use an unconventional box shadow since Safari built their browser to spec for table rows. The spec says table row position is undefined which prevents us from using relative positioning to position our focus outline.
> fix(@clayui/css): Adds .table-focus for focus outline around table row

- packages/clay-badge/docs/badge.mdx
- packages/clay-badge/docs/index.js
- packages/clay-badge/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-badge/src/__tests__/index.tsx
- packages/clay-badge/src/index.tsx
- packages/clay-badge/stories/Badge.stories.tsx
- packages/clay-button/docs/button.mdx
- packages/clay-button/docs/index.js
- packages/clay-button/src/Button.tsx
- packages/clay-button/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-button/src/__tests__/index.tsx
- packages/clay-button/stories/Button.stories.tsx
- packages/clay-css/src/scss/cadmin/components/_badges.scss
- packages/clay-css/src/scss/cadmin/variables/_badges.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_badges.scss
- packages/clay-css/src/scss/variables/_buttons.scss
Edit: We need to follow this up with https://liferay.atlassian.net/browse/LPS-201347 and remove beta variants.
https://liferay.atlassian.net/browse/LPS-198003
This adds translucent buttons and badges. I decided to stick with `.btn-translucent` and `.btn-translucent.btn-info`, instead of something like `.btn-translucent-info`. I think it will be easier to implement on the JS side.
For the dark variants, I did something different and want some feedback whether it's a good idea. We keep the class names the same,`.btn-translucent.btn-info`, but qualify it with `.clay-dark` on the parent element or component. This will apply dark styles to everything inside. I noticed we are shifting to be more accommodating with user preferences maybe can provide the dark theme version similar to cadmin by …
> feat(@clayui/css): Adds translucent buttons and badges

- packages/clay-core/src/live-announcer/LiveAnnouncer.tsx
This is a report made by the Cloud team, they use server side rendering. So we need to check that we are not using the browser API when rendering on the server side.
> fix(@clayui/core): fixes bug when rendering LiveAnnouncer on server side

- packages/clay-core/src/hooks/index.ts
- packages/clay-core/src/hooks/useIsFirstRender.ts
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
This behavior should only happen when items change, as in React.js, regardless of the first render it will invoke useEffect, in this scenario this ends up breaking the hydrate behavior of the first render for the selected items.
So we prevent this case from being computed on the first rendering and only being called when the items change.
> fix(@clayui/core): fixes error when deselecting the indeterminate state for pre selected items in the first render

- packages/clay-panel/docs/markup-panel.md
- packages/clay-panel/src/Group.tsx
- packages/clay-panel/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/src/index.tsx
[Ticket](https://liferay.atlassian.net/browse/LPS-201300)
[Thread-Slack](https://liferay.slack.com/archives/C03CAD9EF/p1699525029248659)
> LPS-201300 Fixing Accessibility Issue at Clay Panel Component

- packages/clay-core/src/table/Cell.tsx
- packages/clay-core/src/table/Row.tsx
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/table/context.tsx
- packages/clay-core/stories/Table.stories.tsx
- packages/clay-css/src/scss/atlas/variables/_tables.scss
- packages/clay-css/src/scss/cadmin/components/_tables.scss
- packages/clay-css/src/scss/cadmin/variables/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/mixins/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
- packages/clay-table/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-table/src/index.tsx
From https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2540961873/Border+Radius
With the changes in the new component and FDS initiative, this brought changes to the look of the table, such as striped by default and bordered which is only in the header, it also brought new sizes. This PR does not apply all these styles because we still need to work on the CSS part. This PR only introduces sections and striped.
> feat(@clayui/table): updates the table look

- clayui.com/plugins/gatsby-remark-use-clipboard/index.js
The build was failing because the language could be null, strangely it seems like this has happened before but it didn't fail, it could have been some change in the package updates that could have caused this but this now fixes the clayui.com build failures and storybook.
> fix(clayui.com): fix build error

- packages/clay-core/package.json
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/collection/types.ts
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/drop-down/Item.tsx
- packages/clay-core/src/drop-down/Menu.tsx
- packages/clay-core/src/table/Body.tsx
- packages/clay-core/src/table/Cell.tsx
- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/Row.tsx
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/table/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/table/context.tsx
Ticket [LPS-202287](https://liferay.atlassian.net/browse/LPS-202287)
This PR is still a draft but it adds the main functionality of being able to hide the column, by default we are leaving this functionality always activated but it is possible to deactivate it using the `columnsVisibility` API.
There are still visual details to adjust that are related to DropDown, like the DropDown header and the new switch size, I will work on that tomorrow.
> feat(@clayui/core): adds column visibility feature

- .github/workflows/close-issues.yml
- .github/workflows/release.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- .storybook/preview.js
- package.json
- packages/clay-core/src/table/Cell.tsx
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/table/useTreeNavigation.tsx
- packages/clay-css/src/scss/cadmin/variables/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/mixins/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
- yarn.lock
Closes [LPS-202866](https://liferay.atlassian.net/browse/LPS-202866)
The icon update is still in draft, I need to make some adjustments, @pat270, would you have any ideas on how we can try to achieve these use cases of the sorting icon state? I don't know if we have something like this in CSS.
Even though I'm using the button, I'm making it invisible to SR because we're using the head for sorting for accessibility reasons, so when you press the whole head it changes the sorting if it's enabled for the column, so we can use `aria -sort`.
> fix(@clayui/core): updates the sort icon for table

- packages/clay-core/src/vertical-nav/Item.tsx
- packages/clay-core/src/vertical-nav/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-nav/src/__tests__/index.tsx
Jira issue: https://liferay.atlassian.net/browse/LPS-196557
Evidence using AXE DevTools:
> fix(@clayui/vertical-nav): Update Vertical Navigation markup to fix JAWS read

- packages/clay-css/src/scss/atlas/variables/_panels.scss
- packages/clay-css/src/scss/components/_panels.scss
- packages/clay-css/src/scss/mixins/_panels.scss
- packages/clay-css/src/scss/variables/_panels.scss
- packages/clay-panel/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/src/__tests__/index.tsx
- packages/clay-panel/src/index.tsx
- packages/clay-panel/stories/Panel.stories.tsx
> Dear reviewer, [there is still an ongoing conversation on slack](https://liferay.slack.com/archives/C049XG98GQL/p1700832971192009) about how to handle this new design, I originally suggested allowing any custom header in the `clay:panel` taglib, like we do with the React component, but I think it is better, in terms on consistency, to keep a reduced number of cases as far as we can.
> 
> I wanted to update the code beforehand to be sure that this was feasible and not an ugly patch, but feel free to close this PR or request an alternative if this is a bad idea.
This PR adds a new displayType for ClayPanel component, matching a new design that we need in portal to implement the following UI:
https://www.figma.com/file/zf4akVPokkJdRKvgQtHxC0/LPS-114700--Translation-improvements-for-web-cont …
> LPS-202818 Update version

- packages/clay-css/src/scss/cadmin/components/_print.scss
- packages/clay-css/src/scss/components/_print.scss
- causes CSS to be removed when converting CSS to rtl
https://liferay.atlassian.net/browse/LPD-16364
> fix(@clayui/css): LPD-16364 @page {.css-selector{}} is not valid css

- packages/clay-core/src/drop-down/Menu.tsx
- packages/clay-core/src/table/Head.tsx
Ticket [LPD-16299](https://liferay.atlassian.net/browse/LPD-16299)
This fixes the bug when not being able to navigate via keyboard in the Columns Visibility of the table and improves accessibility, I'm still not sure what would be the best case here for toggle accessibility because DropDown is a menuitem list, so we still need to have the focus of the switch so that it announce correctly through SR, otherwise the announce will only be for the menuitem. Any idea?
> fix(@clayui/core): fixes bug when not focusing on the first item

- packages/clay-core/src/picker/Picker.tsx
Thread https://liferay.slack.com/archives/C049XG98GQL/p1707334836231499
When the items are updated, the visual focus is stale, meaning that when navigating via the keyboard it will not work because the key does not exist in the list, so we need to update the visual focus when the list is updated during the component life cycle.
> fix(@clayui/core): fixes bug when visual focus is lost when items are updated in Picker

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/stories/TreeView.stories.tsx
Ticket [LPS-203851](https://liferay.atlassian.net/browse/LPS-203851)
Well, basically this is a follow-up fix where the original fix only fixed the bug in Chrome and still kept reproducing in Firefox. After some tests it seems that the problem was always happening when the DropDown Item is a link, when clicking on the link the TreeView node's blur event is triggered first than the dropdown item, causing the dropdown trigger to disappear and the menu was repositioned and for some reason it didn't trigger the click on the DropDown item afterwards. I still haven't found a clear explanation about this behavior and because it happens in Firefox, my assumption is still the order of events and perhaps the cancellation midway.
To prevent the DropDown trigger from disappearing, I'm just adding that …
> fix(@clayui/core): LPS-203851 fixes bug when keeping DropDown open in TreeView actions in Firefox

- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
Jira issue: https://liferay.atlassian.net/browse/LPD-17368
> LPD-17368 Accessibility issue in Pagination Picker

- packages/clay-autocomplete/src/Item.tsx
- packages/clay-core/src/typography/TextHighlight.tsx
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/variables/_globals.scss
Follow up #5777
Well looking at the story apparently this is to be updated in Autocomplete too, so I'm updating the components here that are related to highlight. There is a small visual bug when I'm testing this in Autocomplete cc @pat270.
> feat(@clayui/autocomplete): update component highlight

- clayui.com/plugins/gatsby-plugin-clay-css-tasks/clay-icon-aliases.js
- clayui.com/static/js/icons-autogenerated.json
Jira issue: https://liferay.atlassian.net/browse/LPD-17080
This is a follow-up PR do update the SEO icon aliases, as requested in jira description.
> Follow-up fix(@clayui/css): LPD-19703 Change seo icon aliases

- packages/clay-button/docs/button.mdx
- packages/clay-button/docs/index.js
- packages/clay-button/src/Button.tsx
Jira issue: https://liferay.atlassian.net/browse/LPD-17350
- Adding borderless example
- Removing unstyled, null, translucent, and beta examples.
- The translucent example can be found in the [storybook](https://storybook.clayui.com/?path=/story/design-system-components-button--default&args=translucent:true;size:!null) already, among with the types.
[Documentation preview](https://deploy-preview-5784--next-clayui.netlify.app/docs/components/button.html)
> docs(Button): LPD-17350 - Buttons - Simplify Clay page and align to Lexicon

- packages/clay-core/src/collection/types.ts
- packages/clay-core/src/collection/useCollection.tsx
Ticket [LPD-21653](https://liferay.atlassian.net/browse/LPD-21653)
Basically we are always exposing the `index` of the item in the collection, at this moment I am adding it only for the case where there are no other APIs together like the TreeView due to the type of API that we would have to modify and it would probably be a breaking change.
> feat(@clayui/core): adds the `index` available in the item collection API

- packages/clay-core/docs/table.mdx
https://liferay.atlassian.net/browse/LPD-18963
@matuzalemsteles not sure if my code example is correct. I had trouble getting it to work locally. My understanding of Provider is poor.
> docs(clayui.com): LPD-18963 Add warning about missing icons

- .github/workflows/clay-nightly.yml
Before merging this we need to add the build hook to the secret of the Github repository, I think we need to open a ticket for this.
> feat: add cron job to run clayui.com's nightly build

- packages/clay-css/src/scss/variables/_popovers.scss
- the fade-in Sass function doesn't work with CSS variables
https://liferay.atlassian.net/browse/LPD-22263
> fix(@clayui/css): LPD-22263 remove use of fade-in function

- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/index.tsx
Ticket [LPD-20600](https://liferay.atlassian.net/browse/LPD-20600)
The size of the navbar when interacting with it in a mobile version and returning to the screen size on the desktop ends up breaking because we use animation via CSS together with JS and we end up leaving the height of the navbar fixed for the animation to happen but we don't clean it after it ends so this ends up breaking when returning to the desktop screen instead of mobile, now we are clearing the height after the animation ends.
> fix(@clayui/navigation-bar): fixes navbar size bug when resizing

- jest.config.js
- package.json
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/stories/Card.stories.tsx
Hi guys!
According to this issue https://liferay.atlassian.net/browse/LPD-1261, on the Echo team we need a new variant of cards that have radio buttons, so here I'm sending  a solution for this.
A new prop has been added, which is `selectableType`. This prop defines whether the selectable element will have a checkbox or a radio button. In addition, A `radioProps` prop is also added to be able to pass the necessary props to the radio input. Along with all this, a new case in storybook has been added with two radio cards, to see the behavior of these cards:
https://github.com/liferay/clay/assets/9701095/b414ad66-bb10-4c40-9684-cfe88b0cda4a
Finally, to give the user the option of not truncating the text (it's another requirement in our design and in general accessibility), a new `truncate` …
> feat(@clayui/card): Radio Card component variant

- packages/clay-button/src/Group.tsx
- packages/clay-button/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-css/src/scss/cadmin/components/_button-groups.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/components/_button-groups.scss
- packages/clay-css/src/scss/variables/_buttons.scss
https://liferay.atlassian.net/browse/LPD-23703
> feat(@clayui/css): LPD-23703 Adds btn-group-spaced for a separated button group

- packages/clay-core/docs/picker.js
- packages/clay-core/docs/picker.mdx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/stories/Picker.stories.tsx
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-date-picker/src/DateNavigation.tsx
Ticket [LPD-23824](https://liferay.atlassian.net/browse/LPD-23824)
Well basically we are adding the `width` API to define the size behavior of the Picker Panel, when marking the `flexible` API the panel will adapt to the size of the trigger and the minimum of 160px or fixed with the minimum of 160px. I believe this is a simple API rather than having an API that the developer can define the size of because it is not responsive and this adds a lot of flexibility beyond what is described.
> feat(@clayui/core): adds new width API for the picker

- packages/clay-core/src/table/Row.tsx
This is a bug that was discovered when implementing the new Table to the FrontEndDataSet [LPD-24920](https://liferay.atlassian.net/browse/LPD-24920). Basically when we have column visibility enabled if we want to render the actions in the last cell it is not rendering the element, so now this fixes this for this use case.
> fix(@clayui/core): fixes bug when not rendering the action cell

- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/context.tsx
This is a use case that was discovered when integrating ClayTable with FDS where the selection column will always be visible and is not shown in the columns visibility menu. So we are adding a new API to allow omitting the column and always making it visible, something that is important for the table to continue functioning and is not necessarily part of the data structure. An option would also be to add the OOTB selection feature with controlled state, because this way, when clicking on select all, the dev can implement the selection of all items in the backend.
> feat(@clayui/core): add new API to omit a column to columns visibility

- packages/clay-core/src/table/Row.tsx
Follow-up #5817
I had only done the test for the case of static rendering but had not done the coverage for the case of dynamic rendering, an important point is that we do this as a speculation of the size of the items within a row but this value can change if necessary in the cell, I believe that the best thing is for the developer to avoid cases like this so as not to break other table behaviors along with collection, so it always passes the items that will be rendered. This is also great for recommending that they are pure functions and have no side effects.
> fix(@clayui/core): Fixes bug when rendering the last columns visibility cell for dynamic rendering

- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
Jira issue: https://liferay.atlassian.net/browse/LPD-19473
Evidence:
https://github.com/liferay/clay/assets/47724428/2626eb39-a74a-49a7-b1d5-2a7a07b99dac
> refactor(@clayui/treeview): LPD-19473 Improve TreeView Contrast on Active and Hover states

- packages/clay-empty-state/src/index.tsx
Follow-up #5819
We made a change that broke the behavior where there are some cases where reduced motion is not necessary because the main image is static and so we have to disable the use of reduced motion by setting the `imgSrcReducedMotion` variable to `null`.
> fix(@clayui/empty-state): fixes bug when always trying to render the image for reduced motion when disabled

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/stories/Card.stories.tsx
Hi guys!,
I am sending this pull because while fixing this bug https://liferay.atlassian.net/browse/LPD-1261, I realized the following:
https://github.com/liferay/clay/assets/9701095/51e8abd8-830f-4812-b611-c29b2eecbefe
As you see in the video, when you navigate by keyboard, the navigation does not recognize which radio button is selected, and when you return to the cards, the radio input that is not selected is focused.
This happens because to group the radio buttons in a group it is necessary to add the same `name` to all the inputs [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radiogroup_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radiogroup_role#:~:text=When%20using%20HTML%27s%20native%20input%20radio%20button%2C%20%3Cinput%20typ …
> feat(@clayui/card): LPD-1261 Add name to group all radio type inputs

- packages/clay-modal/src/Hook.ts
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-popover/src/index.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/stack.ts
Jira issue: https://liferay.atlassian.net/browse/LPD-15613
**Issue**
1. The popover remains open after interacting with the Tab key.
2. If the popover is on a modal, when the Escape Key is pressed, both popover and modal are closed
**Evidence**
https://github.com/liferay/clay/assets/47724428/977048ed-b189-4de8-979b-9ebb39854cb3
> refactor(@clayui/popover): LPD-15613 Popover: closeOnClickOutside prop does not work with keyboard interaction

- packages/clay-core/docs/picker.mdx
This was an issue I found during the investigation of bug on ClayPicker
> docs(Picker): Fix the documentation path to flexible width example

- jest.config.js
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/stories/Picker.stories.tsx
Ticket: https://liferay.atlassian.net/browse/LPD-28522
The language selector is not displaying correctly: the labels of the status are overlapping the language key and the number of fields is not appearing.
Be able to set an auto width so that the menu can grow with the content.
- **fix(@clayui/picker): LPD-28522 Add option to add auto width**
- **fix(@clayui/picker): LPD-28522 Update picker stories**
> fix(@clayui/picker): LPD-28522 Fix language selector not displaying correctly on web content

- packages/clay-core/src/table/Cell.tsx
Well, I ended up thinking a lot about this... to "fix" the visual bug of the resizer indicator in FDS when using the new ClayTable and the cell activates sort. The indicator that FDS adds as `children` to the cell needs to be positioned on the edges of the cell but when it has sort it fails due to the internal HTML structure changing to support the visual states that we have to cover the Lexicon and this also ends up due to the properties CSS that prevent this.
A first solution I thought of was to add a new API to add new `right` or `left` elements in a cell independent of the internal structure when truncate or sort is enabled but this can add flexibility that we don't want and can break the Lexicon extension principles so to not go along this line of development as we will be developing …
> chore(@clayui/core): adds support for resizer indicator in table

- packages/clay-css/src/scss/cadmin/components/_modals.scss
- packages/clay-css/src/scss/cadmin/variables/_modals.scss
- packages/clay-css/src/scss/components/_modals.scss
- packages/clay-css/src/scss/variables/_modals.scss
- packages/clay-modal/src/Header.tsx
- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
Ticket [LPD-31019](https://liferay.atlassian.net/browse/LPD-31019)
Well, that's moving the focus to the modal title instead of the dialog. As we have a configuration that allows us to customize the modal header and it may be that the developer does not configure it correctly or does not use `Modal.Title` we still focus on the dialog as a fallback.
@pat270 do we have any class that removes the visual state of focus on h1?
> fix(@clayui/modal): move focus to h1

- packages/clay-css/src/scss/mixins/_globals.scss
- Added pseudo class and element keywords to filter for in the mixin `clay-map-to-css`
https://liferay.atlassian.net/browse/LPD-33629
Added a work around to make keys like hover, focus, disabled work when recursively generating selectors, but we should start encouraging using key names wrapped in quotes like '&:hover'.
> LPD-33629 $modal-palette map should output pseudo classes for .close

- packages/clay-core/docs/focus-trap.js
https://liferay.atlassian.net/browse/LPD-34243
> docs(clayui.com): LPD-34243 Fixes Focus Trap page syntax error

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-shared/src/Overlay.tsx
Context https://liferay.slack.com/archives/C04CPMRMXAL/p1723558235946469
Well, basically, the message from Chrome about blocking focus due to the use of aria-hidden seems intermittent and only happens once, at least in the tests I've done, but I can still see the focused element when adding a watch to `document.activeElement`.
So I think this is more of a warning about good practices or avoiding problems with SR, but I think this would be an unrealistic case, perhaps since when using SR in a real case, you are normally using keyboard interaction and when you close the menu, the focus returns to the trigger that does not have aria-hidden, so this will not happen in this use case. I believe that this may be another bug in Chrome that should show this message in case of keyboard interaction …
> fix(@clayui/drop-down): fixes bug with chrome blocking element focus when clicking outside the menu

- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/__tests__/index.tsx
- packages/clay-navigation-bar/src/index.tsx
- packages/clay-navigation-bar/stories/NavigationBar.stories.tsx
https://liferay.atlassian.net/browse/LPD-29692
> feat(@clayui/navigation-bar): Add sr-only description for mobile view

- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-shared/src/Overlay.tsx
Ticket [LPD-35161](https://liferay.atlassian.net/browse/LPD-35161)
To avoid the accessibility error we avoid adding aria-hidden to the focusable element that we use for the focus trap. So basically we removed aria-hidden and I thought we would also need to ignore the suppression we do with inert but it wasn't necessary.
> LPD-35161 Removes suppression of focusable elements from focus trap

- jest.config.js
- packages/clay-core/src/picker/Option.tsx
- packages/clay-core/src/picker/__tests__/BasicRendering.tsx
- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination-bar/src/__tests__/index.tsx
Jira issue: https://liferay.atlassian.net/browse/LPD-38518
- **LPD-38518 - Add prop "href" to handle options with links**
- **LPD-38518 - Add case test**
- **LPD-38518 -Handle options with links on pagination bar**
- **LPD-38518 - Add case test for pagination bar**
- **LPD-38518 - Update jest.conig**
> LPD-38518 - ClayPaginationBarWithBasicItems does not render picker with links when deltas use links

- jest.config.js
- packages/clay-form/src/DualListBox.tsx
- packages/clay-form/stories/DualListBox.stories.tsx
https://liferay.atlassian.net/browse/LPD-36696
I added children to the component so we can pass in things like an error message. I also removed disabling the move buttons if length is 0.
> fix(@clayui/form): LPD-36696 DualListBox adds children and don't disable left right buttons if no items are selected

- packages/clay-core/src/table/Body.tsx
- packages/clay-core/src/table/__tests__/IncrementalInteractions.tsx
jira ticket: https://liferay.atlassian.net/browse/LPD-39956
- **fix(@clayui/core): LPD-39956 - Not render left arrow button when child array is empty**
- **fix(@clayui/core): LPD-39956 - Update tests**
> fix(@clayui/core):LPD 39956 Clay Table with nested rows shows expand button when children is empty array.

- .eslintrc.js
- .github/workflows/main.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
Well, running lint didn't show any errors, but let's see how this will work. I also think I'll add a new commit here updating to the new version of React 18.x. As this doesn't affect whoever uses it, we can already see how Clay works in a new version of React, but we don't need to use the new React features yet. Maybe we can add compatibility, for example, using `useId` if it's in the new version would be an option.
> feat: adding react compiler plugin

- clayui.com/plugins/gatsby-plugin-clay-css-tasks/clay-icon-aliases.js
- clayui.com/static/images/icons/icons.svg
- clayui.com/static/js/flags-autogenerated.json
- packages/clay-css/src/images/icons/flags-rw-RW.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
Jira issue: https://liferay.atlassian.net/browse/LPD-41002
> feat(@clayui/css): LPD-41347 - Add Rwanda Flag Icon

- packages/clay-drop-down/docs/drop-down.mdx
- packages/clay-management-toolbar/docs/index.js
- packages/clay-management-toolbar/stories/ManagementToolbar.stories.tsx
Jira issue: https://liferay.atlassian.net/browse/LPD-41311
> docs(Dropdown): LPD-41311 Update Clay Documentation for Caret Icon Usage

- packages/clay-core/src/table/Cell.tsx
- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/__tests__/__snapshots__/BasicRendering.tsx.snap
Jira issue: https://liferay.atlassian.net/browse/LPD-42395
- **feat (@clayui/table): LPD-42395 Add tooltips to table action buttons in Clay Table**
- **feat (@clayui/table): LPD-42395 Update snapshot**
> feat(@clayui/table):LPD 42395 Add tooltips to table action buttons in Clay Table

- packages/clay-navigation-bar/src/Item.tsx
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
Hi guys!
I am sending you the fix for this issue https://liferay.atlassian.net/browse/LPD-42404
Thanks in advance! :smile:
> fix(@clayui/core): Adapt snapshots

- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/Row.tsx
From https://github.com/liferay-platform-experience/liferay-portal/pull/865
Well, this PR only makes a small internal adjustment to recalculate the number of columns when the data changes. This is welcome because we can have applications that can change the data while the user interacts, not necessarily linked to column visibility, for example, a table editor.
The bug originated because of column visibility, but I don't believe this is a bug, but because of the way it is done in FDS, which should not change the data that is passed to the Table. It is recommended to always leave the data intact because we deal with this internally.
> fix(@clayui/core): fixes bug when updating the state at render time and the number of table columns when the state changes

- packages/clay-core/src/nav/Link.tsx
- packages/clay-core/src/vertical-nav/Item.tsx
- packages/clay-core/src/vertical-nav/VerticalNav.tsx
- packages/clay-core/src/vertical-nav/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/stories/VerticalNav.stories.tsx
- packages/clay-css/src/scss/cadmin/components/_menubar.scss
- packages/clay-css/src/scss/cadmin/variables/_menubar.scss
- packages/clay-css/src/scss/components/_icons.scss
- packages/clay-css/src/scss/components/_menubar.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/variables/_menubar.scss
- packages/clay-css/src/scss/variables/_navs.scss
- packages/clay-nav/src/Vertical.tsx
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
https://liferay.atlassian.net/browse/LPD-40160
I'm sending this as a draft because we have a problem with the accordion headers. They can only be `button` and in some of the headers we have nested plus buttons. Having a `button` nested in a `button` violates:
> [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2), but there must be no [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) descendant and no descendant with the [tabindex](https://html.spec.whatwg.org/multipage/interaction.html#attr-tabindex) attribute specified.
from the w3c spec. I need some help figuring out which component we should place `<div role="button">` to make our markup valid.
> feat(@clayui/css): LPD-40160 Adds menubar-primary for CMS Product Menu variant

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
fix(@clayui/css): LPD-44040 Update Cadmin colors that were missed in the original pr
https://liferay.atlassian.net/browse/LPD-40824
> fix(@clayui/css): LPD-40824 Update code color to #e60000 red

- packages/clay-css/src/scss/cadmin/components/_multi-step-nav.scss
- packages/clay-css/src/scss/cadmin/variables/_multi-step-nav.scss
- packages/clay-css/src/scss/components/_multi-step-nav.scss
- packages/clay-css/src/scss/variables/_multi-step-nav.scss
- packages/clay-multi-step-nav/docs/index.js
- packages/clay-multi-step-nav/docs/multi-step-nav.mdx
- packages/clay-multi-step-nav/src/MultiStepNav.tsx
- packages/clay-multi-step-nav/stories/MultiStepNav.stories.tsx
https://liferay.atlassian.net/browse/LPD-36816
> feat(@clayui/css): LPD-36816 Multi Step Nav adds multi-step-nav-center

- packages/clay-core/package.json
- packages/clay-core/src/vertical-nav/VerticalNav.tsx
- packages/clay-core/src/vertical-nav/__tests__/BasicRendering.tsx
- packages/clay-core/src/vertical-nav/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/stories/Accessibility.stories.tsx
- packages/clay-core/stories/VerticalNav.stories.tsx
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-nav/src/__tests__/index.tsx
- packages/clay-nav/stories/Nav.stories.tsx
Ticket: https://liferay.atlassian.net/browse/LPD-46005
The prop aria-label can be passed to the vertical navigation.
Added a prop called `ariaLabel` and an `useEffect` to display the console error when this prop is not passed
1. Go to Clay Vertical Navigation
2. Open Devtools
3. Check if tag `<nav>` has an aria-label property
4. When the propis not passed, there should be a warning logged to the console when in a development build
> LPD-46396 - Clay Vertical Navigation should include a prop that allows an aria-label to be added to the nav element.

- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
https://liferay.atlassian.net/browse/LPD-46380
@veroglez I sent this as a separate pr. I think this fixed the issue? It's really hard for me to tell. Lmk if this isn't correct.
This is related to https://github.com/liferay/clay/pull/5914
> fix(@clay/css): LPD-46380 Labels in dropdown-item are slightly misaligned

- packages/clay-date-picker/src/index.tsx
Ticket: https://liferay.atlassian.net/browse/LPD-46943
Passing `2025-01-19 04:00 PM` as value with use12Hours, the time picker shows 16:00 PM
The hour format should be reversed, `hh` for 12 hours and `HH` for 24h
1. Go to [Clay > Date Picker component > Time](https://deploy-preview-5923--next-clayui.netlify.app/docs/components/date-picker.html#time)
2. Update value from `null` to  `2025-01-19 04:00 PM`
3. Add `use12Hours` prop
4. Open the dropdown by clicking on the calendar icon and see the value matching.
> fix(@clayui/date-picker): LPD-46943 The Date Picker component shows time using the wrong format

- packages/clay-shared/src/Overlay.tsx
https://liferay.atlassian.net/browse/LPD-48227
@matuzalemsteles not related to this pr, but should we be using `inert` for all our dropdown menus and popups?
> fix(@clayui/shared): Only run hide code if menus match in Overlay

- packages/clay-core/src/vertical-nav/VerticalNav.tsx
Since we introduced a new API and made it required, this would be a major change because we would have to update all applications that use the component to define the `aria-label`, so the ideal would be to make the API optional. Since we have a warning message, this will notify developers to pay attention to this and configure it according to each use case.
> fix(@clayui/core): fixes build bug in applications

- packages/clay-empty-state/docs/empty-state.mdx
Ticket [LPD-49337](https://liferay.atlassian.net/browse/LPD-49337)
I thought about adding the images to codesandbox but this requires more configuration and can make things more slow because it will load the image in all examples, so since we already host the image on our website it is easier to pass the URL to our website, best practice is to continue with this now.
> docs(@clayui/empty-state): LPD-49337 fixes bug when not showing empty state images

- packages/clay-drop-down/docs/drop-down.mdx
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
Ticket [LPD-52457](https://liferay.atlassian.net/browse/LPD-52457)
I was no longer able to publish the site on Netlify due to a bug in the API Table generator that is related to not being able to understand or interpret the DrilldownWithItems types that we recently changed. I am also adding the API Table for DropDownWithItems that had the same bug.
> fix(@clayui/drop-down): fix Dropdown types to correctly generate API Table

- packages/clay-drop-down/src/Items.tsx
Ticket [LPD-52748](https://liferay.atlassian.net/browse/LPD-52748)
Well it is safe to add an `otherProps` to the DropDownWithItems component along with the Drilldown that now both share the same components internally but I kept the idea of ​​just adding the `target` type in the API to avoid increasing the surface and increase this as the needs arise to avoid having a high number of props support that can eventually become a problem because we cannot change.
> feat(@clayui/drop-down): adds target prop to high-level components

- packages/clay-css/src/scss/variables/_modals.scss
- packages/clay-modal/stories/Modal.stories.tsx
https://liferay.atlassian.net/browse/LPD-53627
> fix(@clayui/css): LPD-53627 Modals scope splash image to modal-banner-img instead of aspect-ratio

- packages/clay-shared/src/Overlay.tsx
https://liferay.atlassian.net/browse/LPD-48347
> fix(@clayui/shared): LPD-48347 Close overlay on left click only

- packages/clay-css/BREAKING.md
- packages/clay-css/src/images/icons/environment-connected.svg
- packages/clay-css/src/images/icons/environment-disconnected.svg
- packages/clay-css/src/images/icons/environment.svg
https://liferay.atlassian.net/browse/LPD-54010
Deprecate environment.svg, environment-connected.svg, and environment-disconnected.svg
> chore(@clayui/css): LPD-54010 Deprecate environment, environment-connected, environment-disconnected

- packages/clay-css/src/scss/cadmin/components/_form-validation.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_form-validation.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-form/docs/form.mdx
- packages/clay-localized-input/docs/localized-input.mdx
- packages/clay-localized-input/docs/localized-input/markup.mdx
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/index.tsx
- packages/clay-localized-input/stories/LocalizedInput.stories.tsx
https://liferay.atlassian.net/browse/LPD-51801
~Not sure if I implemented this correctly, but it looks like they just want a style change?~
> feat(@clayui/css): LPD-51801 Adds .blockquote variant for .form-text

- package.json
- packages/clay-core/package.json
- packages/clay-core/src/index.ts
- packages/clay-core/src/language-picker/LanguagePicker.tsx
- packages/clay-core/src/language-picker/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/package.json
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/__tests__/index.tsx
- packages/clay-localized-input/src/index.tsx
- yarn.lock
https://liferay.atlassian.net/browse/LPD-50722
> feat(@clayui/localized-input): LPD-50722 Use Language Picker for switching languages

- .eslintrc.js
- package.json
- packages/clay-charts/src/BillboardWrapper.tsx
- packages/clay-charts/src/GeoMap.tsx
- packages/clay-charts/src/index.tsx
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/overlay-mask/OverlayMask.tsx
- packages/clay-core/stories/TreeView.stories.tsx
- packages/clay-drop-down/src/Items.tsx
- packages/clay-shared/src/FocusScope.tsx
- packages/clay-shared/src/useFocusManagement.ts
- yarn.lock
previously approval here, https://github.com/liferay/clay/pull/6107
Will investigate babel integration separately
> chore: enable react-compiler eslint rule

- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/index.tsx
https://liferay.atlassian.net/browse/LPD-61062
one of the rules in react is that we shouldn't ever manually change a prop value or reassign it. So I moved initialMonth to a newly named variable and set it to `new Date()` if no prop is assigned.
> fix(date-picker): create a new date object for initialMonth if none is provided and create new variable so that we aren't re-assigning a prop value

- packages/clay-multi-select/stories/MultiSelect.stories.tsx
I've only been able to catch the failures in our "chromatic" ci test, which only runs on publish. Hoping this is the final fix...
> chore: fix exported types again

- packages/clay-core/src/side-panel/Header.tsx
- packages/clay-core/src/side-panel/SidePanel.tsx
- packages/clay-core/src/side-panel/SidePanelWithDrilldown.tsx
- packages/clay-core/src/side-panel/__tests__/SidePanelWithDrillDown.tsx
- packages/clay-core/src/side-panel/index.ts
- packages/clay-core/src/vertical-bar/Panel.tsx
- packages/clay-core/stories/SidePanel.stories.tsx
- packages/clay-css/src/scss/cadmin/variables/_slideout.scss
- packages/clay-css/src/scss/variables/_slideout.scss
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/usePrevious.ts
Hi team,
I’m sending a PR for this story https://liferay.atlassian.net/browse/LPD-47740, which includes a variant of the SidePanel with drilldown.
https://github.com/user-attachments/assets/7c12a67e-2316-4104-ab81-ae178a61a246
Additionally, I’ve also done a modification of the SidePanel header, as specified in this task https://liferay.atlassian.net/browse/LPD-60257. 
@pat270, I tried to adjust the back button in the header using `btn-outline-borderless btn-secondary ml-n2`. However, the negative margin should be 12 px instead of 8 px, and we currently don’t have a class for that margin. Could you help me with this?
Thanks in advance!
> feat(@clayui/core): LPD-48310 Add tests

- .storybook/main.js
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-autocomplete/src/Item.tsx
- packages/clay-autocomplete/src/__tests__/IncrementalInteractions.tsx
- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-multi-select/stories/MultiSelect.stories.tsx
This new API allows for configuring an action in the autocomplete dropdown that will always appear as the first item in the list and when selecting it will call the onClick callback. This also works in MultiSelect as well
https://github.com/user-attachments/assets/7f16d754-d071-4b5a-b19f-bd3db7d44059
> feat: add a primaryAction API for autocomplete
