- gulpfile.js
Hey Rob,
Commented out the maven-publish task for now, let me know if this works for you.
> Misc: Don't run maven-publish task for now

- packages/clay/src/content/tables.html
- packages/clay/src/content/test_table_view_template.html
- packages/clay/src/content/typography.html
- packages/clay/src/scss/atlas/variables/_tables.scss
- packages/clay/src/scss/components/_tables.scss
- packages/clay/src/scss/components/_type.scss
- packages/clay/src/scss/components/_utilities.scss
- packages/clay/src/scss/variables/_tables.scss
- Added pattern to accommodate sticker and text in one cell
- Added pattern for icons around `th` with truncating text
- Update link colors in `th` to match Lexicon 2 design
> Clay Table Updates

- packages/claycss.com/src/pages/docs/components/cards.md
- packages/claycss.com/src/pages/docs/components/form_custom.md
- packages/claycss.com/src/pages/docs/components/labels.md
Just updating some markups with the latest changes made in Clay.
cc @pat270
> Update some markups at claycss.com

- packages/clay/src/content/alerts.html
- packages/clay/src/content/application-bar.html
- packages/clay/src/content/dropdowns.html
- packages/clay/src/content/grid.html
- packages/clay/src/content/management-bar.html
- packages/clay/src/content/menu_bar_vertical.html
- packages/clay/src/content/nav_underline.html
- packages/clay/src/content/navbar.html
- packages/clay/src/content/navigation-bar.html
- packages/clay/src/content/subnav.html
- packages/clay/src/content/tbar.html
- packages/clay/src/content/test_card_view_template.html
- packages/clay/src/content/test_form_hierarchy.html
- packages/clay/src/content/test_list_view_template.html
- packages/clay/src/content/test_table_view_template.html
- packages/clay/src/content/test_users_and_organizations.html
- packages/clay/src/content/test_users_and_organizations_form_vertical_navigation.html
- packages/clay/src/scss/atlas/variables/_globals.scss
- packages/clay/src/scss/atlas/variables/_menubar.scss
- packages/clay/src/scss/components/_grid.scss
- packages/clay/src/scss/components/_menubar.scss
- packages/clay/src/scss/mixins/_grid.scss
- packages/clay/src/scss/mixins/_menubar.scss
- packages/clay/src/scss/variables/_globals.scss
- packages/clay/src/scss/variables/_menubar.scss
/cc @carloslancha @marcoscv-work
> #453 Added `.container-form-lg`, `.menubar-vertical-expand-lg`, and demos to break at lg breakpoint

- packages/claycss.com/src/pages/docs/components/dropdowns.md
Just update the Dropdown markup and some examples of soy with the ClayDropdown API change.
> Update Dropdown markup in claycss.com

- packages/claycss.com/src/pages/docs/components/list_groups.md
- packages/claycss.com/src/pages/docs/components/management_toolbar.md
- packages/claycss.com/src/pages/docs/components/progress_bars.md
Just some updates to markups and changes to the Soy API.
* Update the ListGroups markups
* Update soy examples from the ListGroup
* Update Management Toolbar markups
* Update soy examples from the ProgressBars page
> Some updates from the claycss.com

- packages/clay/src/content/management-bar.html
- packages/clay/src/scss/components/_navbar.scss
- packages/clay/src/scss/mixins/_navbar.scss
Just a heads up there's no interaction defined in Lexicon to close the search bar once opened in mobile.
> #512 management bar does not look correctly when contains only a search

- packages/clay/src/content/test_card_view_template.html
- packages/clay/src/scss/components/_cards.scss
- packages/clay/src/scss/variables/_cards.scss
@carloslancha the markup is now:
```
<ul class="card-page">
<li class="card-page-item-header">
<h4 class="card-section-header">My Heading</h4>
</li>
</ul>
```
> (#542) Put `card-section-header` inside `card-page li`

- packages/clay-charts/src/ChartBase.js
> Fix region parameter in ChartBase

- packages/claycss.com/electric.config.js
> ignore clay-isomorphic on claycss

- packages/clay-link/src/ClayLink.js
- packages/clay-link/src/ClayLink.soy
- packages/clay-link/src/__tests__/ClayLink.js
- packages/clay-link/src/__tests__/__snapshots__/ClayLink.js.snap
> Adding support for title attribute in links

- packages/clay-charts/package.json
> Adds missing metal dependency

- packages/clay-charts/src/ChartBase.js
- packages/clay-charts/src/DataComponent.js
- packages/clay-charts/src/__tests__/Chart.js
> Create lifecycle tests for clay-charts

- packages/clay/src/content/alerts.html
- packages/clay/src/content/modals.html
- packages/clay/src/content/test_upload_documents.html
- packages/clay/src/content/utilities.html
- packages/clay/src/scss/atlas/variables/_alerts.scss
- packages/clay/src/scss/atlas/variables/_modals.scss
- packages/clay/src/scss/atlas/variables/_progress-bars.scss
- packages/clay/src/scss/atlas/variables/_tables.scss
- packages/clay/src/scss/atlas/variables/_utilities.scss
- packages/clay/src/scss/components/_alerts.scss
- packages/clay/src/scss/components/_badges.scss
- packages/clay/src/scss/components/_labels.scss
- packages/clay/src/scss/components/_modals.scss
- packages/clay/src/scss/components/_progress-bars.scss
- packages/clay/src/scss/components/_utilities.scss
- packages/clay/src/scss/mixins/_links.scss
- packages/clay/src/scss/mixins/_modals.scss
- packages/clay/src/scss/variables/_alerts.scss
- packages/clay/src/scss/variables/_badges.scss
- packages/clay/src/scss/variables/_cards.scss
- packages/clay/src/scss/variables/_labels.scss
- packages/clay/src/scss/variables/_links.scss
- packages/clay/src/scss/variables/_list-group.scss
- packages/clay/src/scss/variables/_modals.scss
- packages/clay/src/scss/variables/_progress-bars.scss
- packages/clay/src/scss/variables/_tables.scss
- packages/clay/src/scss/variables/_utilities.scss
Sorry this is a big pull, these patterns weren't in any of the original designs.
> (#709) File upload modal

- src/scss/lexicon-base/_dropdowns.scss
https://issues.liferay.com/browse/LPS-80096
> Update: (Fixes #859) Fix whitespace issue with inline-scroller

- packages/clayui.com/src/pages/docs/layout/grid.md
Hey @jbalsas,<br><br>Attached is the fix for [Issue #900](https://github.com/liferay/clay/issues/900).<br><br>Let me know if you have any questions.<br><br>:rocket: Thanks!<br><br>@alexandervalencia
> Fixes Lexicon Grid pattern link

- README.md
Please check spelling errors 😁and if you have any suggestions leave your thoughts.
> Update README.md with more informations

- packages/generator-metal-clay/app/templates/_webpack.config.js
During the workshop, I've realized that I miss updating the yeoman template
> Update: (Fixes #1049)  Update Yeoman generator to use webpack common config

- clayui.com/gatsby/onCreateNode.js
- clayui.com/src/components/Sidebar/Sidebar.js
> (clayui.com) Adds a default value to redirect and layout if it is empty

- src/content/blogs_action.html
- src/content/management-bar.html
- src/content/test_assorted.html
- src/scss/lexicon-base/_management-bar.scss
https://issues.liferay.com/browse/LPS-86792
> Fixes #1252 - Management Bar added .management-bar-item-xs-inline-block

- src/js/side-navigation.js
https://issues.liferay.com/browse/LPS-86163
> Fixes #1266 - (1.x) Force reflow sidenav to prevent issue in IE11

- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/atlas.scss
- packages/clay-css/src/scss/base.scss
- packages/clay-css/src/scss/bootstrap.scss
Decided to import Bootstrap files individually for https://github.com/liferay/clay/issues/1270.
> Fixes #1274 - Duplicate CSS in Liferay DXP 7.1

- CONTRIBUTING.md
hey guys, I started to write some things to CONTRIBUTING.md according to my living together here and conversations that we had in issues and pull requests loose there, please let me know if I forgot to jot down something, this is the best time to we can discuss patterns too 🙂. 
hey @mwilliams2014 would like your help to do the review, i will be very grateful 🙂.
> Fixes #1217 - Adds CONTRIBUTING.md

- packages/clay-css/src/scss/atlas/variables/_globals.scss
> Fixes #1623 - ClayCSS 2.x Change headers sizes

- packages/clay-css/src/content/dropdowns_drill_down.html
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/atlas/_variables.scss
- packages/clay-css/src/scss/atlas/variables/_drilldown.scss
- packages/clay-css/src/scss/components/_drilldown.scss
- packages/clay-css/src/scss/variables/_drilldown.scss
https://issues.liferay.com/browse/LEXI-377
> Fixes #1386 ClayCSS 2.x adds new component Drilldown

- packages/clay-css/src/content/dropdowns_drill_down.html
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/atlas/_variables.scss
- packages/clay-css/src/scss/atlas/variables/_drilldown.scss
- packages/clay-css/src/scss/components/_drilldown.scss
- packages/clay-css/src/scss/variables/_drilldown.scss
https://issues.liferay.com/browse/LEXI-377
@matuzalemsteles I made a quick demo using Jquery on the Test Site. Let me know if the pattern doesn't make sense.
> Fixes #1386 ClayCSS adds new component Drilldown

- packages/clay-multi-select/src/ClayMultiSelect.js
To understand more why add this, see the comments in #1581, please leave your thoughts on this, I would love to hear other ideas.
>  Fixes #1581 - Compares the old value of selectedItems with the new value to set focus to the input

- package.json
- packages/clay-alert/src/ClayAlert.js
- packages/clay-alert/src/ClayAlertBase.js
- packages/clay-alert/src/ClayStripe.js
- packages/clay-alert/src/ClayToast.js
- packages/clay-autocomplete/src/ClayAutocomplete.js
- packages/clay-checkbox/src/ClayCheckbox.js
- packages/clay-dataset-display/src/ClayDatasetDisplay.js
- packages/clay-dropdown/src/ClayDropdownItem.js
- packages/clay-management-toolbar/src/ClayManagementToolbar.js
- packages/clay-multi-select/src/ClayMultiSelect.js
- packages/clay-radio/src/ClayRadio.js
- packages/clay-table/src/ClayTable.js
- packages/clay-tooltip/demos/index.html
- packages/clay-tooltip/src/ClayTooltip.js
As decided in https://docs.google.com/document/d/1uYT_r59q-GisQEHuRmucFCkzKnmILFY2vil8WgEtQhg/edit?ts=5c90adf1 :
> On touch interfaces tooltip have to appear on long press. The delay time for it is 500ms.
> Fixes #1672 | Adds support for TouchEvents on ClayTooltip

- packages/clay-css/src/content/test_toggle_switch_old.html
- packages/clay-css/src/content/toggle_switch.html
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_toggle-switch.scss
- packages/clay-css/src/scss/variables/_toggle-switch.scss
See https://github.com/liferay/clay/pull/1699
> Fixes #1689 ClayCSS 2.x Toggle Switch add option to use label for="id" markup

- packages/clay-css/src/content/form_elements_input_groups.html
- packages/clay-css/src/content/form_group.html
- packages/clay-css/src/content/test_form_group_sm.html
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/variables/_forms.scss
https://issues.liferay.com/browse/LEXI-482
The markup:
```
<div class="form-group form-group-sm">
<label></label>
<input>
</div>
```
or
```
<div class="form-group-autofit form-group-sm">
...
</div>
```
> Fixes #1669 ClayCSS 2.x added `.form-group-sm` for inputs definition of small size

- packages/clay-css/src/content/form_elements_input_groups.html
- packages/clay-css/src/content/form_group.html
- packages/clay-css/src/content/test_form_group_sm.html
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_input-groups.scss
- packages/clay-css/src/scss/variables/_forms.scss
https://issues.liferay.com/browse/LEXI-482
> Fixes #1669 ClayCSS added `.form-group-sm` for inputs definition of small size

- packages/clay-css/src/scss/atlas/variables/_application-bar.scss
- packages/clay-css/src/scss/atlas/variables/_management-bar.scss
- packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
- packages/clay-css/src/scss/components/_application-bar.scss
- packages/clay-css/src/scss/components/_management-bar.scss
- packages/clay-css/src/scss/components/_navigation-bar.scss
- packages/clay-css/src/scss/mixins/_navbar.scss
- packages/clay-css/src/scss/variables/_application-bar.scss
- packages/clay-css/src/scss/variables/_management-bar.scss
- packages/clay-css/src/scss/variables/_navigation-bar.scss
Input focus will be fixed by the input pull. Dropdown item focus will be fixed in the future.
> Fixes #1777 ClayCSS Atlas Application Bar, Management Bar, Navigation Bar Focus Styles

- packages/clay-css/src/scss/atlas/variables/_icons.scss
- packages/clay-css/src/scss/components/_icons.scss
- packages/clay-css/src/scss/variables/_icons.scss
Hey @pat270, @matuzalemsteles, @marcoscv-work, @eduardoallegrini, could any of you check this out?
> Fixes #1606 - Grays out inactive arrow

- migrate-the-clay-components-from-v2-to-v3.md
- packages/clay-list/README.md
- packages/clay-list/package.json
- packages/clay-list/src/Header.tsx
- packages/clay-list/src/Item.tsx
- packages/clay-list/src/ItemField.tsx
- packages/clay-list/src/ItemText.tsx
- packages/clay-list/src/ItemTitle.tsx
- packages/clay-list/src/QuickActionMenu.tsx
- packages/clay-list/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-list/src/__tests__/index.tsx
- packages/clay-list/src/index.tsx
- packages/clay-list/stories/index.tsx
- packages/clay-list/tsconfig.declarations.json
- packages/clay-list/tsconfig.json
So I created the generic building blocks for creating a clay list. I wasn't sure how specific we want the API. Should I create another component based on this one that implements the API for our [soy version](https://clayui.com/docs/components/list.html)?
> Fixes #1942 - Creates basic ClayList component

- CONTRIBUTING.md
Please check if there is a misspelling 😁
> docs(CONTRIBUTING): Add new Git Commit Messages rules and use of TypeScript

- next.clayui.com/content/docs/components/drop-down.mdx
- next.clayui.com/package.json
- next.clayui.com/src/components/clay/DropDown.js
- next.clayui.com/src/components/clay/Editor.js
- packages/clay-drop-down/src/Group.tsx
- packages/clay-drop-down/src/Item.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/src/Search.tsx
- packages/clay-drop-down/src/index.tsx
hey @bryceosterhaus, this documentation is very simple and contains only the minimum so people can start, I thought we'd just add this for now so we can increment later, since there will be a release tomorrow... but here, there's a lot space to add more information to show people where they can come with composition.
> docs(drop-down): add ClayDropDown component doc

- next.clayui.com/content/docs/css/components/alerts.md
- next.clayui.com/content/docs/css/components/buttons.md
- next.clayui.com/content/docs/css/components/forms/checkbox-radio.md
- next.clayui.com/content/docs/css/components/forms/form-group.md
- next.clayui.com/content/docs/css/components/forms/forms-hierarchy.md
- next.clayui.com/content/docs/css/components/forms/text-input-multi-select.md
- next.clayui.com/content/docs/css/components/links.md
- next.clayui.com/content/docs/css/components/tables.md
- next.clayui.com/content/docs/css/components/tabs.md
While @eduardoallegrini don't start working reviewing ARIA best practices on our documentation I think that is okay.
> docs(next.clayui.com): Adds references for WAI-ARIA best practices on CSS documentation

- clayui.com/content/docs/components/toolbars/management-toolbar.md
- packages/clay-css/src/content/management-bar.html
- packages/clay-css/src/scss/components/_management-bar.scss
https://issues.liferay.com/browse/LEXI-477
> ClayCSS 2.x Management Bar Navbar Text should break to new line

- packages/clay-css/src/content/form_elements_date_picker.html
- packages/clay-css/src/content/form_elements_time.html
- packages/clay-css/src/scss/_components.scss
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/atlas/_variables.scss
- packages/clay-css/src/scss/atlas/variables/_time.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/components/_time.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_time.scss
https://issues.liferay.com/browse/LEXI-481
> fix(clay css) #1424 Add Clay Time (Time Picker)

- packages/clay-table/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-table/src/index.tsx
> chore(table): Update snapshots

- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/index.tsx
- packages/clay-pagination/src/index.tsx
> fix(pagination): one page should only render one item

- .eslintrc.json
- packages/clay-alert/src/ToastContainer.tsx
- packages/clay-alert/stories/index.tsx
- packages/clay-color-picker/src/Basic.tsx
- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/src/util.ts
- packages/clay-drop-down/src/hooks.ts
- packages/clay-form/src/MultiSelect.tsx
- packages/clay-navigation-bar/src/index.tsx
- packages/clay-pagination/src/PaginationEllipsis.tsx
- packages/clay-pagination/src/index.tsx
- packages/clay-radio-group/src/index.tsx
As discussed here: https://github.com/liferay/clay/pull/2159#discussion_r300099627
> style(typescript): prevent `type[]` and use `Array<type>`

- packages/clay-autocomplete/src/Item.tsx
- packages/clay-form/package.json
- packages/clay-form/src/InputWithAutocomplete.tsx
- packages/clay-form/src/__tests__/InputWithAutocomplete.tsx
- packages/clay-form/src/index.tsx
- packages/clay-form/stories/index.tsx
- packages/clay-shared/src/useKeyHandlerForList.ts
Fix for https://github.com/liferay/clay/issues/2141
> feat(clay-form): create high-level InputWithAutocomplete component

- packages/clay-card/package.json
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/Description.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/src/index.tsx
- packages/clay-card/stories/index.tsx
- packages/clay-drop-down/src/DropDownWithBasicItems.tsx
Checking for tests to pass. original convo at https://github.com/liferay/clay/pull/2208
> feat(card): create CardWithInfo and CardWithHorizontal high-level components

- jest.config.js
- packages/clay-color-picker/package.json
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/src/util.ts
- packages/clay-pagination/src/ClayPaginationWithBar.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/index.tsx
- packages/clay-pagination/src/index.tsx
- packages/clay-pagination/stories/index.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/sub.ts
Hey folks, this is just a draft of a composed Pagination Bar component. Makes sense create another package `@clayui/pagination-bar` for hosting a high-level component more detailed or just leave the Pagination Bar as a composition of Pagination, Button and Dropdown?
> chore(pagination): Adds Pagination Bar story on pagination

- packages/clay-multi-step-nav/src/MultiStepNavWithBasicItems.tsx
> fix(@clayui/multi-step-nav): fixes wrong import of MultiStepNav that breaks this package

- packages/clay-button/src/ButtonWithIcon.tsx
> feat(@clayui/button): add forwardRef to ClayButtonWithIcon

- packages/clay-data-provider/package.json
- packages/clay-data-provider/src/LRUCache.ts
- packages/clay-data-provider/src/__tests__/LRUCache.ts
- packages/clay-data-provider/src/__tests__/index.tsx
- packages/clay-data-provider/src/types.ts
- packages/clay-data-provider/src/useCache.ts
- yarn.lock
>  fix(@clayui/data-provider): add LRUCache implementation

- .github/semantic.yml
Not sure if we already have the bot configured or not. I don't think I have the right settings to add it or see where its at.
> feat: add semantic PR bot

- packages/clay-list/src/ItemTitle.tsx
- packages/clay-list/src/List.tsx
- packages/clay-list/src/ListWithItems.tsx
- packages/clay-list/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-list/src/__tests__/index.tsx
- packages/clay-list/src/index.tsx
- packages/clay-list/stories/index.tsx
Sending this to get feedback if this is the right direction we want to take this component.
TODO:
> feat(list): create high-level ClayListWithItems component

- packages/clay-modal/src/Header.tsx
> chore(@clayui/modal): change header status icons

- packages/clay-management-toolbar/src/DefaultState.tsx
- packages/clay-management-toolbar/src/SearchForm.tsx
- packages/clay-management-toolbar/src/SearchInput.tsx
- packages/clay-management-toolbar/src/__tests__/BasicRendering.tsx
- packages/clay-management-toolbar/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-management-toolbar/stories/index.tsx
> feat(@clayui/management-toolbar): add callback to search button

- packages/clay-table/src/Cell.tsx
- packages/clay-table/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-table/stories/index.tsx
> chore(@clayui/table): Adds a text for testing truncating on storybook

- packages/clay-form/src/InputWithMultiSelect.tsx
Fixes: https://github.com/liferay/clay/issues/2371
> fix(multi-select): allow for event callbacks on input element

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/__tests__/index.tsx
- packages/clay-slider/package.json
- packages/clay-slider/src/index.tsx
- packages/clay-slider/stories/index.tsx
> chore: fix slider and only renders children of modal when visible

- .github/ISSUE_TEMPLATE/Bug.md
- .github/ISSUE_TEMPLATE/Proposal.md
- .github/ISSUE_TEMPLATE/Question.md
Inspired by https://github.com/liferay/liferay-frontend-guidelines/pull/82
> feat: add issue templated for github issues

- packages/clay-form/src/InputWithMultiSelect.tsx
- packages/clay-form/src/__tests__/InputWithMultiSelect.tsx
- packages/clay-form/src/__tests__/__snapshots__/InputWithMultiSelect.tsx.snap
- packages/clay-label/src/index.tsx
This implements changes (#2376) in focus behavior in MultiSelect.
> chore(@clayui/form): change the focus behavior of the labels to the close button

- next.clayui.com/content/docs/components/forms/css-text-input-multi-select.md
- next.clayui.com/content/docs/components/forms/multi-select.mdx
- next.clayui.com/src/components/clay/MultiSelect.js
- packages/clay-form/src/MultiSelectInput.tsx
@bryceosterhaus I realized that you got issue #2378 to work with, I don't know if you will add the documentation for this use case but I just started the MultiSelect documentation.
> chore(next.clayui.com): add MultiSelect docs

- packages/clay-sticker/stories/index.tsx
from https://github.com/liferay/clay/issues/2464#issuecomment-532613613
> chore(sticker): add alt attribute in stories

- next.clayui.com/src/components/clay/List.js
- packages/clay-list/stories/index.tsx
> chore: fixes QuickActionMenu misalignment

- packages/clay-navigation-bar/package.json
- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/index.tsx
> fix(@clayui/navigation-bar): replace ClayLink with ClayButton and add truncated text

- packages/clay-navigation/src/BreadcrumbEllipsis.tsx
> fix(@clayui/navigation): removes unnecessary use of FocusScope

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/types.ts
- packages/clay-modal/src/useModal.tsx
> fix(@clayui/modal): stop closing modal before animation

- packages/clay-tabs/stories/index.tsx
> fix(@clayui/tabs): add the relationship between tab and tabpane in stories

- packages/clay-navigation-bar/package.json
Just a detail that went unnoticed in #2525
> chore(@clayui/navigation-bar): remove unused dependency

- next.clayui.com/content/docs/components/date-picker.mdx
> chore(next.clayui.com): add a note about Date Picker not using mask

- packages/clay-slider/src/index.tsx
- packages/clay-slider/stories/index.tsx
> chore(@clayui/slider): add a relationship between label and slider

- packages/clay-color-picker/package.json
- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/index.tsx
> fix(@clayui/color-picker): add focus control

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/Description.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/stories/index.tsx
> feat(@clayui/card): add indeterminate and disabled state for high-level components

- packages/clay-panel/src/index.tsx
> chore(@clayui/panel): add docs to ClayPanel

- next.clayui.com/content/docs/components/modal.mdx
Fixes #2560
I didn't even add good practice descriptions to create tests with Modal. As I said here #2553. I'll take care of adding later as soon as I have more use cases.
> chore(next.clayui.com): add more docs on using Modal

- next.clayui.com/content/docs/components/drop-down.mdx
- next.clayui.com/src/components/clay/DropDown.js
> chore(next.clayui.com): add more documentation about DropDown

- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-form/src/Checkbox.tsx
- packages/clay-form/src/__tests__/__snapshots__/Checkbox.tsx.snap
- packages/clay-form/stories/index.tsx
Fixes #2573
I'm removing the trapped value that I was giving to Checkbox and letting people handle it. It's strange why we left the value fixed, I don't remember why.
> fix(@clayui/form): remove fixed value from Checkbox

- packages/clay-multi-select/stories/index.tsx
provides example for https://github.com/liferay/clay/issues/2378
> chore(multi-select): add story for new/removed items example

- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/index.tsx
> feat(@clayui/color-picker): add prop to put ColorPicker in disabled state

- packages/clay-color-picker/src/index.tsx
> feat(@clayui/color-picker): pass other props to Color Picker Input

- next.clayui.com/content/docs/migration/migrate-the-clay-components-from-v2-to-v3.md
- next.clayui.com/src/styles/_guide.scss
> docs(next.clayui.com): add more information and organize migrate guide

- packages/clay-drop-down/src/DropDownWithItems.tsx
> fix(@clayui/drop-down): add `alignmentPosition` support in DropDownWithItems

- clayui.com/content/authors.yml
- clayui.com/content/blog/2019-06-20-clay-v3-beta.md
- clayui.com/content/blog/2019-10-25-introducing-clay-v3.md
- clayui.com/src/pages/index.js
- clayui.com/src/styles/_blog.scss
- clayui.com/src/styles/_guide.scss
- clayui.com/src/templates/blog.js
#2653
Let me know if I forgot something to let people know, the idea is to give you an overview of what we did in Clay v3 and to present.
> chore(clayui.com): adding the post of "Introducing Clay v3"

- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/stories/index.tsx
Fixes: https://github.com/liferay/clay/issues/2640
@thektan can you verify this works as you would expect?  I added an additional nested element in the TooltipProvider story
> fix(tooltip): find closest node with title attribute

- packages/clay-shared/src/useFocusManagement.ts
> fix(@clayui/shared): collects focusable elements within a focusable element

- packages/clay-drop-down/src/DropDownWithItems.tsx
> fix(@clayui/drop-down): search for symbols in nested item structures

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/__tests__/index.tsx
> fix(@clayui/drop-down): hide DropDown when focus shifts out of element

- clayui.com/content/docs/components/charts.mdx
- clayui.com/content/docs/components/forms/css-slider.md
- clayui.com/content/docs/components/forms/form.mdx
- clayui.com/content/docs/components/forms/input.mdx
- clayui.com/content/docs/components/forms/multi-step-nav.mdx
- clayui.com/content/docs/components/forms/slider.mdx
- clayui.com/content/docs/components/popover.mdx
- clayui.com/content/docs/components/tooltip.mdx
- clayui.com/gatsby/onCreateNode.js
- clayui.com/src/components/clay/Slider.js
- clayui.com/src/templates/docs.js
- packages/clay-slider/src/index.tsx
> chore(clayui.com): add Slider doc

- clayui.com/content/docs/components/forms/multi-select.mdx
- clayui.com/src/components/clay/MultiSelect.js
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/index.tsx
Fixes #2685
See the Storybook with the use case, but this is a step to support the extension point, would still lack support to customize the content of Label, we still have to check what will be the best solution I will deal with in another PR.
> feat(@clayui/multi-select): adds support for DropDown.Menu content customization

- packages/clay-table/src/Body.tsx
- packages/clay-table/src/Cell.tsx
- packages/clay-table/src/Head.tsx
- packages/clay-table/src/Row.tsx
- packages/clay-table/src/index.tsx
fixes https://github.com/liferay/clay/issues/2669
> fix(table): add forwardRef to table components

- packages/clay-multi-select/src/index.tsx
> fix: prevent backspace from navigating backwards

- packages/clay-list/src/Item.tsx
- packages/clay-list/src/__tests__/__snapshots__/index.tsx.snap
fixes https://github.com/liferay/clay/issues/2550
> fix(list): add keyboard access to quick actions

- packages/clay-form/src/Form.tsx
- packages/clay-form/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-form/stories/index.tsx
fixes https://github.com/liferay/clay/pull/2762
> fix(form): add margin between icon and feedback message

- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/index.tsx
> fix(@clayui/multi-select): Extracting filter to a prop

- package.json
Going to keep this PR open to see how build time decreases with each change.
> chore(ci): only build src and not types for ci

- packages/clay-css/src/content/alerts.html
- packages/clay-css/src/scss/atlas/variables/_alerts.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/mixins/_utilities.scss
- packages/clay-css/src/scss/variables/_alerts.scss
> feat(clay-css): Only 3.x Alert with Action Button

- packages/clay-css/src/content/form_custom.html
- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/mixins/_grid.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
> feat(clay-css): New font-weight for Radio and Check Box

- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/mixins/_grid.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
> feat(clay-css): 2.x Custom Control backport relevant changes from #2828

- packages/clay-form/src/Select.tsx
- packages/clay-form/src/SelectWithOption.tsx
- packages/clay-form/stories/index.tsx
fixes https://github.com/liferay/clay/issues/2840
cc @diegonvs
> feat(select): add optgroups for select

- packages/clay-css/src/content/menu-bar-vertical-decorated.html
- packages/clay-css/src/scss/_mixins.scss
- packages/clay-css/src/scss/components/_menubar.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_menubar.scss
Just need to add the class `menubar-decorated` to `menubar`.
> feat(clay-css): Menubar added `.menubar-vertical-expand-md.menubar-decorated` and `.menubar-vertical-expand-lg.menubar-decorated`

- packages/clay-label/demos/index.html
- packages/clay-label/src/ClayLabel.js
- packages/clay-label/src/ClayLabel.soy
- packages/clay-label/src/__tests__/ClayLabel.js
- packages/clay-label/src/__tests__/__snapshots__/ClayLabel.js.snap
> feat(clay-label): Add support for truncating the label

- packages/clay-alert/src/Footer.tsx
- packages/clay-alert/src/__tests__/ClayAlert.tsx
- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/src/index.tsx
- packages/clay-alert/stories/index.tsx
- packages/clay-button/src/Button.tsx
> feat(alert): add ability to put a button within an alert

- packages/clay-dropdown/demos/index.html
- packages/clay-dropdown/src/ClayDropdownBase.js
- packages/clay-dropdown/src/ClayDropdownBase.soy
- packages/clay-dropdown/src/__tests__/ClayActionsDropdown.js
- packages/clay-dropdown/src/__tests__/ClayCreationMenuDropdown.js
- packages/clay-dropdown/src/__tests__/ClayDropdown.js
- packages/clay-dropdown/src/__tests__/ClayDropdownBase.js
> fix(clay-dropdown): renders new items values ​​when they change

- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/stories/index.tsx
fixes https://github.com/liferay/clay/issues/2855
> feat(tooltip): allow custom renderer for TooltipProvider content

- packages/clay-checkbox/src/ClayCheckbox.js
- packages/clay-checkbox/src/ClayCheckbox.soy
- packages/clay-checkbox/src/ClayCheckboxLabel.soy
- packages/clay-dropdown/demos/index.html
- packages/clay-isomorphic/fixtures/expected/ClayCheckboxLabel.render
- packages/clay-isomorphic/fixtures/expected/ClayRadioLabel.render
- packages/clay-isomorphic/fixtures/input/ClayCheckboxLabel.render
- packages/clay-isomorphic/fixtures/input/ClayRadioLabel.render
- packages/clay-radio/src/ClayRadio.js
- packages/clay-radio/src/ClayRadio.soy
- packages/clay-radio/src/ClayRadioLabel.soy
> fix: escape special characters in label

- clayui.com/src/styles/_sidebar.scss
> fix(clayui.com): Page navigation should be properly positioned in IE11

- clayui.com/plugins/gatsby-remark-api-table/index.js
- clayui.com/src/components/Sidebar/Navigation.js
- clayui.com/src/components/Sidebar/Sidebar.js
- clayui.com/src/styles/site/_site.scss
issue #2805
This prevents content under nav from scrolling. I'm not sure how to wrap the api table in `table-responsive`.
> fix(clayui.com): Adds overflow hidden on body when mobile nav is open

- packages/clay-modal/src/Body.tsx
- packages/clay-modal/stories/index.tsx
- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
> feat(modal): add prop for scrollable body

- packages/clay-list/src/Item.tsx
- packages/demos/package.json
- packages/demos/stories/DragDrop.tsx
- packages/demos/stories/index.tsx
- yarn.lock
I've made a drag and drop example here, but only a suggestion, a draft. 
It doesn't support reordering but only dragging between columns. 
I didn't manage to get Prettier to run on the `drag-drop.js` file so the formatting might be off.
The goal of this PR is to check if my approach is good, if the file structure I made is valid and to know of any groundbreaking mistakes before I proceed too far.
> feat(clay-css): Create drag and drop example

- packages/clay-css/src/content/test_card_view_template.html
- packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
- packages/clay-css/src/scss/atlas/variables/_navs.scss
- packages/clay-css/src/scss/components/_navbar.scss
> feat(clay-css): Navbars add support for `.nav-item .dropdown`

- packages/clay-data-provider/src/useResource.ts
> fix(@clayui/data-provider): fix warning message

- packages/clay-form/src/RadioGroup.tsx
- packages/clay-form/src/Toggle.tsx
- packages/clay-form/src/__tests__/Toggle.tsx
- packages/clay-form/src/__tests__/__snapshots__/Toggle.tsx.snap
- packages/clay-form/src/index.tsx
- packages/clay-form/stories/index.tsx
fixes #2893
Note, I still need to add and updates docs, just wanted to get approval on this API pattern before going with docs.
> feat(@clayui/form): create new toggle component

- packages/clay-css/src/content/cards.html
- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/components/_aspect-ratio.scss
- packages/clay-css/src/scss/components/_cards.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/variables/_cards.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
issue #2843 
The aspect ratio markup:
```
<div class="card">
<div class="aspect-ratio card-item-first">
<div class="aspect-ratio-item-top-left">
<span class="sticker sticker-danger">JPG</span>
</div>
<div class="aspect-ratio-item-top-right">
<button class="component-action" type="button">
<svg class="lexicon-icon lexicon-icon-heart-full" focusable="false" role="presentation">
<use xlink:href="{{rootPath}}/images/icons/icons.svg#heart-full"></use>
</svg>
</button>
</div>
<div class="aspect-ratio-item-bottom-right">
<button class="btn btn-secondary btn-sm" type="button">Secondary</button>
</div>
<div class="aspect-ratio-item-bottom-left">
<span class="label label-success">
<span class="label-item label-item-expand">Available</span>
</span>
</div>
</div>
<div class="card-body">
Card Body …
```
> feat(clay-css): Add Product Card

- clayui.com/src/pages/index.js
2019 is so two-thousand-and-late!
> fix: keep it phresh w/a dynamic copyright year

- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Search.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-drop-down/src/__tests__/index.tsx
- packages/clay-drop-down/stories/index.tsx
> feat(@clayui/drop-down): add ability to add attributes to form element

- clayui.com/src/pages/index.js
--> "Clay Team" to "Clay Contributors"
> fix(clayui.com): make the footer more accurate 

- CONTRIBUTING.md
- change `blob` from `develop` to `master`
> docs: update link to "contribution with CSS"

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/stories/index.tsx
> feat(@clayui/drop-down): add more options for alignment

- packages/clay-alert/src/__tests__/ClayAlert.tsx
- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/src/index.tsx
- packages/clay-alert/stories/index.tsx
> feat(@clayui/alert): add hideCloseIcon prop

- packages/clay-css/src/content/dropdowns.html
- packages/clay-css/src/content/typography_kbd.html
- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
- packages/clay-css/src/scss/components/_type.scss
- packages/clay-css/src/scss/mixins/_dropdown-menu.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_type.scss
> feat(clay-css): Adds c-kbd component for styling kbd element

- packages/clay-css/src/scss/components/_tables.scss
fix(clay-css): Table removes table-responsive hack related to border-collapse
https://issues.liferay.com/browse/LPS-95346
> fix(clay-css): Add border-spacing, border-collapse not working in IE

- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/Item.tsx
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/index.tsx
> fix(@clayui/pagination): add button type for pagination

- packages/clay-tabs/src/TabPane.tsx
- packages/clay-tabs/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-tabs/stories/index.tsx
> fix(@clayui/tabs): adjust class name timing so that it the tab properly fades in

- clayui.com/content/docs/css/playground.mdx
- clayui.com/gatsby/onCreateNode.js
- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/LayoutNav/Search.js
- clayui.com/src/components/Playground/index.js
- clayui.com/src/components/clay/Editor.js
- clayui.com/src/templates/docs.js
- clayui.com/src/utils/react-live-theme.js
fixes #2867
Demo: https://deploy-preview-2952--next-clayui.netlify.com/docs/css/playground.html
**Page:**
**Sidebar Location:**
> feat(clayui.com): add playground for css

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Section.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-drop-down/stories/index.tsx
> feat(@clayui/drop-down): adds section API support to drop-down items

- clayui.com/content/docs/components/upper-toolbar.mdx
- clayui.com/package.json
- clayui.com/src/components/clay/UpperToolbar.js
- packages/clay-upper-toolbar/.yarnrc
- packages/clay-upper-toolbar/README.md
- packages/clay-upper-toolbar/package.json
- packages/clay-upper-toolbar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-upper-toolbar/src/__tests__/index.tsx
- packages/clay-upper-toolbar/src/index.tsx
- packages/clay-upper-toolbar/stories/index.tsx
- packages/clay-upper-toolbar/tsconfig.declarations.json
- packages/clay-upper-toolbar/tsconfig.json
- packages/generator-clay-component/app/index.js
fixes #2895
~Simple draft of what low-level would look like.~  Am I missing anything else?
> feat(@clayui/upper-toolbar): Create basic components

- clayui.com/content/docs/components/alerts.mdx
- clayui.com/content/docs/components/forms/toggle-switch.mdx
- clayui.com/content/docs/components/tooltip.mdx
- clayui.com/src/components/clay/Alerts.js
- clayui.com/src/components/clay/Toggle.js
- clayui.com/src/components/clay/Tooltip.js
Went through and updated some of the docs on our site that were out of date.
> docs(clayui.com): update docs

- packages/clay-css/src/content/form_elements_range.html
- packages/clay-css/src/content/popovers.html
- packages/clay-css/src/content/utilities_c_focus_inset.html
- packages/clay-css/src/content/utilities_c_inner.html
- packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/atlas/variables/_range.scss
- packages/clay-css/src/scss/atlas/variables/_utilities.scss
- packages/clay-css/src/scss/components/_utilities.scss
- packages/clay-css/src/scss/variables/_bs4-variable-overwrites.scss
- packages/clay-css/src/scss/variables/_range.scss
- packages/clay-css/src/scss/variables/_utilities.scss
> feat(clay-css): Adds $component-focus-inset-box-shadow

- packages/clay-css/src/content/badges_and_labels.html
- packages/clay-css/src/scss/atlas/variables/_labels.scss
- packages/clay-css/src/scss/mixins/_labels.scss
- packages/clay-css/src/scss/variables/_labels.scss
> feat(@clayui/css): Labels add `label-inverse-*` variants

- scripts/check-size/convertBytes.js
forgot to update this https://github.com/liferay/clay/pull/2987
> chore: use all caps for constants

- packages/clay-breadcrumb/package.json
- packages/clay-breadcrumb/src/Item.tsx
- packages/clay-card/package.json
- packages/clay-card/src/Card.tsx
- packages/clay-card/src/Description.tsx
- packages/clay-drop-down/package.json
- packages/clay-drop-down/src/Item.tsx
- packages/clay-label/package.json
- packages/clay-label/src/index.tsx
- packages/clay-list/package.json
- packages/clay-list/src/ItemTitle.tsx
- packages/clay-list/src/QuickActionMenuItem.tsx
- packages/clay-list/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/package.json
- packages/clay-pagination/src/Item.tsx
> fix: use ClayLink over anchor tag

- packages/clay-tooltip/src/TooltipProvider.tsx
Update in regards to https://github.com/liferay/clay/pull/3007#issuecomment-598643306
> fix(@clayui/tooltip): remove polyfill in favor of ponyfill(ponyfill.com)

- packages/clay-css/src/images/icons/flags-sk-SK.svg
- packages/clay-css/src/scss/functions/_global-functions.scss
issue #2996
@bryceosterhaus @rolandpakai needs this for 7.2.x TS issue
> fix(clay-css): SVG Icons update the flag of Slovakia

- packages/clay-css/src/images/icons/flags-ms-MY.svg
- packages/clay-css/src/scss/functions/_global-functions.scss
> feat(clay-css): 2.x SVG Icons adds Malaysian flag

- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
> fix(@clayui/css): Atlas Custom Checkbox and Radio should be 16px x 16px

- README.md
> fix(README): update links

- packages/clay-multi-select/src/ClayMultiSelect.js
> fix(@clay-multi-select): Consistant HTMLescape in _addLabelItem

- packages/clay-date-picker/src/Helpers.ts
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/index.tsx
fixes #2972
previous PR https://github.com/liferay/clay/pull/3043
> feat(@clayui/date-picker): add helper for easily getting locale info from moment

- packages/clay-date-picker/src/DateNavigation.tsx
- packages/clay-date-picker/src/DayNumber.tsx
- packages/clay-date-picker/src/InputDate.tsx
- packages/clay-date-picker/src/Select.tsx
- packages/clay-date-picker/src/TimePicker.tsx
- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/index.tsx
> fix(@clayui/date-picker): adds the API to disable date picker features

- packages/clay-date-picker/src/InputDate.tsx
- packages/clay-date-picker/src/index.tsx
> feat(@clayui/date-picker): Add forwardRef support to Input and new onNavigation API

- packages/clay-label/src/index.tsx
- packages/clay-label/stories/index.tsx
> feat(@clayui/label): add prop for inner element attributes

- packages/clay-css/src/content/button_group.html
- packages/clay-css/src/scss/components/_button-groups.scss
> fix(@clayui/css): Button Group Vertical `.btn-monospaced` shouldn't shrink inside `autofit-col`

- clayui.com/content/docs/components/forms/css-dual-list-box.md
- clayui.com/content/docs/components/forms/css-select-box.md
- clayui.com/content/docs/components/forms/dual-list-box.mdx
- clayui.com/content/docs/components/forms/select-box.mdx
- clayui.com/src/components/clay/DualListBox.js
- clayui.com/src/components/clay/SelectBox.js
- packages/clay-form/src/DualListBox.tsx
- packages/clay-form/src/SelectBox.tsx
Update for https://github.com/liferay/clay/pull/3044
> chore(@clayui/form): add note about select functionality not working in react-live

- clayui.com/content/docs/components/css-alerts.md
Fixes [Alert Page Typo #3072](https://github.com/liferay/clay/issues/3072)
> chore(@clayui/alerts): Fix typo

- clayui.com/content/docs/components/forms/css-date-and-time-pickers.md
> fix(clayui.com): fix multiple dates being active

- packages/clay-css/src/scss/variables/_forms.scss
> fix(clay-css): 2.x Forms Base Theme Select element has no icon

- packages/clay-panel/src/Title.tsx
- packages/clay-panel/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/src/__tests__/index.tsx
- packages/clay-panel/src/index.tsx
- packages/clay-panel/stories/index.tsx
Hey @bryceosterhaus here's the PR that addresses #3123.
Not much to note, after some brainstorming with myself it was very simple due to the answers you gave to my questions. Unless I made it too simple in a way it doesn't do what we wanted it to do haha.
I can open an issue for adding documentation for this and work on that tomorrow, alongside something else.
> feat(@clayui/panel): Add ClayPanelTitle

- clayui.com/content/docs/components/css-labels.md
- clayui.com/content/docs/components/css-panel.md
- clayui.com/src/components/clay/Panel.js
- clayui.com/src/templates/docs.js
- packages/clay-panel/README.mdx
fixes #3135
Updated https://github.com/liferay/clay/pull/3136 and squashed changes
> docs(clayui.com): Documentation for the ClayPanelTitle component

- .codesandbox/ci.json
forgot to update this portion as well
> chore: update CSB dependencies

- packages/clay-css/gulpfile.js
- packages/clay-css/src/content/buttons.html
- packages/clay-css/src/scss/atlas/variables/_alerts.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_utilities.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/variables/_alerts.scss
- packages/clay-css/src/scss/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_links.scss
- packages/clay-css/src/scss/variables/_utilities.scss
- packages/clay-css/tasks/metalsmith.js
> fix(@clayui/css): Buttons, Close, and links using anchor tag should have cursor: not-allowed

- README.md
- clayui.com/content/blog/2019-10-25-introducing-clay-v3.md
- clayui.com/content/docs/contributing.md
- clayui.com/content/docs/contributing/how-to-contribute.mdx
- clayui.com/content/docs/contributing/index.md
- clayui.com/content/docs/contributing/versioning-policy.md
- clayui.com/content/docs/foundations/accessibility.md
- clayui.com/content/docs/foundations/index.md
- clayui.com/content/docs/foundations/principles.md
- clayui.com/content/docs/get-started/composing.md
- clayui.com/content/docs/get-started/how-to-use-clay.md
- clayui.com/content/docs/get-started/introduction.md
- clayui.com/content/docs/get-started/migrate-the-clay-components-from-v2-to-v3.md
- clayui.com/content/docs/get-started/web-components.md
- clayui.com/content/docs/migration/index.md
- clayui.com/content/docs/storybook.md
- clayui.com/gatsby/createPages.js
I noticed that our sidebar structure was a bit odd. I moved a few pages into the "Get Started", added links for contributing and storybook page, and I also removed pages that we weren't using.
> chore(clayui.com): restructure pages and structure

- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/src/index.tsx
- packages/clay-alert/stories/index.tsx
> fix(@clayui/alert): fix inaccurate padding

- clayui.com/content/docs/css/utilities/autofit.md
- packages/clay-css/src/content/utilities.html
- packages/clay-css/src/scss/mixins/_utilities.scss
> fix(@clayui/css): Mixin `clay-autofit-float` undeprecate `.autofit-col-end`

- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_cards.scss
- packages/clay-css/src/scss/variables/_tables.scss
- packages/clay-css/tasks/metalsmith.js
> fix(@clayui/css): Cards `card-interactive-primary` Chrome 81/83 hover transition artifact

- packages/clay-css/gulpfile.js
- packages/clay-css/src/scss/variables/_cards.scss
- packages/clay-css/tasks/metalsmith.js
> fix(clay-css): 2.x Cards `card-interactive-primary` Chrome 81/83 hover transition artifact

- packages/clay-form/TOGGLE_SWITCH.mdx
- packages/clay-pagination/README.mdx
- packages/clay-pagination/src/Ellipsis.tsx
- packages/clay-pagination/src/Item.tsx
- packages/clay-pagination/src/PaginationWithBasicItems.tsx
- packages/clay-popover/README.mdx
- packages/clay-progress-bar/README.mdx
- packages/clay-slider/README.mdx
- packages/clay-slider/docs/index.js
- packages/clay-tooltip/README.mdx
Addresses the second half of components listed #3210 
- Pagination
- Popover
- Progress Bar
- Slider
- Toggle
- Tooltip
Mostly changes in `mdx` files, but I've also modified an existing example and added a new example for Slider.
> feat(clayui.com): Improve component docs by updating content Pt.2

- clayui.com/content/docs/components/css-toolbar.md
Hey @bryceosterhaus @pat270 I think that both of you can take a look at this and let me know if I've included the examples I was supposed to, taking inspiration from [here](https://github.com/liferay/clay/issues/3219#issuecomment-627505325).
It was tricky sifting through some close-to-duplicate examples, but please do let me know if I missed something or included something that wasn't necessary.
> feat(clayui.com): Add Markup/CSS page for Toolbar component

- .github/workflows/main.yml
> fix: bad glob for diff

- .github/workflows/main.yml
> fix: bad diff args

- clayui.com/src/components/Editor/index.js
- packages/clay-alert/docs/index.js
- packages/clay-tabs/docs/index.js
update for https://github.com/liferay/clay/pull/3280
fixes #3279
> chore(clayui.com): refactor

- clayui.com/gatsby-config.js
- packages/clay-css/src/index.md
File was accidentally removed in https://github.com/liferay/clay/commit/fc6e798cb2556b1cb04f299deea6734e6f210acc
> fix(clay-css): re-add file that was accidentally deleted

- packages/clay-layout/src/ContainerFluid.tsx
- packages/clay-layout/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-layout/src/__tests__/index.tsx
> fix(@clayui/layout): add ability to disable fluid-max-* class

- packages/clay-toolbar/.yarnrc
- packages/clay-toolbar/README.md
- packages/clay-toolbar/package.json
- packages/clay-toolbar/src/Action.tsx
- packages/clay-toolbar/src/Item.tsx
- packages/clay-toolbar/src/Label.tsx
- packages/clay-toolbar/src/Link.tsx
- packages/clay-toolbar/src/Nav.tsx
- packages/clay-toolbar/src/Section.tsx
- packages/clay-toolbar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-toolbar/src/__tests__/index.tsx
- packages/clay-toolbar/src/index.tsx
- packages/clay-toolbar/stories/index.tsx
- packages/clay-toolbar/tsconfig.declarations.json
- packages/clay-toolbar/tsconfig.json
fixes #3300
follow up from https://github.com/liferay/clay/pull/3302
@kresimir-coko, check out the comments on my updates
> refactor(@clayui/toolbar): clean up logic

- packages/clay-link/src/__tests__/index.tsx
- packages/clay-link/src/index.tsx
> feat(@clayui/link): add default value for 'rel' if target exists

- packages/clay-layout/src/Col.tsx
- packages/clay-layout/src/Container.tsx
- packages/clay-layout/src/ContainerFluid.tsx
- packages/clay-layout/src/Content.tsx
- packages/clay-layout/src/Row.tsx
- packages/clay-layout/src/Sheet.tsx
- packages/clay-layout/stories/index.tsx
> feat(@clayui/layout): Add forwardRef to all exposed layout components

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_root.scss
> feat(@clayui/css): Absorb Bootstrap 4's _root.scss into Clay CSS

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_type.scss
> feat(@clayui/css): Absorb Bootstrap 4 _type.scss into Clay CSS

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_images.scss
> feat(@clayui/css): Absorb Bootstrap 4 _images.scss

- packages/clay-css/src/content/site-scss/_site.scss
- packages/clay-css/src/content/typography.html
- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_code.scss
- packages/clay-css/templates/includes/header.ejs
> feat(@clayui/css): Absorb Bootstrap 4 _code.scss

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
> feat(@clayui/css): Absorb Bootstrap 4 _tables.scss

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/components/_form-validation.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_forms.scss
> feat(@clayui/css): Absorb Bootstrap 4 _forms.scss into Clay CSS _forms.scss and _form-validation.scss

- packages/clay-css/src/content/buttons.html
- packages/clay-css/src/content/site-js/toggle_css.js
- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/templates/includes/footer.ejs
> feat(@clayui/css): Absorb Bootstrap 4 _buttons.scss into Clay CSS _buttons.scss

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_transitions.scss
> feat(@clayui/css): Absorb Bootstrap 4 _transitions.scss

- packages/clay-css/src/images/icons/special-character.svg
- packages/clay-css/src/scss/functions/_global-functions.scss
> feat(@clayui/css): SVG Icons adds `special-character`

- packages/clay-css/src/scss/_bs4.scss
- packages/clay-css/src/scss/components/_navs.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/variables/_navs.scss
> feat(@clayui/css): Absorb Bootstrap 4 _nav.scss into Clay CSS _nav.scss

- packages/clay-button/docs/index.js
Fixes #3444 
Nothing special of note here, except that I added multiple examples of Buttons to match all Display Types.
> feat(clayui.com): Add JSP code example to Button

- packages/clay-label/docs/index.js
Fixes #3454 
Apart from adding the JSP examples I also removed some excess new lines in code examples.
> feat(clayui.com): Add JSP code example to Label

- packages/clay-badge/docs/index.js
Fixes #3428 
Thing of note is that I made the JSP code examples match the several Badges in the React example.
> feat(clayui.com): Add JSP code example to Badge

- packages/clay-navigation-bar/docs/index.js
Fixes #3456 
This one is a bit different than the ones before it because it has some JSP specific syntax inside the example, apart from that I did some formatting in the fle too, as it was indented using spaces before.
> feat(clayui.com): Add JSP code example to Navigation Bar

- packages/clay-button/README.mdx
- packages/clay-button/docs/index.js
> docs(@clayui/button): add example for icon with text

- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination-bar/src/__tests__/index.tsx
> fix(@clayui/pagination-bar): automatically go to page 1 if active page exceeds delta

- CONTRIBUTING.md
fixes #3475
@wincent @jbalsas, let me know if you want this modified at all or if we should put it in a different location
> docs: add process for updating clay in liferay-portal

- packages/clay-sticker/docs/index.js
Fixes #3466 
Apart from adding the JSP example I've also done some SF and I removed one of the React examples as it wasn't being used.
> feat(clayui.com): Add JSP code example to Sticker

- packages/clay-css/src/js/svg4everybody.js
> fix(@clayui/css): Update svg4everybody to 2.1.9

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/variables/_bs4-variable-overwrites.scss
Fixes: https://github.com/liferay/clay/issues/3521
> feat(@clayui/css): Add new spacers

- packages/clay-css/src/scss/components/_reboot.scss
fixes #3533
@matuzalemsteles feel free to merge this
> fix(@clayui/css): Attribute `hidden` should hide elements

- packages/clay-modal/src/Hook.ts
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/stories/index.tsx
fixed merge conflict from https://github.com/liferay/clay/pull/3515
> chore(@clayui/modal): add new example to story with Autocomplete and DropDown

- packages/clay-css/src/content/dropdowns_drill_down.html
- packages/clay-css/src/scss/components/_drilldown.scss
- packages/clay-css/src/scss/components/_dropdowns.scss
- packages/clay-css/src/scss/variables/_drilldown.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
issue #3337 
@kresimir-coko You can view the markup and the pattern I used under Dropdowns Drilldown on the test site.
> feat(@clayui/css): Drilldown should work with Dropdown Menu, have dual click areas inside `dropdown-item`, and have `min-height`

- clayui.com/content/docs/components/css-color-picker.md
- packages/clay-color-picker/package.json
- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-css/src/scss/variables/_clay-color.scss
fixed merge conflict from https://github.com/liferay/clay/pull/3535
> chore(@clayui/color-picker): update snapshots

- packages/clay-button/src/ButtonWithIcon.tsx
- packages/clay-button/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-button/src/__tests__/index.tsx
- packages/clay-button/stories/index.tsx
> feat(@clayui/button): add prop for removing monospaced from button

- clayui.com/content/docs/components/css-slider.md
- packages/clay-css/src/content/form_elements_range.html
- packages/clay-css/src/scss/atlas/variables/_range.scss
- packages/clay-css/src/scss/components/_range.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_range.scss
> fix(@clayui/css): Clay Range hides `.clay-range-thumb` and styles thumb pseudo elements so input range will work without JS

- CONTRIBUTING.md
Helpful snippet about running tests first
> docs: update guide for updating liferay-portal

- package.json
- packages/clay-css/src/scss/components/_drilldown.scss
- packages/clay-drop-down/package.json
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/drilldown/Menu.tsx
- packages/clay-drop-down/src/drilldown/index.tsx
- packages/clay-drop-down/src/index.tsx
- packages/clay-drop-down/stories/index.tsx
- yarn.lock
Finally got the animations working for this. I had to make sure to add the transition class after applying the transform.
Anyways, here is a rough idea of an initial high-level component for drilldown. This would likely be for dropdown only right now. I think before we break this into smaller low-level components, we need an idea of where people will use this.
Do we have any sort of docs outlined for this? I wasn't able to find them. cc @jbalsas
> feat(@clayui/drilldown): high-level component

- packages/clay-drop-down/src/drilldown/Menu.tsx
- packages/clay-layout/src/Col.tsx
fixes #3561
Update from https://github.com/liferay/clay/pull/3589
> fix(@clayui/layout): add additional check

- packages/clay-color-picker/src/GradientSelector.tsx
- packages/clay-color-picker/src/Hue.tsx
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/hooks.ts
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_clay-color.scss
updated tests from https://github.com/liferay/clay/pull/3572
I tried a handful of ways to use "PointerEvent" but since its not fully supported by jsdom, I tried jsut updating the event names in the tests and it seems to work fine.
fixes #3540
> fix(@clayui/color-picker): update tests

- packages/clay-data-provider/src/useResource.ts
> fix(@clayui/data-provider): checks if the request body is read using request.bodyUsed

- clayui.com/gatsby-browser.js
- clayui.com/plugins/gatsby-plugin-meta-redirect/gatsby-node.js
- clayui.com/src/components/Editor/index.js
- clayui.com/src/components/Hooks/useStateWithLocalStorage.js
- clayui.com/src/components/Hooks/useStickyState.js
- clayui.com/src/components/LayoutNav/LayoutNav.js
Small updates for https://github.com/liferay/clay/pull/3523
Going to merge and if we need any other updates we can add as necessary, this won't be live un clayui.com till next release
> fix(@clayui.com): code collapse

- packages/clay-popover/src/index.tsx
> fix(@clayui/popover): focus on the body only when the scroll is enabled

- packages/clay-link/docs/index.js
> feat(@clayui/link): Add JSP code example

- packages/clay-progress-bar/docs/index.js
> feat(@clayui/progress-bar): Add JSP code example

- clayui.com/content/docs/css/index.md
- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/LayoutNavHome/index.js
- clayui.com/src/styles/_autocomplete.scss
@matuzalemsteles I added an explanation of Base and Atlas themes. I'd like to make it more clear, let me know whatever suggestions you have.
> docs(clayui.com): Add explanation about Base and Atlas

- clayui.com/content/docs/components/css-modals.md
- clayui.com/content/docs/components/css-tooltips.md
- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/LayoutNavHome/index.js
- clayui.com/src/pages/index.js
- clayui.com/src/styles/_code.scss
- clayui.com/src/styles/_guide.scss
- clayui.com/src/styles/_navbar.scss
- clayui.com/src/styles/site/_content-site.scss
- other css fixes that were annoying me
> docs(clayui.com): Adds modal-height-* docs and fix CSS Tooltip examples to have no whitespace

- packages/clay-css/src/scss/components/_utilities-functional-important.scss
> fix(@clayui/css): add font weight semibold

- packages/clay-multi-select/package.json
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
> feat(@clayui/multi-select): improves the filter for case-sensitive or non-sequential characters

- clayui.com/gatsby/createPages.js
- clayui.com/redirects.json
fixes #3691 
This adds functionality to maintain a list of redirect urls. This current list covers the broken links on lexicons site
> feat(clayui.com): add redirects.json file

- packages/clay-nav/src/Vertical.tsx
- packages/clay-nav/stories/index.tsx
> feat(@clayui/nav): Adds support for Decorator variation in ClayVerticalNav

- clayui.com/src/templates/docs.js
Fixes #3716
This is a little weird that it didn't break before or we didn't really notice.
> fix(clayui.com): fixes the error when trying to iterate through a NodeList

- docs/developing_components.md
Fixes #3705 
Let me know if I missed the mark with this, I think I covered everything as concise as I could.
> docs(clayui.com): Document how we develop components in Clay for viewing on GitHub

- packages/clay-drop-down/README.mdx
- packages/clay-drop-down/docs/api-dropdown.mdx
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
> chore(clayui.com): adds DropDownWithDrilldown component doc

- clayui.com/src/components/Typography/Typography.js
- packages/clay-layout/README.mdx
fixes #3715
Updates for https://github.com/liferay/clay/pull/3720
> docs(@clayui/layout): Add documentation for Layout

- packages/clay-nav/docs/index.js
> fix(@clayui/nav): fix documentation typo

- packages/clay-card/src/CardWithUser.tsx
> fix(@clayui/card): make alt attribute configurable

- packages/clay-card/src/Card.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
> fix(@clayui/card): stops adding unnecessary classes when the component is not selectable

- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-sticker/src/index.tsx
Fixes https://github.com/liferay/clay/issues/3773
> feat(@clayui/card): Add support for stickerProps

- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/stories/index.tsx
Fixes https://github.com/liferay/clay/issues/3799
> fix(@clayui/card): Remove support for labels in CardWithUser

- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
Fixes https://github.com/liferay/clay/issues/3812
Tag update required in portal
> fix: Do not render description if it's not passed. Make description optional in CardWithUser. Update tests and snapshots.

- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
Fixes https://github.com/liferay/clay/issues/3814
Do not require any tag update in portal, but https://issues.liferay.com/browse/LPS-123984 depends on this
> fix: flush and fluid should not be used together in CardWithInfo

- packages/clay-css/src/content/tables.html
- packages/clay-css/src/scss/atlas/variables/_tables.scss
- packages/clay-css/src/scss/components/_reboot.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
https://issues.liferay.com/browse/LPS-123682
fixes #3806
> fix(@clayui/css): Atlas Table caption color is not accessible

- packages/clay-form/src/Toggle.tsx
- packages/clay-form/src/__tests__/__snapshots__/Toggle.tsx.snap
fixes https://github.com/liferay/clay/issues/3838
> fix(@clayui/form): ClayToggle should use a label element instead of span

- packages/clay-multi-select/package.json
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/index.tsx
Fixes #3850 
I've tested this in Storybook and on DXP, it seemed to work fine from my light testing.
> feat(@clayui/multi-select): Use ClayButtonWithIcon instead of <button>

- packages/clay-multi-select/BREAKING.md
fixes #3867
Rather than address this right now, I think its safest to do this at the next major change.
> docs(@clayui/multi-select): Add note about renaming at next breaking change

- clayui.com/content/docs/components/markup-forms-hierarchy.md
- packages/clay-css/src/content/sheet.html
- packages/clay-css/src/scss/components/_buttons.scss
- packages/clay-css/src/scss/components/_sheets.scss
- packages/clay-css/src/scss/variables/_sheets.scss
Provides a pattern for vertically aligning small buttons inside sheet.
fixes #3866
> fix(@clayui/css): Component Title used in Sheet should work

- packages/clay-panel/src/index.tsx
- packages/clay-panel/stories/index.tsx
> fix(@clayui/panel): allow for the panel to be expanded on first render

- packages/clay-shared/src/setElementFullHeight.ts
- packages/clay-shared/src/useInternalState.ts
updates from comments on https://github.com/liferay/clay/pull/3760
> chore(@clayui/shared): simplify function and naming

- packages/clay-button/src/Button.tsx
- packages/clay-color-picker/package.json
- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-list/src/ListWithItems.tsx
- packages/clay-multi-step-nav/src/Indicator.tsx
- packages/clay-multi-step-nav/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/package.json
- packages/clay-panel/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-panel/src/index.tsx
> fix(@clayui/panel): make sure <button> has a type

- packages/clay-button/src/Group.tsx
- packages/clay-button/stories/index.tsx
> feat(@clayui/button): add api for stacking button group vertically

- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-drop-down/stories/index.tsx
- packages/clay-shared/src/useInternalState.ts
> feat(@clayui/drop-down): add api for controlling the active state of the menu

- CONTRIBUTING.md
I think it's much easier to read and follow when its all in a code block like this. 
I also removed the portion about clay-css variables since we removed those files from portal at https://github.com/liferay-frontend/liferay-portal/pull/736/commits/88c9b8db74fbb49d6677bb1f38f000354dd95134
> chore: clean up release process docs

- packages/clay-date-picker/src/Hooks.ts
- packages/clay-date-picker/src/__tests__/IncrementalInteractions.tsx
- packages/clay-date-picker/src/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-date-picker/src/__tests__/__snapshots__/Internationalization.tsx.snap
- packages/clay-date-picker/src/index.tsx
- packages/clay-time-picker/src/index.tsx
> fix(@clayui/date-picker): update timepicker format

- packages/clay-css/src/scss/atlas/variables/_alerts.scss
> fix(@clayui/css): Atlas Alert close font-size should be 16px

- packages/clay-css/src/scss/atlas/variables/_clay-color.scss
> fix(@clayui/css): Atlas Clay Color change close button icon to be 16px

- packages/clay-color-picker/src/Basic.tsx
- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/Splotch.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/index.tsx
- packages/clay-css/src/scss/variables/_clay-color.scss
- packages/clay-date-picker/src/index.tsx
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-panel/src/index.tsx
- packages/clay-shared/src/index.tsx
- packages/clay-shared/src/useInternalState.ts
fixes #3910 
@pat270 can you verify some of these css changes I made? I noticed the styling was wonky when we added both palettes to the drop down. I took the specs from https://docs.google.com/document/d/1IUGl5VOWh6lqRa1baRoshVcytc8XbqVMkk30vRW4SM8/edit#heading=h.7dwfrx5xjmtw
> feat(@clayui/color-picker): update color-picker API to allow for both color palettes

- packages/clay-panel/src/index.tsx
> feat(@clayui/panel): add 'show' class to collapsable panel's button

- packages/clay-card/src/Card.tsx
- packages/clay-card/src/CardHorizontal.tsx
- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/index.tsx
- packages/clay-card/stories/index.tsx
fixes #3932
@marcoscv-work can you verify this is what you would expect?
> feat(@clayui/card): add active state for card when it is selected

- lerna.json
fixes #3939
Putting in draft just to get some eyes on this first before going with it
> chore: update lerna mode to use fixed instead of independent

- CONTRIBUTING.md
Just adding some more details for release process
> chore: update release docs

- CONTRIBUTING.md
fixes #3948
Updated docs so that we release all 2.x packages under the same version at the same time
> chore: update release docs for 2.x

- packages/clay-charts/src/BillboardWrapper.tsx
- packages/clay-color-picker/src/GradientSelector.tsx
- packages/clay-color-picker/src/Hue.tsx
- packages/clay-drop-down/src/Menu.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-slider/src/index.tsx
fixes #3956
Thought it was overkill to add a helper in "shared" for this, so I just added it to each package individually.
> fix: use isomorphic helpers for useLayoutEffect

- packages/clay-alert/docs/markup-alert.md
- packages/clay-css/src/content/alerts.html
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/variables/_alerts.scss
@matuzalemsteles all we need to do is add a new variant `feedback` that uses the class `alert-feedback`.
issue #3968
> feat(@clayui/css): Alerts adds `alert-feedback` modifier

- packages/clay-alert/docs/index.js
- packages/clay-alert/src/__tests__/ClayAlert.tsx
- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/src/index.tsx
- packages/clay-alert/stories/index.tsx
Fixes #4015
This PR was made on top of @pat270's PR (#4014), once it is merged I will rebase and go ahead. I'm still not sure if that would be the ideal name but going ahead with `feedback`.
> feat(@clayui/alert): Adds the new feedback variant

- CONTRIBUTING.md
I took some of the recommendations from this Slack thread, https://liferay.slack.com/archives/C3JBR21HA/p1616066596085500
Let me know if I can make it more clear or add anything else
> chore: fill in gaps for release process

- packages/clay-multi-select/package.json
- packages/clay-multi-select/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-multi-select/src/__tests__/index.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-multi-select/stories/index.tsx
- packages/clay-shared/src/index.tsx
fixes https://github.com/liferay/clay/issues/4017
@FabioDiegoMastrorilli can you verify the "async" example in the storybook and see if thats what you would expect?
> feat(@clayui/multi-select): add async functionality for source items

- packages/clay-card/docs/markup-card.md
> docs(clayui.com): Document card-page

- packages/clay-css/src/scss/atlas/variables/_toggle-switch.scss
> fix(@clayui/css): Atlas Toggle Switch should be 48px wide

- .github/ISSUE_TEMPLATE/Icon.md
Create new GitHub issue template to request new icons
> chore(gh): Add GH issue template for new icons

- packages/clay-drop-down/docs/api-dropdown.mdx
> docs(@clayui/drop-down): Add information about ClayDropDown.Section

- packages/clay-css/src/scss/atlas/variables/_tables.scss
> chore(@clayui/clay-css): Remove unused variable

- packages/clay-drop-down/README.mdx
> docs(@clayui/drop-down): Add a note about DropDownWithDrillDown menus

- packages/clay-nav/src/Vertical.tsx
Hi everyone, I opened 2 Issues
https://github.com/liferay/clay/issues/4120
https://github.com/liferay/clay/issues/4121
Fixing and Improving some warnings from @clayui/nav
Feel free to suggest changes, thanks!
> fix(@clayui/nav): Adjust condition, to avoid set Boolean values in className property

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-toolbar/src/Action.tsx
fixes https://github.com/liferay/clay/issues/4139
saw the issue and was an easy fix so thought I would send over
> fix(@clayui/toolbar): spritemap should be optional

- package.json
- packages/clay-color-picker/package.json
- yarn.lock
> chore(@clayui/color-picker): upgrade tinycolor2 to 1.4.2

- packages/clay-css/src/content/nav_tabs.html
- packages/clay-css/src/content/nav_underline.html
- packages/clay-css/src/content/sidebar.html
- packages/clay-css/src/content/slideout.html
- packages/clay-css/src/content/test_card_view_template.html
- packages/clay-css/src/content/test_card_view_template_info_panel.html
- packages/clay-css/src/content/test_list_view_template.html
- packages/clay-css/src/content/test_list_view_template_info_panel.html
- packages/clay-css/src/content/test_table_view_template.html
- packages/clay-css/src/content/test_table_view_template_info_panel.html
- packages/clay-tabs/docs/markup-tabs.md
> docs(clayui.com): Tabs changes/adds missing attributes `aria-selected` for tab links

- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/cadmin/components/_utilities.scss
- packages/clay-css/src/scss/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/components/_utilities.scss
> fix(@clayui/css): Utilities remove duplicate rounded utilities

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/variables/_buttons.scss
fixes #4176
I still need to document our mixins and functions. I'd like to use Sassdoc but haven't found a way to convert it to clayui.com. I can document directly in the source using comments which is nice for someone combing through the code. We should probably discuss this in a separate issue.
> feat(@clayui/css): Buttons use nested property names in variables to stay as close as possible to the way our CSS is written

- packages/clay-css/src/scss/components/_grid.scss
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/variables/_sheets.scss
> fix(@clayui/css): $container-max-widths Sass map should accept CSS Custom Properties

- packages/clay-css/src/scss/cadmin.scss
- packages/clay-css/src/scss/cadmin/_variables.scss
- packages/clay-css/src/scss/cadmin/components/_timelines.scss
- packages/clay-css/src/scss/cadmin/variables/_timelines.scss
- packages/clay-css/src/scss/components/_timelines.scss
- packages/clay-css/src/scss/mixins/_timelines.scss
> fix(@clayui/css): Cadmin adds Timelines component, used in Asset Publisher Configuration Modals

- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/atlas/variables/_timelines.scss
- packages/clay-css/src/scss/cadmin/components/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_custom-forms.scss
- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_custom-forms.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_forms.scss
> fix(@clayui/css): Removes unused variables

- CONTRIBUTING.md
> docs(contributing): add notes about testing local changes

- CONTRIBUTING.md
> docs(contributing): add information about `yarn checkDeps`

- packages/clay-form/src/SelectWithOption.tsx
> chore(@clayui/form): add missing key prop to `OptGroup`

- clayui.com/content/blog/2021-09-13-clay0-css-cadmin.md
> docs(clayui.com): Add blog post about cadmin

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/variables/_globals.scss
Decided not to define every variable in Atlas due to https://github.com/liferay/clay/issues/4195#issuecomment-897202074. This only defines all globals in Atlas to minimize the `Undefined variable` error due to missing global variables.
fixes #4195
> fix(@clayui/css): Atlas Global Variables define all global variables for easier copy and paste for those extending Clay CSS

- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/src/scss/variables/_carousel.scss
- packages/clay-css/src/scss/variables/_custom-forms.scss
- packages/clay-css/src/scss/variables/_globals.scss
> fix(@clayui/css): Global Variables deprecate unused Bootstrap 4 variables

- clayui.com/content/authors.json
> fix(clayui.com): add missing authors

- CONTRIBUTING.md
@matuzalemsteles sending this to avoid future errors 
during a release.
> docs(release): add a note about `lerna version`

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/src/tree-view/useItem.tsx
- packages/clay-core/stories/TreeView.stories.tsx
> feat(@clayui/core): make it possible to enable or disable drag and drop

- clayui.com/content/docs/components/markup-treeview.md
- packages/clay-core/docs/api-treeview.mdx
- packages/clay-core/docs/treeview.js
- packages/clay-core/docs/treeview.mdx
- packages/clay-core/src/index.ts
- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewGroup.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/useTree.ts
This PR adds the documentation of the TreeView component, still missing add information on how to add Actions, depending on the final implementation #4421.
I'm also exposing the TreeView component in the `@clayui/core` package but under the UNSAFE flag for now.
> chore(@clayui/core): adds TreeView documentation

- packages/clay-core/package.json
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/stories/TreeView.stories.tsx
> feat(@clayui/core): add a loading indicator to the TreeView

- packages/clay-css/src/scss/_mixins.scss
- packages/clay-css/src/scss/cadmin/components/_tooltip.scss
- packages/clay-css/src/scss/cadmin/variables/_tooltip.scss
- packages/clay-css/src/scss/components/_tooltip.scss
- packages/clay-css/src/scss/mixins/_tooltip.scss
- packages/clay-css/src/scss/variables/_tooltip.scss
> feat(@clayui/css): Tooltip generate styles using `clay-tooltip-variant` mixin

- clayui.com/gatsby-config.js
- clayui.com/package.json
- yarn.lock
Fixes #4494
Well, I also changed the plugin to use the new GA client which is gtag which is now recommended by Google.
> fix(clayui.com): updates Google Analytics ID

- packages/clay-css/src/scss/atlas/variables/_navs.scss
- packages/clay-css/src/scss/cadmin/components/_navs.scss
- packages/clay-css/src/scss/cadmin/variables/_navs.scss
- packages/clay-css/src/scss/components/_navs.scss
- packages/clay-css/src/scss/mixins/_nav.scss
- packages/clay-css/src/scss/variables/_navs.scss
> feat(@clayui/css): Navs convert to Clay mixin pattern

- packages/clay-navigation-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-navigation-bar/src/__tests__/index.tsx
- packages/clay-navigation-bar/src/index.tsx
- packages/clay-navigation-bar/stories/index.tsx
> fix(@clayui/navigation-bar): fix error when rendering only one Item

- packages/clay-core/src/tree-view/TreeViewItem.tsx
Since we can't use async/await in DXP, we should also avoid using it in
our components
Fixes #4529
Depends on #4531
> fix(@clayui/core): avoid async/await in TreeViewItem

- packages/clay-popover/src/index.tsx
- packages/clay-popover/stories/index.tsx
This will allow closing the popover when clicking outside
of it.
Fixes #4536
> feat(@clayui/popover): add a closeOnClickOutside prop

- packages/clay-css/src/scss/components/_cards.scss
- packages/clay-css/src/scss/mixins/_cards.scss
- packages/clay-css/src/scss/mixins/_custom-forms.scss
- packages/clay-css/src/scss/variables/_cards.scss
fixes #4545
This one will probably conflict with #4546 depending on which gets merged first. I can add the changes from #4546 to this one if it's easier.
> feat(@clayui/css): Cards converts `.form-check-card` to Clay mixin pattern

- packages/clay-form/docs/markup-select.md
- packages/clay-form/docs/markup-text-input.md
> docs(clayui.com): Select adds more detailed docs and examples

- packages/clay-drop-down/docs/markup-dropdown.md
> docs(clayui.com): Drop Down adds autofit docs

- packages/clay-popover/src/index.tsx
> feat(@clayui/popover): close the popover when the ESC key is pressed

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/stories/TreeView.stories.tsx
> fix(@clayui/core): add a default value to nestedKey

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/stories/TreeView.stories.tsx
> fix(@clayui/core): hide expander icon on nodes that don't have chidren

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/stories/TreeView.stories.tsx
> feat(@clayui/core): allow passing extra css classes to expander button

- packages/clay-core/stories/TreeView.stories.tsx
@zhangyan0701 had [doubts](https://docs.google.com/spreadsheets/d/1gPuEUpPkzpAz5Lm7k2rOLETcoC-c7ix_o2cKR28Qjpc/edit#gid=855876666) about this so I thought adding an example
would be a good idea.
> chore(@clayui/core): add a story for onLoadMore error handling

- packages/clay-core/src/tree-view/TreeView.tsx
- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/context.ts
- packages/clay-core/stories/TreeView.stories.tsx
@matuzalemsteles as requested [here](https://github.com/liferay/clay/pull/4590#discussion_r791243990)
> chore(@clayui/core): rename expanderButtonClasses to expanderClassName

- packages/clay-link/src/index.tsx
Adding a clearer API. Discussed in https://liferay.slack.com/archives/C3JBR21HA/p1643723253270239
> feat: add plain/common API for button links

- packages/clay-shared/src/FocusScope.tsx
Fixes #4613
There are some cases where FocusScope is declared more than once nested, for example, TimePicker uses FocusScope to manage focus with left and right keys and the component is declared in DatePicker which also has a FocusScope declared.
There is a conflict of who is managing an element aria between the two FocusScopes declared nested and each one can have a configuration, to avoid having conflict between the focus managers, we use the context to know if there is a focus manager parent and we avoid propagation of the event.
> fix(@clayui/shared): fix focus control collision when having FocusScope nested

- clayui.com/content/docs/components/markup-aspect-ratio.md
- packages/clay-css/src/scss/_variables.scss
- packages/clay-css/src/scss/cadmin/_variables.scss
- packages/clay-css/src/scss/cadmin/components/_aspect-ratio.scss
- packages/clay-css/src/scss/cadmin/variables/_aspect-ratio.scss
- packages/clay-css/src/scss/components/_aspect-ratio.scss
- packages/clay-css/src/scss/variables/_aspect-ratio.scss
- Also adds 8-to-3 in Cadmin
- Adds `aspect-ratio` docs to clayui.com
fixes #4620
> feat(@clayui/css): Aspect Ratio adds `aspect-ratio-8-to-3` (37.5%)

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/mixins/_buttons.scss
- packages/clay-css/src/scss/variables/_buttons.scss
> fix(@clayui/css): Atlas Buttons `btn-sm` icons should be 16px

- packages/clay-multi-select/src/index.tsx
> fix(@clayui/multi-select): fix error when adding labels with whitespace

- package.json
- packages/clay-css/src/scss/cadmin/components/_empty-state.scss
- packages/clay-css/src/scss/cadmin/variables/_empty-state.scss
- packages/clay-css/src/scss/components/_empty-state.scss
- packages/clay-css/src/scss/variables/_empty-state.scss
- packages/clay-empty-state/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-empty-state/src/index.tsx
- packages/clay-empty-state/stories/index.tsx
**What is new?**
New feature in clayui/empty-state, `small` property is included in this component.
https://user-images.githubusercontent.com/44723449/153244299-eef1558b-1d40-4804-b462-190904464f9f.mov
**Fixes**
#4641
> feat(@clayui/empty-state): Include Small property in empty state component

- packages/clay-core/src/tree-view/useMultipleSelection.tsx
Fixes #4680
Well, the fix is simple but the explanation is contained in the issue.
> fix(@clayui/core): fix error when not updating parent's loc

- packages/clay-core/src/tree-view/useMultipleSelection.tsx
I took into account Julien's comment in PR #4681, so I'm adding more comments and explaining in more detail how the `useMultipleSelection` hook works in the code. I hope this can help to better understand the strategies and data structures used and the reasons, this should also help other people who are interested in understanding the code to contribute. Let's keep refining!
> chore(@clayui/core): adds comments about how multiple selection works in TreeView

- packages/clay-breadcrumb/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/__tests__/DropDownWithDrilldown.tsx
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithDrilldown.tsx.snap
- packages/clay-drop-down/src/__tests__/__snapshots__/DropDownWithItems.tsx.snap
- packages/clay-drop-down/src/__tests__/index.tsx
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-pagination/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-upper-toolbar/src/__tests__/__snapshots__/index.tsx.snap
Related issue: https://github.com/liferay/clay/issues/4708
> feat(@clayui/drop-down): Render Menu only after trigger is clicked the first time

- packages/clay-css/src/scss/atlas/variables/_type.scss
> fix(@clayui/css): Atlas remove extra `$code-color` variable

- packages/clay-css/src/scss/cadmin/components/_breadcrumbs.scss
- packages/clay-css/src/scss/cadmin/variables/_breadcrumbs.scss
- packages/clay-css/src/scss/components/_breadcrumbs.scss
- packages/clay-css/src/scss/variables/_breadcrumbs.scss
> fix(@clayui/css): Breadcrumbs convert to Clay mixin pattern

- packages/clay-css/src/scss/atlas/variables/_multi-step-nav.scss
Fixes https://github.com/liferay/clay/issues/4859
> fix(@clayui/multi-step-nav): fix color of steps according to lexicon

- packages/clay-css/src/images/icons/flags-ca-ES-VALENCIA.svg
- packages/clay-css/src/scss/functions/_global-functions.scss
- packages/clay-css/tasks/lib/metalsmith/flag_data.json
> fix(clay-css): Adds Valencian flag (ca-ES-VALENCIA)

- packages/clay-css/src/scss/atlas/variables/_tables.scss
- packages/clay-css/src/scss/cadmin/components/_tables.scss
- packages/clay-css/src/scss/cadmin/variables/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
- packages/clay-css/src/scss/mixins/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
Sorry this is another big one. 
fixes #4858
> fix(@clayui/css): Convert Tables to Clay mixin pattern

- jest.config.js
I added some more use cases in the TreeView and it changed the jest limit, we don't need to add tests to cover these cases and that's ok but I need to update the threshold here.
> chore: update branch threshold for TreeView

- CONTRIBUTING.md
> docs(CONTRIBUTING): adds information about the automated release process

- packages/clay-alert/src/__tests__/ClayAlert.tsx
- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/stories/Alert.stories.tsx
Closes #4907
I'm just adding a test case that makes sense to test via unit test and some other examples in the storybook that we can test with visual regression testing with chromatic.
> chore(@clayui/alert): adds new test cases for alert and examples in storybook

- src/fonts/alloy-font-awesome/scss/_icons-alloy.scss
- https://issues.liferay.com/browse/LPS-147457
- use fixed versions for dependencies
related to https://github.com/liferay/clay/pull/4688
issue https://github.com/liferay/clay/issues/4683
I have sent a change also on alloy-font-awesome: https://github.com/liferay/liferay-frontend-projects/pull/951
But not sure if we use generated files here, or we get them with some dependency I could not find.
> fix(lexicon-ux): 1.x Updates content property values to conform to what is allowed by OAW Tracker

- packages/clay-autocomplete/src/DropDown.tsx
Issue: https://github.com/liferay/clay/issues/4931
> feat(@clayui/autocomplete): Support menu alignment by Viewport

- packages/clay-css/src/scss/cadmin/components/_grid.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/components/_grid.scss
- packages/clay-css/src/scss/variables/_globals.scss
> fix(@clayui/css): Grid compare the breakpoint positions instead of the `$container-max-widths` values

- clayui.com/content/docs/css/utilities/markup-accessibility.md
- clayui.com/content/docs/css/utilities/markup-borders.md
- clayui.com/content/docs/css/utilities/markup-color-utilities.md
- clayui.com/content/docs/css/utilities/markup-display.md
- clayui.com/content/docs/css/utilities/markup-flex.md
- clayui.com/content/docs/css/utilities/markup-float.md
- clayui.com/content/docs/css/utilities/markup-overflow.md
- clayui.com/content/docs/css/utilities/markup-position.md
- clayui.com/content/docs/css/utilities/markup-shadow.md
- clayui.com/content/docs/css/utilities/markup-text.md
- clayui.com/content/docs/css/utilities/markup-vertical-align.md
- clayui.com/content/docs/css/utilities/markup-visibility.md
- clayui.com/content/docs/css/utilities/markup-width-and-height.md
> docs(clayui.com): Document CSS utilities

- packages/clay-css/src/scss/cadmin/components/_utilities.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/components/_utilities.scss
- packages/clay-css/src/scss/variables/_utilities.scss
> fix(@clayui/css): Utilities update inline-scroller focus ring

- clayui.com/src/components/CodeClipboard/CodeClipboard.js
> fix(clayui.com): fix clipboard error in examples

- packages/clay-css/src/scss/atlas/variables/_alerts.scss
- packages/clay-css/src/scss/cadmin/components/_alerts.scss
- packages/clay-css/src/scss/cadmin/variables/_alerts.scss
- packages/clay-css/src/scss/components/_alerts.scss
- packages/clay-css/src/scss/variables/_alerts.scss
> fix(@clayui/css): Alert Indicator SF and adjust alignment in base theme

- packages/clay-tooltip/src/TooltipProvider.tsx
Fixes #4976
I just made some small changes so that we can listen for out and over events of the tooltip when the TooltipProdiver is used in the React.js scope, so we can identify if the mouse is over the tooltip or has left it so we can control the visibility of the tooltip.
> fix(@clayui/tooltip): adds the possibility to hover over the tooltip

- docs/proposals/0000-collection-components.md
Closes #4112
This PR is an early draft for the Collection RFC, I still have a lot to write and detail on the implementation design as well as the functionality, alternatives considered and how it affects the implementation, and how we can get to implement this still in v3 or v4.
I worked on a sketch with a diagram to demonstrate some ideas about the design of this internal component, so this helps provide a little more context.
> Better reading when expanding the image
I wanted to send this earlier to get some ideas on this as I develop my thinking on this so by the end of this week a lot here could change.
> docs(RFC): RFC 0004 Collection component

- packages/clay-core/docs/treeview.mdx
> docs(@clayui/core): fix error in TreeView documentation and add more details about creating a nested item

- packages/clay-drop-down/src/Item.tsx
> feat(@clayui/drop-down): add new `roleItem` property to set item role

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_modals.scss
- packages/clay-css/src/scss/cadmin/variables/_popovers.scss
- packages/clay-css/src/scss/variables/_forms.scss
- packages/clay-css/src/scss/variables/_modals.scss
- packages/clay-css/src/scss/variables/_popovers.scss
> fix(@clayui/css): Use calc() instead of Sass math so we can handle mixed units better

- docs/proposals/0004-collection-components.md
Fixes #5031
I did a review of the integration session with ErrorBoundary, I had stated that we could catch errors in scenarios that I called a localized error, that is, a network error occurs in an asynchronous call when calling `loadMore` for example, this is not possible because ErrorBoundary just catches errors in render time instead of error from a handler for example because it doesn't affect application execution or crash. I just added a few notes on what scenarios we can cover for and recommendations for a list and tree.
> docs(RFC): RFC 0004 review of ErrorBoundary integration with Collection

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/atlas/variables/_custom-forms.scss
- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/atlas/variables/_utilities.scss
- packages/clay-css/src/scss/cadmin/variables/_menubar.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_menubar.scss
> fix(@clayui/css): Mixins `clay-css` should accept `c-unset` as a value to reset a property

- packages/clay-data-provider/src/useResource.tsx
Fixes #5056
This only fixes the case for the first request, it doesn't sync requests made by another instance in the component's life stream, for example when doing the refetch only the instance that made it is updated the others with the same endpoint are not and also for `loadMore `.
But if another instance does the refetch or `loadMore` and has the cache policy it will not make a new request when the cache policy is `cache-first`.
There isn't a real need for this yet, so it's not intentional for the DataProvider to magically do this behind the scenes, since we have a need for this we can plan for this feature in the future.
> fix(@clayui/data-provider): fixes error of not retrieving initial cache value when there are multiple instances for the same endpoint

- packages/clay-data-provider/src/useResource.tsx
- packages/clay-provider/src/Provider.tsx
- packages/clay-provider/src/index.ts
> feat(@clayui/data-provider): instantiates the DataClient locally if the Provider is not declared

- packages/clay-shared/src/__tests__/FocusScope.tsx
> chore(@clayui/shared): adds test to cover the use case of moving focus when there is an element in "progress"

- clayui.com/src/components/LayoutNav/Search.js
Fixing: https://github.com/liferay/clay/issues/5078
Feel free to change the react part.
> feat(clayui.com): Add JS key shortcut for linux and windows

- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/LayoutNav/Search.js
- clayui.com/src/templates/docs.js
https://github.com/liferay/clay/issues/5078
The last one! 😇
- Improving compatibility keyboard for some cases on firefox/windows by adding preventDefault.
- Adding better legibility of `aria-keyshortcuts` when are listed
> feat(clayui.com): Add aria changes and improve compatibility

- packages/clay-button/BREAKING.md
- packages/clay-button/docs/markup-button.md
- packages/clay-button/src/Button.tsx
- packages/clay-button/stories/Button.stories.tsx
- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_buttons.scss
fixes #5081
I added the `size` and `shape` attributes to `ClayButton`, hopefully these make sense.
> feat(@clayui/css): Buttons adds a 24px tall button, `btn-xs`

- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/mixins/_grid.scss
- packages/clay-css/src/scss/mixins/_highlight.scss
- packages/clay-css/src/scss/mixins/_list-group.scss
- packages/clay-css/src/scss/mixins/_loaders.scss
- packages/clay-css/src/scss/mixins/_menubar.scss
- packages/clay-css/src/scss/mixins/_modals.scss
- packages/clay-css/src/scss/mixins/_navbar.scss
- packages/clay-css/src/scss/mixins/_slideout.scss
- packages/clay-css/src/scss/mixins/_stickers.scss
- packages/clay-css/src/scss/mixins/_tables.scss
- packages/clay-css/src/scss/mixins/_tbar.scss
- packages/clay-css/src/scss/mixins/_utilities.scss
> fix(@clayui/css): Mixins check if parameter is map to avoid Sass error

- packages/clay-core/src/typography/Heading.tsx
- packages/clay-core/src/typography/__tests__/index.tsx
- packages/clay-core/stories/Heading.stories.tsx
> feat(@clayui/core): adds API to set heading fontSize independent of tag

- clayui.com/src/components/LayoutNav/LayoutNav.js
- clayui.com/src/components/LayoutNavHome/index.js
- clayui.com/src/components/Sidebar/Sidebar.js
- clayui.com/src/pages/404.js
- clayui.com/src/styles/site/_variables.scss
https://github.com/liferay/clay/issues/5143
> fix(clayui.com) General accessibility issues

- package.json
- packages/clay-autocomplete/docs/api-autocomplete.mdx
- packages/clay-autocomplete/docs/autocomplete.mdx
- packages/clay-autocomplete/docs/index.js
- packages/clay-autocomplete/package.json
- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-autocomplete/src/DropDown.tsx
- packages/clay-autocomplete/src/Item.tsx
- packages/clay-autocomplete/src/__tests__/IncrementalInteractions.tsx
- packages/clay-autocomplete/src/index.tsx
- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
- packages/clay-core/package.json
- packages/clay-core/src/collection/Collection.tsx
- packages/clay-core/src/index.ts
- packages/clay-core/src/tree-view/Collection.tsx
- packages/clay-data-provider/src/__tests__/index.tsx
- packages/clay-data-provider/src/useResource.tsx
- packages/clay-data-provider/src/util.ts
- packages/clay-drop-down/src/Item.tsx
- packages/clay-drop-down/src/ItemList.tsx
- packages/clay-provider/src/DataClient.ts
- yarn.lock
Closes #5100
This PR implements the Collection pattern to Autocomplete, this implements the OOTB features of the Collection such as list virtualization (enabled by default), static content and dynamic content.
Dynamic content has a filter by default as does static content. The filter can be customized when `items` is behaved as controlled, for example this is good for cases where the filter is done by an asynchronous request instead of the filter happening in the browser with all the data.
```jsx
<ClayAutocomplete
defaultItems={['one', 'two', 'three', 'four', 'five']}
messages={{
loading: 'Loading...',
notFound: 'No results found',
}}
>
{(item) => (
<ClayAutocomplete.Item key={item}>
{item}
</ClayAutocomplete.Item>
)}
</ClayAutocomplete>
```
In the example above the filter is enabled …
> feat(@clayui/autocomplete): add the Collection pattern and loading state

- clayui.com/src/templates/docs.js
Forgotten commit, sorry :-(
https://github.com/liferay/clay/issues/5143
> fix(clayui.com): Github link accessibility fixe

- packages/clay-shared/src/useFocusManagement.ts
Related #5164
This is a PR related to #5164, which improves the conditional to decide which fiber to use to find for focusable elements, the element reference has two fibers that correspond to its state, the alternating fiber which can be the fiber in progress and the fiber current. This PR navigate for both fibers when it doesn't find focusable elements, this happens more in DropDown use cases when the menu is rendered over conditional when the `renderMenuOnClick` prop is enabled, there can be different situations, where it can find the focusable elements in the fiber current or alternate because a state update is in progress for example.
> fix(@clayui/shared): fixes flag to switch which fiber to use to find focusable elements

- packages/clay-modal/src/Modal.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/modal.tsx.snap
> feat(@clayui/modal): add `aria-modal` attribute to dialog

- packages/clay-panel/src/index.tsx
> fix(@clayui/panel): Remove fixed height after panel is shown

- packages/clay-modal/src/Hook.ts
Hi Team,
could you please check my fix?
This fixes: https://github.com/liferay/clay/issues/5235
Thanks, Roland
cc: @matuzalemsteles
> fix(@clayui/modal): fix double click in the file select window in case outside of the modal

- packages/clay-table/docs/index.js
- packages/clay-table/stories/Table.stories.tsx
> docs(@clayui/table): adds caption to table examples

- packages/clay-css/src/scss/components/_spinners.scss
> fix(@clayui/css): Bootstrap spinners are broken

- packages/clay-css/src/scss/cadmin/components/_sidebar.scss
- packages/clay-css/src/scss/cadmin/variables/_sidebar.scss
- packages/clay-css/src/scss/components/_sidebar.scss
- packages/clay-css/src/scss/mixins/_sidebar.scss
- packages/clay-css/src/scss/variables/_sidebar.scss
fixes #5185 
Also added `$sidebar` and `$cadmin-sidebar` maps to style the base `.sidebar` component.
> fix(@clayui/css): Sidebar adds focus state

- packages/clay-pagination/docs/pagination.mdx
> docs(clayui.com): Pagination how to add aria-labels

- packages/clay-core/src/picker/Option.tsx
> fix(@clayui/core): update Picker select icon

- packages/clay-multi-select/src/index.tsx
Fixes #5250
This API was already available in all components related to Menu, now also adding to Multi Select.
> feat(@clayui/multi-select): add new `alignmentByViewport` API

- packages/clay-css/src/scss/atlas/variables/_sidebar.scss
- packages/clay-css/src/scss/mixins/_sidebar.scss
- packages/clay-css/src/scss/variables/_sidebar.scss
> fix(@clayui/css): Sidebar should be able to overwrite focus styles on sidenav-start and sidenav-end

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/mixins/_forms.scss
> fix(@clayui/css): Select box selected state should have darker background-color

- packages/clay-alert/docs/alert.mdx
- packages/clay-alert/docs/index.js
- packages/clay-alert/src/index.tsx
- packages/clay-alert/stories/Alert.stories.tsx
- packages/clay-css/src/scss/atlas/variables/_alerts.scss
> feat(@clayui/alert): Adds a secondary variant and symbol attribute

- packages/clay-link/docs/index.js
- packages/clay-link/docs/link.mdx
> docs(clayui.com): Link adds more examples

- packages/clay-css/src/scss/variables/_utilities.scss
> fix(@clayui/css): Readd text-underline and add text-none

- packages/clay-core/src/tree-view/context.ts
> fix(@clayui/core): fix `selection.toggle` typing error

- packages/clay-css/src/scss/atlas/variables/_list-group.scss
- packages/clay-css/src/scss/cadmin/variables/_list-group.scss
> fix(@clayui/css): List Group removes default color on `.list-group`

- packages/clay-css/src/scss/atlas/variables/_list-group.scss
- packages/clay-css/src/scss/cadmin/variables/_list-group.scss
- packages/clay-list/docs/markup-list.md
> fix(@clayui/css): Adjust list-group-text and subtext to match Lexicon specs

- packages/clay-tabs/src/Content.tsx
- packages/clay-tabs/src/List.tsx
- packages/clay-tabs/src/TabPane.tsx
> feat(@clayui/tabs): adds `forwardRef` to Tabs components

- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/variables/_buttons.scss
> fix(@clayui/css): Buttons increase font-weight of text in btn-monospaced

- clayui.com/src/components/LayoutNavHome/index.js
- clayui.com/src/pages/index.js
> clayui.com: Fix axe-accessibility issues

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
> fix(@clayui/core): fix error when not rendering drag button when Item is just string

- packages/clay-css/src/scss/cadmin/variables/_pagination.scss
It fixes https://github.com/liferay/clay/issues/5414
> fix(@clayui/css): Cadmin Pagination active state should have more contrast

- packages/clay-pagination-bar/docs/index.js
> fix(@clayui/pagination-bar): fix bug in documentation example

- packages/clay-core/docs/vertical-bar.js
- packages/clay-core/docs/vertical-bar.mdx
> docs(clayui.com): Vertical Bar add docs on resize property

- packages/clay-css/src/scss/cadmin/variables/_treeview.scss
- packages/clay-css/src/scss/variables/_treeview.scss
> fix(@clayui/css): Treeview btn should inherit component's color

- packages/clay-alert/src/__tests__/__snapshots__/ClayAlert.tsx.snap
- packages/clay-alert/src/index.tsx
> fix(@clayui/alert): move close button outside of ARIA

- packages/clay-empty-state/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-empty-state/src/index.tsx
Fixes https://github.com/liferay/clay/issues/5454
> fix(@clayui/empty-state): Empty alt attribute

- jest.config.js
> chore: update Picker test threshold

- packages/clay-css/src/scss/atlas/variables/_navs.scss
- packages/clay-css/src/scss/components/_navs.scss
- packages/clay-css/src/scss/mixins/_nav.scss
- packages/clay-css/src/scss/variables/_navs.scss
> fix(@clayui/css): Nav Tabs adds nav-tabs-light and adjust borders

- jest.config.js
- packages/clay-css/src/scss/cadmin/components/_multi-step-nav.scss
- packages/clay-css/src/scss/cadmin/variables/_multi-step-nav.scss
- packages/clay-css/src/scss/components/_multi-step-nav.scss
- packages/clay-css/src/scss/variables/_multi-step-nav.scss
- packages/clay-multi-step-nav/docs/index.js
- packages/clay-multi-step-nav/docs/multi-step-nav.mdx
- packages/clay-multi-step-nav/src/Indicator.tsx
- packages/clay-multi-step-nav/src/Item.tsx
- packages/clay-multi-step-nav/src/MultiStepNavWithBasicItems.tsx
- packages/clay-multi-step-nav/stories/MultiStepNav.stories.tsx
#5444
@matuzalemsteles This is the CSS implementation for Multi Step Nav error state. I wasn't able to complete the React component part of it today.
> feat(@clayui/css): Multi Step Nav adds error state

- packages/clay-tabs/docs/index.js
- packages/clay-tabs/docs/tabs.mdx
- packages/clay-tabs/src/List.tsx
> fix(@clayui/tabs): displayType should output nav-tabs variants

- clayui.com/content/docs/components/markup-forms-hierarchy.md
- jest.config.js
- packages/clay-css/src/scss/components/_sheets.scss
- packages/clay-css/src/scss/variables/_sheets.scss
- packages/clay-layout/src/Sheet.tsx
- packages/clay-layout/src/index.tsx
> feat(@clayui/css): Sheets adds sheet-row for aligning content flush

- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/atlas/variables/_pagination.scss
> fix(@clayui/css): Atlas Menubar and Pagination update active and hover state to improve contrast

- jest.config.js
- packages/clay-drop-down/src/DropDownWithItems.tsx
> feat(@clayui/drop-down): add active state to item for cascading menu

- packages/clay-card/src/CardWithHorizontal.tsx
- packages/clay-card/src/CardWithInfo.tsx
- packages/clay-card/src/CardWithNavigation.tsx
- packages/clay-card/src/CardWithUser.tsx
- packages/clay-card/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-card/stories/Card.stories.tsx
This is a solution for proposal https://github.com/liferay/clay/issues/5425
The changes made here were discussed in https://github.com/liferay/clay/pull/5492
Please let me know if anything else needs to be added. Thank you!
> feat(clay-card): Added card-title aria labels and sticker titles.

- packages/clay-css/src/scss/atlas/variables/_buttons.scss
- packages/clay-css/src/scss/atlas/variables/_pagination.scss
- packages/clay-css/src/scss/cadmin/components/_pagination.scss
- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
- packages/clay-css/src/scss/cadmin/variables/_pagination.scss
- packages/clay-css/src/scss/components/_pagination.scss
- packages/clay-css/src/scss/mixins/_links.scss
- packages/clay-css/src/scss/variables/_pagination.scss
> fix(@clayui/css): Pagination maps `.page-item.active .page-link` to `active-class` instead of `active`

- packages/clay-nav/src/Nav.tsx
- packages/clay-nav/src/Vertical.tsx
- packages/clay-nav/src/__tests__/__snapshots__/index.tsx.snap
> fix(@clayui/nav): fix overlapping items in VerticalNav

- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/atlas/variables/_pagination.scss
- packages/clay-css/src/scss/cadmin/variables/_menubar.scss
- packages/clay-css/src/scss/cadmin/variables/_pagination.scss
- packages/clay-css/src/scss/mixins/_links.scss
> fix(@clayui/css): Pagination and Menubar update hover and active borders

- packages/clay-core/src/tree-view/TreeViewItem.tsx
Fixes https://github.com/liferay/clay/issues/5551
> fix(@clayui/core): Add the missing id so that the screen reader makes a correct reading

- packages/clay-css/src/scss/variables/_icons.scss
> fix(@clayui/css): Remove dependence on _nav variables in _icons.scss

- packages/clay-css/src/scss/cadmin/variables/_buttons.scss
fixes #5561
https://issues.liferay.com/browse/LPS-187217
> fix(@clayui/css): Cadmin btn-sm icons should be 16px x 16px

- packages/clay-core/src/vertical-nav/VerticalNav.tsx
- packages/clay-core/src/vertical-nav/context.ts
> fix(@clayui/core): fix typo

- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
> fix(@clayui/core): fix error when submitting the form

- clayui.com/content/docs/css/utilities/markup-accessibility.md
- packages/clay-css/src/scss/cadmin/components/_progress-bars.scss
- packages/clay-css/src/scss/cadmin/components/_utilities-functional-important.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/mixins/_transition.scss
fixes #5581 
https://issues.liferay.com/browse/LPS-187861
> fix(@clayui/css): Cadmin c-prefers-* should qualify the cadmin class

- clayui.com/content/docs/css/content/typography.md
- clayui.com/content/docs/css/utilities/markup-color-utilities.md
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/variables/_utilities.scss
> feat(@clayui/css): Utilities adds more text and bg color utilities

- packages/clay-multi-select/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-multi-select/src/index.tsx
> fix(@clayui/multi-select): fixes error when not disabling the MultiSelect component

- jest.config.js
- packages/clay-drop-down/src/DropDown.tsx
> fix(@clayui/drop-down): fixes error when restoring focus from DropDown

- packages/clay-nav/docs/index.js
- packages/clay-nav/docs/vertical-nav.mdx
> docs(clayui.com): Vertical Nav adds custom link markup section

- packages/clay-core/src/aria/useFocusWithin.tsx
> fix(@clayui/core): fix bug losing component focus when item is removed from DOM

- packages/clay-core/src/tree-view/DragLayer.tsx
> fix(@clayui/core): fix position of TreeView drag preview

- packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx
- packages/clay-pagination-bar/src/__tests__/__snapshots__/index.tsx.snap
> fix(@clayui/pagination-bar):fix Picker trigger highlight error go to parent element

- packages/clay-core/src/hooks/index.ts
- packages/clay-core/src/hooks/useIsMounted.ts
- packages/clay-core/src/live-announcer/LiveAnnouncer.tsx
> fix(@clayui/core): fix error when updating state after component is unmounted

- jest.config.js
- packages/clay-multi-select/src/Labels.tsx
- packages/clay-multi-select/src/index.tsx
> fix(@clayui/multi-select): fix error when not getting list data when pressing enter or comma

- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-multi-select/src/index.tsx
Fixes [LPS-190031](https://liferay.atlassian.net/browse/LPS-190031)
Basically, we had a bottleneck when calling the `createItemsLayout` function, which is responsible for assembling the data structure of the items in the collection, for example extracting the id configured in the render props and the label of the item that can be used for the SR in some components. This function was being called in every rendering which is unnecessary and very costly when we have a large amount of data.
Now we are just assembling the data structure when we render the component and reassembling it when the data changes or when the `children` changes.
The image below is a performance snapshot of the component's interaction when opening the menu, trying to scroll through the list, and closing the menu.
> The …
> fix(@clayui/core): fix collection rendering performance bottleneck

- packages/clay-css/src/images/icons/flags-es-AR.svg
- packages/clay-css/src/images/icons/flags-es-CO.svg
- packages/clay-css/src/images/icons/flags-es-MX.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
Solution for [LPP-50048](https://liferay.atlassian.net/browse/LPP-50048) based on this slack thread: https://liferay.slack.com/archives/C04A7NLM7L1/p1688780613193039
> fix(@clayui/css): Remove fixed height and width to follow SVG guidelines

- packages/clay-panel/src/index.tsx
This is a proposal solution for https://liferay.atlassian.net/browse/LPS-192048
> feat(@clayui/panel): Allow passing classNames to collapse header

- packages/clay-core/docs/picker.js
- packages/clay-core/docs/picker.mdx
> docs(clayui.com): adds compositing examples to Picker

- packages/clay-css/src/scss/functions/_type-conversion-functions.scss
https://liferay.atlassian.net/browse/LPP-50466
https://liferay.atlassian.net/browse/LPS-193500
> fix(@clayui/css): log() errors on dart-sass 1.65.1, use error instead

- packages/clay-core/src/collection/useVirtual.ts
- packages/clay-core/src/drop-down/Menu.tsx
- packages/clay-shared/src/useNavigation.tsx
> fix(@clayui/core): improves navigation for navigating up and down when opening a Menu

- packages/clay-color-picker/package.json
- packages/clay-color-picker/src/Alpha.tsx
- packages/clay-color-picker/src/Editor.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-css/src/scss/cadmin/components/_clay-color.scss
- packages/clay-css/src/scss/cadmin/variables/_clay-color.scss
- packages/clay-css/src/scss/components/_clay-color.scss
- packages/clay-css/src/scss/components/_range.scss
- packages/clay-css/src/scss/mixins/_forms.scss
- packages/clay-css/src/scss/variables/_clay-color.scss
- packages/clay-css/src/scss/variables/_range.scss
- yarn.lock
This PR is a refactor from https://github.com/liferay/clay/pull/5174
Jira ticket:  [LPS-193699](https://liferay.atlassian.net/browse/LPS-193699)
> @clayui/color-picker: Add alpha transparency slider

- jest.config.js
- packages/clay-color-picker/src/Hue.tsx
- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/__tests__/index.tsx
- packages/clay-css/src/scss/cadmin/variables/_clay-color.scss
Jira issue: [LPS-193701](https://liferay.atlassian.net/browse/LPS-193701)
> refactor(@clayui/color-picker): Change Hue component visual

- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/variables/_globals.scss
https://liferay.atlassian.net/browse/LPS-185377
> fix(@clayui/css): Use component-focus-box-shadow for anchor tags

- packages/clay-css/src/scss/atlas/variables/_range.scss
- packages/clay-css/src/scss/mixins/_forms.scss
https://liferay.atlassian.net/browse/LPS-190644
> fix(@clayui/css): Cadmin focus-visible Clay Range doesn't show outline on tab

- packages/clay-css/src/scss/cadmin/components/_cards.scss
- packages/clay-css/src/scss/variables/_cards.scss
https://liferay.atlassian.net/browse/LPS-195376
> fix(@clayui/css): Custom Control remove padding in form-check-box

- packages/clay-core/src/table/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/table/useTreeNavigation.tsx
From #5702
This PR is the next final iteration to add the remaining tests of the incremental interaction suite.
> chore(@clayui/core): add keyboard interaction tests to table

- jest.config.js
- packages/clay-core/src/tree-view/useMultipleSelection.tsx
- packages/clay-core/stories/TreeView.stories.tsx
Jira issue: https://liferay.atlassian.net/browse/LPS-199450
> fix(@clayui/treeview) - Fix ClayTreeView broken when using filtered items

- packages/clay-core/src/aria/useFocusWithin.tsx
- packages/clay-core/src/table/Cell.tsx
- packages/clay-core/src/table/Row.tsx
- packages/clay-css/src/scss/_license-text.scss
- packages/clay-css/src/scss/variables/_tables.scss
> chore(@clayui/core): add focus to table

- packages/clay-core/src/vertical-nav/VerticalNav.tsx
Jira issue: https://liferay.atlassian.net/browse/LPS-202223
> fix(@clayui/vertical-nav): Fix focusable vertica navbar when item has active property equals to false

- packages/clay-tooltip/src/TooltipProvider.tsx
- packages/clay-tooltip/src/useClosestTitle.ts
Jira issue: https://liferay.atlassian.net/browse/LPS-165642
> fix(@clayui/tooltip): Fix close tooltip when pressing Escape key

- packages/clay-core/src/table/Cell.tsx
- packages/clay-core/src/table/__tests__/__snapshots__/BasicRendering.tsx.snap
From https://liferay.atlassian.net/browse/LPS-203308?focusedCommentId=2529765
> fix(@clayui/core): fix accessibility error for `aria-colindex` value

- packages/clay-shared/src/Overlay.tsx
- packages/clay-shared/src/useInteractOutside.tsx
Jira issue: https://liferay.atlassian.net/browse/LPS-203851
https://github.com/liferay/clay/assets/47724428/b00dd13b-7490-4346-8b88-2b936b25d347
> fix(@clayui/drop-down): Fix Dropdown doesnt close when click outside

- packages/clay-core/src/drop-down/Item.tsx
Jira issue: https://liferay.atlassian.net/browse/LPS-202099
Evidence:
https://github.com/liferay/clay/assets/47724428/55a36e32-7f26-425c-b304-baa10ae9a035
> fix(@clayui/pagination): Fix select pages from ellipsis dropdown

- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/picker/__tests__/__snapshots__/BasicRendering.tsx.snap
Jira issue: https://liferay.atlassian.net/browse/LPS-205552
> fix(@clayui/picker): Update Picker markup with aria-controls

- packages/clay-css/src/scss/atlas/variables/_toggle-switch.scss
- packages/clay-css/src/scss/cadmin/components/_toggle-switch.scss
- packages/clay-css/src/scss/cadmin/variables/_toggle-switch.scss
- packages/clay-css/src/scss/components/_toggle-switch.scss
- packages/clay-css/src/scss/mixins/_toggle-switch.scss
- packages/clay-css/src/scss/variables/_toggle-switch.scss
- packages/clay-form/docs/index.js
- packages/clay-form/docs/toggle-switch.mdx
- packages/clay-form/docs/toggle.js
- packages/clay-form/src/Toggle.tsx
- packages/clay-form/stories/Toggle.stories.tsx
https://liferay.atlassian.net/browse/LPS-202286
I still need to write docs and update `@clayui/form`. We can add `toggle-switch-sm` to the toggle-switch or the whole group.
> feat(@clayui/css): Toggle Switch adds toggle-switch-sm modifier

- packages/clay-core/src/drop-down/Menu.tsx
- packages/clay-core/src/table/Head.tsx
- packages/clay-css/src/scss/cadmin/variables/_toggle-switch.scss
- packages/clay-css/src/scss/variables/_toggle-switch.scss
Ticket [LPS-196503](https://liferay.atlassian.net/browse/LPS-196503)
Small adjustments to Columns Visibility DropDown like Toggle size and spacing.
> chore(@clayui/core): visual adjustments to columns visibility DropDown

- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/cadmin/variables/_menubar.scss
Jira issue: https://liferay.atlassian.net/browse/LPS-201512
Follow Marcos's fix recommendations in the ticket.
https://github.com/liferay/clay/assets/47724428/30a6851b-06f8-4dd7-b758-0ae6f48cf494
> fix(@clayui/css): Fix text behaviour in Vertical Navigation component

- CONTRIBUTING.md
Jira issue: https://liferay.atlassian.net/browse/LPD-17076
> docs(contributing.md): LPD-17076 - Change Clay documentation to add LPD ticket number on commit messages

- packages/clay-css/src/scss/atlas/variables/_tooltip.scss
- packages/clay-css/src/scss/cadmin/variables/_tooltip.scss
https://liferay.atlassian.net/browse/LPD-2053
Please let me know if anything else is needed for this.
> fix(clayui.com) Change tooltip background color

- packages/clay-table/stories/Table.stories.tsx
https://liferay.slack.com/archives/C04A7NLM7L1/p1708530956187929?thread_ts=1708504726.279119&cid=C04A7NLM7L1 for more context.
> chore(@clayui/table): remove xl size from storybook example option

- clayui.com/content/docs/css/color.mdx
https://liferay.atlassian.net/browse/LPD-1759
> docs(clayui.com): secondary-3 should be secondary-l3

- packages/clay-core/src/collection/types.ts
- packages/clay-core/src/collection/useCollection.tsx
- packages/clay-core/src/table/Head.tsx
- packages/clay-core/src/table/Row.tsx
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/src/table/context.tsx
Ticket [LPD-19431](https://liferay.atlassian.net/browse/LPD-19431)
> fix(@clayui/core): fixes bug when switching column visibility

- packages/clay-css/src/scss/atlas/variables/_globals.scss
https://liferay.atlassian.net/browse/LPD-20261
> fix(@clayui/css): LPD-20261 Atlas $secondary-l0 is missing !default flag

- clayui.com/plugins/gatsby-plugin-clay-css-tasks/clay-icon-aliases.js
- clayui.com/static/js/icons-autogenerated.json
https://liferay.atlassian.net/browse/LPD-17079?focusedCommentId=2590707
> chore(clayui.com): Adds aliases for SVG icons braces and brackets

- packages/clay-autocomplete/stories/Autocomplete.stories.tsx
https://liferay.atlassian.net/browse/LPD-1932
> fix(clay-autocomplete): Remove autocomplete async filter paginated example

- jest.config.js
- packages/clay-drop-down/src/DropDownWithItems.tsx
- packages/clay-pagination-bar/src/DropDown.tsx
This is a follow-up to add aria-label on the pagination bar using DropDown, in addition to the Picker.
https://liferay.atlassian.net/browse/LPD-17368
> fix(@clayui/pagination-bar): LPD-17368 Follow up - Add aria-label

- packages/clay-core/src/table/Head.tsx
Ticket [LPD-22031](https://liferay.atlassian.net/browse/LPD-22031)
> fix(@clayui/core): fixes bug when changing column visibility when there is only one column visible and disabled

- packages/clay-alert/docs/alert.mdx
- packages/clay-alert/docs/api-alert.mdx
- packages/clay-alert/docs/index.js
- packages/clay-alert/docs/markup-alert.md
Ticket [LPD-17791](https://liferay.atlassian.net/browse/LPD-17791)
> docs(@clayui/alert): remove secondary variation and add new example

- packages/clay-css/src/scss/variables/_modals.scss
> fix(@clayui/css): fix padding in modal footer

- packages/clay-css/src/scss/cadmin/variables/_empty-state.scss
- packages/clay-css/src/scss/variables/_empty-state.scss
Jira issue: https://liferay.atlassian.net/browse/LPD-2278
> fix(@clayui/empty-state): LPD-2278 Panels with empty states cannot be zoomed 200%

- packages/clay-empty-state/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-empty-state/src/index.tsx
- packages/clay-empty-state/stories/EmptyState.stories.tsx
Jira issue: https://liferay.atlassian.net/browse/LPD-24798
> LPD-24798 - Make imgSrcReducedMotion be displayed when the props passed has value

- packages/clay-empty-state/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-empty-state/src/index.tsx
Jira issue: https://liferay.atlassian.net/browse/LPD-1647
> refactor(@clayui/empty-state): LPD-1647 Remove truncate text in Empty State

- packages/clay-form/docs/checkbox.mdx
- packages/clay-form/src/Checkbox.tsx
- packages/clay-form/src/__tests__/__snapshots__/Checkbox.tsx.snap
Jira issue: https://liferay.atlassian.net/browse/LPD-1815
> refactor(@clayui/checkbox): LPD-1815 Remove readOnly property and add disabled

- packages/clay-core/src/table/Head.tsx
To more context https://github.com/liferay-platform-experience/liferay-portal/pull/602#issuecomment-2159422755
> fix(@clayui/table): fixes bug when hiding all columns

- packages/clay-css/src/scss/cadmin/variables/_popovers.scss
- packages/clay-css/src/scss/mixins/_popovers.scss
- packages/clay-css/src/scss/variables/_popovers.scss
- packages/clay-popover/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-popover/src/index.tsx
- **fix(@clayui/popover): LPD-15615 Add focus on popover when disableScroll is enabled**
- **fix(@clayui/css): LPD-15615 Add focus style on popover when disableScroll is enabled**
Jira issue: https://liferay.atlassian.net/browse/LPD-15615
> fix(@clayui/popover): LPD-15615 Popover: focus is not redirected to popover when disableScroll prop is true

- CONTRIBUTING.md
Ticket [LPD-24190](https://liferay.atlassian.net/browse/LPD-24190)
I added some more details to the documentation about Clay's release process, let me know if there's anything else missing or we need to explain more details about a step that I ended up forgetting.
> chore: adds more details on Clay's release

- clayui.com/content/docs/css/color.mdx
- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-tabs/docs/markup-tabs.md
Related to this Lexicon PR:
https://github.com/liferay-design/liferay.design/pull/1228/
> LPD-29322 - Improve L0 accessible colors to be closer to 3:1 ratio

- packages/clay-css/src/scss/cadmin/components/_multi-step-nav.scss
- packages/clay-css/src/scss/cadmin/variables/_multi-step-nav.scss
- packages/clay-css/src/scss/components/_multi-step-nav.scss
- packages/clay-css/src/scss/variables/_multi-step-nav.scss
https://liferay.atlassian.net/browse/LPD-32258
> fix(@clayui/css): LPD-32258 Convert .mutli-step-title to use Sass map

- packages/clay-drop-down/docs/api-dropdown.mdx
- packages/clay-drop-down/docs/drop-down.mdx
- packages/clay-drop-down/docs/markup-dropdown.md
Jira issue: https://liferay.atlassian.net/browse/LPD-32817
> docs(drop-down): LPD-32817 Change "Dropdown" to "Dropdown Menu"

- packages/clay-core/src/tree-view/TreeViewItem.tsx
- packages/clay-core/src/tree-view/__tests__/__snapshots__/BasicRendering.tsx.snap
https://liferay.atlassian.net/browse/LPD-1277
- **fix(@clayui/tree-view): LPD-1277 Add id to correlate label with checkbox**
- **fix(@clayui/tree-view): LPD-1277 Add id prop to correlate label with checkbox**
- **fix(@clayui/tree-view): LPD-1277 Update snapshots**
> fix(@clayui/tree-view): LPD-1277 TreeView with checkbox need a label

- packages/clay-color-picker/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-color-picker/src/index.tsx
- packages/clay-color-picker/stories/ColorPicker.stories.tsx
https://liferay.atlassian.net/browse/LPD-32529
feat(@clayui/color-picker): Remove small color-picker example and add small toggle for all examples
> feat(@clayui/color-picker)

- packages/clay-css/src/scss/atlas/variables/_forms.scss
- packages/clay-css/src/scss/cadmin/components/_forms.scss
- packages/clay-css/src/scss/cadmin/variables/_forms.scss
- packages/clay-css/src/scss/components/_forms.scss
- packages/clay-form/src/DualListBox.tsx
- packages/clay-form/src/SelectBox.tsx
- packages/clay-form/stories/DualListBox.stories.tsx
https://liferay.atlassian.net/browse/LPD-34319
> fix(@clayui/form): LPD-34319 adds disabled to Dual Listbox

- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
Jira issue: https://liferay.atlassian.net/browse/LPD-36353
> fix(@clayui/css): Remove white-space: nowrap on dropdown-menu-width-shrink

- packages/clay-css/src/scss/cadmin/components/_tables.scss
- packages/clay-css/src/scss/components/_tables.scss
https://liferay.atlassian.net/browse/LPD-36088
> fix(@clayui/css): LPD-36088 Table Striped hover states should work

- packages/clay-core/src/table/Cell.tsx
- packages/clay-css/src/scss/_license-text.scss
https://liferay.atlassian.net/browse/LPD-35107
> LPD-35107 - Update sorting icons for Clay Table

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/variables/_globals.scss
https://liferay.atlassian.net/browse/LPD-39299
This needs to make it into DXP before we can merge https://github.com/liferay-platform-experience/liferay-portal/pull/753
> feat(@clayui/css): LPD-39299 Adds d4-l1 for colors

- README.md
https://liferay.atlassian.net/browse/LPD-39867
> chore(clay): LPD-39867 Update readme with troubleshooting Python

- packages/clay-css/src/scss/atlas/variables/_menubar.scss
- packages/clay-css/src/scss/cadmin/variables/_menubar.scss
Jira issue: https://liferay.atlassian.net/browse/LPD-39579
> fix(@clayui/vertical-nav): LPD-39579 Vertical Navigation Items height should be 40px by default, not 41px

- packages/clay-css/src/scss/cadmin/variables/_tables.scss
- packages/clay-css/src/scss/mixins/_tables.scss
- packages/clay-css/src/scss/variables/_tables.scss
Jira issue: https://liferay.atlassian.net/browse/LPD-39960
> fix(@clayui/css): LPD-39960 Fix padding between text and icon on table head

- packages/clay-css/src/scss/cadmin/variables/_sidebar.scss
- packages/clay-css/src/scss/variables/_sidebar.scss
jira issue: https://liferay.atlassian.net/browse/LPD-39580
> fix(@clayui/sidebar): LPD-39580 Sidebar Header Title should be bold (700)

- packages/clay-drop-down/docs/drop-down.mdx
- packages/clay-drop-down/docs/index.js
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-drop-down/src/DropDownWithDrilldown.tsx
- packages/clay-drop-down/stories/DropDown.stories.tsx
- packages/clay-localized-input/src/index.tsx
- **fix(@clayui/dropdown) LPD-41310 remove default value from triggerIcon and update docs**
- **Revert "feat(@clayui/dropdown): LPD-41310 Add "triggerIcon=undefined" prop to prevent caret-icon to be displayed"**
> LPD 41310 Follow up

- clayui.com/static/images/icons/icons.svg
- clayui.com/static/js/flags-autogenerated.json
- packages/clay-css/src/images/icons/flags-de-AT.svg
- packages/clay-css/src/images/icons/flags-de-CH.svg
- packages/clay-css/src/images/icons/flags-fr-BE.svg
- packages/clay-css/src/images/icons/flags-fr-CH.svg
- packages/clay-css/src/images/icons/flags-it-CH.svg
- packages/clay-css/src/images/icons/flags-mk-MK.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
https://liferay.atlassian.net/browse/LPD-42908
> feat(@clayui/css): LPD-42908 Adds language flags fr-BE, fr-CH, de-CH, it-CH, mk-MK, de-AT

- clayui.com/static/images/icons/icons.svg
- clayui.com/static/js/flags-autogenerated.json
- packages/clay-css/src/images/icons/flags-no-NO.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
https://liferay.atlassian.net/browse/LPD-44385
> feat(@clayui/css): LPD-44385 Add language flag no-No.svg

- packages/clay-form/docs/markup-toggle-switch.md
- packages/clay-form/src/Toggle.tsx
- packages/clay-form/src/__tests__/__snapshots__/Toggle.tsx.snap
https://liferay.atlassian.net/browse/LPD-45345
> fix(@clayui/form): LPD-45345 Radio Toggle Switch should use role="radio"

- packages/clay-css/src/scss/atlas/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_globals.scss
- packages/clay-css/src/scss/cadmin/variables/_stickers.scss
- packages/clay-css/src/scss/variables/_globals.scss
- packages/clay-css/src/scss/variables/_stickers.scss
- packages/clay-sticker/docs/index.js
- packages/clay-sticker/src/index.tsx
- packages/clay-sticker/stories/Sticker.stories.tsx
https://liferay.atlassian.net/browse/LPD-40080
> feat(@clayui/css): LPD-40080 Add new sticker variants sticker-outline-*

- packages/clay-css/src/scss/cadmin/components/_multi-step-nav.scss
- packages/clay-css/src/scss/components/_multi-step-nav.scss
https://liferay.atlassian.net/browse/LPD-45685
> fix(@clayui/css): LPD-45685 Multi Step Nav should use focus-visible

- packages/clay-nav/docs/index.js
- packages/clay-nav/docs/vertical-nav.mdx
- **docs(@clayui/vertical-nav):LPD-46396 -Follow up to change documentation for vertical navbar**
> docs(@clayui/vertical-nav):LPD-46396 -Follow up to change documentation for vertical navbar'

- packages/clay-core/stories/LanguagePicker.stories.tsx
- packages/clay-css/src/scss/cadmin/variables/_dropdowns.scss
- packages/clay-css/src/scss/variables/_dropdowns.scss
https://liferay.atlassian.net/browse/LPD-41942
> feat(@clayui/css): LPD-41942 Picker (dropdown-menu-select) change max-height to 7 items

- packages/clay-date-picker/src/Hooks.ts
Ticket: https://liferay.atlassian.net/browse/LPD-47879
> fix(@clayui/date-picker) LPD-47879 Fix time formatting when switching between 12h and 24h

- packages/clay-management-toolbar/src/ManagementToolbar.tsx
https://liferay.atlassian.net/browse/LPD-49362
> feat(@clayui/management-toolbar): LPD-49362 Add fluidSize prop

- packages/clay-core/docs/table.mdx
- packages/clay-table/docs/table/markup.mdx
I am having trouble testing on the new clay site so I was unable to test this, but this is my proposed change for https://liferay.atlassian.net/browse/LPD-47018.
> docs(@clayui/table): Add code example of table-nested-rows

- package.json
- yarn.lock
https://liferay.atlassian.net/browse/LPD-49837
> chore: LPD-49837 Fix storybook error

- jest.config.js
- packages/clay-alert/src/index.tsx
- packages/clay-drop-down/src/DropDown.tsx
- packages/clay-multi-select/src/MultiSelect.tsx
- packages/clay-multi-select/src/index.tsx
- packages/clay-navigation-bar/src/index.tsx
- packages/clay-panel/src/index.tsx
- packages/clay-popover/src/index.tsx
- packages/clay-sticker/src/Sticker.tsx
- packages/clay-sticker/src/index.tsx
- packages/clay-tabs/src/index.tsx
- packages/clay-upper-toolbar/src/index.tsx
Context https://liferay.slack.com/archives/C049XG98GQL/p1740557002709139
With the update of Clay's website we made many changes to the types to make the API Table work properly and some were removed and went unnoticed in the final review, I am adding back here all those that were left out that could break the build of the applications, as soon as I merge this I will make a new release.
> fix: exports the missing types

- packages/clay-core/docs/icon-selector.mdx
- packages/clay-core/src/drop-down/Menu.tsx
- packages/clay-core/src/focus-trap/FocusMenu.tsx
- packages/clay-core/src/focus-trap/index.ts
- packages/clay-core/src/icon-selector/IconSelector.tsx
Ticket: https://liferay.atlassian.net/browse/LPD-47056
Handle keyboard interactions on the dropdown grid
Use the `useNavigation` hook to handle keyboard interactions
https://github.com/user-attachments/assets/8edd1570-ad8a-4c0c-a93c-81c7d07e807f
>  feat(@clayui/core): LPD-47056 Add Keyboard Interactions to the Icon Selector

- packages/clay-form/docs/dual-list-box.mdx
https://liferay.atlassian.net/browse/LPD-50666
> docs(clayui.com): ClayDualListbox docs has incorrect import

- packages/clay-drop-down/src/DropDownWithItems.tsx
Discovery bug https://github.com/liferay-platform-experience/liferay-portal/pull/1099#issuecomment-2749413745
> fix(@clayui/drop-down): fixes bug when transforming tree items to a linked list

- packages/clay-css/src/scss/atlas/variables/_modals.scss
- packages/clay-css/src/scss/cadmin/variables/_modals.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/variables/_modals.scss
- packages/clay-css/src/scss/variables/_utilities.scss
- packages/clay-modal/stories/Modal.stories.tsx
- packages/clay-modal/stories/static/group-1075.svg
https://liferay.atlassian.net/browse/LPD-52454
@marcoscv-work @BarbaraCabrera @matuzalemsteles I added an example of the CMS modal in storybook here.
> chore(@clayui/modal): LPD-52454 Add example of Page Management CMS modal

- packages/clay-css/src/images/icons/flags-my-MM.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
- packages/clay-icon/docs/aliases.js
https://liferay.atlassian.net/browse/LPD-52767
> feat(@clayui/css): LPD-52767 Icons adds Myanmar Flag

- packages/clay-css/src/images/icons/flags-en-IE.svg
- packages/clay-css/src/images/icons/flags-en-LV.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
- packages/clay-icon/docs/aliases.js
https://liferay.atlassian.net/browse/LPD-52791
> feat(@clayui/css): LPD-52791 Icons adds Ireland and Latvia flags

- packages/clay-css/src/scss/mixins/_navbar.scss
https://liferay.atlassian.net/browse/LPD-47138
> chore(@clayui/css): LPD-47138 Mixins, Improve compile time in Navbar

- packages/clay-button/package.json
- packages/clay-button/src/Button.tsx
- packages/clay-button/stories/Button.stories.tsx
https://liferay.atlassian.net/browse/LPD-50102
> feat(@clayui/button): LPD-50102 Adds loading prop to show loading indicator

- packages/clay-css/src/images/icons/flags-bs-BA.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
- packages/clay-icon/docs/aliases.js
Ticket: [LPD-54569](https://liferay.atlassian.net/browse/LPD-54569?linkSource=email)
> feat(@clayui/css): LPD-54569 Add Bosnia & Herzegovina Flag.

- www/app/_components/Sandpack.server.tsx
https://liferay.atlassian.net/browse/LPD-56202
> feat(www): LPD-56202 - Make the SandpackCodeEditor editable.

- packages/clay-autocomplete/src/Autocomplete.tsx
- packages/clay-color-picker/src/Custom.tsx
- packages/clay-color-picker/src/index.tsx
- packages/clay-core/src/icon-selector/IconSelector.tsx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-core/src/side-panel/Header.tsx
- packages/clay-core/src/side-panel/__tests__/BasicRendering.tsx
- packages/clay-core/src/side-panel/__tests__/IncrementalInteractions.tsx
- packages/clay-core/src/side-panel/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/table/Table.tsx
- packages/clay-core/stories/SidePanel.stories.tsx
- packages/clay-css/src/scss/atlas/variables/_sidebar.scss
- packages/clay-css/src/scss/atlas/variables/_utilities.scss
- packages/clay-css/src/scss/cadmin/variables/_sidebar.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/variables/_sidebar.scss
- packages/clay-link/src/Link.tsx
- packages/clay-multi-select/src/MultiSelect.tsx
- packages/clay-navigation-bar/src/index.tsx
Resent from: https://github.com/liferay/clay/pull/6086
https://liferay.atlassian.net/browse/LPD-47980
> fix(@clayui/core): LPD-47980 SidePanel close button should announce the title of the sidebar

- packages/clay-data-provider/src/__tests__/index.tsx
- packages/clay-multi-select/src/__tests__/index.tsx
https://liferay.atlassian.net/browse/LPD-60256
> chore: LPD-60256 Remove reference to active timer.

- packages/clay-css/src/images/icons/pause.svg
- packages/clay-css/src/scss/functions/_lx-icons-generated.scss
https://liferay.atlassian.net/browse/LPD-59796
> fix(@clayui/css): LPD-59796 SVG Icons update pause.svg

- package.json
- packages/clay-core/package.json
- packages/clay-core/src/index.ts
- packages/clay-core/src/language-picker/LanguagePicker.tsx
- packages/clay-core/src/language-picker/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/package.json
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/__tests__/index.tsx
- packages/clay-localized-input/src/index.tsx
- yarn.lock
https://liferay.atlassian.net/browse/LPD-50722
Resending this as it broke many tests. I was particularly having trouble with https://github.com/liferay/liferay-portal/blob/49dc40209ee35b7bf7ba10327e80295530b8e641/modules/dxp/apps/search-experiences/search-experiences-web/test/js/shared/PageToolbar.js.
> feat(@clayui/localized-input): LPD-50722 LocalizedInput to use LanguagePicker

- packages/clay-core/src/index.ts
- packages/clay-core/src/language-picker/LanguagePicker.tsx
- packages/clay-core/src/language-picker/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/__tests__/__snapshots__/index.tsx.snap
- packages/clay-localized-input/src/__tests__/index.tsx
- packages/clay-localized-input/src/index.tsx
https://liferay.atlassian.net/browse/LPD-58735
We had to revert https://liferay.atlassian.net/browse/LPD-50722 due to the PR causing test failures in DXP. I cherry picked a bad commit https://github.com/liferay/clay/pull/6091/files#diff-42f90f0eb0ec7f5ad552898e9aee91430b4099ba5b45316545f7c4ebe5e3b9d9R149.
> @feat(@clayui/localized-input): LPD-58735 Use LangagePicker in LocalizedInput

- packages/clay-date-picker/src/index.tsx
- packages/clay-date-picker/stories/DatePicker.stories.tsx
Hi guys! I'm sending the fix for https://liferay.atlassian.net/browse/LPD-62575. Could you review it? Thanks in advance!
> fix(@clayui/date-picker): LPD-62575 Take into account use12Hours in the Time example placeholder

- packages/clay-css/src/scss/cadmin/variables/_stickers.scss
- packages/clay-css/src/scss/variables/_stickers.scss
- packages/clay-sticker/docs/sticker.mdx
- packages/clay-sticker/docs/sticker/markup.mdx
- packages/clay-sticker/src/Sticker.tsx
- packages/clay-sticker/stories/Sticker.stories.tsx
https://liferay.atlassian.net/browse/LPD-63912
> feat(@clayui/css): LPD-63912 Add sticker-xxl

- packages/clay-alert/src/index.tsx
- packages/clay-core/src/picker/Picker.tsx
- packages/clay-list/package.json
- packages/clay-list/src/ItemTitle.tsx
- packages/clay-list/src/ListWithItems.tsx
- packages/clay-modal/src/Header.tsx
- packages/clay-modal/src/__tests__/IncrementalInteractions.tsx
- packages/clay-modal/src/__tests__/__snapshots__/IncrementalInteractions.tsx.snap
- packages/clay-modal/src/__tests__/__snapshots__/index.tsx.snap
- yarn.lock
https://liferay.atlassian.net/browse/LPD-65537
The goal is that all of these extra props are optional so that we don't break any existing usages.
> LPD-65537 - Update props for clay components that include aria labels that cannot be translated. 

- packages/clay-core/docs/side-panel.mdx
- packages/clay-core/src/focus-trap/FocusTrap.tsx
- packages/clay-core/src/focus-trap/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/src/side-panel/SidePanelWithDrilldown.tsx
- packages/clay-core/src/side-panel/__tests__/SidePanelWithDrillDown.tsx
- packages/clay-core/src/side-panel/__tests__/__snapshots__/BasicRendering.tsx.snap
- packages/clay-core/stories/SidePanel.stories.tsx
- packages/clay-css/src/scss/cadmin/components/_slideout.scss
- packages/clay-css/src/scss/cadmin/components/_utilities.scss
- packages/clay-css/src/scss/cadmin/variables/_sidebar.scss
- packages/clay-css/src/scss/cadmin/variables/_slideout.scss
- packages/clay-css/src/scss/cadmin/variables/_utilities.scss
- packages/clay-css/src/scss/components/_sidebar.scss
- packages/clay-css/src/scss/components/_slideout.scss
- packages/clay-css/src/scss/components/_utilities.scss
- packages/clay-css/src/scss/mixins/_globals.scss
- packages/clay-css/src/scss/variables/_slideout.scss
- packages/clay-css/src/scss/variables/_utilities.scss
@veroglez I scoped header / footer changes here. You can cherry-pick the top two commits in your pr.
> fix(@clayui/css): LPD-65265 c-slideout unsticky sidebar header and footer in small height screens

- .github/workflows/main.yml
we keep getting some random CI failures and the error message isn't clear why it is failing. I suspect a stale cache.
> chore: fix github actions

- packages/clay-css/src/scss/functions/_global-functions.scss
https://liferay.atlassian.net/browse/LPD-66425
> fix(@clayui/css): LPD-66425 Nested CSS variables shouldn't cause errors

- packages/clay-css/src/scss/cadmin/variables/_globals-z-index.scss
- packages/clay-css/src/scss/variables/_globals-z-index.scss
https://liferay.atlassian.net/browse/LPD-66602
> fix(@clayui/css): LPD-66602 Lower sticky-* z-index to 989
